### ISSUE TITLE
Unable to click a tab top of the screen when there's more than one row of tabs

### ISSUE THREAD

**Issue by BrandyCarolpie** [onemen/TabMixPlus#100]
Unable to click a tab top of the screen to select a tab when there's more than one row of tabs.

Using Firefox 96.0b10 (64-bit) and TabMixPlus 1.0.0-pre.4

**Comment by mgfor** [comment]
I have the same problem I think.
Noticed recently, possibly came with pre5.
When I want to select a tab, I often click on the upper edge of it (since it's easier when quickly selecting the tab).
But the tab does not get selected. Seems theres a tiny space now above a tab where it doesn't register the click.

On Waterfox 4.0.6 Windows 10 20h2

**Comment by onemen** [comment]
can you provide a screenshot and mark the area that is not-clickable ?
also attach a file with your Tab mix preferences

**Comment by mgfor** [comment]
I've compared the version with TMP off against this one, but it doesn't look different.
Only thing I'm getting a on mouse over Tooltip "New Tab" when TMP is off.
The screenshot is when TMP was on, the red scare is the area where the tab doesn't get activated with TMP, but does get activated without TMP. Here it's already not working with only 1 row (but Multi-row is activated)

![image](https://user-images.githubusercontent.com/25982440/153097552-a755e66c-7857-4aa6-8d4a-5f6a3180938a.png)
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/8028387/TMPpref.txt)

**Comment by BrandyCarolpie** [comment]
It's the entire tab bar at the top that doesn't mouse over the tab when it's two rows.

Attached are one row and two rows pictures + tmp preferences. I have tried a complete re-installation of everything like previously instructed. Now running Using Firefox 97.0 (64-bit) and TabMixPlus 1.0.0-pre.5.


![two_rows](https://user-images.githubusercontent.com/50971349/153103302-43da0874-3cd0-4e53-ad3f-6c3b681ce7fc.png)
![one_row](https://user-images.githubusercontent.com/50971349/153103303-454ee861-8929-45de-b482-f7ebc3c4a96c.png)
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/8028621/TMPpref.txt)

**Comment by onemen** [comment]
So far I can't reproduce this issue on my PC (windows 11).

can you try to create new clean profile ant test how Tab mix work, without changing anything except enabling multi-row .
don't install other extensions or change ANY default setting (pref or theme or custom style)

**Comment by mgfor** [comment]
Can reproduce with Vanilla Waterfox with only TMP1.0-pre5 as extension, Firefox Modern Dark and Light Theme.

Btw: the other Waterfox themes are all broken when used with the Multi-row tab bar.

**Comment by onemen** [comment]
Download and try this [test build](http://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.6.20220211.1.xpi)

**Comment by mgfor** [comment]
Thanks onemen, that fixed it!
