### ISSUE TITLE
TMP issue

### ISSUE THREAD

**Issue by Mrsash2020** [onemen/TabMixPlus#101]
I am not sure if you are aware of this issue. message in Addon window.
![TMP](https://user-images.githubusercontent.com/62192773/148632489-1cb590e1-fdea-46e5-9496-3f80469a2d29.jpg)

**Comment by 117649** [comment]
Its OK, Its cause no harm.

Have you tried restart your firefox? it should be hide automatically after first restart.

**Comment by Mrsash2020** [comment]
Yup restarted and its gone.
thanks
