### ISSUE TITLE
Addons manager not showing (blank)

### ISSUE THREAD

**Issue by harryray33** [onemen/TabMixPlus#102]
I've followed the instructions and put in the chrome folder...Although Tab mix plus installs OK my addon manager is not showing the extensions, themes etc.

I tried removing any reference to addons in the BootstrapLoader.jsm file and restarted Firefox..the extensions now shoiw but I can't install Tabmix, I get a file is corrupt message.

Any ideas what to do please?

**Comment by harryray33** [comment]
I've upgraded to Firefox 88 and now the addons page is showing but Tab mix wont install...still getting the file is corrupt message

**Comment by onemen** [comment]
You most likely missed a step, try to follow the instruction again _to the letter_.

Can you post a screenshot of you chrome folder in your profile and of you Firefox folder

**Comment by harryray33** [comment]
Thanks, I'll do a screenshot...

I'm pretty sure I did everything correctly and the Chrome folder is correct. 
When I originally tried to install it on my Firefox 69 it installed OK but the add-on page was blank, now I've bumped up to 88.0.1 it's the opposite problem the add-on page is OK, but Tab mix wont install.

I tried both utilities and utilities for extensions only and the dev build of Tabmix and the other versions on the site.

**Comment by harryray33** [comment]
I'm pretty sure I did everything correctly and the Chrome folder is correct.
When I originally tried to install it on my Firefox 69 it installed OK but the add-on page was blank, now I've bumped up to 88.0.1 it's the opposite problem the add-on page is OK, but Tab mix wont install.

I tried both utilities and utilities for extensions only and the dev build of Tabmix and the other versions on the site.

I'm using Firefox portable (88.0.1)..I don't know if using the portable edition makes a difference?

For some reason I can't attach a file but the files are installed in Firefox portable>data>profile>chrome>utils.
7 files, BootstrapLoader.jsm, boot.jsm, chrome.manifest, RDFDataSource.jsm, RDFManifestConverter.jsm, userchrome.jsm, xppref.jsm.

Are there different versions of these files for different editions of Firefox?

**Comment by onemen** [comment]
Tab mix versions from here only supports Firefox from version 78 and newer.

try to create new test profile if possible on the latest Firefox version available to you.

regarding you questions about portable, try to open an issue [here](https://github.com/xiaoxiaoflood)

**Comment by harryray33** [comment]
I'm running 88.0.1 
I've tried running a test profile with no luck. 

Possibly wrong version of bootstraploader?

**Comment by onemen** [comment]
look like others reported to [xiaoxiaoflood](https://github.com/xiaoxiaoflood) about issue installing extensions on portable Firefox.
Read this [issue]( 
https://github.com/xiaoxiaoflood/firefox-scripts/issues/93)

**Comment by harryray33** [comment]
Thanks, I've been posting to  xiaoxiaoflood, but not a lot of help I'm afraid.

The strange thing is, is that it was installing to FF portable 69 (but blanked out the add-on page) but it's not installing to portable 88.0.1

**Comment by onemen** [comment]
I've just installed Tab mix successfully on Firefox Portable 96.0 (downloaded from [here](https://portableapps.com/apps/internet/firefox_portable))

1. Download this [config zip file](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/fx-folder.zip) and extract it to a location in you file system.
2. Download this [bootstrap zip file](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/utils_extensions_only.zip) and extract it to a location in you file system.
3. Download latest Tab Mix versions from [here](https://github.com/onemen/TabMixPlus/releases) and save the file.
4. **Close Firefox Portable**, if it is running.
5. Copy the files you extracted in **step 1** to your Firefox Application folder ```YOUR_FIREFOX_PORTABLE_FOLDER/App/Firefox64```.
6. In your profile folder ```YOUR_FIREFOX_PORTABLE_FOLDER/Data/profile``` create ```chrome``` folder.
7. Copy the ```utils`` folder you extracted in **step 2** to the new folder you have just created.
8. Start Firefox Portable, Open ```about:support``` and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup.
9. Start Firefox Portable, Open ```about:addons``` and drag the xpi file you have downloaded in **step 3**

GOOD LUCK

**Comment by harryray33** [comment]
Thanks for that, will it work on 88.0.1?..I'm reluctant to go to 96 unless I can get rid of all traces of Proton.

**Comment by onemen** [comment]
You already have 88, so try it.

**Comment by 117649** [comment]
> Thanks for that, will it work on 88.0.1?..I'm reluctant to go to 96 unless I can get rid of all traces of Proton.

[Lepton](https://github.com/black7375/Firefox-UI-Fix) got you.

**Comment by onemen** [comment]
Closing out old issues that have long grown stale.
Feel free to ping me if this is still an issue and I can reopen.
