### ISSUE TITLE
TMP Options\Display\Tab BarPosition: Bottom - disappears after browser restart

### ISSUE THREAD

**Issue by dv8472** [onemen/TabMixPlus#103]
Hello,

When I try to apply the following setting: "TMP Options\Display\Tab Bar\Position: Bottom (below content)", it works for currently opened window.
If I restart the browser, the bottom tab bar disappears.
However, the tabs are still open in the background, as I can circle through them using CTRL+TAB.
Tested on Linux and Windows, both are affected.
Tested on Windows with a completely new profile, to rule out any installed add-on or another custom settings, but the problem still exist.

**Comment by onemen** [comment]
Read [this](http://tabmixplus.org/support/viewtopic.php?t=2) 
try to supply more details...

**Comment by dv8472** [comment]
I'm sorry if I missied some details:
- tested with Firefox 95-96
- TMP version 1.0.0-pre.4
- "Create new testing profile" + "Disable other extensions" - this was already mentioned before (new profile, without any other extensions or settings), didn't helped either

Please let me know, if there are any other details you would like to have.

**Comment by onemen** [comment]
Export your Tab mix preferences, and attached the file to here

**Comment by dv8472** [comment]
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/7874619/TMPpref.txt)

**Comment by onemen** [comment]
Thank You.

I can confirm that with your setting the tabs disappear after restart.

I start working on it soon

**Comment by dv8472** [comment]
I thank you very much, and also for bringing the TMP back to FF.

**Comment by onemen** [comment]
Download and test this version [1.0.0-pre.5.20220115.1.xpi](http://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.5.20220115.1.xpi)

**Comment by dv8472** [comment]
Looks fine.
Thanks a lot!
