### ISSUE TITLE
Right click context menu glitches

### ISSUE THREAD

**Issue by combat-entropy** [onemen/TabMixPlus#104]
Running Firefox 96 on Windows.
Very rarely (twice total since I discovered this resurrection of TabMixPlus in November) my right click context menu will go glitchy. No idea how to trigger it or reproduce it sadly.  Restarting the browser solves it. 

I have attached a video the first instant is right clicking on a text field where it is unusable, the second just right clicking on the rest of the page where it has scroll arrows and is truncated but usable,

https://user-images.githubusercontent.com/45645324/150681068-520250a1-4ed4-46cf-9c28-d4cc582b9fb0.mp4

The browser console generated the following text when right clicking. 
```
Uncaught TypeError: el.render is not a function
    <anonymous> chrome://global/content/elements/menu.js:172
    openContextMenu chrome://browser/content/nsContextMenu.js:94
    receiveMessage resource:///actors/ContextMenuParent.jsm:23
```

**Comment by onemen** [comment]
I can't reproduce it.
The browser console info you attached don't give any indication that the error come from Tab MIx.

Please attache a file with your Tab Mix preferences.

**Comment by combat-entropy** [comment]
Here are my preferences 
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/7939127/TMPpref.txt)

**Comment by onemen** [comment]
I've test Tab Mix with your preferences, and i can't reproduce this issue

**Comment by benzBrake** [comment]
@onemen 
I have the same problem. My Firefox version is dev 97b9
https://user-images.githubusercontent.com/11323774/152681477-cd0695e2-9e4d-48ee-bcf9-285a51a21723.mp4

**Comment by onemen** [comment]
@benzBrake, pleas follow our [Troubleshooting pages](http://tabmixplus.org/support/viewpage.php?t=2&p=how-to-post) for instruction regarding how to provide us with more information.

**Comment by 117649** [comment]
> @onemen I have the same problem. My Firefox version is dev 97b9 https://user-images.githubusercontent.com/11323774/152681477-cd0695e2-9e4d-48ee-bcf9-285a51a21723.mp4

What are you even doing here? 
Let's say TMP isn't some thing you could expect it to go smoothly with a hot restart. Many things need to be in place even before you see the browser window. In your example it not surprise for the context menu not loaded on a chrome page like 'about:addons', Refresh the page should usually fix it if not try shutdown Firefox completely then do a clean start.

**Comment by onemen** [comment]
Closing out old issues that have long grown stale.
Feel free to ping me if this is still an issue and I can reopen.
