### ISSUE TITLE
TMP cause click on media butons on tab select the tab

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#107]
![image](https://user-images.githubusercontent.com/8281345/151230627-22aacb70-4063-4175-8ab2-fc90ca946fd6.png)

@onemen Its this guy.

Seems TMP some how unblocked the propagation of event.

Tested on 96 & 97 with latest repo of main.

**Comment by 117649** [comment]
It looks like just need a extra exclude condition.
In `click.js` ln30 & ln137:
```diff
+    const isOverlayIcon = aEvent.target.classList.contains("tab-icon-overlay");
    // don't do anything if user left click on tab or tabbar button
+    if (isCloseButton || isOverlayIcon|| aEvent.target._overPlayingIcon ||
        target.localName == "toolbarbutton") {
      return;
    }
```

**Comment by onemen** [comment]
I understand your logic, however I don't have this issue.
can you attach your preferences.

**Comment by 117649** [comment]
![image](https://user-images.githubusercontent.com/8281345/151329010-3a07538a-e6f6-4d33-bde4-72daf834814a.png)
![image](https://user-images.githubusercontent.com/8281345/151329083-6cc964bc-3746-4df7-9167-0e0e4cf38bde.png)
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/7949171/TMPpref.txt)

The root-cause here is  `aEvent.target` was the `<image xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" class="tab-icon-overlay" role="presentation" selected="true"/>` not the tab element.

I've really surprised you are not have this issue since events should bubbling by same rules anywhere, aren't they? You have to not have the tab with the media button selected for the issue to be noticeable.

**Comment by onemen** [comment]
I probably have different tab clicking options, that's why i didn't have this issue.

however you are right the check for `aEvent.target._overPlayingIcon` that we have is left over form 7 years ago, now it will always falsy

**Comment by onemen** [comment]
can you test this patch

```diff
diff --git a/addon/chrome/content/click/click.js b/addon/chrome/content/click/click.js
index 580f3c2a..0cbf9ec9 100644
--- a/addon/chrome/content/click/click.js
+++ b/addon/chrome/content/click/click.js
@@ -8,6 +8,15 @@ var TabmixTabClickOptions = {
   _tabFlipTimeOut: null,
   _blockDblClick: false,
 
+  isOverlayIcons(event) {
+    const overlayIcons = [
+      "tab-icon-sound", // for Firefox 78 - 91
+      "tab-sharing-icon-overlay",
+      "tab-icon-overlay",
+    ];
+    return overlayIcons.some(icon => event.target.classList.contains(icon));
+  },
+
   // Single click on tab/tabbar
   onTabClick: function TMP_onTabClick(aEvent) {
     if (!aEvent)
@@ -31,7 +40,7 @@ var TabmixTabClickOptions = {
 
     // don't do anything if user left click on tab or tabbar button
     if (leftClick &&
-        (isCloseButton || aEvent.target._overPlayingIcon ||
+        (isCloseButton || this.isOverlayIcons(aEvent) ||
          target.localName == "toolbarbutton")) {
       return;
     }
@@ -134,7 +143,7 @@ var TabmixTabClickOptions = {
     const target = aEvent.originalTarget;
     const isCloseButton = aEvent.target.classList.contains("tab-close-button");
     // don't do anything if user left click on tab or tabbar button
-    if (isCloseButton || aEvent.target._overPlayingIcon ||
+    if (isCloseButton || this.isOverlayIcons(aEvent) ||
         target.localName == "toolbarbutton") {
       return;
     }
diff --git a/addon/chrome/content/tab/tabBindings.js b/addon/chrome/content/tab/tabBindings.js
index 9754a9aa..13676e59 100644
--- a/addon/chrome/content/tab/tabBindings.js
+++ b/addon/chrome/content/tab/tabBindings.js
@@ -83,7 +83,7 @@
       void this.clientTop; // just using this to flush style updates
     }
     // prevent chrome://global/content/bindings/tabbox.xml#tab mousedown handler
-    if (this.mOverCloseButton || this._overPlayingIcon) {
+    if (this.mOverCloseButton || TabmixTabClickOptions.isOverlayIcons(event)) {
       event.stopPropagation();
     } else if (this.mouseDownSelect) {
       this.onMouseCommand(event);
```

**Comment by 117649** [comment]
I don't think this is necessary or appropriate.
`this` is the tab element here and it is the parent of the `_overPlayingIcon` property.
This is what `_overPlayingIcon` is for and how it meant to be used. Its not right to go a long way around.

> ```diff
> diff --git a/addon/chrome/content/tab/tabBindings.js b/addon/chrome/content/tab/tabBindings.js
> index 9754a9aa..13676e59 100644
> --- a/addon/chrome/content/tab/tabBindings.js
> +++ b/addon/chrome/content/tab/tabBindings.js
> @@ -83,7 +83,7 @@
>        void this.clientTop; // just using this to flush style updates
>      }
>      // prevent chrome://global/content/bindings/tabbox.xml#tab mousedown handler
> -    if (this.mOverCloseButton || this._overPlayingIcon) {
> +    if (this.mOverCloseButton || TabmixTabClickOptions.isOverlayIcons(event)) {
>        event.stopPropagation();
>      } else if (this.mouseDownSelect) {
>        this.onMouseCommand(event);
> ```

**Comment by 117649** [comment]
> can you test this patch
> 
> ```diff
> diff --git a/addon/chrome/content/click/click.js b/addon/chrome/content/click/click.js
> index 580f3c2a..0cbf9ec9 100644
> --- a/addon/chrome/content/click/click.js
> +++ b/addon/chrome/content/click/click.js
> @@ -8,6 +8,15 @@ var TabmixTabClickOptions = {
>    _tabFlipTimeOut: null,
>    _blockDblClick: false,
>  
> +  isOverlayIcons(event) {
> +    const overlayIcons = [
> +      "tab-icon-sound", // for Firefox 78 - 91
> +      "tab-sharing-icon-overlay",
> +      "tab-icon-overlay",
> +    ];
> +    return overlayIcons.some(icon => event.target.classList.contains(icon));
> +  },
> +
>    // Single click on tab/tabbar
>    onTabClick: function TMP_onTabClick(aEvent) {
>      if (!aEvent)
> @@ -31,7 +40,7 @@ var TabmixTabClickOptions = {
>  
>      // don't do anything if user left click on tab or tabbar button
>      if (leftClick &&
> -        (isCloseButton || aEvent.target._overPlayingIcon ||
> +        (isCloseButton || this.isOverlayIcons(aEvent) ||
>           target.localName == "toolbarbutton")) {
>        return;
>      }
> @@ -134,7 +143,7 @@ var TabmixTabClickOptions = {
>      const target = aEvent.originalTarget;
>      const isCloseButton = aEvent.target.classList.contains("tab-close-button");
>      // don't do anything if user left click on tab or tabbar button
> -    if (isCloseButton || aEvent.target._overPlayingIcon ||
> +    if (isCloseButton || this.isOverlayIcons(aEvent) ||
>          target.localName == "toolbarbutton") {
>        return;
>      }
> diff --git a/addon/chrome/content/tab/tabBindings.js b/addon/chrome/content/tab/tabBindings.js
> index 9754a9aa..13676e59 100644
> --- a/addon/chrome/content/tab/tabBindings.js
> +++ b/addon/chrome/content/tab/tabBindings.js
> @@ -83,7 +83,7 @@
>        void this.clientTop; // just using this to flush style updates
>      }
>      // prevent chrome://global/content/bindings/tabbox.xml#tab mousedown handler
> -    if (this.mOverCloseButton || this._overPlayingIcon) {
> +    if (this.mOverCloseButton || TabmixTabClickOptions.isOverlayIcons(event)) {
>        event.stopPropagation();
>      } else if (this.mouseDownSelect) {
>        this.onMouseCommand(event);
> ```

For the simple cases I can came up with this is working.
