### ISSUE TITLE
Windows order change every time Firefox start

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#109]
I have noticed that when I use more than two windows, every time I start Firefox, with `previous windows and tabs`, the order of the windows changed.
when Tab Mix disabled, the order does not change after each restart.

The first window always kept its order but all other windows location change, if I open 3 window, 1,2,3 next time the order will be 1,3,2 and if I restart Firefox then the order go back to 1,2,3.

If I use 5 windows then the order goes :  1,2,3,4,5 --> 1,5,4,3,2 --> 1,2,3,4,5

@117649, can you test and let me know if you can reproduce the same issue.
In addition, can you test it with other extensions that uses the same Overlays.jsm Code? 

**Screenshot example with 3 windows** 
![screen-1](https://user-images.githubusercontent.com/3650909/152107741-62ca3888-5736-4074-a0f0-cdb3b0730d4d.png)

**Comment by 117649** [comment]
Yes I can seethe problem.
Yes It did happens to other extension use `Overlays.jsm`.
I only have one such addon.
The `Overlays.jsm` code I adopted for TMP and other my addons are from @xiaoxiaoflood and I believe it was origin from Thunderbird's source code.

**Comment by 117649** [comment]
I'm not using firefox with multi windows open in one desktop and only have one monitor for many years so this problem is just invisible for me.
The only place I can think of for check is session manager for now.
I'll try if restore session have same effect.

**Comment by 117649** [comment]
Yes restore a session have same effect.

**Comment by 117649** [comment]
tabGroups have a different `Overlays.jsm` which is much older and different and it seems not have suffer from same problem.

**Comment by 117649** [comment]
My assumption of the reason of the problem:
when we using `Overlay.jsm` we only load one instance in the `bootstrap.js`.
This actually queued all overlay calls from windows into that one instance and because of the `Overlay.jsm` handle the overlay work in a FILO manner(sorry if I'm wrong on this, I can't check at this time) and it would hold on the `"load"` event of the window(I guess) the order of the window make to desktop are made also FILO.

**Comment by onemen** [comment]
> tabGroups have a different `Overlays.jsm` which is much older and different and it seems not have suffer from same problem.

```js
		xmlHttpRequest(path, (xmlhttp) => {
			if(xmlhttp.readyState === 4) {
				// We can't get i from the push before because we can be adding and removing overlays at the same time,
				// which since this is mostly an asynchronous process, would screw up the counter.
```
that code is already asynchronous
