### ISSUE TITLE
Multi-row tab bar not scrollable using mouse

### ISSUE THREAD

**Issue by mgfor** [onemen/TabMixPlus#111]
I'm pretty sure this worked in the older TabMix Plus on the old Firefox.
I'm currently on Waterfox 4.0.6

The mousewheel scrolling works when I use the Multi-Row patch from the Quantum Nox Theme. (without TabMixPlus)
But when I install TabMixPlus pre4 or pre5 now it doesn't scoll using the mousewheel anymore. Seems it's disabled or broken?

Additionally, I noticed the normal tab bar (not multi-row) seems not scrollable too.

**Comment by onemen** [comment]
Make sure you enable scroll preferences:
![mouse_prefs](https://user-images.githubusercontent.com/3650909/152730033-5f22c7ac-ca49-4774-9cf4-2a00775972e5.png)

**Comment by mgfor** [comment]
Thank you so much onemen, that was it.
Strange it's disabled by default, since usually it's enabled when TMP is not installed.

And thank you for bringing back TMP! I think it's time for another donation :)

**Comment by onemen** [comment]
Thank you for your support
