### ISSUE TITLE
"Change opening order" setting has no effect.

### ISSUE THREAD

**Issue by Disappeaer** [onemen/TabMixPlus#113]
Hi there. For some reason the "change opening order" setting at Events / New Tab doesn't seem to work and new tabs always open **right next to the initial parent tab** instead of the tab last opened as they are supposed to. 
Waterfox G4.0.6 / 1.0.0-pre.5 dev-build (I've tried older dev build pre-releases but no dice either.) Any ideas?

**Comment by onemen** [comment]
I don't see any problem with this preferences.
tested both in Waterfox G4.0.6  and Firefox Nightly.

This feature only apply when you open new tab in the background

**Comment by Disappeaer** [comment]
After some extensive troubleshooting it seems it was a problem with Foxygestures. It just wouldn't respect the TMP setting.
Changing to Gesturefy and eventually letting Autohotkey taking care of mouse gestures solved the issue.
Thanks for your good work with the addon, greatly appreciated. 

Any ideas if it's possible to implement a manual tab unload feature?  I mean, sure there are a couple of addons doing that, but it'd be nice to let TMP take care of it, so it applies the "unloaded tabs" style set in options, unloading tabs with those other addons don't do that.

**Comment by onemen** [comment]
see #98
