### ISSUE TITLE
TMP doesn't work anymore

### ISSUE THREAD

**Issue by jis5ey** [onemen/TabMixPlus#114]
Hello!

I've been using TMP for several month on Waterfox without any issues. Today, I found out my browser does not display my multiple tab rows anymore. When I try to open the option window, it's just a blank pop-up window. So I went back here and realized it was maybe because there's a new version and it has been auto-updated. In the release description, it says:
> @xiaoxiaoflood published a new version of BootstrapLoader visit [firefox-scripts](https://github.com/xiaoxiaoflood/firefox-scripts#instructions) repository and follow step 3 again to get the latest version.

So I did that. Picked the same "utils.zip" that I had downloaded the first time from xiaoxaoflood and replaced my previous files with the new ones. Restarted Waterfox, but TMP still doesn't work :((

Am I missing something? 

FYI, I'm using Waterfox G4.0.6 (64-bit) and TMP is version 1.0.0-pre.5. I use a lot of tabs and it's a nightmare to not have TMP anymore :( I'm seeking help please.

EDIT: In the meantime, I have disabled the extension auto-update, rolled back to 1.0.0-pre.4 and to the previous BootstrapLoader.jsm from xiaxiaoflood, so that I can still use TMP.

**Comment by 117649** [comment]
> FYI, I'm using Waterfox G4.0.6 (64-bit) and TMP is version 1.0.0-pre.5. I use a lot of tabs and it's a nightmare to not have TMP anymore :( I'm seeking help please.

`BootstrapLoader.jsm` will do you nothing at all.
Waterfox already incorporate it and for how things work the build-in version will over write standalone file version.
If you have problems during an upgrade type 'about:support' in address bar go to the page hit 'Clear cache...' button and agree browser to restart. After browser restart do nothing but shut it complete down manually then start it up again.
This shall aasure you no lingering sandbox and addon file are all latest.

**Comment by onemen** [comment]
@jis5ey,

Sorry for the inconvenient,  let us know if it work for you

**Comment by mgfor** [comment]
I've successfully installed TMP-pre5 on Waterfox 4.0.6. But had to install the new bootstrap loader for extensions (the only extensions zip) first in the chrom dir. 
Worked well here.

**Comment by jis5ey** [comment]
> If you have problems during an upgrade type 'about:support' in address bar go to the page hit 'Clear cache...' button and agree browser to restart. After browser restart do nothing but shut it completely down manually then start it up again.
> This shall aasure you no lingering sandbox and addon file are all up to date.

^ that did the trick! tyvm 🤗
