### ISSUE TITLE
Open links to other site in new tab is not working afer update FF from 91.5.1 esr to 91.6.0 esr

### ISSUE THREAD

**Issue by YogSottot** [onemen/TabMixPlus#115]
Open links to other site in new tab is not working afer update FF from 91.5.1 esr to 91.6.0 esr

**what is your operating system**:
    - linux, kubuntu 20.04
    - firefox 91.6.0 esr
    - TMP [v1.0.0-pre.5](https://github.com/onemen/TabMixPlus/releases/tag/v1.0.0-pre.5)
    
**post your Tab Mix Plus preferences and as a file**:
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/8030527/TMPpref.txt)

**check if you can reproduce this issue on new profile**:
    Yes. A new clean profile has been created. Install only TMP and xiaoxiaoflood's utils.zip. No other extensions or userjs.

**post an example for a page to reproduce this issue**:
    https://www.steamgifts.com/
    Click with the left button on Steam-Link to the right of the game name
    On FF 91.5.1 it is opened in new tab
    On FF 91.6.0 it is opened in current tab

I'm also tried: "Force to open in new tab: All links".  It also does not work.
    
   ![steam](https://i.imgur.com/fih8unx.png)

**Comment by onemen** [comment]
Thank you @YogSottot for your complete report.

I can confirm this issue.

Firefox push the fix for [bug 1742801](https://bugzilla.mozilla.org/show_bug.cgi?id=1742801) that was originally landed on Firefox 96 to 91.6esr 9 days ago.

I will update Tab Mix code accordingly.

**Comment by YogSottot** [comment]
> Download and try this [test build](http://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.6.20220210.1.xpi)

It works. Thank you for quick support.
