### ISSUE TITLE
Cannot install TMP latest dev build xpi into Firefox 97

### ISSUE THREAD

**Issue by seamaiden50** [onemen/TabMixPlus#116]
Running Firefox 97.0 (64-bit) stable release version on Windows 10 Home (64-bit). Tried repeatedly to install the latest TMP dev build xpi into Firefox 97. Error when installing said, "This add-on could not be installed because it appears to be corrupt."

Re-read the instructions for installing legacy extensions and watched the video. I unzipped the required files into the Firefox installation folder again and the utils (scripts) into my profile chrome folder again. In about:config, the preference "extensions.langpacks.signatures.required" is set to "false." Restarted Firefox. Same issue.

One problem might be that there is no userChrome.js file in my profile chrome folder for the scripts to refer to. Do I need to create a userChrome.js file? What should be in it? Feel free to zip me a sample userChrome.js file and email it to me (janeocean50@gmail.com). Thank you.

**Comment by 117649** [comment]
> One problem might be that there is no userChrome.js file in my profile chrome folder for the scripts to refer to. Do I need to create a userChrome.js file? What should be in it? Feel free to zip me a sample userChrome.js file and email it to me ([janeocean50@gmail.com](mailto:janeocean50@gmail.com)). Thank you.

No! you don't.

>  I unzipped the required files into the Firefox installation folder again and the utils (scripts) into my profile chrome folder again. 

You should use 'utils (extension)'
![image](https://user-images.githubusercontent.com/8281345/153335850-d491cd5b-609c-4381-ae8f-21ea47e544e4.png)

**Comment by seamaiden50** [comment]
Thanks. I was using the utils (extensions and scripts). Next time I will use utils (extensions). I removed Firefox 97 and installed Firefox ESR 91.6.0 to see if it will be easier to install TMP in that.

**Comment by 117649** [comment]
> Thanks. I was using the utils (extensions and scripts). Next time I will use utils (extensions). I removed Firefox 97 and installed Firefox ESR 91.6.0 to see if it will be easier to install TMP in that.

literally to say what you do not gonna help. 
If you get:

>"This add-on could not be installed because it appears to be corrupt."

Is because you get a bad .xpi or not get a working extension loader.
As long as you are using 'utils' that include one there is no different. 

If you've ensure everything is in its good shape and in right place.
Then clear the startup cache: go to 'about:support' hit 'Clear startup cache...' agree to restart.
You can always throw a manually complete shut down and restart after that to make sure everything is shining.

Restart without clear cache may not do you anything at all and clear cache without manually restart may also not do enough.

**Comment by seamaiden50** [comment]
I have tried everything but still cannot get TMP to install. Tried in Firefox 91.6.0esr and the latest version of Firefox. I am just not technical enough to figure this out, and I cannot help with the manual if I cannot install the extension. My apologies.

**Comment by 117649** [comment]
> I have tried everything but still cannot get TMP to install. Tried in Firefox 91.6.0esr and the latest version of Firefox. I am just not technical enough to figure this out, and I cannot help with the manual if I cannot install the extension. My apologies.

You can still try Waterfox

**Comment by onemen** [comment]
@seamaiden50 , check if this help

![about_support](https://user-images.githubusercontent.com/3650909/154215668-01019b6f-60f7-4533-8d4a-d777305ecbe2.png)

I have created two self-extracted zip:

Download and extract [Firefox folder config](http://tabmixplus.org/support/legacy_extensions_loader/firefox-folder-config.exe) to the path of your `Firefox Binary`, see **1** in the image above.

Download and extract [profile scripts](http://tabmixplus.org/support/legacy_extensions_loader/profile-scripts-loader.exe) to the path of your profile you copied from about:support, see **2** in the image above.

After you finished to extract both file go to 'about:support' hit 'Clear startup cache...' agree to restart, see **3** in the image above.

**Comment by onemen** [comment]
@seamaiden50,

Did you tried the above steps?

**Comment by Massimo-B** [comment]
On Linux, I can only get TMP working with Firefox ESR 91.7.0. I have
bootstrap loader
workaround bug 857456
0.1.93.2021.09.30
from  xiaoxiaoflood.

Trying that bootstrap loader on the default 98.0.1 Firefox doesn't work because they have remove the ability to run unsigned addons. The developer version 99 can do that but here I fail to install the TMP xpi. So currently ESR seems to be the only version supported. Actually this is matching what https://www.tabmixplus.org/ says with "(78.0 - 94.*)".

**Comment by onemen** [comment]
@Massimo-B ,

Please report about any issues with bootstrap loader or scripts to [xiaoxiaoflood](https://github.com/xiaoxiaoflood/firefox-scripts/issues)

**Comment by MelchiorGaspar** [comment]
hey Oneman, 
thx so much reviving one of my favorite Firefox addons you wrote...
best of luck getting it up to speed.

I am having this same issue on on Firefox 98.0.2
it will not install because Firefox says it is corrupted...

**Comment by onemen** [comment]
> ooh I just read the comment from [Massimo-B](https://github.com/Massimo-B)
> " Firefox doesn't work because they have remove the ability to run unsigned addons."
> ooh my... that sucks kinda.. yeah..

This is **not true**, It work on my windows 11 PC without any problems on all Firefox versions including 98.0.2, 99 beta and 100 nightly.

check again that you install all the necessary scripts:
 - [comment from above](https://github.com/onemen/TabMixPlus/issues/116#issuecomment-1041197340)
 - [Readme](https://github.com/onemen/TabMixPlus/#readme)
 - [Legacy extensions loader](https://github.com/xiaoxiaoflood/firefox-scripts#instructions)
 
What is you operating system?

**Comment by MelchiorGaspar** [comment]
I'm running Windows 11 Pro fully up to date.
ok.

**Comment by onemen** [comment]
> but are these scripts compatible with multi process Firefox?

YES.

**Comment by Massimo-B** [comment]
Offtopic: 
Could you clarify about the difference between this repo and the https://addons.mozilla.org/de/firefox/addon/tab-mix-plus-webextension/ ? Are you working on both in parallel?
So this repo is still based on the old XUL architecture that is still possible to run on recent Firefox by using the bootstrap loader? I would like to continue this and also lother discussions on the [forum](https://www.tabmixplus.org/forum/) when it works to register again, #132.

**Comment by MelchiorGaspar** [comment]
> > but are these scripts compatible with multi process Firefox?
> 
> YES.

thx I have it and TMP installed and running again!! ^_^
ty so much Oneman.

**Comment by onemen** [comment]
> Could you clarify about the difference between this repo and the https://addons.mozilla.org/de/firefox/addon/tab-mix-plus-webextension/ ? Are you working on both in parallel?

The mentioned version is WebExtension that contain only ["Links"](https://outgoing.prod.mozaws.net/v1/d852e17c0504d4e85511478984a418c3ee923ac14374f1352e73449c3e74681c/http%3A//tabmixplus.org/support/viewpage.php%3Ft=3&p=links%20) features form legacy Tab mix plus.

Due to the limitation/restriction of WebExtension I'm not planing on adding more features to it.

> So this repo is still based on the old XUL architecture that is still possible to run on recent Firefox by using the bootstrap loader?
Yes.
it has all features form legacy Tab mix plus except Session Manager.
I'm currently working on implementing Session Manager.

> I would like to continue this and also lother discussions on the [forum](https://www.tabmixplus.org/forum/) when it works to register again

I have recently updated the forum software and it is fully functional again

**Comment by Massimo-B** [comment]
> Yes.
> it has all features form legacy Tab mix plus except Session Manager.

As I just migrated back to Firefox after years using Palemoon (with increasing issues...), is the current version here working on both Palemoon and recent Firefox, or is the Tab Mix Plus for Palemoon a different code base?
https://addons.palemoon.org/addon/tab-mix-plus/

If this branch is still using XUL and works with bootstrap loader on recent FF, is that expected to work in next future or is XUL support going to be discontinued soon in Firefox soon?

**Comment by onemen** [comment]
Tab Mix Plus for Palemoon is a different code base: https://bitbucket.org/onemen/tabmixplus/src/master/

> If this branch is still using XUL and works with bootstrap loader on recent FF, is that expected to work in next future or is XUL support going to be discontinued soon in Firefox soon?

It is working without a problem on al version including Firefox Nightly. I don't think that Firefox will block the bootstrap loader.

You can always try [waterfox](https://www.waterfox.net/). it has the bootstrap loader build in

**Comment by onemen** [comment]
Closing out old issues that have long grown stale.
Feel free to ping me if this is still an issue and I can reopen.

**Comment by onemen** [comment]
@seamaiden50 

Look at the new [documents](https://onemen.github.io/tabmixplus-docs/)
