### ISSUE TITLE
Bottom multi-row tabbar overflows/truncated

### ISSUE THREAD

**Issue by poire-z** [onemen/TabMixPlus#117]
Firefox 97, TMP v1.0.0-pre.5 2022-02-06 (which somehow includes files dated 2022-02-12 from your last commit e4af796223).

With TabBar position "Bottom (below content)" and "Multi-row" enabled, when going into 2 or more rows, the multirow tabbar would overflow and the 2nd++ rows would be truncated:
![image](https://user-images.githubusercontent.com/24273478/154160780-06c8d8ec-f5a4-43f1-86b4-5e9e424f4801.png)
(Here, I use some bottom status bar userChrome script, without it, I wouldn't even see the 2nd row).

I could solve the issue with some userStyle:
```css
#tabmix-bottom-toolbox > toolbox {
  height: calc(var(--tab-min-height_mlt) * var(--tabmix-visibleRows, 1)) !important
}
```
![image](https://user-images.githubusercontent.com/24273478/154161120-66486d1a-47a4-425d-80a7-9eb8696004af.png)
(the minor remaining padding/margins issues are probably some other CSS hacks of mine, trying to get the feeling I had for years with TMP on FF56/Waterfox - I had tweaked them with single row, and you change a few margins when going into multirow).

I think in e4af796223, you rename the CSS variable `-tabmix-visiblerows` to `-tabmix-visibleRows` (with an uppercase R), but there is still one bit remaining with the old lowercase r in the codebase:
https://github.com/onemen/TabMixPlus/blob/e4af79622321791b0672546b927871f4c4a8c194/addon/chrome/content/overlay/browser.css#L331
which is what my user stsyle is adding.

Strangely, I tested earlier v1.0.0-pre.4 and v1.0.0-pre.2, and I got the same issue :/

Anyway, thank you a lot for resurrecting TMP !

Another little issue: with TMP 0.5.8.1 on old FF/WF, when restoring a closed tab (Undo/Re-open close tab), I always got this tab restored positionned at the end, after the last tab.
With current TMP, it often gets restored between the 1st and 2nd tabs, sometimes in the middle of tabs, rarely at the end :/
Any idea ? Dunno if this position is determined by your code, or if it's done by Firefox's code.
edit: looks like it's Firefox's own "undoCloseTab" - managed to get what I want by using `gBrowser.moveTabTo(undoCloseTab(), gBrowser.tabs.length - 1)` as my shortcut action.

**Comment by onemen** [comment]
@poire-z , thank you for the report.

sorry for the typo.

you can download v1.0.0-pre.5 again
