### ISSUE TITLE
after upgrading to Firefox 98: "Reload Tab Every" clock icon disappeared from tab

### ISSUE THREAD

**Issue by dv8472** [onemen/TabMixPlus#119]
Hello,

after upgrading to Firefox 98: "Reload Tab Every" clock icon disappeared from tab.
Before: 
![image](https://user-images.githubusercontent.com/22549066/157397844-f12ece3f-9482-42b7-8728-e704af79b34f.png)
Only the clock icon is gone, the reload function seems to work unaffected.
Therefore minor cosmetic issue.

**Comment by onemen** [comment]
make sure you are using Tab Mix version v1.0.0-pre.5

**Comment by dv8472** [comment]
I do
![image](https://user-images.githubusercontent.com/22549066/157441877-6bd018d2-479f-450f-ac22-c2b285939e4b.png)

**Comment by 117649** [comment]
> make sure you are using Tab Mix version v1.0.0-pre.5

@onemen #118
A pre.6 is really needed here......

**Comment by onemen** [comment]
Download version [v1.0.0-pre.6](https://github.com/onemen/TabMixPlus/releases)

report back

**Comment by dv8472** [comment]
yeah, fixed, thank you!
