### ISSUE TITLE
There is a chance autoreload state is not restored upon session restore

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#120]
If it happens auto-reload on some tabs would be turned off every time after restore a session.
Only clear startup cache can ease the issue and it may not enough for just clear one time.
No obviously related error message could be found.

**Comment by onemen** [comment]
@117649 ,
can you test if it fixed with this commit from yesterday: [update restored tabs attributes](https://github.com/onemen/TabMixPlus/commit/fd4372a59afe7e93fde64ed24a28beb1e2864f8e)

**Comment by 117649** [comment]
> @117649 , can you test if it fixed with this commit from yesterday: [update restored tabs attributes](https://github.com/onemen/TabMixPlus/commit/fd4372a59afe7e93fde64ed24a28beb1e2864f8e)
I will, but there won't be a clear sign of its effectiveness since it a problem randomly occur.
I'll report if it happens again.

**Comment by 117649** [comment]
One thing I've just noticed, is tab bar force scroll to reveal selected tab whenever an not selected tab finish loading a default Firefox behavior?

**Comment by onemen** [comment]
> is tab bar force scroll to reveal selected tab whenever an not selected tab finish loading a default

probably by this:
https://github.com/onemen/TabMixPlus/blob/fd4372a59afe7e93fde64ed24a28beb1e2864f8e/addon/chrome/content/tabmix.js#L590

maybe we can check if it not visible before `Tabmix.tabsUtils.isElementVisible(gBrowser.selectedTab)`
or move this line to `onSSWindowRestored` ?

The original commit message from 2013 was `Call ensureTabIsVisible from onSSTabRestoring to make sure selected tab is visible when a session is restoring`

**Comment by onemen** [comment]
or maybe i should call `gBrowser.ensureTabIsVisible(gBrowser.selectedTab, false); ` on `onSSTabRestoring` event

**Comment by 117649** [comment]
> > is tab bar force scroll to reveal selected tab whenever an not selected tab finish loading a default
> 
> probably by this:
> 
> https://github.com/onemen/TabMixPlus/blob/fd4372a59afe7e93fde64ed24a28beb1e2864f8e/addon/chrome/content/tabmix.js#L590
> 
> maybe we can check if it not visible before `Tabmix.tabsUtils.isElementVisible(gBrowser.selectedTab)` or move this line to `onSSWindowRestored` ?
> 
> The original commit message from 2013 was `Call ensureTabIsVisible from onSSTabRestoring to make sure selected tab is visible when a session is restoring`

I'm not understand here.
Why you want to 'make sure selected tab is visible when a session is restoring' ?
I mean aren't Firefox gonna set selected tab according to the session restored by it self when restoring?

**Comment by onemen** [comment]
It was added back on 2013, i don't remember the reason
can you test how it work for you if you remove this line?

**Comment by 117649** [comment]
> It was added back on 2013, i don't remember the reason can you test how it work for you if you remove this line?

Done.
Not seeing any obvious problem so far.

**Comment by onemen** [comment]
OK.
I will remove it and upload version v1.0.0-pre.6 tommorow

**Comment by 117649** [comment]
@onemen  I found some thing a little annoying with attributes restore on tab restored (`SSTabRestored`). That is attributes is restored on tab finish loading the page but user can change the config before load is complete and that would be overwrite. And if the page loading is timeout the attributes is not restored however if tab is refreshed the attributes is restored on next successful loading. But only timeout have this behavior other type of failed to load(e.g. 404) does not. 
Maybe not tie attribute restore to the restore state of individual tab?
