### ISSUE TITLE
Auto reload may not always triggering if the tab is hidden

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#121]
@onemen Tab group extensions can put tabs in hidden state.
I also don't remember notice this ever happen before 98.
Maybe some thing related to some config?

And I found some thing a little annoying with attributes restore on tab restored. That is attributes is restored on tab finish loading but user can change the config before load is complete and that would be overwrite. And if the tab loading is timeout the attributes is not restored however if tab is refreshed the attributes is restored on next successful loading. But only timeout have this behavior other type of failed to load(e.g. 404) do not. 
Maybe not tie attribute restore to the restore state of individual tab?

**Comment by onemen** [comment]
@117649 

In 969106f I've change the event we are listening from `SSTabRestoring` to `SSTabRestored` ,
test if changing it back to `SSTabRestoring` will help
or add listener for both `SSTabRestoring` to `SSTabRestored`  in
https://github.com/onemen/TabMixPlus/blob/c00c954a0326d8c7c527c7267003a95810132ffd/addon/chrome/content/tabmix.js#L320

```diff
-        this._tabEvents = ["SSTabRestored", "PrivateTab:PrivateChanged",
+        this._tabEvents = ["SSTabRestoring", "SSTabRestored", "PrivateTab:PrivateChanged", 
```

Can you test if Tabmix.restoreTabState is called for hidden tabs?

> Maybe not tie attribute restore to the restore state of individual tab?
how you thing we should call Tabmix.restoreTabState?

**Comment by 117649** [comment]
> if Tabmix.restoreTabState is called for hidden tabs?

Yes, there is no problem on restore auto reload state for hidden tabs.
The problem here is tab may not auto reload while in hidden state.
May be because `settimeout()` on hidden tabs are put into hibernate.

> how you thing we should call Tabmix.restoreTabState?

`SSTabRestoring` is some how tied to history restore of the tab to a degree. So there may be a situation for it to not trigger on a tab when restore a session? But it seems fine for undo close tabs.
`SSTabRestored` is send when network loading is done on a tab this may be a little to late. The effect is most obvious when undo close tab, the auto-reload indicator is placed after page finish loading.

`SSWindowRestored` may be a good point for restoring a session? It is dispatched at end of `restoreWindow()`.

**Comment by 117649** [comment]
> How do you test if auto reload it triggered for hidden tabs?

TMP can set unread tab to a different color and font.

I feel I have found several times a auto reload tab is not turned to unread for way more time then auto reload timer.

**Comment by onemen** [comment]
> I feel I have found several times a auto reload tab is not turned to unread for way longer then set auto reload time.

let me know to reproduce this

**Comment by 117649** [comment]
> 

Set a tab to auto reload for like every 30 minutes.
Set tab to hidden.
Wait for a time longer than 30 minutes with relative high memory usage of system, may also involve system sleep.
Show the tab and see if its style is unread.

**Comment by 117649** [comment]
I'm currently trying these changes:
```diff
diff --git a/addon/chrome/content/tabmix.js b/addon/chrome/content/tabmix.js
index 4357d57a..3d320e95 100644
--- a/addon/chrome/content/tabmix.js
+++ b/addon/chrome/content/tabmix.js
@@ -234,8 +234,8 @@ var TMP_eventListener = {
       case "SSWindowRestored":
         this.onSSWindowRestored();
         break;
-      case "SSTabRestored":
-        this.onSSTabRestored(aEvent.target);
+      case "SSTabRestoring":
+        this.onSSTabRestoring(aEvent.target);
         break;
       case "TabOpen":
         this.onTabOpen(aEvent);
@@ -317,7 +317,7 @@ var TMP_eventListener = {
       Tabmix.assert(ex);
     }
 
-    this._tabEvents = ["SSTabRestored", "PrivateTab:PrivateChanged",
+    this._tabEvents = ["SSTabRestoring", "PrivateTab:PrivateChanged",
       "TabOpen", "TabClose", "TabSelect", "TabMove", "TabUnpinned",
       "TabAttrModified"];
     this.toggleEventListener(gBrowser.tabContainer, this._tabEvents, true);
@@ -573,6 +573,7 @@ var TMP_eventListener = {
         const url = TabmixSvc.ss.getLazyTabValue(tab, "url");
         TMP_Places.asyncSetTabTitle(tab, url);
       }
+      Tabmix.restoreTabState(tab);
     });
 
     if (this.tabsAlreadyOpened) {
@@ -584,7 +585,7 @@ var TMP_eventListener = {
     }
   },
 
-  onSSTabRestored(tab) {
+  onSSTabRestoring(tab) {
     Tabmix.restoreTabState(tab);
 
     // don't mark new tab as unread
@@ -719,7 +720,7 @@ var TMP_eventListener = {
   lastTimeTabOpened: 0,
   onTabOpen_delayUpdateTabBar: function TMP_EL_onTabOpen_delayUpdateTabBar(aTab) {
     if (aTab.hasAttribute("pending")) {
-      this.onSSTabRestored(aTab);
+      this.onSSTabRestoring(aTab);
       if (Tabmix.isBlankNewTab(aTab.label)) {
         aTab.label = Tabmix.getString("tabs.emptyTabTitle");
         gBrowser._tabAttrModified(aTab, ["label"]);
```

**Comment by onemen** [comment]
![display](https://user-images.githubusercontent.com/3650909/158788615-ca9d8038-e3ad-47c9-835d-2592f5a610b4.png)

make sure `extensions.tabmix.unreadTabreload` is false

also try toggle `browser.sessionstore.restore_tabs_lazily` report how it work when it work in each value.

> Set a tab to auto reload for like every 30 minutes.
> Set tab to hidden.

does the hidden tab is in `pending`  state?

**Comment by 117649** [comment]
> does the hidden tab is in `pending` state?

Don't look like so
![image](https://user-images.githubusercontent.com/8281345/158807147-e5d61d1d-09ab-41c0-ba6b-8aa189949520.png)

**Comment by 117649** [comment]
@onemen 
Aren't this mean if there is any tabs opened before TMP startup this block will always be run and vise versa? why?
https://github.com/onemen/TabMixPlus/blob/c00c954a0326d8c7c527c7267003a95810132ffd/addon/chrome/content/tabmix.js#L578-L583

**Comment by onemen** [comment]
> Aren't this mean if there is any tabs opened before TMP startup this block will always be run and vise versa? why?

If tab was opened (by SessionStore) before Tab mix was started we need to call `onTabOpen_delayUpdateTabBar` after the window restored

regarding `Tabmix.restoreTabState` i need to make more test to make sure each tab is restored after its attributes are fully restored by SessionStore

**Comment by 117649** [comment]
> If tab was opened (by SessionStore) before Tab mix was started we need to call `onTabOpen_delayUpdateTabBar` after the window restored

Firefox reuse existing window for restore sometimes could the `this.tabsAlreadyOpened` be lock at `true` for such case?

**Comment by onemen** [comment]
> Firefox reuse existing window for restore sometimes could the `this.tabsAlreadyOpened` be lock at `true` for such case?

Yes, I need to fix this section to only run on window open.

maybe instead of `TMP_eventListener.tabsAlreadyOpened = gBrowser.tabs.length > 1;` i can addEventListener for "SSWindowRestored" with `{once; true}`

I also need to update Tabmix.restoreTabState not to call autoReload.initTab on tab with "_reload" attribute.
