### ISSUE TITLE
Pale Moon 30 Breaks TabMixPlus Functions

### ISSUE THREAD

**Issue by BoFiS** [onemen/TabMixPlus#124]
So I'm not sure if there's a newer version to be used with Pale Moon, but on the new v30 they just pushed yesterday, TabMixPlus only partially works.  Upon first boot none of my settings for where to display close tab buttons work, though I can toggle them around and get the right-side close button back, but not for "current tabs" only "all tabs" works, but has to be set each time you open the browser.  Additionally, I cannot scroll the wheel to cycle through tabs as before, no amount of toggling that option brings that feature back :-(

**Comment by onemen** [comment]
This repository is only for Firefox and Waterfox versions
for Report about Pale Moon issues [here](https://bitbucket.org/onemen/tabmixplus/issues?status=new&status=open)
