### ISSUE TITLE
TMP wont enable after I disabled it due to glitch

### ISSUE THREAD

**Issue by Mrsash2020** [onemen/TabMixPlus#126]
I am having an issue with latest build of firefox where TMP would say new version available/update or something. I restart after update and it is again disabled by default. So this after a few attempts I click the disabled button/check and now no option to enable. Can you please assist?

Thanks for the help

**Comment by onemen** [comment]
try this:

1.     remove Tab mix.
2.     Open about:support and click "Clear startup cache…" to restart Firefox
3.     After Firefox starts close it again to make sure cache was clean.
4.     Start Firefox
5.     Install Tabmix and enable it

**Comment by Mrsash2020** [comment]
Ok will try. 2 questions.

Will the settings be retained?
The last time I was installing it, I barely got it installed. What would be the procedure to install in this case?

thanks

**Comment by onemen** [comment]
> Will the settings be retained?

Yes

> What would be the procedure to install in this case.

In step 5. above:
- Download [latest Tab mix](https://github.com/onemen/TabMixPlus/releases) to your local machine
- Open about:addons and click the cog icon to open the `tools for all add-ons`
- Click on `Install Add-on From File...`
![install](https://user-images.githubusercontent.com/3650909/159187612-540f4967-4765-4e54-829c-6ca490a5fbd4.png)

**Comment by Mrsash2020** [comment]
Ok Cool

Tried it this time as you said same message

Download latest Tab mix to your local machine
Open about:addons and click the cog icon to open the tools for all add-ons
Click on Install Add-on From File...

![image](https://user-images.githubusercontent.com/62192773/159188420-4277ca18-de0b-482f-bce2-e071d43be05f.png)

**Comment by onemen** [comment]
This is clear indication that you did not install the `Legacy extensions loader` properly
follow this [instructions](https://github.com/xiaoxiaoflood/firefox-scripts#instructions)

also look at this [link](https://github.com/onemen/TabMixPlus/issues/116#issuecomment-1041197340)

**Comment by Mrsash2020** [comment]
Oh wow feel so stupid. I went from a Win7 install on an old drive to Win7/Win11 dual install. My Profiles for both Firefox and thunderbird sit on Drive D so that both OS's update same profiles regardless of the OS. 
When I installed both OS and pointed to this drive for profile it all worked. Its only a month later now it started giving me problems. What I missed was the first step. That is unzip default and config to the C:\Program Files\Mozilla Firefox folder

Just did that and followed post 4 and viola! it works. Yay!

Thanks for your help. much appreciated.

**Comment by onemen** [comment]
👍

**Comment by Mrsash2020** [comment]
Hello again. Thought I ask a question. With my dual boot Win7/Win11 the profile folder is common on Drive D. Regardless of which OS I choose its meant to have continuity etc. I booted into Win11 today and suddenly TMP was disabled. I thought no issues. updated firefox on Win11 still disabled. Removed and then followed the add to C:\Program Files\Mozilla Firefox folder thinking I might have missed that. Still would not install on the Win11.
So booted back into Win7. Added no issues and working no issues. So dont understand since the rest of the process involves the profile folder on drive D. Sorry might have missed something. 

Question is do I need to do anything special for Win11 to ensure it does not keep breaking?

**Comment by onemen** [comment]
I use Firefox on Windows 11 without any problem

try to use different profile for Win7/Win11.

Follow this list to enable Tab Mix again:
-  remove Tab Mix from your profile. then close Firefox without restart.
-  open Firefox, go to about:support and click "Clear startup cache…".
-  open Firefox, and install Tab Mix from a file on your disk, then close Firefox without restart.
-  open Firefox and test if Tab Mix work.

**Comment by Mrsash2020** [comment]
Ok just booted into Win11 to try what you asked. Its funny. Now that I added it in Win 7 its installed and working with no issues on win11

**Comment by onemen** [comment]
> I am still confused why works with one and not with the other

maybe you are using different version of Firefox?

**Comment by Mrsash2020** [comment]
No just checked both same version 98.0.2
