### ISSUE TITLE
TabMixPlus v1.0.0-pre.6 not working properly on Waterfox G4.0.8

### ISSUE THREAD

**Issue by thunderstone135** [onemen/TabMixPlus#127]
Hi, I just wanted to let you know that the latest version of TabMixPlus is not working on the latest version of Waterfox. However, v1.0.0-pre.5 is working just fine so I decided to rollback. Here are some of the things I noticed:
- If I apply **Freeze** on one tab, all tabs get the same treatment.
- There are no icons showing on any tab if **Freeze**, **Lock**, **Protect**, or **Reload** are applied.
- **TabMixPlus Options** will not open; either on the Tools Menu or Add-ons Manager.

I'm sure there are some things that I may have missed since I decided to rollback. Hopefully, the ones I did notice gets fixed on the next version.

**Comment by onemen** [comment]
try to download v1.0.0-pre.6 again to you local machine and reinstall Tab Mix from that file.

report back

**Comment by thunderstone135** [comment]
Whatever you did, you fixed the issue fast 😮 Kudos 👍
