### ISSUE TITLE
WaterFox (Portable) G4.0.8 (64-bit) Updating v1.0.0-pre.6 and ask for restarting every time when load browser

### ISSUE THREAD

**Issue by haho69** [onemen/TabMixPlus#129]
WaterFox (Portable) G4.0.8 (64-bit) Updating v1.0.0-pre.6 and ask for restarting every time when load browser

**Comment by onemen** [comment]
Read here https://github.com/onemen/TabMixPlus/issues/125

**Comment by onemen** [comment]
I've found a typo in the file install.rdf that was bundled in tab_mix_plus-dev-build.xpi

Download [latest Tab mix](https://github.com/onemen/TabMixPlus/releases) **AGAIN** to your local machine
and install Tab Mix from the new file
