### ISSUE TITLE
tab.boxObject is undefined

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#13]
We use tab.boxObject in many places

I'm working on it now

**Comment by 117649** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/getBoxObjectFor
https://bugzilla.mozilla.org/show_bug.cgi?id=1519952

I've done some [here](https://github.com/117649/TabMixPlus/commit/591729617d419976225b24d040a584ddf1103858)(not pr yet) but there is still many.

**Comment by onemen** [comment]
it's already in 33f4ebe
