### ISSUE TITLE
Can't register to the forum

### ISSUE THREAD

**Issue by Massimo-B** [onemen/TabMixPlus#132]
Hi, I thought it's a good idea to track my issue with the forum here:

I can't register to https://www.tabmixplus.org/forum/
I tried different mail addresses and checked all my spamfilters. Could you take a look there?

**Comment by onemen** [comment]
> I can't register to https://www.tabmixplus.org/forum/

I have recently updated the forum software and it is fully functional again.

**Comment by Massimo-B** [comment]
I just tried again without success.
My mail-addresses seem to have been registered without confirmation, I can't use them anymore for new registrations. So I tried to reset their password, without success.

**Comment by onemen** [comment]
sent me an email to tabmix.onemen@gmail.com with the email address you are using
i will try to reset it

**Comment by onemen** [comment]
Closing out old issues that have long grown stale.
Feel free to ping me if this is still an issue and I can reopen.
