### ISSUE TITLE
tab and text corruption when closing a tab using control + W

### ISSUE THREAD

**Issue by MelchiorGaspar** [onemen/TabMixPlus#133]
corrupted tabs and labels in first image
![image](https://user-images.githubusercontent.com/1712842/160789066-8d068ec2-ea81-4819-bcb6-1e439748c1ca.png)

fine if I move them around a bit.. again..
![image](https://user-images.githubusercontent.com/1712842/160789334-78cf221e-8720-4b55-9713-4fd23fb7a538.png)

I take it is a bug?
please fix if you can..
specs and info:
Windows 11 Pro (v21H2)(build 22000.593)
Firefox 98.0.2
TMP addon v1.0.0_pre6
script and extension loader is up to date as I just installed them..

and question please ask and I will do my best to help you nail this bug to the wall.. lol ;)

**Comment by MelchiorGaspar** [comment]
ok now its not doing it for some reason..
strange but ok.. it might happen on and off so I will add another comment if it happens again...

**Comment by onemen** [comment]
Closing out old issues that have long grown stale.
Feel free to ping me if this is still an issue and I can reopen.

**Comment by MelchiorGaspar** [comment]
ok np...
this has not been an issue for some time.. thankfully...
