### ISSUE TITLE
TMP might have caused the navigation toolbar to become non-responsive..

### ISSUE THREAD

**Issue by MelchiorGaspar** [onemen/TabMixPlus#134]
subject says it..
This is the first time it happened so I think it could have happened because of Tab Mix Plus..
as its the only new Firefox extension I am using.

the url box was non-clickable and non-responsive...
and many of the buttons(including extensions based buttons) on the navigation toolbar too.
a shutdown and restart of Firefox was need to fix alleviate..

Firefox v98.0.2
Windows 11 Pro (fully up to date)
EVGA/Nvidia GTX 1070 Ti 8GB
Nvidia display driver v512.15
32GB RAM DDR4

Oneman if you have any questions please ask and I will try to to do m best to answer them.

ps: I noticed yesterday that a bunch of old XUL/XPCOM extensions were auto enabled again.. so I disabled them...

**Comment by onemen** [comment]
Any messages in the browser console ?

**Comment by MelchiorGaspar** [comment]
right... 
sorry, I forgot to check that... lol
if it happens again I will check it...

**Comment by MelchiorGaspar** [comment]
ok it happened again... and I found an entry in the browser console..

08:03:41.681 Uncaught TypeError: tab is null
    TMP_onTabClick chrome://tabmixplus/content/click/click.js:60
    handleEvent chrome://tabmixplus/content/tab/tab.js:497
click.js:60:39
    TMP_onTabClick chrome://tabmixplus/content/click/click.js:60
    handleEvent chrome://tabmixplus/content/tab/tab.js:497

**Comment by MelchiorGaspar** [comment]
there was also these at startup of Firefox..

08:09:23.260 Applying chrome://tabmixplus/content/tabmix.xhtml to chrome://browser/content/browser.xhtml [Overlays.jsm:90:15](chrome://tabmix-resource/content/bootstrap/Overlays.jsm)

08:09:23.271 Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml [Overlays.jsm:90:15](chrome://tabmix-resource/content/bootstrap/Overlays.jsm)

08:09:23.272 Loading eval'd script into chrome://browser/content/browser.xhtml [Overlays.jsm:544:15](chrome://tabmix-resource/content/bootstrap/Overlays.jsm)

08:09:23.272 Tabmix initializer: Object { key: "init", phase: {…} }[tabmix.js:1136:17](chrome://tabmixplus/content/tabmix.js)
08:09:23.273 Tabmix initializer: Object { key: "beforeStartup", phase: {…} }[tabmix.js:1136:17](chrome://tabmixplus/content/tabmix.js)
08:09:23.276 Tabmix initializer: Object { key: "onContentLoaded", phase: {…} }[tabmix.js:1136:17](chrome://tabmixplus/content/tabmix.js)
08:09:23.305 Tabmix initializer: Object { key: "beforeBrowserInitOnLoad", phase: {…} }[tabmix.js:1136:17](chrome://tabmixplus/content/tabmix.js)
08:09:23.310 Tabmix initializer: Object { key: "onWindowOpen", phase: {…} }[tabmix.js:1136:17](chrome://tabmixplus/content/tabmix.js)
08:09:23.316 Tabmix initializer: Object { key: "afterDelayedStartup", phase: {…} }[tabmix.js:1136:17](chrome://tabmixplus/content/tabmix.js)

**Comment by MelchiorGaspar** [comment]
I have noticed when I have a bunch of tabs open and I try to move them around they seem to get stuck
and the movement of tabs is not rendered smoothly or correctly...
I'm not sure if I am saying the above correctly..

**Comment by MelchiorGaspar** [comment]
[Firefox_Troubleshooting Information(v98.0.2)(2022-04-01).txt](https://github.com/onemen/TabMixPlus/files/8397785/Firefox_Troubleshooting.Information.v98.0.2.2022-04-01.txt)

**Comment by onemen** [comment]
Save your Tab mix preferences to a file and attach it here

**Comment by MelchiorGaspar** [comment]
ok, already done lol
I did a backup after configing it the way I like it.. lol
[TMPpref (v1.0.0_pre6)(2022-03-30).txt](https://github.com/onemen/TabMixPlus/files/8397816/TMPpref.v1.0.0_pre6.2022-03-30.txt)

**Comment by MelchiorGaspar** [comment]
ok.

**Comment by onemen** [comment]
> ok, done. now it just uses a marker... to show where its being dropped..

Yes, 
we use only the marker when tabs are in multi-row and, have this option for one row.

You have to use this until i fix this bug

**Comment by MelchiorGaspar** [comment]
ok, thx for working on it.
happy bug hunting.

**Comment by onemen** [comment]
download this test build and install it [1.0.0-pre.7.20220402](http://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.7.20220402.1.xpi)

report back

**Comment by MelchiorGaspar** [comment]
ok will do.

**Comment by MelchiorGaspar** [comment]
nope, it seemed a little bit better at first but its still happening...
I restarted Firefox too.. and reloaded all my tabs
still not rendering the tab movement very well..

Uncaught TypeError: tab is null
    TMP_onTabClick chrome://tabmixplus/content/click/click.js:60
    handleEvent chrome://tabmixplus/content/tab/tab.js:497

and the url box does become un-clickable again.. 
but does recover without having to restart Firefox...

**Comment by onemen** [comment]
can you provide move details

- how many tab you have
- when you see this issue, provide the start position (1st, 2nd..) of the tab you dragged and the end position.
- do you have the scrollbutton (tabs are overflow), and do you see this issue when dragging onto the scrollbutton
- can you reproduce this issue when tabs are not in overflow

**Comment by onemen** [comment]
Open **about:support** and click "Clear startup cache…" to force Firefox to load to make sure the new version is loaded

**Comment by MelchiorGaspar** [comment]
6 tabs open currently, 
email account, gmail, Twitter, Facebook, YouTube, GitHub(this page)
in that order from left to right..
to test I drag the right most tab around and the movement doesn't get rendered correctly...

will clear the cache next.. brb

**Comment by MelchiorGaspar** [comment]
ok, startup cache cleared...
still happening... I drag the right most tab to the left a bit and immediately try to drag it to the right again after
so GitHub tab dragged to the left past the YouTube tab and back to the right but it doesn't allow the animation of the tab movement... but once I release the mouse click it moves it to the right back where it was ..

so an issue as the right most tab is coming up null and not or something???

**Comment by MelchiorGaspar** [comment]
![image](https://user-images.githubusercontent.com/1712842/161383176-c3ac31e6-ad03-4c9b-b8e4-9039e9cdea59.png)

**Comment by MelchiorGaspar** [comment]
08:27:35.316 this.window.gBrowserInit is undefined ext-browser.js:1102
    get activeTab chrome://browser/content/parent/ext-browser.js:1102
    candidates chrome://extensions/content/parent/ext-tabs-base.js:2066
    InterpretGeneratorResume self-hosted:1490
    next self-hosted:1438
    query chrome://extensions/content/parent/ext-tabs-base.js:2088
    next self-hosted:1438
    from self-hosted:491
    query chrome://browser/content/parent/ext-tabs.js:958
    query self-hosted:1183
    result resource://gre/modules/ExtensionParent.jsm:991
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:497
    result resource://gre/modules/ExtensionParent.jsm:991
    callAndLog resource://gre/modules/ExtensionParent.jsm:945
    recvAPICall resource://gre/modules/ExtensionParent.jsm:990
    AsyncFunctionNext self-hosted:700

not sure if this is part of the issue but I noticed it when trying to drag the right most tab around..

**Comment by MelchiorGaspar** [comment]
"can you reproduce this issue when tabs are not in overflow"
I don't have so many tabs open to go into over flow..

**Comment by onemen** [comment]
check in about:addons that you are using the new version 1.0.0-pre-7.20220402.1
![version-pre-7](https://user-images.githubusercontent.com/3650909/161383802-49a3f9cd-fc69-487e-a0c4-00d7c957d45b.png)

**Comment by MelchiorGaspar** [comment]
lol, that was the first thing I did after installing the test build.

**Comment by onemen** [comment]
Can you test it on new profile, with the same preferences

**Comment by MelchiorGaspar** [comment]
ok done, I created a new profile and got Firefox to open it in a new window and tested out only TMP pre7 and tested..
it seems to be working without issues.. 

I wonder if its a conflict with another addon?
I will test out copying some of the sqlite files including bookmarks etc to the new profile and test again...

**Comment by MelchiorGaspar** [comment]
I will install and test a few addons including: 
- uBlockOrigin
- Easy Youtube Video Downloader Express
- etc
these are the addons I use so far on my main profile
![image](https://user-images.githubusercontent.com/1712842/161384981-4dbae560-8c2d-4326-abee-a83fc60c4435.png)

**Comment by onemen** [comment]
I think there is some cache issue on your working profile.

- try to remove Tab Mix from your first profile. then close Firefox without restart.
- open Firefox, got to `about:support` and click "Clear startup cache…" to force Firefox to load to make sure the new version is loaded.
- open Firefox, and install Tab Mix, then close Firefox without restart.
- open Firefox and test Tab Mix

**Comment by MelchiorGaspar** [comment]
ok will do..
but first tested TMP with uBlockOrigin no issue yet

**Comment by MelchiorGaspar** [comment]
done... tab movement seems to be working now...
but that was only a few empty tabs including this one..
will open all the other tabs and try again..

ok all 6 tabs open and YouTube is playing...
it seems to be working correctly for sure...
and I don't know why... lol

**Comment by onemen** [comment]
Can you check what is the date of the file `BootstrapLoader.jsm` in you old profile `chrome\utils`

The latest file from [xiaoxiaoflood](https://github.com/xiaoxiaoflood/firefox-scripts) site is  Feb 19, 2022

**Comment by MelchiorGaspar** [comment]
hmm I just grabbed the latest files only a few days ago when I started to use TMP again and his bootloader for the first time..
but I will check anyway...

ohh well well...
dated: Friday, ‎February ‎4, ‎2022, ‏‎11:18:07 AM
strange as I grabbed his latest archived files just a few days ago..

**Comment by onemen** [comment]
Thank you for helping me identify this bug. 🥇 

I will publish version 1.0.0-pre-7 tomorrow

**Comment by MelchiorGaspar** [comment]
I am glad I could help.. ^_^
and thx for an awesome Firefox addon!
ok, but should I download the BootstrapLoader.jsm from his GitHub repo and replace my copy of it?
since the utils.zip archive seems to be outdated?

**Comment by onemen** [comment]
> ok, but should I download the BootstrapLoader.jsm from his GitHub repo and replace my copy of it?

No. 

I'm not sure that the cache issue was cased by BootstrapLoader.jsm.
just remember, for the next time you install new version manually, it is best to remove the old version first, and follow the steps from above

**Comment by MelchiorGaspar** [comment]
ok.
