### ISSUE TITLE
Nav tool bar hang up after pre7

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#135]
This happened to be 3 times for now.
The symptoms are: It start with one tab can not be select then the nav tool bar stop respond. Only action can be performed at this point is select and switch to another tab not the first one that stop responding. Double click on any where on tab bar is considered double click on the bar no matter it was on the tab. For me dlb click on tab bar open a new tab these tabs are not select-able at this point either.

No error msg have been seen in browser toolbox when it happens.

**Comment by onemen** [comment]
Can you provide steps to reproduce this issue?

Attach a file with your Tab Mix preferences.

**Comment by 117649** [comment]
Well, The most reliable way to trigger this for now is leave the browser open over days and put my system into sleep not shut it down at night.....
Also push the browser to a very high memory usage by open several big galleries at same time.....

But I can confirm this never happened before pre7.
In fact the very first time it happened just after the pre7 is installed. I mean literally after the .xpi is finish install. I then found I can't select a tab and nav bar start hang up.

[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/8458408/TMPpref.txt)

**Comment by onemen** [comment]
try to crate new xpi from the source code and eliminate commits that where pushed after pre.6 (https://github.com/onemen/TabMixPlus/compare/v1.0.0-pre.6...v1.0.0-pre.7) one by one.
(or do a git-bisect if you know how)

**Comment by 117649** [comment]
> try to crate new xpi from the source code (include only the content of [addon](https://github.com/onemen/TabMixPlus/tree/main/addon) folder) and eliminate commits that where pushed after pre.6 ([v1.0.0-pre.6...v1.0.0-pre.7](https://github.com/onemen/TabMixPlus/compare/v1.0.0-pre.6...v1.0.0-pre.7)) one by one. (or do a git-bisect if you know how)

I don't think it worth to go this far or doing this can yield any positive result since there is not a clear way to reproduce it.
I'd say we keep this as a record and wait to see if any more evidence coming up.

**Comment by onemen** [comment]
So far I can't reproduce this issue.
How you `open a link in a background tab` ?

**Comment by 117649** [comment]
> How you `open a link in a background tab` ?

Click with mouse wheel or use DnD extension.
But keep in mind this doesn't means perform such operation can cause the problem. It is more of a random thing.

**Comment by onemen** [comment]
can you post a link to DnD extension?

**Comment by 117649** [comment]
https://github.com/117649/EasyDragToGoPlus-Redux
https://addons.mozilla.org/en-US/firefox/addon/smartup/

**Comment by 117649** [comment]
It just happened again and this time it just during normal tab switching not opening any new tabs weird.

**Comment by onemen** [comment]
try to apply this patch to `chrome/content/overlay/browser.css`

```diff
-/* for the case user drag background tab
-   when selectTabOnMouseDown is false, Firefox 17.0+ */
+/* for the case user drag background tab when selectTabOnMouseDown is false */
 #tabbrowser-tabs[movingBackgroundTab] > #tabbrowser-arrowscrollbox > .tabbrowser-tab[dragged] {
   position: relative;
   z-index: 3;
   pointer-events: none; /* avoid blocking dragover events on scroll buttons */
 }
 
-#tabbrowser-tabs[movingBackgroundTab] > #tabbrowser-arrowscrollbox > .tabbrowser-tab[fadein]:not([dragged]) {
-  transition: transform 200ms ease-out;
+#tabbrowser-tabs[movingBackgroundTab] > #tabbrowser-arrowscrollbox > .tabbrowser-tab:not([tabdrop-samewindow])[dragged] {
+  transition: none !important;
+}
+
+@media (prefers-reduced-motion: no-preference) {
+  #tabbrowser-tabs[movingBackgroundTab] > #tabbrowser-arrowscrollbox > .tabbrowser-tab[fadein]:not([dragged]) {
+    transition: transform 200ms var(--animation-easing-function, ease-out);
+  }
 }
```

**Comment by 117649** [comment]
> try to apply this patch to `chrome/content/overlay/browser.css`
> 
> ```diff
> -/* for the case user drag background tab
> -   when selectTabOnMouseDown is false, Firefox 17.0+ */
> +/* for the case user drag background tab when selectTabOnMouseDown is false */
>  #tabbrowser-tabs[movingBackgroundTab] > #tabbrowser-arrowscrollbox > .tabbrowser-tab[dragged] {
>    position: relative;
>    z-index: 3;
>    pointer-events: none; /* avoid blocking dragover events on scroll buttons */
>  }
>  
> -#tabbrowser-tabs[movingBackgroundTab] > #tabbrowser-arrowscrollbox > .tabbrowser-tab[fadein]:not([dragged]) {
> -  transition: transform 200ms ease-out;
> +#tabbrowser-tabs[movingBackgroundTab] > #tabbrowser-arrowscrollbox > .tabbrowser-tab:not([tabdrop-samewindow])[dragged] {
> +  transition: none !important;
> +}
> +
> +@media (prefers-reduced-motion: no-preference) {
> +  #tabbrowser-tabs[movingBackgroundTab] > #tabbrowser-arrowscrollbox > .tabbrowser-tab[fadein]:not([dragged]) {
> +    transition: transform 200ms var(--animation-easing-function, ease-out);
> +  }
>  }
> ```

So far, it not make things worse anyway.

**Comment by onemen** [comment]
Let me know if this issue will happen again
