### ISSUE TITLE
Useless new tab on address bar

### ISSUE THREAD

**Issue by Massimo-B** [onemen/TabMixPlus#136]
Curiously I get too many new tabs for these scenarios:
Focussing the address bar and pressing enter makes a new duplicated tab appear.
Doing a CTRL+T for a new tab, entering something into the address bar, hitting enter, creates another new tab.

Which setting is wrong here? Something around Events->Tab Opening?

**Comment by onemen** [comment]
Attach a file with your Tab Mix preferences

**Comment by onemen** [comment]
It probably this preference:

![addressbar](https://user-images.githubusercontent.com/3650909/164171888-26e75c77-04d7-4cef-beb6-b7dae15a2f94.png)

**Comment by Massimo-B** [comment]
Thanks, that's it. Solved.
