### ISSUE TITLE
TabMixPlus Preferences into the Firefox settings

### ISSUE THREAD

**Issue by Massimo-B** [onemen/TabMixPlus#137]
Are you able to put a link for the TMP Preferences into the Firefox settings?
Right now the only way to get to the TMP Preferences is via about:addons

**Comment by onemen** [comment]
You can add it to Tools menu
https://tabmixplus.org/support/viewtopic.php?t=3&p=events-tab-opening

**Comment by Massimo-B** [comment]
Is that URL correct? How do I add it to the Tools menu?

**Comment by Massimo-B** [comment]
Found it in Options->Menu->[x]Tab Mix Plus Options...
Now I find it in the Tools menu. Thanks.
It's not possible to have it in Application Menu->More Tools...?
I usually have the old-fashion File, Edit, View... menus hidden, still available via Alt button.

**Comment by onemen** [comment]
there is no point of adding this option to more places.

You can install `Extension Options Menu` script from https://github.com/xiaoxiaoflood/firefox-scripts#instructions

**Comment by Massimo-B** [comment]
Thanks.
