### ISSUE TITLE
Remove a tab from "reopen last close tab" list when the website history is deleted

### ISSUE THREAD

**Issue by Tsharii** [onemen/TabMixPlus#138]
I use an extension named "Delete Browsing History of Domain of Current Page" (it's a very long name).

When I delete the browser history for a domain, the tabs related to this domain still in the "reopen last close tab" list from tab mix plus extension.

Is it normal ?

Also I traduce some lines of the French language for tab mix plus. I am searching how to put that files to be validated by other developers.

Thanks,
Kind regards.

**Comment by onemen** [comment]
can you attach files with your preferences to both extensions "Delete Browsing History of Domain of Current Page" and **Tab Mix Plus**

**Comment by Tsharii** [comment]
There is no preference for the "Delete Browsing History of Domain of Current Page" I invite you to download it.
I send you the tabmixplus preferences
![extension to delete history site tab sub menu](https://user-images.githubusercontent.com/46133147/164404178-fae4388d-f1c9-42a2-8574-dc25fd82a246.png)
![extension to delete history site button and popup](https://user-images.githubusercontent.com/46133147/164404186-0279c0d6-1075-4512-9f3f-a55de73935e1.png)
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/8528733/TMPpref.txt)

**Comment by onemen** [comment]
I've just tested  "Delete Browsing History of Domain of Current Page" on profile without Tab mix

The extension does not remove the entry from `close tab list`, this list handled by Firefox not by Tab mix

Report about the issue to "Delete Browsing History of Domain of Current Page" developer

**Comment by Tsharii** [comment]
I will do that ! Thanks.
Can I send you the files I finish to traduce in French ?

**Comment by onemen** [comment]
> Can I send you the files I finish to traduce in French ?

I don't understand what you want to send, I don't read French

**Comment by onemen** [comment]
@Tsharii 
To post new localization
update all files locally and attach to issue **Localization #72** zip file from the locale/fr folder

**Comment by onemen** [comment]
Feel free to ping me if this is still an issue and I can reopen.
