### ISSUE TITLE
Script no longer works with new config.js

### ISSUE THREAD

**Issue by NoNameNeeded2** [onemen/TabMixPlus#141]
I've copied the needed config.js to the Firefox folder but unfortunately this script now no longer works.

`//  Downloadbutton.uc.js

....

**### It did however work with the old config.js which was this one:**

`// config.js
const Cu = Components.utils;

try {

	Cu.import("resource://gre/modules/Services.jsm");
	Cu.import("resource://gre/modules/osfile.jsm");

	if (!Services.appinfo.inSafeMode) {
		let path = OS.Constants.Path.libDir;
		if (Services.appinfo.OS == 'Darwin') {  // macOS
			path = OS.Path.join(OS.Path.dirname(path), "Resources");
		};
		var ucjsDirPath = OS.Path.join(path, "userChromeJS");
		path = OS.Path.join(ucjsDirPath, "main.js");
		let mainFileURI = OS.Path.toFileURI(path);
		Services.scriptloader.loadSubScript(mainFileURI, this, "UTF-8");
	};

} catch(e) {
	Cu.reportError(e);
};`

**Comment by NoNameNeeded2** [comment]
P.S: What I mean by "new config.js" is the one that is needed to use TMP.

**Comment by onemen** [comment]
This issue is not related to Tab mix.

Report about it in the original `Downloadbutton.uc.js` [repository](https://github.com/Endor8/userChrome.js) and in the `config.js` [repository](https://github.com/xiaoxiaoflood/firefox-scripts)
