### ISSUE TITLE
cannot use the default shortcut for reopen closed tab ctrl+shift+t

### ISSUE THREAD

**Issue by Jerrk** [onemen/TabMixPlus#142]
![](https://i.imgur.com/sM9qoNi.png)

hitting ctrl+shift+t with the firefox window focused doesn't seem to do anything.
with the plugin disabled and a browser restart the shortcut works as normal.

v1.0.0-pre.7
firefox 100.0.1

**Comment by onemen** [comment]
What is is you operating system?
Do you see the same issue on clean profile ?

Make sure in `about:config` that `devtools.browserconsole.contentMessages` is true

Then check the browser console after Firefox starts, report about any messages use see

**Comment by Jerrk** [comment]
Windows 10

I do **not** see the issue on a clean profile.

I found that the NoScript plugin is what causes this issue, though i'm not sure why exactly. 
This is reproducible in a clean profile with only noscript and tabmix installed.

Made a gif of the issue here:
![](https://i.imgur.com/cP6yPdO.gif)

**Comment by onemen** [comment]
Post your Tab mix preferences and NoScript preferences

**Comment by Jerrk** [comment]
It works with default settings 
![](https://i.imgur.com/spPhUA5.gif)

Just incase my default settings are different somehow here they are:
[noscript_data.txt](https://github.com/onemen/TabMixPlus/files/8738076/noscript_data.txt)
[TMPpref1.txt](https://github.com/onemen/TabMixPlus/files/8738079/TMPpref1.txt)

**Comment by Jerrk** [comment]
I found that if i disable noscript and then refresh the keyboard shortcut and then re-enable noscript, the shortcut will work until browser restart.

So its possible to work around it but very inconvenient

**Comment by Jerrk** [comment]
will do, thanks!

**Comment by onemen** [comment]
NoScript use this shortcut

this is the from the file manifest.json in NoScript
```
  "commands": {
    "_execute_browser_action": {
      "description": "NoScript UI",
      "suggested_key": {
        "default": "Alt+Shift+N"
      }
    },
    "togglePermissions": {
      "description": "Toggle permissions",
      "suggested_key": {
        "default": "Ctrl+Shift+T"
      }
    }
  }
```

Look here https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
how you can modify the shortcuts NoScript use

**Comment by Jerrk** [comment]
:facepalm: that was easy 
![](https://i.imgur.com/5pnBQ3m.png)

It works without issue now, thanks again :smile:

**Comment by onemen** [comment]
next version will show extension name for duplicate shortcut:

![image](https://user-images.githubusercontent.com/3650909/169691938-06affcfa-afd3-46e2-9f2f-118458dffe21.png)
