### ISSUE TITLE
Mousewheel to change tabs?

### ISSUE THREAD

**Issue by XeonG** [onemen/TabMixPlus#143]
Does this even work in TMP? There was a userscript that does sort of work.. but with TMP it doens't work at all and I don't see any options for it now?

**Comment by onemen** [comment]
![mousewhell](https://user-images.githubusercontent.com/3650909/170658099-197c6297-04e6-42ff-b2c1-d0cdd59d6441.png)

**Comment by XeonG** [comment]
ah thanks missed it... "Scroll all tabs" should be nuked.. dumbest  most annoying thing those Mozilla idiots ever added.
