### ISSUE TITLE
FF102 tool bar button before tabs bar be overlaped by pinned tab

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#146]
![image](https://user-images.githubusercontent.com/8281345/173196854-e95996c9-28f7-4dab-b472-9a9f08c4100b.png)
Home button at left of tabs bar with pinned tab and tabs bar overflowed.

**Comment by onemen** [comment]
This issue was fixed by commit 89924e8a9cb257d0bb9245420a0ef504ed4b3956

Use version [1.0.0-pre.8](https://github.com/onemen/TabMixPlus/releases/tag/v1.0.0-pre.8)
