### ISSUE TITLE
Addon not signed

### ISSUE THREAD

**Issue by Massimo-B** [onemen/TabMixPlus#147]
Is it right that the Addon is not signed?
With Firefox ESR and `xpinstall.signatures.required` to `false` it seems to load but I still see the warning. Is this option required for TMP?

Could you put a message about Addon signature on the github page?

**Comment by dsyo2008** [comment]
The same problem, now suddenly disabled, try xpinstall.signatures.required, still warning can not be used

**Comment by 117649** [comment]
restart browser

**Comment by onemen** [comment]
Just Installed Firefox ESR on Windows 10, without any issue or warning.

You can ignore Firefox warning regarding any legacy extensions you install with userChromeJS scripts.

If you want to remove this warning try this steps:
- Reinstall latest version of [userChromeJS](https://github.com/xiaoxiaoflood/firefox-scripts#instructions).
- Open **about:support** and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup.
- Reinstall latest **Tab Mix Plus** again.

**Comment by dsyo2008** [comment]
![图片](https://user-images.githubusercontent.com/3739056/173384841-68e2c235-0cab-4024-853a-10e841ac5cfa.png)
![图片](https://user-images.githubusercontent.com/3739056/173385045-8e613a27-c5e5-42d0-8615-abd3f6368e5a.png)
![图片](https://user-images.githubusercontent.com/3739056/173384889-68244735-d909-4065-8a91-a3eecb34bfa6.png)
Tried it but it didn't work

**Comment by dsyo2008** [comment]
> 

Okay, let's see this weekend

**Comment by halt76** [comment]
No good.
I can't even install with a new profile.

It is now dead in 102.0b7.
It is working fine on b6.

**Comment by Massimo-B** [comment]
>     * Reinstall latest version of [userChromeJS](https://github.com/xiaoxiaoflood/firefox-scripts#instructions).
>     * Open **about:support** and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup.
>     * Reinstall latest **Tab Mix Plus** again.

Weird, it seems had that userChromeJS not installed as there was no /usr/lib64/firefox/config.js. But TMP was was and is still working. Anyway, I'm following the instructions and have some issues with the installation on Linux: #148

**Comment by Massimo-B** [comment]
As explained in the other ticket, all is working fine without warnings after removing bootstraploader and installing userChromeJS.

**Comment by 117649** [comment]
@dsyo2008 @halt76 @onemen 
I saw this issue have been resolved by userChromeJS:
https://github.com/xiaoxiaoflood/firefox-scripts/issues/146#issuecomment-1157255047

It seems OK to close this issue?

**Comment by dsyo2008** [comment]
> @dsyo2008 @halt76 @onemen I just saw this issue have been resolved by userChromeJS:[xiaoxiaoflood/firefox-scripts#146 (comment)](https://github.com/xiaoxiaoflood/firefox-scripts/issues/146#issuecomment-1157255047)
> 
> It seems OK to close this issue?
thanks, it works
