### ISSUE TITLE
How to install required userChromeJS on Linux

### ISSUE THREAD

**Issue by Massimo-B** [onemen/TabMixPlus#148]
Coming from [Addon not signed #147](https://github.com/onemen/TabMixPlus/issues/147#issuecomment-1154789534) I realized I had no userChromeJS installed as there was no /usr/lib64/firefox/config.js. But TMP was was and is still working. Anyway, I'm following the instructions and have some issues with the installation on Linux. I'm filing the issue here as xiaoxiaoflood provides many options and I only like to have a working setup for TMP.

Following the instructions https://github.com/xiaoxiaoflood/firefox-scripts#instructions
I copied these 2 files according to my www-client/firefox-91.9.1(esr) on Gentoo Linux:

* /usr/lib64/firefox/config.js
* /usr/lib64/firefox/browser/defaults/preferences/config-prefs.js

Then I've choosen

> * [utils → I'm interested in both scripts and extensions](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/utils.zip)

**Now the question:**
For section

> 4. Save the desired [userChromeJS scripts](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/chrome) into chrome. Read below the description of some of them.

..which of the files do I need?

**Comment by 117649** [comment]
> I had no userChromeJS installed as there was no /usr/lib64/firefox/config.js. But TMP was was and is still working. 

Then 
1: you may have using bootstraploader.xpi or a FF distribution already include one, meaning Waterfox.
2:  you have userChromeJS installed but may lost some file of the installation or you just not found the right path of the installation.

The point is DO NOT use userChromeJS extension and bootstraploader.xpi at same time.
Which could result 2 addon loader and load your addon twice that is not good.

**Comment by Massimo-B** [comment]
> you may have using bootstraploader.xpi

Exactly, that I have, eventhough I have Firefox ESR and not Developer or Nightly.
So you recommend the first option with userChromeJS for FF ESR and I should remove the bootstraploader Addon?

**Comment by Massimo-B** [comment]
That all is working with userChromeJS now after removing the bootstraploader.
No warning anymore.
Though I would prefer having an xpi that I can keep updated automatically. For the userChromeJS I need to take care if there are updates.

**Comment by 117649** [comment]
> That all is working with userChromeJS now after removing the bootstraploader. No warning anymore. Though I would prefer having an xpi that I can keep updated automatically. For the userChromeJS I need to take care if there are updates.

Security policy of release channel of Firefox should not allow running bootstraploader at all.
Yes. You can still install it but it should not functioning properly.
