### ISSUE TITLE
Reload tab every... for keeping login sessions alive

### ISSUE THREAD

**Issue by Massimo-B** [onemen/TabMixPlus#149]
One of the powerful features of TMP is the automatic "Reload tab every...minutes".
I planned to use that for keeping my Online-Banking session alive. Usually it logs out after about 5 minutes which is annoying for daily work.

So I have a main dummy tab open and reloading, while working on some other tabs.
But it's not working. Have you tried this approach? Does TMP do a simple Refresh or a deep Refresh? Actually both should keep my session alive. I'm not sure if the website can distinguish silly reloads or real hyperlink jumps on the page.

**Comment by onemen** [comment]
If you bank site work when you manually do "Reload Tab" fro tab context menu, then is should also work with "Reload tab every..."

**Comment by onemen** [comment]
> So I have a main dummy tab open and reloading, while working on some other tabs.

Reloading one tab should not have any effect on you login state in other tabs

**Comment by Massimo-B** [comment]
> Reloading one tab should not have any effect on your login state in other tabs

Sure it has, at least for tabs within the same session and tab container.
Sometimes it works. I just had the banking session opened now for 1 hour with 3 tabs opened and auto-reload enabled on one tab, without touching the browser during that time.
However sometimes it doesn't work.
This thread should rather be a discussion with users having experience with that. The TMP feature itself seems to work as expected.

**Comment by onemen** [comment]
You can start a discussion in our forum (https://tabmixplus.org/forum/)

Tab Mix auto-reload just mimic Firefox operation of reloading a tab.
