### ISSUE TITLE
Single Window Mode

### ISSUE THREAD

**Issue by banta84** [onemen/TabMixPlus#151]
Hi! after version pre.4 option "Enable Single Window Mode" stops preventing launch other copies firefox when clicking its shortcut. Earler at pre.4 just appear new tab in same application, but later starts other and other firefox windows.... It is intended work or bug?

Tested at firefox 102.0

**Comment by onemen** [comment]
Do you see any messages in the browser console after starting the 2nd window from a shortcut?

**Comment by banta84** [comment]
> Do you see any messages in the browser console after starting the 2nd window from a shortcut?

Applying chrome://tabmixplus/content/tabmix.xhtml to chrome://browser/content/browser.xhtml [Overlays.jsm:90:15](chrome://tabmix-resource/content/bootstrap/Overlays.jsm)
Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml [Overlays.jsm:90:15](chrome://tabmix-resource/content/bootstrap/Overlays.jsm)
Loading eval'd script into chrome://browser/content/browser.xhtml [Overlays.jsm:544:15](chrome://tabmix-resource/content/bootstrap/Overlays.jsm)
Tabmix initializer: 
Object { key: "init", phase: {…} }
[tabmix.js:1140:17](chrome://tabmixplus/content/tabmix.js)
Tabmix initializer: 
Object { key: "beforeStartup", phase: {…} }
[tabmix.js:1140:17](chrome://tabmixplus/content/tabmix.js)
Tabmix initializer: 
Object { key: "onContentLoaded", phase: {…} }
[tabmix.js:1140:17](chrome://tabmixplus/content/tabmix.js)
Tabmix initializer: 
Object { key: "beforeBrowserInitOnLoad", phase: {…} }
[tabmix.js:1140:17](chrome://tabmixplus/content/tabmix.js)
Tabmix initializer: 
Object { key: "onWindowOpen", phase: {…} }
[tabmix.js:1140:17](chrome://tabmixplus/content/tabmix.js)
Tabmix initializer: 
Object { key: "afterDelayedStartup", phase: {…} }
[tabmix.js:1140:17](chrome://tabmixplus/content/tabmix.js)

Not sure how to export full log with expanded strings...just copy-past?

**Comment by onemen** [comment]
Post your Tab Mix preferences as a file

**Comment by banta84** [comment]
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/9032633/TMPpref.txt)

**Comment by onemen** [comment]
download and try the new [test build](https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.8/test_build_tab_mix_plus-1.0.0-pre.9.20220702.1.xpi)

**Comment by banta84** [comment]
1.0.0-pre.9.20220702.1 Nothing changed, after resetting settings too((

**Comment by onemen** [comment]
Thank you for the test.

The good news is that this issue is fixed.

Regarding `PlacesUtils is not defined` issue, it is due to [c6d6d22](https://github.com/onemen/TabMixPlus/commit/c6d6d22cf2b5d2755047cf341c5d1c3e6e25426c#diff-5df73bac872b9017467f3e8cfac8bda3d05075fda0f950d1ad8572934c008906).
The Patch work for Firefox Beta (103) and Nightly (104), I am currently working on making it work for old version before uploading version 1.0.0-pre.9

I've pushed another test build with the fix for #151 without `PlacesUtils is not defined`
Download and try the new [test build](https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.8/test_build_tab_mix_plus-1.0.0-pre.9.20220703.1.xpi)

**Comment by banta84** [comment]
> Thank you for the test.
> 
> The good news is that this issue is fixed.
> 
> Regarding `PlacesUtils is not defined` issue, it is due to [c6d6d22](https://github.com/onemen/TabMixPlus/commit/c6d6d22cf2b5d2755047cf341c5d1c3e6e25426c#diff-5df73bac872b9017467f3e8cfac8bda3d05075fda0f950d1ad8572934c008906). The Patch work for Firefox Beta (103) and Nightly (104), I am currently working on making it work for old version before uploading version 1.0.0-pre.9
> 
> I've pushed another test build with the fix for #151 without `PlacesUtils is not defined` Download and try the new [test build](https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.8/test_build_tab_mix_plus-1.0.0-pre.9.20220703.1.xpi)

Tested 1.0.0-pre.9.20220703.1. Now works both single window mode and bookmark panel! Thank you!
