### ISSUE TITLE
Double click can't open history from managing all history

### ISSUE THREAD

**Issue by klcb2010** [onemen/TabMixPlus#152]
the  v1.0.0-pre.8 and pre.9 ,Double click can't open history from managing all history，on firefox98-102，but v1.0.0-pre.7 is working good

**Comment by onemen** [comment]
Post your Tab mix preferences as a file
do you see any messages in the browser console after trying to open history
can you open history from history sidebar>

**Comment by klcb2010** [comment]
> Post your Tab mix preferences as a file do you see any messages in the browser console after trying to open history can you open history from history sidebar>

[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/9076036/TMPpref.txt)
can you open history from history sidebar>，yes i can.

**Comment by onemen** [comment]
I can not reproduce this issue

**Comment by klcb2010** [comment]
> 

test  on https://www.lanzoui.com/izCFL07gg50f

**Comment by onemen** [comment]
Thank you for the error report, it will help me solve this issue.

**Comment by onemen** [comment]
Are you using any other extensions or scripts ?

**Comment by onemen** [comment]
Download and install this [test build](http://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.9.20220709.1.xpi)

**Comment by klcb2010** [comment]
> Are you using any other extensions or scripts ?

The extensions and scripts I use come from

**Comment by klcb2010** [comment]
> Download and install this [test build](http://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.9.20220709.1.xpi)

Now it working good on fox-102，not test on 98， Thank you for your hard work
