### ISSUE TITLE
Locked tabs still change to different URL with target="_self"

### ISSUE THREAD

**Issue by JimDanner** [onemen/TabMixPlus#153]
A [locked tab](https://tabmixplus.org/support/viewpage.php?t=3&p=frozen_tabs) is "a tab that is prevented from navigating to another page or URL." But that does not work when you click on a link on the page that has the attribute `target="_self"`.

This may be the intention of the makers of such webpages, but of course TMP serves to give us more control.

To reproduce:

1. Open [nu.nl](https://www.nu.nl/)
2. Lock the tab
3. Click on a link on the page to an article (most links there have that attribute)

Expected result would be a new tab, and actual result is that the current tab navigates to a different URL.

**Comment by onemen** [comment]
Download and install this [test build](http://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.9.20220709.2.xpi)

**Comment by JimDanner** [comment]
Yes, that has solved the issue
