### ISSUE TITLE
Allow hiding (removing) tab-row scroll arrows

### ISSUE THREAD

**Issue by JimDanner** [onemen/TabMixPlus#154]
When not all tab rows fit in the available space, scrolling arrows appear to the right of the tabs. If the user has the following setup:
<img width="600" alt="Screenshot 2022-07-09 at 18 02 44" src="https://user-images.githubusercontent.com/87583812/178115528-22df019d-343b-4386-92e1-ada8a27e3b29.png">
with the mouse gestures set as follows:
<img width="600" alt="Screenshot 2022-07-09 at 18 03 42" src="https://user-images.githubusercontent.com/87583812/178115549-bc8797b2-af66-4d95-8055-6ffd7dddd6df.png">

then the scroll arrows are not needed: if more than 3 rows of tabs are present, the rows can be scrolled with the mouse wheel.

Could it be an option to not display the scroll arrows? I have now hidden them in userChrome.css with

```css
#tabmix-scrollbox {
	display: none !important;
}
```

but it would be cleaner to have an option for it.

**Comment by onemen** [comment]
> but it would be cleaner to have an option for it.

It will require more code then the 3 line you added above:
- new style in our css file
- new preference
- code to show the new preference in our preference window
- label translation to all languages we include.

If we start adding more preference we just bloat the extension.

The style you are using is the best solution.
