### ISSUE TITLE
Tabs opened from a pinned tab have strange placement

### ISSUE THREAD

**Issue by JimDanner** [onemen/TabMixPlus#155]
When I open a new tab from a link on a page that is open in a pinned tab, the new tab appears all the way on the top left, at the same location as the first pinned tabs. **EDIT:** it also happens with new tabs opened from search, history etc., as long as they are opened when a pinned tab is active.

Situation before opening the new tab (the second pinned tab is active):
<img width="117" alt="Screenshot 2022-07-09 at 19 08 42" src="https://user-images.githubusercontent.com/87583812/178116021-626f9615-35ac-4906-827f-f1980baf57b8.png">

Situation right after opening the new tab in the background:
<img width="97" alt="Screenshot 2022-07-09 at 19 09 01" src="https://user-images.githubusercontent.com/87583812/178116037-e0edc138-f93f-4ad0-9f04-da671fd430a1.png">

Situation after switching to the newly opened tab:
<img width="119" alt="Screenshot 2022-07-09 at 19 09 17" src="https://user-images.githubusercontent.com/87583812/178116054-bef8d74d-f38a-4d2e-9bf2-23e0cc2877c9.png">
(The pinned tabs are now behind the new tab.)

The new tab can then be dragged and placed between the normal tabs – but it should have opened there in the first place.

This is with TMP 1.0.0-pre.8 in Firefox 102.0.1 on macOS 12.4. My TMP settings are attached.
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/9077575/TMPpref.txt)

**Comment by onemen** [comment]
I don't see this issue on my windows 11, I will try to install macOS 12.4 on my virtual machine

**Comment by JimDanner** [comment]
It is worth remarking that the problem only happens when tab-row-scrolling is possible, i.e. when there is at least one invisible tab row. So for example:

- I have 32 tabs; they just fit in my 3 tab rows -> the new tab is opened in the correct location. (It now adds a fourth tab row and enables tab-row scrolling)
- Now I have 33 tabs, of which the last 3 or so are in the fourth, invisible, tab row (more than just one because the scrollability has re-arranged the tabs). If I open a new tab while a pinned tab is open, the problem now happens.
- Now I close 3 tabs, so I have 31 -> the problem still happens, because there is still a hidden tab row
- I close 3 more so we go back to 3 tab rows -> the problem now disappears.

I note that there is one additional odd behavior: when I increase the number of tabs until an additional row is needed, and then close one tab, the additional row stays. I have to close more tabs before it disappears. There is no calculation of whether one fewer tab row would be enough; the row disappears only when it has become empty.

**Comment by onemen** [comment]
Download and install this [test build](http://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.9.20220710.1.xpi)

**Comment by onemen** [comment]
I don't check for this case when the last row have more that one tab in order to avoid flickering by hide/show the scroll arrow.

**Comment by JimDanner** [comment]
Right, that's the chicken-and-egg problem: because of the scroll arrows, the hidden row has more than one tab; because the hidden row still has a tab after one was closed, the scroll arrows are on screen.
