### ISSUE TITLE
1.0.0-pre.8: Tab Dragging seems to be broken for Multi-Row tabs

### ISSUE THREAD

**Issue by JesseNewman19** [onemen/TabMixPlus#156]
Hard to pinpoint exactly which release bricked this, but ever since FF 101 when I was forced to re-apply UserChromeJS and download the latest TabMixPlus update [1.0.0-pre.8](https://github.com/onemen/TabMixPlus/compare/v1.0.0-pre.7...v1.0.0-pre.8) I have been unable to drag tabs correctly. No matter what I do it will always attempt to drag it to the very end of the tab list, regardless of which row the tab is on.

**Comment by onemen** [comment]
Attach a file with your Tab Mix preferences.

Do you see any message in the browser console after trying to drag a tab?
Do you see the same issue on clean profile with only Tab Mix installed ?

**Comment by JesseNewman19** [comment]
No console messages on tab dragging. Attaching my preferences and will test a new profile shortly.
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/9087369/TMPpref.txt)

**Comment by JesseNewman19** [comment]
A new profile did not experience the issue. I imported my preferences that I posted here and still did not experience the issue. At this point I assumed that something got corrupted with my TMP install, so I removed it from my main profile, restarted firefox, and then reinstalled the extension and everything is now working correctly. Closing issue.
