### ISSUE TITLE
New tab has no URL display in Address Bar

### ISSUE THREAD

**Issue by Sqrlly** [onemen/TabMixPlus#157]
Using TMP v1.0.0-pre.9 with Waterfox G4 1.3.2.  When I open a new tab (any means, Ctrl+T, File -> New Tab, "+" button by tabs, New tab (after this tab)) first off the address bar is empty and has the focus with the background "Search with <your search engine> or enter a url" text.  This part is okay as can just type an address and hit enter.  But it is a change from earlier behavior where it had the URL of the new tab, unselected, and you would have to hit Ctrl+A before typing a new address.  This is an improvement, but I feel the preferred behavior would be for it to have the new tab URL and it be selected so you can type and replace it.

The problem though comes in after you take any of these actions:

- Move the focus from Address Bar entry (tab, or clicking elsewhere).  Esc is the exception here and actually works as expected.
- Click a link on the new tab
- Enter a URL in the address bar and hit enter

When doing one of those the Address Bar remains blank, not even showing the address just typed in there, with the background text to enter a search or address.

The address can be made to display if you switch to another tab and then back to the affected tab, the URL will now show in the Address Bar.

I use a custom New Tab page which is a local HTML file with various links.

**Comment by onemen** [comment]
Can you attach your tabmix preferences as a file.

Do you see any messege in the browser console.

**Comment by Sqrlly** [comment]
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/9197110/TMPpref.txt)

Only this upon opening a new tab:

```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. informenter-background.js:174
    on_tab_activated moz-extension://f32914f0-3fdc-44c2-977f-50b8d90771c3/informenter-background.js:174
```
Doesn't look TMP related.  Let me know if want to test for anything else.  TMP seems to be working normally otherwise.

Also I notice it actually seems to happen when I go to any new page/URL.  Such as clicking a link on a page.  Not only the ones described above.

**Comment by onemen** [comment]
Download and install this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.10.20220727.1.xpi)

**Comment by Sqrlly** [comment]
Well it's different now.  When I open a new tab and either click a link or type a url and hit enter it shows a url in the address bar, but it's the url of my new tab page, not the page I went to.  Even if I then switch to another tab and come back it still has the url of the new tab page and not the page that is up.  If I then go to another url, like a google result or something, the address bar updates correctly.

**Comment by onemen** [comment]
2nd try
Download and install this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.10.20220728.1.xpi)

**Comment by Sqrlly** [comment]
Looking good!  I would be perfectly fine with it just like this.  Only minor suggestion I would have would be when opening the new tab instead of the address bar being blank for input, have the new tab url there and the text selected.  But hitting Esc brings the URL back (or clicking outside of the address bar), so not much of a concern.  Just remembering the old behavior. :-)

Thanks for the fix!
