### ISSUE TITLE
Cannot install TMP in Firefox

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#158]
Running Firefox 103.0, which I believe is the current version. When I click on the xpi link to install the current version of TMP, Firefox reports that the file is corrupt and cannot be installed. Is there something I need to know? Thank you.

**Comment by onemen** [comment]
try to download the xpi file to your computer, then install the extension from a file.
if you still have an issue update [userChromeJS](https://github.com/xiaoxiaoflood/firefox-scripts#instructions) files

**Comment by VLM-TechEd** [comment]
Up and running, thank you. Okay to close.
