### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Mrsash2020** [onemen/TabMixPlus#162]
Sorry to bring this up again. Had Win7/Win11 dual boot with both working fine pointing to profile on D drive for seamless move for a few months now. Just decided to move to Win11. Installed the latest update for firefox for Win11 and it seems to be broken again. Only thing that could be an issue as per instructions [https://github.com/xiaoxiaoflood/firefox-scripts#instructions](url).
I have copied the files to C:\Program Files\Mozilla Firefox, but still no joy. Keeps saying add on disabled.

Update: Ok after a few tries its showing as installed but nothing is as per my settings and I cant bring up the TMP options to edit settings etc.

Win 11
Latest firefox

**Comment by onemen** [comment]
Maybe it is cache issue

After you make 100% sure that you have installing latest version of userChromeJS (bootstarpLoader) properly, do the following:
- Remove old install of Tab Mix Plus.
- Open about:support and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup.
- Close Firefox again (don't use restart).
- Start Firefox.
- Install Tab Mix Plus.

**Comment by Mrsash2020** [comment]
Did that and it now says addon appears to be corrupt.

Question: You are referring to this instruction when you say installed bootstrap?
1 Download this zip file and extract its content to Firefox installation folder (usually C:\Program Files\Mozilla Firefox). For Linux paths, read this. And this for macOS paths.

**Comment by onemen** [comment]
@Mrsash2020

I'm referring to all the instructions in [xiaoxiaoflood repositoty](https://github.com/xiaoxiaoflood/firefox-scripts#readme)
You have to follow all the instructions steps 1-6.

If you see the warning `addon appears to be corrupt` when you try to install, than most likely you did not install the scripts correctly.
make sure that in your user profile there is `chrome` folder, and that it contain `utils` folder with this files


![files](https://user-images.githubusercontent.com/3650909/188864018-313a48f2-b0da-4a51-9bd7-13f4c1879a9d.png)

**Comment by Mrsash2020** [comment]
@onemen 

Definitely followed the instructions. Its been working perfectly on the win 7 with only minor issues with win 11 rarely.

The D:\Firefox\ is the profile folder being accessed by both win7 and win 11 firefox installs so not sure why win 11 troubles me this time. Scratching my head here.

![Screenshot 2022-09-07 214812](https://user-images.githubusercontent.com/62192773/188871539-79fdf29f-17c8-4a5b-8593-a7f9821ec4ee.png)

**Comment by onemen** [comment]
try to create new clean profile for windows 11, don't copy anything from the old profile

**Comment by Mrsash2020** [comment]
We were on the same wavelength. Redid everything and it works, yay!!!!

Thanks again for your help.

**Comment by Mrsash2020** [comment]
Ok spoke too soon. My bookmarks wont open from the bookmark list now. Disabling TMP and restarting works for bookmarks. Unsure what I did wrong. Any thoughts?

**Comment by onemen** [comment]
Do you see any messages in the browser console after you try to open your bookmarks?

**Comment by Mrsash2020** [comment]
Ok renamed each of the things I downloaded and found the culprit to be privateTab.uc.js.

**Comment by onemen** [comment]
> Sorry didnt check the console. I assume you mean Ctl+Shift+K console right?

No. Its Ctl+Shift+j, look in Tools menu > Browser Tools > Browser console

> Ok renamed each of the things I downloaded and found the culprit to be privateTab.uc.js. renamed to privateTab.uc.js.bak
> 
> I noticed they were all named *.js.html previously. Guess I wasn't using any of it so didn't notice. Yesterday when I "right clicked > Save link as" resulted in *.html files. Therefore copy pasted code in notepad and changed extension to *.js.

You probably downloaded some *uc.js scripts from https://github.com/xiaoxiaoflood/firefox-scripts.

Make sure you are using the latest version of each script.
If you are planing to use scripts as well as legacy extensions (Tab mix plus and other...) the you need to install 
[utils → I'm interested in both scripts and extensions](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/utils.zip)

**Comment by Mrsash2020** [comment]
> No. Its Ctl+Shift+j, look in Tools menu > Browser Tools > Browser console
> 
Renamed privateTab.uc.js.bak to privateTab.uc.js. Closed ans opened FF. clicked bookmark.
![image](https://user-images.githubusercontent.com/62192773/189232673-cbf948fc-5b17-47b4-97d2-8a796f453a96.png)


> You probably downloaded some *uc.js scripts from https://github.com/xiaoxiaoflood/firefox-scripts.
> 
From here the scripts save as html https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/chrome
From here(bottom of page with individual links) as txt files https://github.com/xiaoxiaoflood/firefox-scripts


> Make sure you are using the latest version of each script. If you are planing to use scripts as well as legacy extensions (Tab mix plus and other...) the you need to install [utils → I'm interested in both scripts and extensions](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/utils.zip)
> 
Definitely using this link since I wanted both

**Comment by onemen** [comment]
What is your firefox version?

**Comment by Mrsash2020** [comment]
104.0.2 latest

**Comment by onemen** [comment]
there is incompatibility between Tab Mix Plus and `privateTab.uc.js` both make changes to `PlacesUIUtils._openNodeIn` function
I will report about this to @xiaoxiaoflood, in the mean time you can replace your version of privateTab.uc.js with this file:
https://tabmixplus.org/dev-builds/misc/privateTab.uc.js

**Comment by Mrsash2020** [comment]
thanks much appreciated

**Comment by onemen** [comment]
@xiaoxiaoflood just uploaded new version of [privateTab.uc.js](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/privateTab.uc.js)
