### ISSUE TITLE
Tab width and multirow works on Firefox but not Waterfox

### ISSUE THREAD

**Issue by vertigo220** [onemen/TabMixPlus#163]
W10 Version 21H2 (OS Build 19044.1826)
Latest Firefox (91.13.0esr (64-bit)) and Waterfox (G4.1.5 (64-bit))
Fresh profiles with no extensions
Installed userChromeJS with third option (scripts and extensions) and rebuild_userChrome.uc.js using exact same steps for both
Tried disabling the scripts with no effect

When I set a tab width size in TMP in Firefox, it works as expected without issue. When I set it in Waterfox, the tabs don't change size. I can get them to change by opening some tabs then closing at least two, and only when closing the last tab do they change, but then as soon as I move the cursor away from the tabs they change back to the default size. Multi-row also doesn't work in Waterfox but works with Firefox.

I prefer Waterfox for many reasons, but am wondering if Firefox is going to be the better choice for my main browser as so far it seems to be more compatible with TMP, and am wondering if that's a common finding or if this is a one-off. Anyways, hopefully you can replicate and figure out the issue, let me know if you need anything else.

**Comment by onemen** [comment]
What is your theme ?
Currently `Tab Mix Plus` multi-row work only with modern theme.

**Comment by vertigo220** [comment]
Ah. Waterfox defaults to the Lepton theme. Switching to Firefox Modern fixed it immediately. Thanks!
