### ISSUE TITLE
Double click can't open history from managing all history on  firefox 105

### ISSUE THREAD

**Issue by klcb2010** [onemen/TabMixPlus#165]
Double click can't open history from managing all history

![微信截图_20220921194423](https://user-images.githubusercontent.com/32628414/191495865-a3e26f4b-99b7-418b-8a82-4436b1f22f04.png)

**Comment by onemen** [comment]
What is you Tab Mix Plus version ?

Please attach a file with you Tab Mix Plus preferences.

**Comment by klcb2010** [comment]
> What is you Tab Mix Plus version ?
> 
> Our latest version is [v1.0.0-pre.9](https://github.com/onemen/TabMixPlus/releases)
> 
> Please attach a file with you Tab Mix Plus preferences.
> 
> If you are using privateTab script make sure to install the latest version from [here](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/chrome)

 version what i  install is [pre.9](https://github.com/onemen/TabMixPlus/releases)

**Comment by onemen** [comment]
Test if it work on new profile

**Comment by klcb2010** [comment]
> Test if it work on new profile

still  not  work

**Comment by onemen** [comment]
You probably did not install [userChromeJS](https://github.com/xiaoxiaoflood/firefox-scripts#readme) properly.

Tab Mix Plus work for me in all Fireofx versions without any issue.

**Comment by klcb2010** [comment]
> You probably did not install [userChromeJS](https://github.com/xiaoxiaoflood/firefox-scripts#readme) properly.
> 
> Tab Mix Plus work for me in all Fireofx versions without any issue.

I install the  latest version of  [userChromeJS](https://github.com/xiaoxiaoflood/firefox-scripts#readme) ，it  work  now， thx！
