### ISSUE TITLE
Tab dragging is not working

### ISSUE THREAD

**Issue by soeyu** [onemen/TabMixPlus#166]
## I don't know if this is a bug either 
Firefox Developer Edition 106b2(64bit)
TabMixPlus version 1.0.0-pre.9
![pic](https://raw.githubusercontent.com/soeyu/pic/master/1.webp)

**Comment by klcb2010** [comment]
> ## I don't know if this is a bug either
> 
> Firefox Developer Edition 106b2(64bit) TabMixPlus version 1.0.0-pre.9 ![pic](https://raw.githubusercontent.com/soeyu/pic/master/1.webp)

你这什么录制工具？ 老牛逼了

**Comment by onemen** [comment]
Attach a file with your Tab Mix Plus preferences

**Comment by soeyu** [comment]
I created a new Firefox profile and TabMixPlus is using the default preferences, and the console reports an error whether "when dragging a tab move it directly" is checked or not.( google translate 😂)
https://user-images.githubusercontent.com/3954659/191885765-a44c053a-99e4-4301-a286-0e5bc8b1a510.mp4

[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/9630548/TMPpref.txt)

**Comment by soeyu** [comment]
> > ## I don't know if this is a bug either
> > Firefox Developer Edition 106b2(64bit) TabMixPlus version 1.0.0-pre.9 ![pic](https://raw.githubusercontent.com/soeyu/pic/master/1.webp)
> 
> 你这什么录制工具？ 老牛逼了

[ScreenToGif](https://github.com/NickeManarin/ScreenToGif)
动图视频都能导出

**Comment by onemen** [comment]
Thank you for the report @soeyu.

I can confirm that this is a bug

```js
Uncaught TypeError: tabBar._getDropEffectForTabDrag is not a function
    handleDragover chrome://tabmixplus/content/minit/minit.js:276
    on_dragover chrome://tabmixplus/content/changecode.js line 223 > eval:11
    handleEvent chrome://browser/content/tabbrowser-tabs.js:1862
252 minit.js:276:28
```

I will try to fix it soon....

**Comment by onemen** [comment]
Download and try this new version of Tab mix [1.0.0-pre.10.20220925](https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.9/tab_mix_plus-1.0.0-pre.10.20220925.1.xpi)

**Comment by soeyu** [comment]
it works, thx @onemen
