### ISSUE TITLE
Current Tab Color Not Working

### ISSUE THREAD

**Issue by DAMoran2022** [onemen/TabMixPlus#167]
The color of the currently installed theme bleeds through the **CURRENT** tab, blending with the tab background color, but  the other tab colors work fine.

Windows 7E x64, Waterfox G5.0b5, TMP 1.0.0.pre 9.

**Comment by onemen** [comment]
What is your theme ?

attach your Tab Mix preferences?

**Comment by DAMoran2022** [comment]
Most themes have the issue in web extension TMP but no0t in legacy TMP, but here ia the one that most clwarly demonstrates the problem: Dark 1.2.

Where do I find a file containing the TMP preferences:

**Comment by DAMoran2022** [comment]
After further testing (using theme Dark 1.2) it appears that even without TMP installed Firefoc colors the CURRENT tab only with the theme color, so it may be something TMP cannot correct.

**Comment by onemen** [comment]
can you post a screenshot?

**Comment by DAMoran2022** [comment]
Here it is--using theme Dark 1.2. Current tab is the one on the right. TMP is configured for current tab color of yellow.
![Tab Mix Plus](https://user-images.githubusercontent.com/113235837/192361008-4417bd9d-bf57-4b32-8756-08de7e5ef8de.png)

**Comment by DAMoran2022** [comment]
fixed the Tab color display problem by  CHANFING CONGIG....

userChrome.theme.enable FALSE

**Comment by onemen** [comment]
Hello DAMoran2022,

Follow the instructions here <https://github.com/onemen/TabMixPlus#readme>,
in order to install a helper scripts that enable the use of legacy
extensions in modern firefox.
