### ISSUE TITLE
Multi-row tabs does not work properly With Waterfox G5

### ISSUE THREAD

**Issue by KhurramFHassan** [onemen/TabMixPlus#168]
I have installed TMP following your instruction on Waterfox G5.0.1 and would like to use multi-row tabs with all rows visible. However, it is not working properly. It only shows 2 rows of tabs with an up arrow and a disabled down arrow. It only shows the 1st four rows; I have 6 rows in all. Waterfox just updated today; so probably it needs to be fixed in TMP.

Khurram

**Comment by lanmaster** [comment]
After update from Waterfox 4.1.5 to 5.0.1 i see that ui is broken too. Tabs in lowest row is not clickable and cannot scroll tabs on mouse wheel. Only fisrt up row is working. Also there is only 2 rows visible at one time.
![image](https://user-images.githubusercontent.com/6203028/194056792-22833ae8-b1f1-4940-b21b-0e3ef8c97249.png)

**Comment by onemen** [comment]
I will have to check what has changed in Waterfox 5

**Comment by onemen** [comment]
As a temporary workaround, try to set `userChrome.theme.enable` to **flase**

Report if it work for you.

**Comment by KhurramFHassan** [comment]
Setting userChrome.theme.enable to false works. Thanks.

**Comment by 117649** [comment]
@onemen WF use a modified version of [lepton](https://github.com/black7375/Firefox-UI-Fix) as it's default theme. But I don't have problem with lepton on FF. I guess this is mostly a css problem reference the original lepton may be helpful.

**Comment by onemen** [comment]
@117649 , see this comment [Waterfox/issues/2780](https://github.com/WaterfoxCo/Waterfox/issues/2780#issuecomment-1268905601)

**Comment by lanmaster** [comment]
> As a temporary workaround, try to set `userChrome.theme.enable` to **false**
> 
> Report if it work for you.

It work. Thanks!

**Comment by onemen** [comment]
@117649 and anyone that want to test the patch see #169

**Comment by onemen** [comment]
@black7375,
> Hello, I'am lepton theme author.
> Is `#TabsToolbar[multibar]` that you can check when it's multi row mode in TabMixPlus?
> If it's right, I think lepton theme can do the patch.

Yes, 
I have the patch ready see #169.
The main issue I have with Waterfox `userChrome.css` implementation is that many rule have an !imporant and it is very hard to modify for other theme/extensions

**Comment by onemen** [comment]
Try this new [test version](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.11.20221007.1.xpi)

It should solve the main issue with Multi-row.

Waterfox added many preferences in `about:config` to control its theme, look for all preferences that start with `userchrome`.
You can toggle these preferences and see if it work/look better. some changes only take effect after restart.

**Comment by black7375** [comment]
Unfortunately, due to the CSS loading order of Firefox, the style will not be applied unless `!important` is used.

- https://github.com/black7375/Firefox-UI-Fix/blob/master/docs/Restrictions.md#css-loading-order


I'll see if I can increase compatibility with TMP on the weekend.

**Comment by black7375** [comment]
@onemen I have a question.

For now, I've checked most of the other compatibility.
Only one new tab button shape is left.

The shape of `#tabs-newtab-button` is crushed, and it seems to be due to the following code.

![image](https://user-images.githubusercontent.com/25581533/194619568-d7827c42-481a-4d8c-a9c7-dc4d33c289b6.png)

https://github.com/onemen/TabMixPlus/blob/2d97d67a02affbc66062655790aa3e64472d921f/addon/chrome/content/overlay/multirow.css#L22-L24

Is `--tab-min-height_mlt` important part in TMP?
Can it be removed from the TMP to reduce the conflict?

If it's impossible, `height` is planning to force an `unset` in Lepton.

**Comment by 117649** [comment]
> If it's impossible, `height` is planning to force an `unset` in Lepton.

If I'm not making a mistak `extensions.tabmix.tabBarMode` is 2 means multi line mode. 
You should be able to make specific rules for the situation with that pref.

**Comment by onemen** [comment]
Yes, `--tab-min-height_mlt` is important, I am using it to set tab height for multi-row.
I set `--tab-min-height_mlt` to be `--tab-min-height` + 2 * `-tab-block-margin`.
the default `-tab-block-margin` In Firefox proton is 4px but i am changing it to 1px for multi-row, without it the vertical gap between to rows will be 8px.

**Comment by black7375** [comment]
I'll come up with a way to avoid conflict or bypass tomorrow. Thank you for your quick reply.

**Comment by onemen** [comment]
@black7375, 

Is there a way for me to test the new style ?

**Comment by black7375** [comment]
I've created a temporary branch.
https://github.com/black7375/Firefox-UI-Fix/tree/tmp

**Comment by black7375** [comment]
Now, It seems to work well with multi-row in my environment !!
https://github.com/black7375/Firefox-UI-Fix/releases/tag/v6.3.0

**Comment by onemen** [comment]
@black7375

let me know how it work with Tab mix [latest](https://github.com/onemen/TabMixPlus/releases) version

**Comment by black7375** [comment]
The old version was clearly working.
https://www.reddit.com/r/FirefoxCSS/comments/y61hw2/lepton_now_support_tabmixplus/

Strangely, the new version doesn't work in Pure Firefox.
![image](https://user-images.githubusercontent.com/25581533/203057824-676bc883-18b9-4869-8cf3-b20032383014.png)

**Comment by onemen** [comment]
I was pushed b1d46ba788a63b1e89c99f8f3f293214ec6f5f88.
maybe this commit mess things up.
can you test if reverting the commit help?

**Comment by black7375** [comment]
Yes. Today I'm busy, so I'll tell you after the test tomorrow.

**Comment by black7375** [comment]
It has been confirmed to work well.

![image](https://user-images.githubusercontent.com/25581533/203177668-9f49e718-110b-4594-852e-46fe1547ecd2.png)

---

It's a mistake made by adjusting the value of `browser.tabs.tabMinWidth`

**Comment by onemen** [comment]
Thank you for your help
