### ISSUE TITLE
Error when using data-l10n localization

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#17]
when window start i see this error in the console

```
23:11:16.682 [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 692"  data: no] 2 L10nRegistry.jsm:692:19
```

The error when loading the preference window, ```Uncaught (in promise) undefined``` also related to l10n.
when i removed all data-l10n attribute from the xhtml files (menu.xhtml, mouse.xhtml) the error is gone.

However Firefox stile crashing when loading from Add-ons page so it probably not related.

**Comment by 117649** [comment]
On Add-ons page reload and wait for recommended extension section to fully loaded can 100% avoid crash.

**Comment by onemen** [comment]
it crash when trying to open options from this view:
![image](https://user-images.githubusercontent.com/3650909/105571183-b3cc1880-5d56-11eb-99a1-cb8ab8906701.png)

but it work OK from extension view:
![image](https://user-images.githubusercontent.com/3650909/105571201-da8a4f00-5d56-11eb-8570-67cd8a3fd583.png)
