### ISSUE TITLE
Is the option menu supposed to look this scuffed?

### ISSUE THREAD

**Issue by xerance** [onemen/TabMixPlus#170]
[107.0a1 (2022-10-12) (64-bit)](https://puu.sh/JoRin/670ac04fdc.mp4)

FF nightly - 107.0a1 (2022-10-12) (64-bit)
Windows 10 - professional  64bit 

Is it supposed to look like this? window is non-resizable and seems like a lot of text is missing as I don't recall tab mix plus used to look like this back in the day?

**Comment by onemen** [comment]
I have a fix ready for this issue [fix: add missing flex-direction (affects Firefox 107+) ](https://github.com/onemen/TabMixPlus/commit/f01f2b9df32cb17c7c820a022f5cbf1aaae6a6bf)

Download and try this [test version](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.11.20221013.1.xpi).

**Comment by xerance** [comment]
Thanks, works like a charm
