### ISSUE TITLE
Not loading in Firefox 106

### ISSUE THREAD

**Issue by cxen** [onemen/TabMixPlus#171]
TabMixPlus is being marked as unverified and is being disabled in the stable release of Firefox 106.

I reinstalled xiaoxiaoflood/firefox-scripts and tried to reinstall the latest TabMixPlus but it does not help.

**Comment by onemen** [comment]
uninstall Tabmix
Close Firefox
repeat again the instructions from xiaoxiaoflood/firefox-scripts

**Comment by cxen** [comment]
> uninstall Tabmix Close Firefox repeat again the instructions from xiaoxiaoflood/firefox-scripts

This worked, thanks.
Not sure why it was disabled suddenly.
