### ISSUE TITLE
Options window Error

### ISSUE THREAD

**Issue by ozzyjr** [onemen/TabMixPlus#172]
I have an error in the options window that appears unconfigured and with difficult access to some options.

Firefox Nightly 108.0a1

![Captura de Tela 2022-10-20 às 08 22 13](https://user-images.githubusercontent.com/12512993/196936086-b18debff-419c-482f-a2e5-1982d9195193.jpg)

**Comment by onemen** [comment]
I have a fix ready for this issue [fix: add missing flex-direction (affects Firefox 107+) ](https://github.com/onemen/TabMixPlus/commit/f01f2b9df32cb17c7c820a022f5cbf1aaae6a6bf)

Download and try this [test version](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.11.20221013.1.xpi).

**Comment by ozzyjr** [comment]
I can't download the extension. It's giving an error on the download and on the website

**Comment by onemen** [comment]
look like https://tabmixplus.org is down, try again later

**Comment by ozzyjr** [comment]
It worked! Thanks.

![Captura de Tela 2022-10-20 às 15 02 59](https://user-images.githubusercontent.com/12512993/197024310-677aff98-2523-4d4b-9af2-870db246a416.jpg)

**Comment by XeonG** [comment]
Just had this same issue.. so added the fix and its the option dialog looks better.. ubt I have another problem it seems [enter] in the address bar is no longer working.. unless I disable TMP.. then it works after restart.. enabled TMP..not working...

**Comment by onemen** [comment]
Download and install Tab Mix Plus [latest](https://github.com/onemen/TabMixPlus/releases) version.
