### ISSUE TITLE
New Window Loses Address Bar Focus

### ISSUE THREAD

**Issue by Brenex** [onemen/TabMixPlus#173]
When I open a new window, the focus on the address bar is only momentary, and then it loses focus. There is no issue with focus loss when opening a new tab. This works correctly and focus is maintained on the address bar. Please see below. I have isolated it to TMP as it only occurs when it is enabled. This has nothing to do with focus on closing of last window as it does not involve a window being closed. Regardless, even playing with that setting does not affect this.

![giphy](https://user-images.githubusercontent.com/3178983/197564380-84dae002-fda0-47c9-9e57-148b58215aa7.gif)

**Comment by onemen** [comment]
Attach a file with your Tab mix preferences

**Comment by Brenex** [comment]
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/9854659/TMPpref.txt)

**Comment by onemen** [comment]
what is your preference for home page ?

**Comment by Brenex** [comment]
Do you mean for FF preference for a home page? If so, this is it:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/3178983/197617588-3d1ecda1-aa2b-47f0-876e-1411e9240370.png">

**Comment by onemen** [comment]
can you test how tabmix work on new profile ?

**Comment by onemen** [comment]
I will upload a test version with a possible fix tomorrow

**Comment by Brenex** [comment]
Thank you. I did try with a new profile and the same thing happens.

**Comment by onemen** [comment]
Try this test version.
Download [this version](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.11.20221025.1.xpi) to your machine and install it.

Report back.

**Comment by Brenex** [comment]
that fixed it. It worked after installing and clearing cache!
