### ISSUE TITLE
107.0b7 can't drag tab on tabs bar

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#176]
![image](https://user-images.githubusercontent.com/8281345/199292077-e8102d46-6440-40cf-b0ed-c209884fb9e3.png)
![image](https://user-images.githubusercontent.com/8281345/199292276-33bc128a-bed7-4c49-9fd8-271450b3bf78.png)

[dev_TMPpref.txt](https://github.com/onemen/TabMixPlus/files/9912473/dev_TMPpref.txt)

**Comment by onemen** [comment]
This issue was fixed 2 month ago 5e5edf0
Make sure you are using the latest version

**Comment by 117649** [comment]
> This issue was fixed 2 month ago [5e5edf0](https://github.com/onemen/TabMixPlus/commit/5e5edf0e1bf8a68750a8abe151b86f10e2486f77) Make sure you are using the latest version

Its ok now.
looks like I'm missing a complete power down of the browser.
