### ISSUE TITLE
Bookmarks in the sidebar are not loaded in a new tab even if bookmarks are checked in the "Load in new tab" setting.

### ISSUE THREAD

**Issue by okimurin** [onemen/TabMixPlus#178]
Windows11:22h2
Firefox version:dev107.0b8
tabmixplus:1.0.0-pre.11.20221101.1

**Comment by onemen** [comment]
Attach a file with your Tab mix preferences

**Comment by okimurin** [comment]
I fixed it by resetting the settings. Thank you.

**Comment by onemen** [comment]
👍
