### ISSUE TITLE
Firefox crashing when loading Tab Mix options from Add-ons

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#18]
Firefox crashing when loading Tab Mix options from Add-ons:
it crash when trying to open options from this view (all extensions):
![image](https://user-images.githubusercontent.com/3650909/105571183-b3cc1880-5d56-11eb-99a1-cb8ab8906701.png)

but it work OK from extension view (only Tab mix):
![image](https://user-images.githubusercontent.com/3650909/105571201-da8a4f00-5d56-11eb-8570-67cd8a3fd583.png)

_Originally posted by @onemen in https://github.com/onemen/TabMixPlus/issues/17#issuecomment-765878335_

I think i have a fix for this issue. 
The problem is in aboutaddons.js, we add click event for the option button after load event and from MutationObserver.
when you open Add-ons tabs for the first time both load event and mutation add click listener to the button.
when we click it both listeners runs and Firefox try to open the same window twice

It work for me with this patch, if it look right to you i will commit it

```diff
diff --git a/addon/chrome/content/preferences/overlay/aboutaddons.js b/addon/chrome/content/preferences/overlay/aboutaddons.js
index 14d8f245..f296fbe2 100644
--- a/addon/chrome/content/preferences/overlay/aboutaddons.js
+++ b/addon/chrome/content/preferences/overlay/aboutaddons.js
@@ -38,13 +38,16 @@ function updateShowItemPreferences() {
   //   }
   const tabmixItem = getHtmlBrowser().contentDocument.querySelector(`addon-card[addon-id="${ID}"]`);
   if (tabmixItem) {
-    tabmixItem.querySelector(`panel-item[action="preferences"]`)
-        .button.addEventListener("click", event => {
-          event.stopPropagation();
-          try {
-            windowRoot.ownerGlobal.Tabmix.openOptionsDialog(-1);
-          } catch (ex) { }
-        });
+    const optionsButton = tabmixItem.querySelector(`panel-item[action="preferences"]`).button;
+    optionsButton._tabmix_command_installed = true;
+    if (!optionsButton._tabmix_command_installed) {
+      optionsButton.addEventListener("click", event => {
+        event.stopPropagation();
+        try {
+          windowRoot.ownerGlobal.Tabmix.openOptionsDialog(-1);
+        } catch (ex) { }
+      });
+    }
   }
   // const addonOptionsItem = getHtmlBrowser().contentDocument.querySelector(`template[name="addon-options"]`).content.querySelector(`[action="preferences"]`);
   // addonOptionsItem.setAttribute("onclick",
```

**Comment by 117649** [comment]
I've notice a empty tab flash away which indicate the script may not function in anyway at all.

**Comment by 117649** [comment]
Ok, It looks there is a mistake on order of the code line. Once sort it out things seems running.
```javascript
function updateShowItemPreferences() {
  const tabmixItem = getHtmlBrowser().contentDocument.querySelector(`addon-card[addon-id="${ID}"]`);
  if (tabmixItem) {
    const optionsButton = tabmixItem.querySelector(`panel-item[action="preferences"]`).button;//move this inside if()
    if (!optionsButton._tabmix_command_installed) {
    optionsButton._tabmix_command_installed = true;
      optionsButton.addEventListener("click", event => {
        event.stopPropagation();
        try {
          windowRoot.ownerGlobal.Tabmix.openOptionsDialog(-1);
        } catch (ex) { }
      });
    }
  }
}
```
but this kind of method can't handle the situation when the browser restore a session.

**Comment by onemen** [comment]
i'v just swap 2 lines when removing a comment

> but this kind of method can't handle the situation when the browser restore a session.
I don't understand it, how can i test when it fails ?

**Comment by 117649** [comment]
> i'v just swap 2 lines when removing a comment
> 
> > but this kind of method can't handle the situation when the browser restore a session.
> I don't understand it, how can i test when it fails ?

When browser a session overlay won't be apply to the about:addons because it load from cache and may also before TMP is load.
The 'preferences.xhtml' has a inline script that close the tab and open the option dialog when it opened in a tab. The downside as I said is a empty tab that flash once before dialog open.

**Comment by onemen** [comment]
I did not notice any this issue when opening the browser with restored session
I will leave the script in 'preferences.xhtml' just in case but i prefer to move it to  preferences.js as an Immediately-invoked Function Expressions (IIFE)

**Comment by onemen** [comment]
Fix by https://github.com/onemen/TabMixPlus/commit/3fb78cf7f12f2f8bb86c2bfcb01c5f3f054a0f7b
