### ISSUE TITLE
tab close button not present when there's one tab

### ISSUE THREAD

**Issue by purple512** [onemen/TabMixPlus#181]
I have "Close tab button" set to "on all" but it's missing when there's only one tab, see pictures.

![one tab](https://user-images.githubusercontent.com/79816784/200887632-313891aa-ea64-44de-a74b-ab6066a15a02.png)

![two tabs](https://user-images.githubusercontent.com/79816784/200887701-1896a079-499f-41da-9c69-246fe50241e1.png)

I checked with element inspector and the extension sets `<tabs ... closebuttons="noclose">` when there's one tab and otherwise `<tabs ... closebuttons="alltabs">`. Haven't tried to debug further. I don't understand why it would do this.

**Comment by onemen** [comment]
There is no reason to show close button on last empty tab

**Comment by purple512** [comment]
There is certainly a reason. What if I want to close the browser by closing the last tab? Shouldn't I be able to do that in the same way as closing any other tab, without moving all the way over to the close window button? This is the default behavior of Firefox, I don't understand why it must be changed or why an exception to "on all tabs" is necessary.

It's also not consistent at all. If I create a new window, I get one blank tab with a close button (good). But if I open a second tab and then close that second tab, now the first tab has no close button.

**Comment by onemen** [comment]
This is currently the code that remove the button on last tab
https://github.com/onemen/TabMixPlus/blob/b73ca6d0bbe02637139fe93b3028a0f2907d212b/addon/chrome/content/links/setup.js#L287-L294

I can update the code to only remove the button from last tab if one of this condition is true:
1.    if `Do not close window when closing last tab` is set **and** the tab is blank, about:blank or other `new tab`.
2.    if `Prevent last tab from closing`.
