### ISSUE TITLE
Address bar input is not working with TMP on

### ISSUE THREAD

**Issue by gelirhil** [onemen/TabMixPlus#182]
TMP blocks address bar input with Enter button or LMB clicking on suggestions on latest Nightly. Browser console gets this:
`InternalError: too much recursion[UrlbarInput.sys.mjs:162:36](resource:///modules/UrlbarInput.sys.mjs)`

Turning TMP off resolves the issue. Search bar works well both with TMP on or off.

Windows 10 x64 21H2
FF 108.0a1 (2022-11-10) (64-bit)
TMP 1.0.0-pre.11.20221013.1
bootstrap loader 0.1.93.2021.09.30
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/9983941/TMPpref.txt)

**Comment by onemen** [comment]
Read here #180

Download and install this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.11.20221109.1.xpi)

**Comment by gelirhil** [comment]
> Download and install this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.11.20221109.1.xpi)

Thanks, it helped. Sorry for opening issue before reading closed ones.
