### ISSUE TITLE
Web pages not allways on date

### ISSUE THREAD

**Issue by rollandpf** [onemen/TabMixPlus#184]
Hello,

I have a issue with some websites when Tab Mix Plus (version 1.0.0-pre.11.20221013.1) is activated in my Firefox (version 107).

The web pages are always opened from the disk cache. If I want to see if there are new contents, I must manualy update the tab (with a F5) to get the new online version of the page.

The issue is not present when Tab Mix Plus is disabled.

**Comment by onemen** [comment]
Check if you still have this issue with the latest release [v1.0.0-pre.11](https://github.com/onemen/TabMixPlus/releases/tag/v1.0.0-pre.11)

**Comment by rollandpf** [comment]
Hello,

No error messages in the browser console.

After further tries I found the reason of the issue (I forgot to precise that it occur when I open several bookmarks in one go from a bookmark folder).

If I unchek the options in the red rectangle, all the tabs are loaded from the site with the last content.

![image](https://user-images.githubusercontent.com/48216797/203000076-94d98f87-9113-4213-9773-dd1d4f364b8f.png)

**Comment by onemen** [comment]
Can you check how the same tabs work when you start new session with these tabs in pending state.
set the preference `browser.sessionstore.restore_on_demand` to `true`

**Comment by rollandpf** [comment]
By modifying my preferences, to check the behavior of the tabs, I also noticed that the Tab Mix Plus options window no longer displayed all the elements as shown in the previous screenshot:

![image](https://user-images.githubusercontent.com/48216797/221623868-175911f4-65f3-463d-9061-9dd90d327140.png)

My version of Firefox is : 110.0
My Version of Tab Mix Plus is : 1.0.0-pre.13

**Comment by onemen** [comment]
> I don't realy know how to start a new session with these tabs in pending state. What I did : After re-checked the 2 options, I launched my troublesome bookmarks without consulting them, restarted Firefox, closed all the bookmarks et opened them again. No update of the pages content without a F5.

1. In Firefox settings (about:preferences) make sure `Open previous windows and tabs` is checked.
2. Open the bookmarks you are testing, visit each one and reload it with F5.
3. Close Firefox
4. Start Firefox again, all other tab should be pending until selected.
5. Select each one and see if content is updated

**Comment by onemen** [comment]
Download and install this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.14.20230228.1.xpi)
it should solve #184 and #213

**Comment by rollandpf** [comment]
Hello,

On my computer, the test build solved the issue [#213](https://github.com/onemen/TabMixPlus/issues/213) but not the [#184](https://github.com/onemen/TabMixPlus/issues/184).

**Comment by onemen** [comment]
Can you provide a list of bookmarks addresses to it on my pc

**Comment by rollandpf** [comment]
Hello,

I can't provide you with my bookmarks. They are from our intranet.

I searched on internet to find sites with similar issue. Those two presents the same issue: yande.re and /nozomi.la

You can genérate bookmarks like these ones for tours tests:
https://yande.re/post?tags=dragon_ball_z+
https://yande.re/post?tags=oda_eiichirou
https://yande.re/post?tags=matsumoto_leiji+
https://nozomi.la/search.html?q=official_art
https://nozomi.la/search.html?q=science_fiction
https://nozomi.la/search.html?q=copyright_name
...

**Comment by onemen** [comment]
I've push the workaround, it will be included in the next version.

If you still have to use F5 to refresh restored tabs you can always disable this feature

**Comment by onemen** [comment]
Another try....
Download and install this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.14.20230313.1.xpi)

**Comment by onemen** [comment]
Thank you for using Tab Mix Plus.

Tell your friends about it
