### ISSUE TITLE
No dynamic/auto adjustment of how many multirows to be shown

### ISSUE THREAD

**Issue by Dxhs** [onemen/TabMixPlus#186]
Is this an issue with only me or is it a feature?

Would be nice if the empty space was hidden when few tabs are open. See picture below

This isnt an issue when having the tab bar at the bottom insted of top as shown in the picture. When placed at the bottom, the empty space is hidden.

Tab Mix Plus Version
1.0.0-pre.11
Firefox 107.0 (64-bit

![multirow issue](https://user-images.githubusercontent.com/13475068/202674928-0c760fbb-474a-4777-b9a2-95e9fae8d6d9.png)

**Comment by onemen** [comment]
Do you see any messages in the browser console?
Post an attachment with your Tab Mix preferences

**Comment by Dxhs** [comment]
There are some messages in the console yes. One that sticks out is line 54 in the attached file (console*.txt).

Operating system:
OS Name Microsoft Windows 10 Pro
Version 10.0.19044 Build 19044

Tab Mix Plus preferences exported and attached here (TMPpref.txt).

For assurance, I was able to replicate this issue with a new profile in firefox with no addons except 
Tab Mix Plus.

Hope this helps!

[console-export-2022-11-18_11-20-57.txt](https://github.com/onemen/TabMixPlus/files/10040397/console-export-2022-11-18_11-20-57.txt)
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/10040398/TMPpref.txt)

**Comment by onemen** [comment]
Thank you for the information.

I can reproduce this issue when using your preferences file.

**Comment by onemen** [comment]
Download in install this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.12.20221118.1.xpi)

**Comment by Dxhs** [comment]
This build seems to work 🥇 I cannot reproduce the issue anymore
