### ISSUE TITLE
Multirow tab bar number of rows

### ISSUE THREAD

**Issue by cxen** [onemen/TabMixPlus#188]
When using the multirow tab bar, the max rows value expands the tab bar with empty rows instead of dynamically adjusting depending on how many tabs are actually open.

Firefox 107.0
TMP 1.0.0-pre.11

**Comment by onemen** [comment]
Download in install [latest version](https://github.com/onemen/TabMixPlus/releases) again

**Comment by cxen** [comment]
> Download in install [latest version](https://github.com/onemen/TabMixPlus/releases) again

This fixed it, thanks. It seems like I should always try reinstalling before I report any issues.
