### ISSUE TITLE
Now check 'all tabs button' box hide the button for me and vies versa

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#19]
I have Tab-Group installed which cause 'all tabs' button show at first.

**Comment by onemen** [comment]
```
      <preference id="pref_hideAllTabsButton" name="browser.tabs.tabmanager.enabled"            type="bool"
                  inverted="true"/>
```
need to remove ```inverted="true"```

**Comment by onemen** [comment]
Fix by https://github.com/onemen/TabMixPlus/commit/f601e73fcd67bc6a01cc24e4dc4a507c4fe08a4f
