### ISSUE TITLE
New tab opens next to current even when set not to

### ISSUE THREAD

**Issue by explor202** [onemen/TabMixPlus#190]
Issue: With setting "Open New Tab next to current one" unchecked, new tabs are still opened next to the current one when link is right clicked and "open in new tab" is selected. Also duplicated when website default action is to open links in new tab(s) (eBay search results).

Expected results: All new tabs should be opened at the end of the last tab of the last row

OS: Windows 8.1 64-bit
Browser: FF 107.0
TMP: 1.0.0-pre.11

**Comment by onemen** [comment]
Attach a file with your Tab Mix preferences

**Comment by onemen** [comment]
The preference `Open New Tab next to current one` - refers to new "blank" tab, when you use a shortcut Ctrl+T or click on new tab button.

To place tab that open from link at the end change `Open other tabs next to current one` preference.

**Comment by explor202** [comment]
@onemen thank you, I missed the setting "Open other tabs next to current one"
