### ISSUE TITLE
Tab Mix framescript does not work on linux

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#191]
@117649,

I've noticed recently that Tab mix frame script does not work on Linux for non chrome (about:) tabs.

Utils.jsm
```
    let mm = window.getGroupMessageManager("browsers");
    FMM_MESSAGES.forEach(msg => mm.addMessageListener(msg, this));

    // Load the frame script after registering listeners.
    mm.loadFrameScript("chrome://tabmixplus/content/scripts/content.js", true);
```

any idea?

**Comment by 117649** [comment]
@onemen I'm not a user of OS other than WINDOWS on PC.

Is it all down or just some of the function?
What I know is the structure of html of the FF UI are not identical across all the OS. May be it just lost target because that.

**Comment by onemen** [comment]
found it !

look like it was some security issue when using the extension form folder.
https://github.com/xiaoxiaoflood/firefox-scripts/issues/64#issuecomment-906936805

You manage to help me from the past 👍

**Comment by 117649** [comment]
Forgot that myself, after I no longer use load from folder again because of it.
