### ISSUE TITLE
There is a problem with the tab context menu.

### ISSUE THREAD

**Issue by soeyu** [onemen/TabMixPlus#194]
developer edition 109.0b2 (64 bit)

I created a new test profile, only TMP installed and use default preference

my TMP preference
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/10234298/TMPpref.txt)

my firefox profile
![default_profile](https://user-images.githubusercontent.com/3954659/207788532-867b6604-3fd7-4f10-9e15-a489692fe5c1.jpg)

new test firefox profile
![test_profile](https://user-images.githubusercontent.com/3954659/207788539-1384e339-3e35-473d-9949-7970fa2a03c3.jpg)

https://user-images.githubusercontent.com/3954659/207787984-645f1b18-06d6-41ef-8601-057f53f39a49.mp4

**Comment by 117649** [comment]
![image](https://user-images.githubusercontent.com/8281345/207797747-1ecec295-2d51-4f75-887f-1afea7731050.png)
![image](https://user-images.githubusercontent.com/8281345/207797820-461edebb-4e58-4796-b314-1623ee40e0cb.png)
Some shots of console.

**Comment by Tsharii** [comment]
Have same problem with default tab mix plus preferences. Firefox 109b2, 64bit on Windows 10 with all updates from "Windows Update". Firefox scripts from xiaoxiaoflood disabled. I tried to rebuild the startup cache many times before disable Firefox scripts.

My scripts from xiao are "Master Password +" and "Status Bar".

Last Tab Mix Plus version installed from here.

**Comment by skoruppa** [comment]
I have the same issue on Firefox 109b2 for Linux. A temporary workaround is to change Firefox's language to anything else (for example, English) and then back to yours. But after a restart, the issue will be back again (even if our default language is English)

**Comment by onemen** [comment]
Download and try this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.12.20221215.1.xpi)

**Comment by soeyu** [comment]
> Download and try this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.12.20221215.1.xpi)

Mine looks solved. 😄

**Comment by 117649** [comment]
> > Download and try this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.12.20221215.1.xpi)
> 
> Mine looks solved. 😄

A complete shutdown is needed for fix is in effect.
