### ISSUE TITLE
FFv108.0 - Tab Mix Plus could not be verified for use in Firefox and has been disabled

### ISSUE THREAD

**Issue by dv8472** [onemen/TabMixPlus#195]
Hi,

OS: Arch Linux

Have just update from FFv107 to v108, and after resolving the "appears to be corrupt" problem, all I get now is "" & "Tab Mix Plus could not be verified for use in Firefox and has been disabled".
Cleaning startup cache didn't helped.

Possible workaround: install/use the TMP through 
![image](https://user-images.githubusercontent.com/22549066/208163038-6a192f96-4a23-4c3a-894a-dd4291f1595f.png)

**Comment by onemen** [comment]
@dv8472,

Go to [xiaoxiaoflood firefox-scripts page](https://github.com/xiaoxiaoflood/firefox-scripts#instructions) and make sure you have all the latest files installed

Read other tips in #159

**Comment by dv8472** [comment]
@onemen as I said before, the corruption is not the problem anymore.
So far I've managed to possibly track this problem closer to this https://github.com/xiaoxiaoflood/firefox-scripts/issues/212, where I added my findings too.
As I mentioned in there, obviously the new "_// signing bypass by Dumby from forum.mozilla-russia.org_" content in https://github.com/xiaoxiaoflood/firefox-scripts/commit/66e896ec1514499557b64ce205104b04cdb8444a is causing the FF is not able to start and probably making it unable to use that "signing bypass" function, with which I have a problem and for which I opened this ticket.
Also not sure, whether it affectes all OSs, or only some, like in my case with Arch Linux.
However, the workaround via "_Debug Add-ons_" helps somewhat, but one has to do it every time the browser restarts.

I'm curious, what is your experience with something like this?
Have tried FF v108 with that recent fx-folder.zip https://github.com/xiaoxiaoflood/firefox-scripts/commit/66e896ec1514499557b64ce205104b04cdb8444a change already?
Any issues with starting your browser, or installing your Add-on?

**Comment by onemen** [comment]
I am testing Tab Mix regularly on all platforms (Windows, Linux, Mac).
Firefox versions 107, 108, 109 and 110 all work for me with the latest are working for me with the latest `xiaoxiaoflood/firefox-scripts`

If you are using Firefox snap follow this:

Mozilla fixed the issue ([Bug 1785278](https://bugzilla.mozilla.org/show_bug.cgi?id=1785278), [fb762c3](https://github.com/canonical/firefox-snap/pull/8)) with Firefox snap for Linux, by adding an new path to add config files.
Starting with **Firefox 108** you can add the files extracted from [this zip file](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/fx-folder.zip) to these locations:
- copy `config.js` to `/etc/firefox/config.js`
- copy `config-prefs.js` to `/etc/firefox/defaults/pref/config-prefs.js`

**Comment by dv8472** [comment]
No, I'm not using any Snaps.
Standard Arch Linux package https://archlinux.org/packages/extra/x86_64/firefox/.

**Comment by onemen** [comment]
I've only tested on Ubuntu.

**Comment by klcb2010** [comment]
> No, I'm not using any Snaps. Standard Arch Linux package https://archlinux.org/packages/extra/x86_64/firefox/.

你应该看一下UC环境，禁止某个插件只是UC问题。

**Comment by dv8472** [comment]
Fixed in https://github.com/xiaoxiaoflood/firefox-scripts/issues/212#issuecomment-1364484777
