### ISSUE TITLE
Disabled again

### ISSUE THREAD

**Issue by Mrsash2020** [onemen/TabMixPlus#196]
Sorry about this again. Latest Firefox breaks Tax Mix plus after the update. I am not having a whinge but just letting you know. Not sure why it goes from working to not working...

thanks

**Comment by onemen** [comment]
latest change to Firefox require to install new version of [xiaoxiaoflood/firefox-scripts](https://github.com/xiaoxiaoflood/firefox-scripts#instructions)

**Comment by Mrsash2020** [comment]
Am I removing the addon before I do this as currently it shows that its disabled?
hmm am I following the install process again from scratch?

I ask as I only see a one or two files with new dates....

**Comment by level0001** [comment]
Not working for 108.0.1

**Comment by onemen** [comment]
Update file from xiaoxiaoflood/firefox-scripts
Clear cache: Open about:support and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup. 
Remove Tab Mix
Close Firefox (don't use restart)
Start Firefox
install Tab mix again

**Comment by chimalek** [comment]
> Update file from xiaoxiaoflood/firefox-scripts
> Clear cache: Open about:support and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup.
> Remove Tab Mix
> Close Firefox (don't use restart)
> Start Firefox
> install Tab mix again

Thanx. This method works!

**Comment by atarev-crypto** [comment]
I thought this method worked for me after doing it yesterday, but rebooted my machine this morning and it's disabled again.

**Comment by MememeOyaji** [comment]
I tried this method, (Copied xiaoxiaoflood/firefox-scripts  at Fedora37 /lib64/firefox, same directory as old version files existed.)
Tried to re-install TMP but the warning appeared, "This add-on could not be installed because it appears to be corrupt."

Creating new profile brings same result.

Then uninstall Firefox completely.
Install Firefox again.
This method works good.
Something wrong remains at the case of update, I guess.

**Comment by onemen** [comment]
@MememeOyaji 

There was an update on xiaoxiaoflood/firefox-scripts  yesterday.

Make sure you are using the latest files.

**Comment by ozzyjr** [comment]
Disabled again today

<img width="798" alt="image" src="https://github.com/onemen/TabMixPlus/assets/12512993/28cc8102-b39c-4093-8044-69486636cd94">

![image](https://github.com/onemen/TabMixPlus/assets/12512993/7adde09d-d703-48d2-8935-6fc8d7ea13a9)

**Comment by onemen** [comment]
check in https://github.com/xiaoxiaoflood/firefox-scripts#instructions for new updates

then follow the steps above

**Comment by ozzyjr** [comment]
> check in https://github.com/xiaoxiaoflood/firefox-scripts#instructions for new updates
> 
> then follow the steps above

It worked. Thanks

**Comment by pyrates999** [comment]
This should be closed.
