### ISSUE TITLE
Firefox now has built-in spacers in tittle bar while window not maximized 

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#20]
https://github.com/onemen/TabMixPlus/blob/f601e73fcd67bc6a01cc24e4dc4a507c4fe08a4f/addon/chrome/skin/general.css#L66-L67
change 
```css
#tabbrowser-tabs[tabBarSpace] > .tabbrowser-arrowscrollbox
```
to
```css
#tabbrowser-tabs[tabBarSpace] > #tabbrowser-arrowscrollbox 
```
Will make the "Extra spaces on both sides" option function but it does look awkward when the browser window is not maximized.
May be adding more rules to take built-in spacer into consideration or directly manipulate them.

**Comment by onemen** [comment]
We need to change all ```.tabbrowser-arrowscrollbox``` to ```#tabbrowser-arrowscrollbox```

**Comment by 117649** [comment]
![image](https://user-images.githubusercontent.com/8281345/106027042-79230100-6105-11eb-9ba2-0056f0148ae1.png)
Mozilla already have these.
![image](https://user-images.githubusercontent.com/8281345/106027524-ee8ed180-6105-11eb-82fd-6a593351ac4a.png)
They are gone when window is maximized.
![image](https://user-images.githubusercontent.com/8281345/106028564-10d51f00-6107-11eb-8a5e-e3b203d4a87c.png)
Now we restore down and check "Extra spaces on both sides" first tab looks like been stretched.
![image](https://user-images.githubusercontent.com/8281345/106028978-93f67500-6107-11eb-9300-020adc99638a.png)
This not look good.
![image](https://user-images.githubusercontent.com/8281345/106029365-f780a280-6107-11eb-9431-10058f1b5488.png)
![image](https://user-images.githubusercontent.com/8281345/106029437-0e26f980-6108-11eb-88dc-3122a1e8bbca.png)
Extra space on other end also not seem to be much useful.

**Comment by onemen** [comment]
we don't need both spaces
our options are:
1. remove this feature
2. update the css to allow user to show/hide the build-in space

**Comment by 117649** [comment]
> we don't need both spaces
> our options are:
> 
> 1. remove this feature
> 2. update the css to allow user to show/hide the build-in space

Yes this is what I was talking about and for 2nd additional option for always show or hide may also needed.

**Comment by onemen** [comment]
Do you want to work on this ?

**Comment by 117649** [comment]
> 
> 
> Do you want to work on this ?

I think can work on that.

**Comment by 117649** [comment]
@onemen 
https://github.com/onemen/TabMixPlus/pull/50
I don't find any problem yet for both proton and non-proton. Check for yourself.

**Comment by onemen** [comment]
#50 need more work

This is simplification of the Dom tree for  TabsToolbar
```
TabsToolbar:
---------------------------------
left titlebar-spacer (40px)
  left buttons area (empty by deafult)
    left tabmix spacer (15px)
      tabs
    right tabmix spacer (15px)
 right buttons area
right titlebar-spacer (40px)
```
Notice that if the use add buttons to the left area then the spacer is divided on the left like it is divided on the right by default

further more Firefox spacer is not always visible, for example when the top menu is visible the spacer are hidden
see this css rule from Fireofx browser.css
```
:root:not([chromehidden~="menubar"]) #toolbar-menubar:not([autohide="true"]) + #TabsToolbar .titlebar-spacer,
:root:not([sizemode="normal"]) .titlebar-spacer[type="pre-tabs"],
:root[inFullscreen] .titlebar-spacer,
:root:not([tabsintitlebar]) .titlebar-spacer {
	display: none;
}
```

**Comment by onemen** [comment]
The original reason (if i remember it after 15 years) for adding spacer on both side of the was to make it easy to drop links or button to the end

**Comment by 117649** [comment]
> 
> 
> The original reason (if i remember it after 15 years) for adding spacer on both side of the was to make it easy to drop links or button to the end

From what I understand we want only one spacer at left end is that right? 
So I think we just keep TMP spacer stick to tab bar and add counterparts for these rules are enough?

> ```
> :root:not([chromehidden~="menubar"]) #toolbar-menubar:not([autohide="true"]) + #TabsToolbar .titlebar-spacer,
> :root:not([sizemode="normal"]) .titlebar-spacer[type="pre-tabs"],
> :root[inFullscreen] .titlebar-spacer,
> :root:not([tabsintitlebar]) .titlebar-spacer {
> 	display: none;
> }
> ```

**Comment by onemen** [comment]
when user turn off the preference for extra space do we hide both spacer ?

**Comment by 117649** [comment]
> 
> 
> when user turn off the preference for extra space do we hide both spacer ?

I think we just left build-in one alone and show TMP spacer when build-in one is hidden.
