### ISSUE TITLE
Feature request: keybind to move tab to the end (right) or beginning (left)

### ISSUE THREAD

**Issue by purple512** [onemen/TabMixPlus#202]
I often find myself keeping organized by rearranging tabs with dragging, but if there's a lot of tabs it takes a lot of effort to drag all the way to the right because the tab bar won't scroll when dragging so you have to do it in batches -- drag, scroll, drag, scroll, etc.

Multirow tabs would solve this but when I tried it, it was terribly broken. (The minimize/maximize/close buttons disappeared, among other oddities.) I assumed it was experimental.

It would be so convenient if I could set a keybind to just move the current tab all the way to the right (or left), without having to drag it. A context menu item would also suffice but it's less convenient. (Though I suppose both would be best for flexibility.)

Thank you for an excellent extension.

**Comment by onemen** [comment]
![move](https://user-images.githubusercontent.com/3650909/211213764-08930440-0af4-42ae-80c1-f02d6722fb20.png)

**Comment by purple512** [comment]
Oh gosh, I'm embarrassed I didn't see that, I thought I had looked through all the options but I guess I had confused that with "move to new window". Thank you!
