### ISSUE TITLE
Disabling `Focus tabs from diverted windows` causes also tabs from other apps to not get focus

### ISSUE THREAD

**Issue by zakius** [onemen/TabMixPlus#204]
I don't know, if it will be possible to differentiate these nowadays, `browser.tabs.loadDivertedInBackground` set to true behaves like that since I remember, but TMP was able to take care of it recently, not anymore

currently I'm running 110.0b3 (64-bit) and the same thing happened in b2, can't say for sure if it worked in b1 or not

**Comment by onemen** [comment]
Download an install [this test build](https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.12/tab_mix_plus-1.0.0-pre.13.20230120.1.xpi)

**Comment by zakius** [comment]
I'm sorry it took me so long, it works as expected (also on b8), thanks!
