### ISSUE TITLE
FX110b3 ErrMsg

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#205]
![image](https://user-images.githubusercontent.com/8281345/213714619-ea4126ad-c911-4aa8-9a79-de2763f86516.png)
![image](https://user-images.githubusercontent.com/8281345/213714824-8d21afe3-cc4f-4a83-a14f-058517a60841.png)
![image](https://user-images.githubusercontent.com/8281345/213714888-b403924d-9d16-4afc-80d3-b80227648bf1.png)

**Comment by onemen** [comment]
Download an install [this test build](https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.12/tab_mix_plus-1.0.0-pre.13.20230120.1.xpi)
