### ISSUE TITLE
Blank tabs pick up another tab title, and it sticks

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#206]
This is a bit strange, I think. Everything was fine, and then tab titles on blank tabs started showing the title from one tab I used a while ago. The blank tabs themselves are fine — blank as they should be, and when I change the tab title, it changes fine. But when I create a new blank tab, the same thing happens, same title reappears.. 

Win 10
Fx 109.0
TMP 1.0.0-pre.12

**Comment by onemen** [comment]
report if you get any messages in the browser console

**Comment by VLM-TechEd** [comment]
I am not familiar with reading the console. So:

 

I closed Firefox.

I relaunched Firefox.

I opened the console (ctrl-shift-J).

I opened a new window: the tab title correctly reads “New Tab”. 

I opened a new tab (ctrl-T): the tab title is wrong, as previously described.

 

The console now contains the following. I hope you find something useful. Thank you!

Browser Console Mode

Parent process only(Fast)Multiprocess(Slower)

Applying chrome://tabmixplus/content/tabmix.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:92:15 <chrome://tabmix-resource/content/bootstrap/Overlays.jsm> 

Loading eval'd script into chrome://browser/content/browser.xhtml Overlays.jsm:546:15 <chrome://tabmix-resource/content/bootstrap/Overlays.jsm> 

Tabmix initializer: 

Object { key: "init", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "beforeStartup", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "onContentLoaded", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "beforeBrowserInitOnLoad", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "onWindowOpen", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "afterDelayedStartup", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:92:15 <chrome://tabmix-resource/content/bootstrap/Overlays.jsm> 

Loading eval'd script into chrome://browser/content/browser.xhtml Overlays.jsm:546:15 <chrome://tabmix-resource/content/bootstrap/Overlays.jsm> 

Tabmix initializer: 

Object { key: "init", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "beforeStartup", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "onContentLoaded", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "beforeBrowserInitOnLoad", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "onWindowOpen", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "afterDelayedStartup", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:92:15 <chrome://tabmix-resource/content/bootstrap/Overlays.jsm> 

Loading eval'd script into chrome://browser/content/browser.xhtml Overlays.jsm:546:15 <chrome://tabmix-resource/content/bootstrap/Overlays.jsm> 

Tabmix initializer: 

Object { key: "init", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "beforeStartup", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "onContentLoaded", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "beforeBrowserInitOnLoad", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "onWindowOpen", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "afterDelayedStartup", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Unsupported zoom settings: {"defaultZoomFactor":null,"mode":"automatic","scope":null} ExtensionCommon.jsm:726 <resource://gre/modules/ExtensionCommon.jsm> 

Key event not available on some keyboard layouts: key=“w” modifiers=“accel alt shift” id=“mpPk” index.html <chrome://devtools/content/webconsole/index.html> 

Unsupported zoom settings: {"defaultZoomFactor":null,"mode":"automatic","scope":null} 2 ExtensionCommon.jsm:726 <resource://gre/modules/ExtensionCommon.jsm> 

Key event not available on some keyboard layouts: key=“w” modifiers=“accel alt shift” id=“mpPk” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“e” modifiers=“accel,alt” id=“” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“w” modifiers=“accel,alt” id=“” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“s” modifiers=“accel,alt” id=“” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“z” modifiers=“control,alt” id=“key_tm_ucatab” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“l” modifiers=“control,alt” id=“key_tm_clearClosedTabs” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“d” modifiers=“control,alt,shift” id=“key_tm_removesimilar” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“w” modifiers=“control,alt” id=“key_tm_removeall” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“v” modifiers=“control,alt” id=“key_tm_pasteTabUrl” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“c” modifiers=“control,alt” id=“key_tm_copyTabUrl” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“d” modifiers=“control,alt” id=“key_tm_dupTab” browser.xhtml <chrome://browser/content/browser.xhtml> 

this.window.gBrowser is undefined ext-browser.js:1139 <chrome://browser/content/parent/ext-browser.js> 

TypeError: bottomBox is null

status-bar.uc.js:108:5 <file:///C:/Users/VLMin%20001/AppData/Roaming/Mozilla/Firefox/Profiles/gjjt563l.default-release/chrome/status-bar.uc.js?1661881776880> 

Uncaught TypeError: aToolbar is null

    registerToolbarNode resource:///modules/CustomizableUI.jsm:1018

    registerToolbarNode resource:///modules/CustomizableUI.jsm:3967

    onDOMContentLoaded chrome://browser/content/browser.js:1744

CustomizableUI.jsm:1018:16 <resource://modules/CustomizableUI.jsm> 

Error: An unexpected error occurred undefined

Applying chrome://tabmixplus/content/tabmix.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:92:15 <chrome://tabmix-resource/content/bootstrap/Overlays.jsm> 

Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:92:15 <chrome://tabmix-resource/content/bootstrap/Overlays.jsm> 

Loading eval'd script into chrome://browser/content/browser.xhtml Overlays.jsm:546:15 <chrome://tabmix-resource/content/bootstrap/Overlays.jsm> 

Tabmix initializer: 

Object { key: "init", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "beforeStartup", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "onContentLoaded", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "beforeBrowserInitOnLoad", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "onWindowOpen", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Tabmix initializer: 

Object { key: "afterDelayedStartup", phase: {…} }

tabmix.js:1152:17 <chrome://tabmixplus/content/tabmix.js> 

Key event not available on some keyboard layouts: key=“w” modifiers=“accel alt shift” id=“mpPk” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“e” modifiers=“accel,alt” id=“” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“w” modifiers=“accel,alt” id=“” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“s” modifiers=“accel,alt” id=“” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“z” modifiers=“control,alt” id=“key_tm_ucatab” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“l” modifiers=“control,alt” id=“key_tm_clearClosedTabs” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“d” modifiers=“control,alt,shift” id=“key_tm_removesimilar” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“w” modifiers=“control,alt” id=“key_tm_removeall” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“v” modifiers=“control,alt” id=“key_tm_pasteTabUrl” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“c” modifiers=“control,alt” id=“key_tm_copyTabUrl” browser.xhtml <chrome://browser/content/browser.xhtml> 

Key event not available on some keyboard layouts: key=“d” modifiers=“control,alt” id=“key_tm_dupTab” browser.xhtml <chrome://browser/content/browser.xhtml>

**Comment by onemen** [comment]
`Tabmix initializer` indicate that Tab Mix starts without any problem. 
I see some errors that are unrelated to Tab Mix

```
Unsupported zoom settings: {"defaultZoomFactor":null,"mode":"automatic","scope":null} ExtensionCommon.jsm:726 <resource://gre/modules/ExtensionCommon.jsm>

TypeError: bottomBox is null...

Uncaught TypeError: aToolbar is null...
```

Are you using any scripts?  - `status-bar.uc.js` ?, any other extensions?

Try to create new profile

**Comment by VLM-TechEd** [comment]
SCRIPTS:  YES

 

Extension Options Menu

Master Password +

Status Bar (as you suggested)

StyloaiX

 

I turned them all off, with all extensions other than TMP disabled, and restarted Firefox. No effect.

 

OTHER EXTENSIONS: YES

 

Active Reader View

Bookmark search plus 2

Canvas Blocker

Copy plain text

Default bookmark folder

Enable Built-in Container Feature

Facebook container

Malwarebytes Browser Guard

NoSquint Plus

Show/Hide Password

Startpage Privacy Protection

Startpage.com private search engine

Switch to Audible tab

Tab Session Manager

uBlock Origin

Video DownloadHelper

YouTube High Definition

 

The one that jumped out at me is NoSquint, given the zoom errors you flagged. This extension works flawlessly in Pale Moon but the Firefox Web Extensions version has problems. So I disabled it and restarted Firefox. No effect.

 

Next, I disabled all extensions other than TMP and restarted Firefox. No effect.

 

NEW PROFILE: Need to learn how in detail. Will work on this later, when I have more time. For now, thank you, and I’ll be in touch. Meanwhile, I look forward to any input you might offer based upon anything in the foregoing.

**Comment by onemen** [comment]
Upload a file with your Tab Mix Preferences

[How to export Tab Mix preferences to a file](https://tabmixplus.org/support/viewtopic.php?t=3&p=display-tab)

**Comment by VLM-TechEd** [comment]
I don’t know whether sending it this way works. If not, please let me know.


tabmixplus
browser.allTabs.previews=true
browser.ctrlTab.previews=true
browser.link.open_newwindow=3
browser.link.open_newwindow.override.external=-1
browser.link.open_newwindow.restriction=2
browser.newtab.url=about:logopage
browser.search.context.loadInBackground=true
browser.search.openintab=false
browser.sessionstore.interval=60000
browser.sessionstore.max_tabs_undo=500
browser.sessionstore.postdata=0
browser.sessionstore.privacy_level=0
browser.sessionstore.restore_on_demand=true
browser.sessionstore.resume_from_crash=true
browser.startup.page=0
browser.tabs.animate=false
browser.tabs.closeWindowWithLastTab=false
browser.tabs.insertRelatedAfterCurrent=true
browser.tabs.loadBookmarksInBackground=false
browser.tabs.loadDivertedInBackground=false
browser.tabs.loadInBackground=false
browser.tabs.tabClipWidth=140
browser.tabs.tabMaxWidth=1280
browser.tabs.tabMinWidth=100
browser.tabs.warnOnClose=true
browser.warnOnQuit=false
toolkit.scrollbox.clickToScroll.scrollDelay=150
toolkit.scrollbox.smoothScroll=true
extensions.tabmix.altClickTab=28
extensions.tabmix.altClickTabbar=29
extensions.tabmix.autoReloadContent=false
extensions.tabmix.autoReloadMenu=false
extensions.tabmix.bookmarkTabMenu=false
extensions.tabmix.bookmarkTabsMenu=false
extensions.tabmix.closeAllMenu=false
extensions.tabmix.closeLeftMenu=false
extensions.tabmix.closeOnSelect=true
extensions.tabmix.closeOtherMenu=false
extensions.tabmix.closeRightMenu=false
extensions.tabmix.closeSimilarTabs=false
extensions.tabmix.closeTabContent=false
extensions.tabmix.closeTabMenu=false
extensions.tabmix.closedWinToolsMenu=true
extensions.tabmix.copyTabUrlMenu=true
extensions.tabmix.ctrlClickTab=22
extensions.tabmix.ctrlClickTabbar=23
extensions.tabmix.currentTab=true
extensions.tabmix.custom_reload_list=
extensions.tabmix.dblClickTab=11
extensions.tabmix.dblClickTabbar=23
extensions.tabmix.detachTabContent=true
extensions.tabmix.detachTabMenu=true
extensions.tabmix.disableBackground=false
extensions.tabmix.disableIncompatible=true
extensions.tabmix.docShellMenu=false
extensions.tabmix.duplicateMenu=true
extensions.tabmix.duplicateTabContent=true
extensions.tabmix.duplicateWinContent=false
extensions.tabmix.duplicateinWinMenu=false
extensions.tabmix.enablefiletype=true
extensions.tabmix.extraIcons.autoreload=true
extensions.tabmix.extraIcons.locked=true
extensions.tabmix.extraIcons.notpinned=false
extensions.tabmix.extraIcons.protected=true
extensions.tabmix.filetype=xpi zip rar exe tar jar gzip gz ace bin doc docx xls xlsx mdb ppt iso 7z cab arj lzh uue torrent /&disp=attd&/ /php?attachmentid=.*/ /php?act=Attach&type=post&id=.*/ /download\.php?*/
extensions.tabmix.flexTabs=true
extensions.tabmix.focusTab=4
extensions.tabmix.freezeTabContent=false
extensions.tabmix.freezeTabMenu=false
extensions.tabmix.hideAllTabsButton=true
extensions.tabmix.hideIcons=false
extensions.tabmix.hideTabBarButton=true
extensions.tabmix.hideTabbar=0
extensions.tabmix.inversefocusLinks=false
extensions.tabmix.inversefocusOther=false
extensions.tabmix.keepLastTab=false
extensions.tabmix.lasttab.respondToMouseInTabList=true
extensions.tabmix.lasttab.showTabList=true
extensions.tabmix.lasttab.tabPreviews=false
extensions.tabmix.linkTarget=false
extensions.tabmix.linkWithHistory=false
extensions.tabmix.loadBookmarksAndReplace=false
extensions.tabmix.loadBookmarksGroupInBackground=false
extensions.tabmix.loadDuplicateInBackground=false
extensions.tabmix.loadExternalInBackground=false
extensions.tabmix.loadNewInBackground=false
extensions.tabmix.loadOnNewTab.type=0
extensions.tabmix.loadSearchInBackground=false
extensions.tabmix.loadSyncedTabsInBackground=false
extensions.tabmix.loadUrlInBackground=false
extensions.tabmix.load_tabs_progressively=1
extensions.tabmix.lockAppTabs=false
extensions.tabmix.lockTabContent=false
extensions.tabmix.lockTabMenu=false
extensions.tabmix.lockTabSizingOnClose=false
extensions.tabmix.lockallTabs=false
extensions.tabmix.mergeAllWindows=false
extensions.tabmix.mergePopups=true
extensions.tabmix.mergeWindowContent=true
extensions.tabmix.middleClickTab=0
extensions.tabmix.middleClickTabbar=0
extensions.tabmix.middleclickDelete=false
extensions.tabmix.middlecurrent=true
extensions.tabmix.mouseOverSelect=false
extensions.tabmix.mouseOverSelectDelay=250
extensions.tabmix.moveSwitchToTabNext=false
extensions.tabmix.moveTabOnDragging=true
extensions.tabmix.moveToGroup=true
extensions.tabmix.muteTabMenu=true
extensions.tabmix.newTabButton=false
extensions.tabmix.newTabButton.position=2
extensions.tabmix.newTabMenu=false
extensions.tabmix.offsetAmountToScroll=false
extensions.tabmix.openAllLinks=false
extensions.tabmix.openDuplicateNext=true
extensions.tabmix.openInverseLink=false
extensions.tabmix.openLinkHere=false
extensions.tabmix.openNewTabNext=false
extensions.tabmix.openTabNext=false
extensions.tabmix.openTabNextInverse=true
extensions.tabmix.opentabfor.bookmarks=true
extensions.tabmix.opentabfor.history=true
extensions.tabmix.opentabfor.syncedTabs=false
extensions.tabmix.opentabfor.urlbar=true
extensions.tabmix.opentabforLinks=1
extensions.tabmix.optionsToolMenu=true
extensions.tabmix.otherTab=true
extensions.tabmix.pinTabMenu=false
extensions.tabmix.pinnedTabScroll=false
extensions.tabmix.placePopupNextToOpener=true
extensions.tabmix.progressMeter=true
extensions.tabmix.protectTabContent=false
extensions.tabmix.protectTabMenu=false
extensions.tabmix.protectedtabs.warnOnClose=false
extensions.tabmix.reloadAllMenu=false
extensions.tabmix.reloadEvery.onReloadButton=false
extensions.tabmix.reloadLeftMenu=false
extensions.tabmix.reloadOtherMenu=false
extensions.tabmix.reloadRightMenu=false
extensions.tabmix.reloadTabMenu=false
extensions.tabmix.reload_match_address=false
extensions.tabmix.reload_time=60
extensions.tabmix.renameTabMenu=false
extensions.tabmix.replaceLastTabWith.newtab.url=about:newtab
extensions.tabmix.replaceLastTabWith.type=0
extensions.tabmix.restore_on_demand=1
extensions.tabmix.reversedScroll=false
extensions.tabmix.scrollTabs=2
extensions.tabmix.selectLocationBar=false
extensions.tabmix.selectLocationBar.afterLastTabClosed=false
extensions.tabmix.selectTabOnMouseDown=false
extensions.tabmix.sessionToolsMenu=false
extensions.tabmix.sessions.crashRecovery=false
extensions.tabmix.sessions.manager=false
extensions.tabmix.sessions.max_backups=7
extensions.tabmix.sessions.menu.showext=true
extensions.tabmix.sessions.onClose=0
extensions.tabmix.sessions.onStart=2
extensions.tabmix.sessions.onStart.askifempty=true
extensions.tabmix.sessions.onStart.loadsession=-1
extensions.tabmix.sessions.onStart.restorePinned=true
extensions.tabmix.sessions.onStart.sessionpath=
extensions.tabmix.sessions.restore.concatenate=false
extensions.tabmix.sessions.restore.overwritetabs=true
extensions.tabmix.sessions.restore.overwritewindows=true
extensions.tabmix.sessions.restore.reloadall=false
extensions.tabmix.sessions.restore.saveoverwrite=true
extensions.tabmix.sessions.save.closedtabs=false
extensions.tabmix.sessions.save.history=true
extensions.tabmix.sessions.save.locked=true
extensions.tabmix.sessions.save.permissions=true
extensions.tabmix.sessions.save.protected=true
extensions.tabmix.sessions.save.scrollposition=true
extensions.tabmix.sessions.save.selectedtab=true
extensions.tabmix.shiftClickTab=3
extensions.tabmix.shiftClickTabbar=27
extensions.tabmix.shortcuts={"undoClose":"Z alt","mergeWin":"M alt","ucatab":"Z control,alt","dupTab":"D alt","detachTab":"N alt","renametab":"R control","copyTabUrl":"C control,alt","selectMerge":"Q alt","reload":"d&","pasteTabUrl":"V control,alt","removeother":"W alt","removesimilar":"D control,alt","clearClosedTabs":"L control,alt"}
extensions.tabmix.showMergeWindow=false
extensions.tabmix.showTabContextMenuOnTabbar=true
extensions.tabmix.singleWindow=false
extensions.tabmix.slideDelay=10
extensions.tabmix.styles.currentTab={"italic":false,"bold":true,"underline":false,"text":true,"textColor":"rgba(255,255,0,1)","bg":true,"bgColor":"rgba(51,0,51,1)","bgTopColor":"rgba(51,0,51,1)"}
extensions.tabmix.styles.otherTab={"italic":false,"bold":true,"underline":false,"text":true,"textColor":"rgba(0,0,153,1)","bg":true,"bgColor":"rgba(255,255,255,1)","bgTopColor":"rgba(255,255,255,1)"}
extensions.tabmix.styles.progressMeter={"bg":true,"bgColor":"rgba(102,0,204,1)"}
extensions.tabmix.styles.unloadedTab={"italic":false,"bold":true,"underline":false,"text":true,"textColor":"rgba(255,0,0,1)","bg":true,"bgColor":"rgba(255,255,255,1)","bgTopColor":"rgba(255,255,255,1)"}
extensions.tabmix.styles.unreadTab={"italic":false,"bold":true,"underline":false,"text":true,"textColor":"rgba(51,51,255,1)","bg":true,"bgColor":"rgba(255,255,51,1)","bgTopColor":"rgba(255,255,51,1)"}
extensions.tabmix.syncPrefs=false
extensions.tabmix.tabBarMaxRow=4
extensions.tabmix.tabBarMode=2
extensions.tabmix.tabBarPosition=0
extensions.tabmix.tabBarSpace=false
extensions.tabmix.tabFlip=false
extensions.tabmix.tabFlipDelay=250
extensions.tabmix.tabbar.click_dragwindow=false
extensions.tabmix.tabbar.dblclick_changesize=false
extensions.tabmix.tabs.closeButtons=3
extensions.tabmix.tabs.closeButtons.delay=50
extensions.tabmix.tabs.closeButtons.enable=true
extensions.tabmix.tabs.closeButtons.onLeft=false
extensions.tabmix.tabs.warnOnClose=false
extensions.tabmix.tabsList=true
extensions.tabmix.targetIsFrame=true
extensions.tabmix.titlefrombookmark=true
extensions.tabmix.undoClose=true
extensions.tabmix.undoClose.keepMenuOpen=false
extensions.tabmix.undoCloseButton.menuonly=true
extensions.tabmix.undoCloseListContent=true
extensions.tabmix.undoCloseListMenu=true
extensions.tabmix.undoClosePosition=true
extensions.tabmix.undoCloseTabContent=true
extensions.tabmix.undoCloseTabMenu=true
extensions.tabmix.unloadedTab=true
extensions.tabmix.unreadTab=true
extensions.tabmix.unreadTabreload=true
extensions.tabmix.updateOpenedTabsLockState=true
extensions.tabmix.useFirefoxDragmark=true
extensions.tabmix.warnOnclose=true

**Comment by VLM-TechEd** [comment]
I did indeed have a bookmark with the unwanted name and location set to about:blank. I changed the bookmark name, and the problem is gone. I must have assigned “about:blank” to that name at some point without realizing it.

 

Thank you.
