### ISSUE TITLE
Fx111.0b1 ErrMsg

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#208]
![image](https://user-images.githubusercontent.com/8281345/219367972-667438b7-4b87-47c5-83fe-a197cde0a164.png)

**Comment by onemen** [comment]
I will upload new version during the weekend

**Comment by onemen** [comment]
Download latest version [[v1.0.0-pre.13](https://github.com/onemen/TabMixPlus/releases/tag/untagged-6266e3dff2b44131706f)](https://github.com/onemen/TabMixPlus/releases)

**Comment by 117649** [comment]
Can confirm reds are gone.
