### ISSUE TITLE
Mouse drag and drop not working

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#21]
fb6614b5
These changes will put DnD in to work but nothing seems right.

**Comment by onemen** [comment]
Thank you @117649 , i will take a look one after finish working on multi-row

**Comment by 117649** [comment]
Not seeing any error in console so far.
It look like the codes work as intended but the changes in Firefox cause them generate unwanted behavior.
And also some of the changecode() may not in fully effective since the original function they are tap into have changed dramatically.

**Comment by onemen** [comment]
Try to describe the visual bugs you see, what exactly doesn't work and how to reproduce each one

**Comment by 117649** [comment]
> Try to describe the visual bugs you see, what exactly doesn't work and how to reproduce each one

1. Drop indicator: built-in style not working.  Native indicator shows all the time and won't disappear.  There is very limit time the built-in do shows but not consistent and with native indicator displayed at same time.
2.  'When dragging a tab move it directly' has no effect for not checked state.
3. While dragging things into the browser tab bar Firefox have the function of switch the current selected tab to the one mouse pointer hovering on after wait a while. This seems not working right with TMP DnD enabled, switch happened as soon as the mouse cursor passing the tab without any delay.
4. No blank tab opened for .xpi file despite not using the option in TMP's link panel.

**Comment by onemen** [comment]
I'm thinking of removing old tabmix  style indicator 
![image](https://user-images.githubusercontent.com/3650909/105968700-14798f00-6090-11eb-98f7-d9cd43cf7da1.png)

it not adding any better user experience

**Comment by 117649** [comment]
> I'm thinking of removing old tabmix style indicator
> ![image](https://user-images.githubusercontent.com/3650909/105968700-14798f00-6090-11eb-98f7-d9cd43cf7da1.png)
> 
> it not adding any better user experience

If so we mat also be able to simplify `tabbinding.js` .

**Comment by onemen** [comment]
Yes

**Comment by onemen** [comment]
Maybe it is best to write the code from scratch.

We need to add support for:
 - multi-row 
 - tabs with different width to calculate drop index
 - blocking link drop on locked tab (in dragover)
 - open link that will start a download in the current tab instead of new tab
 - block opening new window from detached tab in single window mode
 - hiding close button that is visible on hover only
 - ...

The current code was compatible with Firefox 55. 

currently **dragover** dosn't work since ```aEvent.target.localName``` is never tab or tabs
```
      case "dragover": {
        let target = aEvent.target.localName;
        if (target != "tab" && target != "tabs")
          return;
        if (this.tabBar.useTabmixDnD(aEvent))
          TMP_tabDNDObserver.onDragOver(aEvent);
        break;
      }
```

**Comment by 117649** [comment]
> * tabs with different width to calculate drop index

This one may not needed, current test shows that drop index is on the right position for single row with 'Tab width fit to tab tittle' enabled.

Now for some reason I don't know you may need to flip 'show close button on tab when mouse hover' switch off and on once after updated add-on for it to function.

**Comment by onemen** [comment]
> Now for some reason I don't know you may need to flip 'show close button on tab when mouse hover' switch off and on once after updated add-on for it to function.

this is the simplest of all, we just call ```TabmixTabbar.removeShowButtonAttr``` from dragstart

**Comment by 117649** [comment]
Newest test on the Fx86 and latest commit shows 'built-in style Drop indicator' and 'When dragging a tab move it directly' are working.

**Comment by onemen** [comment]
dragging tab from another window not working

**Comment by 117649** [comment]
> dragging tab from another window not working

I remember there seems a function that check dragging type may be take a look into that.

**Comment by onemen** [comment]
my bad ....
```diff
-   if (aSourceNode.container == aSourceNode.ownerGlobal.gBrowser.tabContainer)
+   if (aSourceNode.container == gBrowser.tabContainer)
```

**Comment by 117649** [comment]
https://github.com/onemen/TabMixPlus/blob/11c112279de573015e31273127a08cca7a4caa8f/addon/modules/ContentClick.jsm#L729-L736
Why? I think when user turn it off then it should be completely off.

**Comment by onemen** [comment]
we don't open new tab for left click on xpi links

**Comment by 117649** [comment]
> we don't open new tab for left click on xpi links

It also affect drag and drop which is inconvenient. Since Firefox are not very responsive regarding xpi dragged in from hard drive it just lost install panel and many attempts may be required. Having a blank page with url helps a lot on retry install a xpi especially when you trying developing an addon . 
And xpi is listed in the options it should obey that control it just shouldn't be hard coded.

**Comment by onemen** [comment]
i will test when i finished updating drag and drop functions

it is most likely work if you drag a file onto about:addons

**Comment by 117649** [comment]
Little change like this that close the condition statement works for me well.
```diff
           .filter(t => filetype.indexOf(t) == -1);
       filetype = [...filetype, ...types];
     }
+    else return false;
     var linkHrefExt = "";
     if (linkHref) {
```

**Comment by onemen** [comment]
@117649 ,
Do you think we need this message, when dragging link to the on tabs ?

![image](https://user-images.githubusercontent.com/3650909/128503605-0c166995-bb39-4737-9044-ab9987d5b11a.png)

**Comment by 117649** [comment]
> 
> 
> @117649 ,
> Do you think we need this message, when dragging link to the on tabs ?
> 
> ![image](https://user-images.githubusercontent.com/3650909/128503605-0c166995-bb39-4737-9044-ab9987d5b11a.png)

Yes. If the function it stated are real and provide by TMP not Mozilla.

May be tweak the wording to shorter the sentence. It indeed pretty long for a tool tip.

**Comment by onemen** [comment]
> Yes. If the function it stated are real and provide by TMP not Mozilla.

When this function was introduced almost 14 years ago it was new feature, now days this is the standard action when dragging a link.

Tabmix block drop on locked tab, user can unlock the tab by pressing Ctrl/meta, but details about this feature and others should be in the documentation and not in tooltip

**Comment by onemen** [comment]
I will change the code to show tooltip when link is dragged over a locked tab
  - for mac **Hold ⌘ to allow link Url to replace locked tab**
  - for others  **Hold Ctrl to allow link Url to replace locked tab** 

I hope you can suggest better wording...

**Comment by 117649** [comment]
> 
> 
> I will change the code to show tooltip when link is dragged over a locked tab
> 
>     * for mac **Hold ⌘ to allow link Url to replace locked tab**
> 
>     * for others  **Hold Ctrl to allow link Url to replace locked tab**
> 
> 
> I hope you can suggest better wording...

 eh. **Hold Ctrl to replace locked tab with link Url** ? 

I'm not sure if this is grammar correct but at least a word shorter.

**Comment by onemen** [comment]
🥇
