### ISSUE TITLE
The right button on Scrollable tab bar does not light up blue when new tab open.

### ISSUE THREAD

**Issue by shalclc** [onemen/TabMixPlus#210]
The right scroll button lights up blue when new tab is opened when the following settings are made. 

about:config 
browser.tabs.insertRelatedAfterCurrent : false

However, when TMP is installed, it does not light up blue.

FF 102.8.0 ESR and TMP 1.0.0-pre.13

**Comment by onemen** [comment]
download and install this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.14.20230219.1.xpi)

**Comment by shalclc** [comment]
I confirmed it is fine.
Thank you very much for your quick response.
