### ISSUE TITLE
Firefox 112 drop support for -moz-image-region

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#211]
Firefox 112 drop support for `-moz-image-region` - [bug 1817071](https://bugzilla.mozilla.org/show_bug.cgi?id=1817071)
we need to split these `png` icons files and update related css files

tabs list
![tabslist](https://user-images.githubusercontent.com/3650909/221144337-a880b035-8318-41dd-b3e5-9201009ffe20.png)

preferences
![tmpoptions](https://user-images.githubusercontent.com/3650909/221144348-b9790c2e-318d-4ce2-9d20-7504c14dca6e.png)

closed tabs
![undoclosetab](https://user-images.githubusercontent.com/3650909/221144357-7cffa9bd-5373-4e1e-86ee-587ce496975b.png)

closed windows
![undoclosewindow](https://user-images.githubusercontent.com/3650909/221144364-38ad7521-c70c-469a-82fb-0666e5e2532c.png)

session manager
![sessionmanager](https://user-images.githubusercontent.com/3650909/221144320-d3f5bfff-c856-4522-ac04-38450d1a1128.png)

**Comment by 117649** [comment]
What about ```-moz-image-rect```?

**Comment by onemen** [comment]
> moz-image-rect

It is only use 8 time in Firefox and it is non-standard feature, it will probably remove .
