### ISSUE TITLE
Visual glitch after updating to 1.0.0-pre.14

### ISSUE THREAD

**Issue by strongBurger** [onemen/TabMixPlus#214]
on firefox 102.0.1

i now get a little glitch artefact next to the last tab from the last update.
check screenshots, its a little square

https://imgur.com/a/Ksn6b14

im using toolkit.legacyUserProfileCustomizations.stylesheets=true to get old themed firefox using userChrome.css

also the square disappear if i close the last tab

**Comment by onemen** [comment]
post your `userChrome.css`

**Comment by onemen** [comment]
I don't really see what the issue in the image you posted.
Attach your Tab Mix preferences

If your using old Firefox at-least use the latest ESR version 102.9 https://www.mozilla.org/en-US/firefox/enterprise/

**Comment by strongBurger** [comment]
okay, i created a new profile and the glitch is gone now.

problem was here: https://i.ibb.co/FxVbmbP/1.png

nevermind its gone
