### ISSUE TITLE
Tab width inconsistency in version 113 when ‘tab width fits to tab width’ option is disabled

### ISSUE THREAD

**Issue by soeyu** [onemen/TabMixPlus#215]
### Description
In version 113, the width of the tabs is inconsistent when the ‘tab width fits to tab width’ option is not enabled, while in version 112 they are equal in width. I checked the console and it seems that Firefox changed some global styles, I don’t know if it’s a new feature or a bug, is there a way to keep the tabs equal in width?

### Configuration file:
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/11218320/TMPpref.txt)
### Reproduce
https://user-images.githubusercontent.com/3954659/231658646-18ccd0c1-1b83-4864-8aef-f586e823fb0d.mp4

#### **Found some style changes, but not all:**
![2](https://user-images.githubusercontent.com/3954659/231659629-dcfcd39a-e160-4758-8ae5-04ee81a4129d.png)
![3](https://user-images.githubusercontent.com/3954659/231660931-24e5a234-df16-4f57-b636-a24a0acd27ed.jpg)

**Comment by onemen** [comment]
Are you using any custom style or style extension?
did you check how tabs look on new profile without any other extension

In Firefox 112 tab display was `-moz-box`  and from 113 it is `flex`

try to add to `userChrome.css`:

```css
#tabbrowser-tabs .tabbrowser-tab  {
  display: -moz-box !important;
}
```

to enable `userChrome.css` set in about:config `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`

**Comment by soeyu** [comment]
I tried it, used the new profile file and set chrome.css, and found that -moz-box became an invalid property value.
![22](https://user-images.githubusercontent.com/3954659/231785467-0ff7f24a-23d5-4fd9-8e1f-b016ee0bf357.jpg)

**Comment by onemen** [comment]
Try other valid value for the display

**Comment by soeyu** [comment]
I tried to delete the ‘auto’ and It looks like it was fixed , version 112 is also not affected.
![244](https://user-images.githubusercontent.com/3954659/231833502-8f675279-2013-4792-bf35-8831dda814b1.jpg)

**Comment by onemen** [comment]
![tabwidth](https://user-images.githubusercontent.com/3650909/231945672-7c3ae1a2-6131-46de-80e5-b4c6d5c08e4b.png)

With `flex: 1 1 0%` there is still an issue with tab width on multi-row

**Comment by onemen** [comment]
I managed to fix this issue. It will be included in version 1.24.0

If you read this post before version 1.24.0 you can test it know

Download this [test build](https://github.com/user-attachments/files/17202518/test-build-1.23.1-20241001.1200.zip)

Rename it to `.xpi` and install it.

Report back.

**Comment by soeyu** [comment]
I have always been using the latest version, and it has been running well in my use cases. There might have been issues before regarding the "multi-row tab" setting, but I don't usually enable multi-row tabs, so I haven’t noticed any specific differences between the 1.24 update and previous versions.（Translated using ChatGPT）

**Comment by onemen** [comment]
Thank you @soeyu for your feedback
