### ISSUE TITLE
Firefox reports TMP .xpi file corrupted

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#216]
Win 10 Home
Firefox 112.0, brand new installation today.
userChromeJS is installed property, as far as I can tell.

Downloaded tab_mix_plus-dev-build.xpi , then File > Open in Firefox generates the error. (That is the only .xpi file I see under Assets.) I recall that this happened long ago, but I don't recall the fix and apparently I did not save it. Sorry.

**Comment by VLM-TechEd** [comment]
I should add that in this brand new Firefox installation, no extension or userscript icons are displaying on the toolbar or in the customized links well. I have never encountered this before and have no earthly idea what may be causing it. The extensions DO appear in the context and Tools menus, as expected per extension. I suspect that this has something to do with that new puzzle-shaped extensions icon. the extensions all appear there, but of course they are not actionable there. Is there some setting that could be turning off all user-installed toolbar buttons? Could that impact TMP?

**Comment by VLM-TechEd** [comment]
OMG, I just "solved" the icon display problem. If click on the new puzzle icon, then right-click on a given extension, then select Pin to Toolbar, the icon appears on the toolbar and the item is removed from the puzzle icon list. How STUPID is that??? !!! Anway, you can ignore all but the corrupt installation problem.

**Comment by onemen** [comment]
Follow these [instructions](https://github.com/xiaoxiaoflood/firefox-scripts#instructions)

**Comment by VLM-TechEd** [comment]
Thank you. I had done all that, but upon rereading the instructions, I realized that I had misinterpreted one of the steps. All works fine now, thank you again.

**Comment by onemen** [comment]
Thank you for using Tab Mix Plus

Tell your friend about it

**Comment by VLM-TechEd** [comment]
I do!
