### ISSUE TITLE
Bug: Certain window sizes cause rapid flickering of tabs when using multiple rows

### ISSUE THREAD

**Issue by Jaxkr** [onemen/TabMixPlus#217]
See attached video for example and reproduction:

https://user-images.githubusercontent.com/1147244/235279005-421363ca-bebe-4411-9a3e-5b953cce1959.mp4

As you can see, the width at which the tabs flicker depends on the number of tabs. I am running Windows 11 and the latest Firefox release.

Also, I donated after installing TabMixPlus last week! Thanks so much for this amazing extension, I love multiple rows of tabs!

**Comment by onemen** [comment]
Try to change the preference for **new tab button** to **right** instead of **after last tab**

**Comment by Jaxkr** [comment]
Fixes it, thanks!!

**Comment by onemen** [comment]
can you post your preference as a file

**Comment by onemen** [comment]
download and try this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.15.20230429.1.xpi)

**Comment by Jaxkr** [comment]
> can you post your preference as a file

I changed my settings back to have new tab button after the last tab. Here's them exported: [TMPpref.txt](https://github.com/onemen/TabMixPlus/files/11359994/TMPpref.txt)

**Comment by onemen** [comment]
let me know if the test build fixed the issue with your original preferences

**Comment by Jaxkr** [comment]
> let me know if the test build fixed the issue with your original preferences

It does. But the New Tab button doesn't always appear behind the last tab. At certain screen sizes it will flicker a few times and then land here, which is the same as having it on the right
![image](https://user-images.githubusercontent.com/1147244/235407439-77daa2e3-000a-44cf-9308-6da2dcd44011.png)


For my personal purposes I consider this issue resolved! I do NOT need a new tab button haha.

**Comment by onemen** [comment]
@Jaxkr 

Can you test this new build, I have update the fix from last year

Download this [test build](https://github.com/user-attachments/files/17189492/test-build-1.23.1-20240930.1506.zip)

Rename it to `.xpi` and install it.

Report back.
