### ISSUE TITLE
Various Tab sizes in the same browser window with latest FF update

### ISSUE THREAD

**Issue by Mrsash2020** [onemen/TabMixPlus#219]
Like the title says I installed the latest FF update and the tab sizes vary in the browser. Please help

**Comment by AuRiMaS666** [comment]
Same problem here as well. This was reported some time ago in #215. Now that v113 is live, the fix would be very much appreciated.

**Comment by Mrsash2020** [comment]
I didnt have this issue before current Firefox update.

**Comment by Jaxkr** [comment]
Also experiencing this issue. I solved it by forcing all my tabs to be the same width :P

![image](https://github.com/onemen/TabMixPlus/assets/1147244/19b1223d-d8a0-4a65-ad92-082eed212e3c)

Works really nicely since I have four rows of tabs!

**Comment by onemen** [comment]
report if this works for you

download and try this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.15.20230429.1.xpi)

**Comment by chimalek** [comment]
> report if this works for you
> 
> download and try this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.15.20230429.1.xpi)

Thanx, works! :)

**Comment by AuRiMaS666** [comment]
Everything seems to work perfectly again. Thanks for a speedy resolution!
