### ISSUE TITLE
"Share" Tab Context Menu item displayed even when unchecked

### ISSUE THREAD

**Issue by AuRiMaS666** [onemen/TabMixPlus#220]
![2023-05-11 10 35 01](https://github.com/onemen/TabMixPlus/assets/59185222/233ba1eb-5958-498c-8add-a3c5ce7549f7)

Small issue, but still a little bit annoying. This seems to be the only problematic context menu item as far as I can tell.

**Comment by onemen** [comment]
check new version https://github.com/onemen/TabMixPlus/releases 15

**Comment by AuRiMaS666** [comment]
Thanks a lot for a speedy fix!
