### ISSUE TITLE
Tab progress bar

### ISSUE THREAD

**Issue by srjjgm** [onemen/TabMixPlus#221]
Tab progress bar is not working well. Sometimes it appears, but in most cases it doesn't.
I have updated userChromeJS files.

**Comment by onemen** [comment]
see #44

Just turn it off

**Comment by srjjgm** [comment]
Ok, I will turn it off until the problem is solved.
    Thanks!
    
    
    
    onemen escreveu em 13/05/2023, 03:54:
    
    
      
      see #44
      Just turn it off
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/onemen/TabMixPlus/issues/221#issuecomment-1546547732",
"url": "https://github.com/onemen/TabMixPlus/issues/221#issuecomment-1546547732",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
