### ISSUE TITLE
Doesn't seem to apply settings correctly on startup anymore

### ISSUE THREAD

**Issue by Jerrk** [onemen/TabMixPlus#225]
firefox nigthly: 116.0a1 (2023-06-08) (64-bit)
TMP: v1.0.0-pre.15

i noticed this a couple of days ago where my right-click context menu would show every single possible option even though i chose to only show 4-5 options.

and then today the tab custom colors also stopped working, now theyre always just white

the "new tab" button disappeared from the right side of the last open tab

I can no longer close the focused tab my middle clicking the tab (weirdly i **can** close unfocused tabs with middle-click)

the tab context menu and website context menus no longer follow the chosen settings.

-----------

There are probably more settings that aren't applying correctly but i couldn't name them off of the top of my head.

I have reinstalled userchrome and reinstalled the plugin with no changes.

My exported settings attached
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/11710381/TMPpref.txt)

**Comment by onemen** [comment]
download and install this test build
https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.16.20230607.1.xpi

**Comment by Jerrk** [comment]
> download and install this test build https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.16.20230607.1.xpi

yes that appears to have fixed all my issues, thanks!
