### ISSUE TITLE
Can't close current tab by clicking on close tab button or middle clicking. 

### ISSUE THREAD

**Issue by pixiekat** [onemen/TabMixPlus#227]
This seems like an odd bug but I was able to get back the functionality by going into safe mode and disabling all of my extensions or just disabling Tab Mix Plus, singularly. 

I'm using Firefox Nightly 116.0a1 (2023-06-15) (64-bit) and TMP 1.0.0-pre15 with boostrap_loader version workaround bug 857456 (it doesn't look like there's an updated version).

I can't see anything in the Tab Closing Events menu that would prevent closing the current tab by middle clicking and Mouse Clicking for middle click on current tab is set to Close Tab so I'm not sure what could be causing this. I can middle click to close fine on OTHER tabs just not the current one, even though there doesn't seem to be any option that would block or allow that.

Any thoughts? Thanks for any help you can provide! It was actually working fine previously but it's only started recently. Everything else works fine. 

Attached is my config: 
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/11769824/TMPpref.txt)

**Comment by onemen** [comment]
download and install this test build
https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.16.20230607.1.xpi

**Comment by pixiekat** [comment]
Oh thanks! I tried looking for a new release but I didn't see one. I'll check that out today.

**Comment by pixiekat** [comment]
Thank you! That seems to have done the trick. I don't see any of the favicons messing up anymore and the tab colours for tab styles are back.
