### ISSUE TITLE
I think we should keep an eye on the Mozilla's proton

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#23]
https://www.ghacks.net/2021/01/23/first-non-final-tabs-redesign-courtesy-of-proton-lands-in-firefox-nightly/
https://www.ghacks.net/2021/01/02/mozilla-is-working-on-a-firefox-design-refresh/

It's look like the Inner structure of the tab may change. Which may lead to needs of update our 'tab binding' in future.

**Comment by onemen** [comment]
Look like it landed on nightly today

**Comment by 117649** [comment]
One thing I can give to the new tab style is its a good fit for multi-row.

**Comment by 117649** [comment]
It is landed on dev edition.
And it break 'tab bindings'.
Have you attempted to fix it? If not I'm going to do so.

**Comment by onemen** [comment]
> Have you attempted to fix it?
No
you can work on it

**Comment by 117649** [comment]
![+](https://user-images.githubusercontent.com/8281345/115600704-9126ad00-a30f-11eb-8ff7-ca0e8babb9ec.png)
So far so good.

**Comment by 117649** [comment]
https://github.com/117649/TabMixPlus/commits/pr/multi-row
I've manage to fix some visual problem but it seems there is something wrong within delaystartup.

**Comment by 117649** [comment]
I've mixed in some fix for aboutaddons.js I'm just not sure whether proton broke it so the fix stay here for now.
https://github.com/117649/TabMixPlus/commit/36527aebc1f1610be3f1bf6afaa0257efdad63ec

**Comment by 117649** [comment]
@onemen Hi, just wonder would you be able to deal with this soon?

**Comment by onemen** [comment]
helpfully in june

**Comment by 117649** [comment]
> 
> 
> helpfully in june

@onemen Greetings any luck on resuming work on this?

**Comment by onemen** [comment]
that's the plane

**Comment by onemen** [comment]
I think we have it all covered by #41 https://github.com/onemen/TabMixPlus/pull/41/commits/fe8a5adbf1a7c2a12452bce6420f0f30e591ce9e

Let me know it anything is missing
