### ISSUE TITLE
Shortcut Alt+C can't be bound in settings menu

### ISSUE THREAD

**Issue by purple512** [onemen/TabMixPlus#230]
I'd like to configure Alt+C as a shortcut (Options -> Menu -> Shortcuts) but when typing this key combination, it triggers the Close button of the settings page.

I found a workaround: set it to a different key, export settings, edit the `extensions.tabmix.shortcuts` value to contain `"C alt"` instead, then re-import.

So, that works well enough for me but it would nice if it was not necessary.

**Comment by onemen** [comment]
Download and try this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.17.20230625.1.xpi)

**Comment by purple512** [comment]
It works! Thank you!
