### ISSUE TITLE
TMP Options dialog too large, goes off bottom of screen

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#234]
Win 10 up to date, Fx 115.0.3, TMP ...16

Because of eyesight issues, I have Windows set to display at 175%. Then I have Firefox set to zoom to 90%. Monitor resolution = 1920x1080, monitor default. The Firefox zoom does not appear to apply to the dialog.

The Options dialog runs off the bottom of the screen so that all the bottom controls (Import/Export, Apply, Close, etc.) are unavailable. I tried alt + spacebar, but the Size feature appears grayed out. So I could not try resizing the dialog on my own.

What else can I try? I suppose I could change the Windows display resolution whenever I want to access TMP Options. Thanks!

**Comment by onemen** [comment]
download and install [this test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.17.20230728.1.xpi)

**Comment by VLM-TechEd** [comment]
Perfectamundo! Thank you!

**Comment by onemen** [comment]
closed by 4839ae52f3d1a3e345c491a357d96684149354fd
