### ISSUE TITLE
Firefox 115 EME-Free - “This add on cannot be installed because it appears to be corrupt”.

### ISSUE THREAD

**Issue by rekabis** [onemen/TabMixPlus#236]
Across two different Windows computers, running both Librewolf and Firefox EME-Free. Both copies of Librewolf were able to upgrade to the latest TMP, but one - and only one - copy of Firefox ran into issues. I even tried to move the xpi from the computer where Firefox was able to install it, but also no dice - it was also reported as “corrupt”.

I have followed the #233 thread, updating both the [config.js](https://github.com/onemen/TabMixPlus/issues/233#issuecomment-1631529506) as well as [running code in the console](https://github.com/onemen/TabMixPlus/issues/233#issuecomment-1623713850) and [clearing the startup cache](about:support) multiple times.

Suggestions?

**Comment by rekabis** [comment]
Update: this continues to occur across Firefox 116.

**Comment by Scrotastic** [comment]
I get the same error on 117.0b8 (64-bit) but I haven't tried mucking around with every permutation of script.

**Comment by onemen** [comment]
Uninstall Tabmix

Use these files and follow [this](https://github.com/xiaoxiaoflood/firefox-scripts#instructions) instructions.

[Firefox config and pref](https://github.com/onemen/TabMixPlus/files/12257459/fx-folder.zip)

[utils → I'm interested in both scripts and extensions](https://github.com/onemen/TabMixPlus/files/12257460/utils_extensions_and_scripts.zip)
[utils → I'm only interested in extensions](https://github.com/onemen/TabMixPlus/files/12257461/utils_extensions_only.zip)
[utils → I'm only interested in scripts](https://github.com/onemen/TabMixPlus/files/12257458/utils_scripts_only.zip)

Donload an install Tab mix

**Comment by fizzybiz** [comment]
Hi Onemen - I followed your instructions to the letter, but am still getting the error "This add-on could not be installed because it appears to be corrupt".  From my hours of googling, it seems to be missing a manifest.jsom file in the .xpi?  I'm using FF version 116.0.3

**Comment by onemen** [comment]
You only see "This add-on could not be installed because it appears to be corrupt", if you did not installed the scripts properly

**Comment by fizzybiz** [comment]
Like I said, I followed your (excellent) notes to the letter. Is there any way of telling what could be wrong?

**Comment by onemen** [comment]
Try new profile

**Comment by fizzybiz** [comment]
Still not working - any more suggestions?  Have created a new profile
Here's what I've done, according to your instructions at https://github.com/xiaoxiaoflood/firefox-scripts#instructions
1. download fx-folder.zip - extracted all contents into c:\Program Files\Mozilla Firefox
2. created a chrome folder in C:\Users\micro\AppData\Roaming\Mozilla\Firefox\Profiles\[new profile name]\chrome 
3. downloaded the "utils_scripts_only.zip" and extracted it all into folder in 2. above
      the chrome folder now has a sub-folder calles \utils with the 3 files "chrome.manifest" "userChrome.jsm" and "xPref.jsm" in it
4. "save the desired userChromeJS scripts into chrome" - I have not done this as I think I've just done that in the above step
5. skipped - don't need this step
6. opened about:support and clicked "clear startup cache" - this automatically restarts Firefox
7. done is previous step

I then go back to https://github.com/onemen/TabMixPlus to step 2
2. download XPI - downloaded tab_mix_plus_dev_build from here; https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.16/tab_mix_plus-dev-build.xpi
3. open about:addons and select Extensions
4. Drag and drop tax_mix_lus-dev-build.xpi into the page

Get the message "this add-on could not be installed because it appears to be corrupt"

**Comment by onemen** [comment]
> downloaded the "utils_scripts_only.zip"

You need to dowload one of the other files.
Tab Mix is extension.
https://github.com/onemen/TabMixPlus/files/12257460/utils_extensions_and_scripts.zip

**Comment by gshillitani** [comment]
This is what my directory looks like. I also followed the instructions to the letter and still get the corrupt extension message. Have I done something wrong?

![Screenshot - Fri Aug 25, 2023 , 11_22_56 PM](https://github.com/onemen/TabMixPlus/assets/8304720/2d518954-2c5c-4320-88b9-cc64ba3bc7a2)

**Comment by fizzybiz** [comment]
OK now I get the error "this add-on could not be installed because it has not been verified"

**Comment by gshillitani** [comment]
> OK now I get the error "this add-on could not be installed because it has not been verified"

That's different, at least :)

**Comment by fizzybiz** [comment]
Sorry, I noticed more in the error log:
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://raw.githubusercontent.com/onemen/TabMixPlus/main/addon/icon.png [icon.png](https://raw.githubusercontent.com/onemen/TabMixPlus/main/addon/icon.png)
1693020248896	addons.xpi-utils	WARN	Add-on {dc572301-7619-498c-a57d-39143191b318} is not correctly signed. 2
1693020248897	addons.xpi	WARN	Invalid XPI: signature is required but missing

**Comment by gshillitani** [comment]
It just started working after I refreshed the cache a few more times...

**Comment by fizzybiz** [comment]
nope, not for me

**Comment by onemen** [comment]
All the files should be inside utils

**Comment by fizzybiz** [comment]
they are

**Comment by fizzybiz** [comment]
![image](https://github.com/onemen/TabMixPlus/assets/61228498/364b5d24-b4db-4ce9-b336-7860327a34c2)

**Comment by fizzybiz** [comment]
![image](https://github.com/onemen/TabMixPlus/assets/61228498/2966f4b1-9570-427a-b48b-0f8585cb7443)

**Comment by fizzybiz** [comment]
@onemen is the add-on correctly signed?

**Comment by onemen** [comment]
@fizzybiz,
the extension does not need to be signed if the script installed properly.

go to about:config and make sure you have this preferences:

`xpinstall.signatures.required` `false` **locked**
`extensions.install_origins.enabled` `false` **locked**
`general.config.obscure_value` `0`
`general.config.filename` `config.js`
`general.config.sandbox_enabled`  `false`

if any of the above preferences is missing or have different value, it is indication that ` fx-folder.zip` did not installed properly.
you need to have `config.js` file in the same directory `firefox.exe` is. and `config-prefs.js` file in `C:\Program Files\Firefox Nightly\defaults\pref`

**Comment by fizzybiz** [comment]
Am I meant to be using FF nightly?

**Comment by fizzybiz** [comment]
all of the above keys are set as you've listed
I have config.js in C:\Program Files\Firefox
I have config-prefs.js in C:\Program Files\Mozilla Firefox\defaults\pref

**Comment by fizzybiz** [comment]
Here's my config.js:

// skip 1st line
lockPref('xpinstall.signatures.required', false);
lockPref('extensions.install_origins.enabled', false);

try {
  const cmanifest = Cc['@mozilla.org/file/directory_service;1'].getService(Ci.nsIProperties).get('UChrm', Ci.nsIFile);
  cmanifest.append('utils');
  cmanifest.append('chrome.manifest');
  Components.manager.QueryInterface(Ci.nsIComponentRegistrar).autoRegister(cmanifest);

  const objRef = ChromeUtils.import('resource://gre/modules/addons/AddonSettings.jsm');
  const temp = Object.assign({}, Object.getOwnPropertyDescriptors(objRef.AddonSettings), {
    REQUIRE_SIGNING: { value: false }
  });
  objRef.AddonSettings = Object.defineProperties({}, temp);

  Cu.import('chrome://userchromejs/content/BootstrapLoader.jsm');
} catch (ex) {};

try {
  Cu.import('chrome://userchromejs/content/userChrome.jsm');
} catch (ex) {};

**Comment by onemen** [comment]
> Am I meant to be using FF nightly?

No.

> I have config.js in C:\Program Files\Firefox
> I have config-prefs.js in C:\Program Files\Mozilla Firefox\defaults\pref

make sure that you have the config.js and config-prefs.js in the same Firefox installation.
config.js need to be in `C:\Program Files\Mozilla Firefox`

if your profile is in `C:\Users\micro\AppData\Roaming\Mozilla\Firefox\Profiles\[new profile name]`
then your profile cache is in `C:\Users\micro\AppData\Local\Mozilla\Firefox\Profiles\[new profile name]`

- remove Tab mix extension.
- close Firefox
- make a backup from your profile cache `C:\Users\micro\AppData\Local\Mozilla\Firefox\Profiles\[new profile name]`
- remove your profile cache `C:\Users\micro\AppData\Local\Mozilla\Firefox\Profiles\[new profile name]`
- start Firefox again
- install Tab mix again

**Comment by fizzybiz** [comment]
> > I have config.js in C:\Program Files\Firefox
> > I have config-prefs.js in C:\Program Files\Mozilla Firefox\defaults\pref
> 
> make sure that you have the config.js and config-prefs.js in the same Firefox installation. config.js need to be in `C:\Program Files\Mozilla Firefox`

Yes, sorry it is

> if your profile is in `C:\Users\micro\AppData\Roaming\Mozilla\Firefox\Profiles\[new profile name]` then your profile cache is in `C:\Users\micro\AppData\Local\Mozilla\Firefox\Profiles\[new profile name]`
> 
>     * remove Tab mix extension.

By this, do you mean delete all the files from the .\chrome\utils folder?  If that's not what you mean, as I have never managed to get the extension to install, there is nothing to remove.

>     * close Firefox
> 
>     * make a backup from your profile cache `C:\Users\micro\AppData\Local\Mozilla\Firefox\Profiles\[new profile name]`
> 
>     * remove your profile cache `C:\Users\micro\AppData\Local\Mozilla\Firefox\Profiles\[new profile name]`
> 
>     * start Firefox again
> 
>     * install Tab mix again

Still get the error "can not be verified"

**Comment by fizzybiz** [comment]
OK, I am going to completely re-install firefox

**Comment by onemen** [comment]
> By this, do you mean delete all the files from the .\chrome\utils folder? If that's not what you mean, as I have never managed to get the extension to install, there is nothing to remove.

no.

profiles are in **....\AppData\Roaming** - don't remove files from here
profiles cache are in **...\AppData\Local**
locate your profile cache in `C:\Users\micro\AppData\Local\Mozilla\Firefox\Profiles\[new profile name]` and follow the instructions from above

**Comment by fizzybiz** [comment]
OK I have used a tool to completely obliterate all traces of FF from my PC, then re-installed, followed the instructions once again to the letter, and I'm still getting "can not be verified"

**Comment by fizzybiz** [comment]
I now have 2 profile folders in \Local and respective caches in \Roaming
The "Profile Folder" is using one with a suffix ".default-release"
The other profile has suffix ".default"

**Comment by fizzybiz** [comment]
> > By this, do you mean delete all the files from the .\chrome\utils folder? If that's not what you mean, as I have never managed to get the extension to install, there is nothing to remove.
> 
> no.
> 
> profiles are in **....\AppData\Roaming** - don't remove files from here profiles cache are in **...\AppData\Local** locate your profile cache in `C:\Users\micro\AppData\Local\Mozilla\Firefox\Profiles\[new profile name]` and follow the instructions from above

what I mean is - you said "remove Tab Mix extension" - I have never installed the extension, so there is nothing to remove except the files I've placed in the \chrome\utils folder

**Comment by fizzybiz** [comment]
Does anyone actually have a working TabMixPlus extension?  Just looking for some hope that it is actually possible to get it to install.  As I said above, I'm using FF version 116.0.3

**Comment by fizzybiz** [comment]
Have now tried deleting both those profiles, creating a new one, starting again...  same result

**Comment by onemen** [comment]
![firefox](https://github.com/onemen/TabMixPlus/assets/3650909/e39c4d4e-5bec-47fe-96d7-faba7fab24b2)

go to about:config

make sure you have installed the files to the right locations:
`Application Binary` is the path install the files from ` fx-folder.zip`
`Profile Folder` is the path to create `chrome` folder and install `utils` folder in it

**Comment by fizzybiz** [comment]
you mean about:support?

**Comment by onemen** [comment]
> you mean about:support?

Yes

**Comment by fizzybiz** [comment]
![image](https://github.com/onemen/TabMixPlus/assets/61228498/6e69b365-caeb-4105-b922-7a99c53b0844)
check
![image](https://github.com/onemen/TabMixPlus/assets/61228498/b9f03430-c93f-48bd-89fa-2c55bbd10c65)
check

**Comment by onemen** [comment]
I don't know why is does not work for you

**Comment by fizzybiz** [comment]
It's still saying it's not verified - when I look that up, it seems to be missing an ID?

**Comment by fizzybiz** [comment]
is my config.js file correct?

**Comment by onemen** [comment]
use this in config.js
```js
// skip 1st line
lockPref('xpinstall.signatures.required', false);
lockPref('extensions.install_origins.enabled', false);

try {
  const cmanifest = Cc['@mozilla.org/file/directory_service;1'].getService(Ci.nsIProperties).get('UChrm', Ci.nsIFile);
  cmanifest.append('utils');
  cmanifest.append('chrome.manifest');
  Components.manager.QueryInterface(Ci.nsIComponentRegistrar).autoRegister(cmanifest);

  const objRef = ChromeUtils.import('resource://gre/modules/addons/XPIDatabase.jsm');
  objRef.XPIDatabase.SIGNED_TYPES.delete("extension");

  Cu.import('chrome://userchromejs/content/BootstrapLoader.jsm');
} catch (ex) {};

try {
  Cu.import('chrome://userchromejs/content/userChrome.jsm');
} catch (ex) {};
```

**Comment by fizzybiz** [comment]
YES!!  Fixed!  TabMixPlus now running

Have sent a donation - many thanks for your time.

**Comment by onemen** [comment]
thank you
