### ISSUE TITLE
Have "other tabs should not resize until cursor leaves toolbar region" available for middle-click?

### ISSUE THREAD

**Issue by BattouSaeen** [onemen/TabMixPlus#241]
Hello,

An option, specifically under mouse gestures:

"When closing a tab, other tabs should not resize until cursor leaves toolbar region - applies only if tabs closed with the tab Close button. This option allows user to close more than one tab without moving the mouse."

was available for middle-click on pre-quantum Firefox.  I am not sure if it was available on pre-117 Firefox as well, as it was such a natural and intuitive behaviour that I only noticed it now when I was closing multiple tabs.  I know on XUL Firefox it was either part of FF or TMP for middle click as well.

So question is, it does work if I use the x button on each tab, but can it be extended to work on middle click as well?

Edit: this is a somewhat relevant setting, right? "extensions.tabmix.lockTabSizingOnClose" (which is set to default true).

Thanks!

**Comment by onemen** [comment]
NO

**Comment by onemen** [comment]
Download and test this new [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.19.20240211.2.xpi)

let me know if it solved this issue?

**Comment by BattouSaeen** [comment]
> Download and test this new [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.19.20240211.2.xpi)
> 
> let me know if it solved this issue?

Hey, thanks a lot! It works so far! :)

**Comment by BattouSaeen** [comment]
I'm unsure, but on Waterfox 6.6.4 I'm noticing this happens again. Sometimes it doesn't, so I can't really predict. Can anyone else confirm?

In my case -> many tabs, so resizing is not really visually relevant, it's more that the tabs are snapping to the end rather than waiting until the mouse moves. They're both related, I know, but just thought I'd explain.
