### ISSUE TITLE
Middle clicking new tab button doesn't place the new tab after the active tab.

### ISSUE THREAD

**Issue by Imold** [onemen/TabMixPlus#243]
After updating to Waterfox G6 middle clicking new tab button no longer places the new tab after active tab. Instead it just puts the new tab at the end, making middle clicking new tab button the same as left clicking. At first I thought it was a problem with Waterfox but I tried disabling TabMixPlus and the problem went away, so I know it has to be a problem with TabMixPlus.

**Comment by onemen** [comment]
I will look into it.

any messages in the browser console?

**Comment by Imold** [comment]
[browser console messages](https://github.com/onemen/TabMixPlus/files/13228358/console-export-2023-11-1_10-52-50.txt)
[Tab Mix preferences](https://github.com/onemen/TabMixPlus/files/13228362/TMPpref.txt)

**Comment by onemen** [comment]
make sure you are using latest [Tab Mix Plus](https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.17/tab_mix_plus-dev-build.xpi)

**Comment by Imold** [comment]
I'm already using v1.0.0-pre.17, and 'Open New Tab next to current one' isn't the issue. 

With tab mix plus disabled, 
left clicking the new tab button opens a new tab at the end of the list, 
and middle clicking the new tab button opens a new tab next to current one.

With tab mix plus enabled, clicking the new tab button with ether button opens a new tab at the end of the list.

The only thing enabling 'Open New Tab next to current one' does is to make clicking the new tab button with ether button open a new tab next to current one, middle click is still treated the same as left click.

**Comment by onemen** [comment]
I need to update Tab Mix code and apply changes from [bug 1418462](https://bugzilla.mozilla.org/show_bug.cgi?id=1418462)

**Comment by onemen** [comment]
Download and install this new [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.18.20240127.1.xpi)

**Comment by Imold** [comment]
It works.
