### ISSUE TITLE
current tab become unread after refresh

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#245]
@onemen After refresh the current tab, it's state become unread and will show the customize style of unread tabs right away after select another tab despite it has been reading all along.

Fx119 pre17 
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/13261098/TMPpref.txt)

**Comment by 117649** [comment]
To reproduce:
Refresh the current tab by any means and wait for it to complete.
Select and switch to another tab.
The previous 'current tab' display the customize style of unread tabs immediately indicating it's state is ```unread``` after refresh.

**Comment by onemen** [comment]
some leftover from bug [1849904](https://bugzilla.mozilla.org/show_bug.cgi?id=1849904)

download and try this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.18.20231106.1.xpi)

**Comment by tomchiverton** [comment]
Looks to have fixed it for me

**Comment by 117649** [comment]
> Looks to have fixed it for me

Same here.

**Comment by 117649** [comment]
@onemen Don't know why but for one instance the fix is ineffective and problem appears again but its gone after a restart.
So I'm just leave a note here for record.
