### ISSUE TITLE
Several minor issues with the latest DEV build

### ISSUE THREAD

**Issue by AuRiMaS666** [onemen/TabMixPlus#246]
So, yesterday I've started out with a fresh Firefox profile and jumped straight to the latest dev version **1.0.0-pre.18.20231106.1**, as it seemed most complete with the fixes for most recent problems other users were reporting here. And these are the issues I've noticed so far:

1. Move to New Window in the Tab Context Menu is missing, compared to vanilla Firefox. Also, the default keyboard shortcut for this function is set to CTRL+SHIFT+V and doesn't work, as it's used for pasting plain text these days.
2. When multiple tabs are selected, Bookmark Tabs in the Tab Context Menu still shows while being unchecked in the options. For a single tab it doesn't appear.
3. When new tabs are set to load as Blank Tabs in TMP options and you move them between windows, there's this more noticeable "flash of white" during the transition and often the page gets stuck in "white mode" until you left click inside the window. It doesn't seem to make a difference, whether the Firefox Home settings are set to Firefox Home or Blank Page.

![firefox default](https://github.com/onemen/TabMixPlus/assets/59185222/67949dc3-c3c5-47f0-aa68-b07d87358a51)
![TMP move to new window](https://github.com/onemen/TabMixPlus/assets/59185222/5ca984b4-500d-4234-9e53-884c4d496be8)
![bookmark tabs](https://github.com/onemen/TabMixPlus/assets/59185222/aa2e498d-93d0-4b50-adb5-a4595ee84b33)

https://github.com/onemen/TabMixPlus/assets/59185222/3393a330-0130-4a68-be72-f07e622ea00c

**Comment by onemen** [comment]
@AuRiMaS666 

Thank you for the report.

1. Can you provide your Tab Mix Plus preferences to reproduce these issues?
2. What is your Firefox version and operating system?
3. how keyboard shortcut CTRL+SHIFT+V work for you on Firefox without Tab Mix Plus
4. any messages in the browser console?

**Comment by AuRiMaS666** [comment]
Sorry, should have included those details in the first place.

1. [TMPpref.txt](https://github.com/onemen/TabMixPlus/files/13363940/TMPpref.txt)

2. Win11 22H2 22621.2428 + FF 119.0.1 with Lepton and Betterfox (latest versions).

3. It works the same way with TMP on and off, pasting plain text when a text field is focused, otherwise it doesn't do anything.

4. When the New Tab Page is selected in TMP options, Browser Console gives this output:

![new tab page](https://github.com/onemen/TabMixPlus/assets/59185222/763b1122-6d07-463f-8d5b-053778a81480)

When Blank Page is selected in TMP options, Browser Console gives this output:

![blank tab](https://github.com/onemen/TabMixPlus/assets/59185222/b762d52a-2da0-4875-a3ef-3598b1e4618b)

This is after one repetition of dragging and dropping a tab outside from a main window and creating a fresh window. Then when you take this new window and drop it back into the main window, no additional output from the Browser Console is given.

With New Tab Page there is no issue with the window turning white.

With Blank Page the page turns white almost every single time after dropping it back in, until you click on it.

When using the context menus, I don't see anything appearing the Browser Console.

I know this sounds a little pedantic and just using New Tab Page option which works with no issues is the way to go anyway. Just want the extension to be as polished as possible.

Also, I have noticed, that when using Preferences --> Restore Defaults, TMP Session Restore feature got turned on. Not sure if this is intentional, but as the disclaimer says, it isn't meant to be used, so I thought I mention that as well.

**Comment by onemen** [comment]
> 1. Move to New Window in the Tab Context Menu is missing, compared to vanilla Firefox. Also, the default keyboard shortcut for this function is set to CTRL+SHIFT+V and doesn't work, as it's used for pasting plain text these days.

- Move to New Window in the Tab Context Menu is missing - set in `about:config` `extensions.tabmix.detachTabMenu`  to **true**
- shortcut CTRL+SHIFT+V doesn't work: in Tab Mix Plus [Options ](https://tabmixplus.org/support/viewtopic.php?t=3&p=menu-shortcuts) change the shortcut.

> 2. When multiple tabs are selected, Bookmark Tabs in the Tab Context Menu still shows while being unchecked in the options. For a single tab it doesn't appear.

- I am not going to add another preferences to hide this menu item when multiple tabs where selected

**Comment by AuRiMaS666** [comment]
Thanks a lot, that did the trick!

I'm fully aware how to change the shortcuts if needed and that unwanted menu item I should be able to sort out with [simpleMenuWizard](https://github.com/stonecrusher/simpleMenuWizard).

**Comment by onemen** [comment]
version [1.0.0-pre.18](https://github.com/onemen/TabMixPlus/releases/tag/v1.0.0-pre.18) is out
