### ISSUE TITLE
All Tabs are blank after restart, address bar is empty, 

### ISSUE THREAD

**Issue by Shahius** [onemen/TabMixPlus#247]
2 days ago after update all tabs are blank, empty, no address in address bar. 
![tabmix](https://github.com/onemen/TabMixPlus/assets/107578713/2b666d1e-328a-4125-b73c-2581f48c3c58)
[console-export-2023-11-15_22-51-27.txt](https://github.com/onemen/TabMixPlus/files/13372061/console-export-2023-11-15_22-51-27.txt)

**Comment by onemen** [comment]
Download and install this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.18.20231116.1.xpi)

**Comment by Shahius** [comment]
So far so good! Thank you!
