### ISSUE TITLE
When TMP is enabled "restore previous tabs" is unreliable on 121

### ISSUE THREAD

**Issue by zakius** [onemen/TabMixPlus#249]
Tabs either are empty with no way to restore or keep the title and address but you have to refresh them manually to make them load. I am unable to verify whether it's an issue within TMP or my injector (I'm using xiaoxiaoflood/firefox-scripts with fixes found in issues and config.js replaced with the one linked in readme, the issue persists after that change)

**Comment by onemen** [comment]
Download and install this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.18.20231123.1.xpi)

**Comment by zakius** [comment]
thank you, after a few quick tests it seems to work properly!

**Comment by blockberd** [comment]
> thank you, after a few quick tests it seems to work properly!

Can confirm. Same here.

**Comment by onemen** [comment]
Thank you all for using **Tab Mix Plus**

**Comment by pyrates999** [comment]
I am also effected by this build on firefox 121.  

![image](https://github.com/onemen/TabMixPlus/assets/106135298/cb10c801-75f6-4dfe-957d-d8382f8aae4e)

**Comment by Mrsash2020** [comment]
The search bar issue fixed from other thread 1.0.0-pre.18.20231207.1 install fixes it. Then installing it from this thread breaks it but does not fix the restore previous session. Seems broken in several way. Sorry not complaining, just reporting.

**Comment by ivan11235** [comment]
I can confirm: the build above is not good. It didnot fix the issue even with CLEAR STARTUP CACHE from about:support.
The build 1.0.0-pre.18.20231207.1.xpi from another thread is better and fix the issue.

Fortunally I have a backup with tabs session in file sessionstore.jsonlz4.
1) disable TabMix addon
2) close Firefox
3) replace sessionstore.jsonlz4 in the profile folder
4) start Firefox -> all tabs are recovered
5) install new Tabmix and enable it
6) tabs seem to be ok
7) open about:support and CLEAR STARTUP CACHE.
Now it seems to be ok.

**Comment by pyrates999** [comment]
What thread is 1.0.0-pre.18.20231207.1.xpi on?

**Comment by ivan11235** [comment]
> What thread is 1.0.0-pre.18.20231207.1.xpi on?

https://github.com/onemen/TabMixPlus/issues/250

**Comment by Mrsash2020** [comment]
Ok open about:support and CLEAR STARTUP CACHE worked. Yay.

**Comment by pyrates999** [comment]
That fixed the bug where a tab wouldn't load.  But this bug is catastrophic because once all the other tabs are blank, if you close firefox, it will only load the tab that had loaded.  All the other tabs that were blank, no longer show up.  And I have to restore from the session store for firefox 119 in order to restore everything the way it was.

If the version from https://github.com/onemen/TabMixPlus/issues/250 fixes this, we need a new release and limit the last release to firefox 119.  And this release should require firefox 121 at the minimum.

I will comment here if this happens again.

**Comment by ivan11235** [comment]
@onemen please help.
Manically I have 40+ tabs, even I use 3-5 of them. It is like a todo-list.
This is why I so want to rely on Tab list and TabMix.
I had installed version 1.0.0-pre.18.20231207.1.xpi.

**Comment by ScavengerGraphics** [comment]
Wanted to note I was having BOTH the Search Bar not working AND this Blank Tab/not restoring problem.
I installed the beta from [here](https://github.com/onemen/TabMixPlus/issues/250#issuecomment-1845494233) , cleared startup cache, and things are working liek they should! YAY!!!! I'm happy on Christmas!

**Comment by onemen** [comment]
version [1.0.0-pre.18](https://github.com/onemen/TabMixPlus/releases/tag/v1.0.0-pre.18) is out
