### ISSUE TITLE
Tab not retain auto reload setting after been restored

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#25]
Tittle. May relate to session manager.

**Comment by 117649** [comment]
https://github.com/onemen/TabMixPlus/blob/59c16d1f6c4b134a2e8505bb594e454e876cab1c/addon/chrome/content/tabmix.js#L55-L56
https://github.com/onemen/TabMixPlus/blob/59c16d1f6c4b134a2e8505bb594e454e876cab1c/addon/chrome/content/tabmix.js#L96
Ok, This is because the session manager is disabled thus `TMP_SessionStore.persistTabAttribute();` won't get called.

**Comment by onemen** [comment]
thank you @117649 for the info

fixed by https://github.com/onemen/TabMixPlus/commit/06b5130a94be1e2d8a06cd4df94ab8e35062c753
