### ISSUE TITLE
search bar not working

### ISSUE THREAD

**Issue by okimurin** [onemen/TabMixPlus#250]
I can no longer search from the search bar.
There is no response when I press the Enter key or the right arrow.

Win10home64bit
Firefox Dev 121.0b8
1.0.0-pre.18.20231123.1

**Comment by onemen** [comment]
Download and install this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.18.20231123.1.xpi)

**Comment by okimurin** [comment]
After installing the test build, the search bar is now working properly.
thank you.

**Comment by Wontell** [comment]
Can confirm,  search bar not working on 121 release

**Comment by onemen** [comment]
@Wontell , did you install the test buildci have mentioned above?

**Comment by Wontell** [comment]
> @Wontell , did you install the test buildci have mentioned above?

Yep it works

**Comment by avesJM** [comment]
After installing test build from above don't forget to CLEAR STARTUP CACHE from about:support. It worked for me. By the way this test build solved my issue with no opening tabs after starting new session too.

**Comment by ay134** [comment]
Got installed the new test build, "restore previous tabs" back to working normally. However the search bar still no respsone and shows nothing on screen. Win 11+FF 121.0.1

**Comment by onemen** [comment]
try
Open about:support and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup.

**Comment by onemen** [comment]
Any messages in Browser console?

**Comment by ay134** [comment]
error message relates to tmp in browser console, not sure if it helps?

![Snipaste_2024-01-16_21-01-09](https://github.com/onemen/TabMixPlus/assets/156697690/bd79fa20-f968-4e19-a205-e4a2c07a824e)

**Comment by onemen** [comment]
@ay134 , the build from December 7 fixed this issue.

make sure you download and install this NEW [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.18.20231207.1.xpi) this version.

verify the version in `about:addons`

you can also try to `Clear startup cache`.
Open about:support and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup

**Comment by ay134** [comment]
just checked the test build in about : addons and it was the 20231123 version installed previously, updated to the 1207 and confirm everything works perfectly, appreciated great help
