### ISSUE TITLE
New error Msgs on 122

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#251]
![image](https://github.com/onemen/TabMixPlus/assets/8281345/ddfcae2f-fd21-4626-bb2a-1a70dec70a94)

Other 2 that maybe related
![image](https://github.com/onemen/TabMixPlus/assets/8281345/74ae7d09-ab85-4227-ac4c-cf97c6a62a6e)

![image](https://github.com/onemen/TabMixPlus/assets/8281345/7afd1a3d-80a5-49fa-8f44-c72afcc7f1ac)
![image](https://github.com/onemen/TabMixPlus/assets/8281345/63ee6b9e-a1ca-4d40-863b-45d3f5778cae)

**Comment by onemen** [comment]
I don't see this messages, are you sure you are using the latest test build?
https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.18.20231207.1.xpi

**Comment by 117649** [comment]
I see it seems because I have other script that edited ```doSearch``` then bind it back to ```searchbar``` with ```bind()```.
And the result of ```bind()``` isn't a normal function but a ```BoundFunctionObject ``` and can't be edited like a function anymore.
What should I do to keep it still a normal function after bind?

**Comment by onemen** [comment]
Can you post the scripts you are using?

**Comment by 117649** [comment]
> Can you post the scripts you are using?

https://github.com/117649/CustomJSforFx/blob/2bdd975a9dd86a6d2d4eb5f9380adf5161ac1242/scripts/alternative_searchbar.uc.js#L433

**Comment by onemen** [comment]
I think that you can use `Cu.getGlobalForObject(searchbar)["eval"]` in  line 422 then you can remove `.bind(searchbar);` on line 433.

**Comment by 117649** [comment]
Thanks.
The script just been updated with a completely workaround of the issue by the author. (https://github.com/Aris-t2/CustomJSforFx/pull/105#issuecomment-1870497137)
But this is still valuable knowledge.
