### ISSUE TITLE
TMP not working in Fx 121.0

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#252]
Greetings! I am terribly sorry to bother you with this, but I am stumped. I just reinstalled Win 10 and therefore Firefox. I also installed the various userChromeJS tools. But these are apparently no longer being maintained:

On page https://github.com/xiaoxiaoflood/firefox-scripts/discussions/295, I read the following:

"This repo has been actually set aside since 115 time. Ever since there is only scattered fixes made by individual user. You have to go through issues area to find the newest working fix people have shared. Sadly until somebody took over the responsibility of maintenance it will keep this way."

From this, I take it that userChromeJS is no longer being maintained; I certainly haven't been able to get any of it to work for a while. Does this mean TMP is dead in the water? I ask, because when I try to install the v. 17 xpi file, Firefox reports "This add-on cannot be installed because it appears to be corrupt."

I would be grateful for any help someone is willing to share. Thank you, and Happy New Year to all!

**Comment by pyrates999** [comment]
See here for updated files that work in firefox 121: https://github.com/onemen/TabMixPlus/discussions/237

Not sure why the main page hasn't been updated with this yet.

**Comment by VLM-TechEd** [comment]
THANK YOU!!!!! My tabs were all wiped out in the restart, but at least now everything works. I feel so very grateful!

 

Happy New Year to all!

**Comment by onemen** [comment]
Follow [this](https://github.com/onemen/TabMixPlus/discussions/237#discussioncomment-6915374) instruction to update **Firefox scripts**.

Download and install this NEW [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.18.20231207.1.xpi)

Happy New Year to all!
Thank you all for using **Tab MIx Plus**

**Comment by VLM-TechEd** [comment]
Thank you, and Happy New Year indeed!

**Comment by poire-z** [comment]
Hijacking this issue to mention another issue after ff120 to 121 update (also happening with the above 1.0.0-pre.18.20231207.1.xpi build):
The Firefox "window" title is no longer updated when I switch tabs (with ctrl-tab or by clicking on a tab in the tabbar), and stays fixed:
![image](https://github.com/onemen/TabMixPlus/assets/24273478/76b5076b-78c5-425f-9549-911f945b090f)
and this is logged in the browser console when I switch tabs:
![image](https://github.com/onemen/TabMixPlus/assets/24273478/9c370120-5174-4a33-8325-c3b4ee440214)

I also notice when Ctrl-Tab + release + Ctrl-Tab that I often don't get back to my initial tab.
And that sometimes, a first Ctrl-Tab don't switch tab at all.
These are my settings:
![image](https://github.com/onemen/TabMixPlus/assets/24273478/ce600e4d-eef2-4a7a-abcd-da7c80032fc8)

(I do monkey-patch TMP with firefox-scripts userchromejs - and tweak its css with styloaix - but the above issue keeps happening with my stuff disabled. If someone can confirm they don't experience the above issues, I'll look again more on my side.)

Thank you for TMP (and for the time and headache it must take/cause to keep it updated with Firefox changes... :/)

**Comment by onemen** [comment]
@poire-z.

Tabmix 1.0.0-pre.18.20231207.1.xpi  work without a problem on Firefox 121.

it is probably a profile cache issue
try these steps 
* Remove Tab mix extension.
* go to about:config and set extensions.experiments.enabled to true
* Open about:support and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup.
* Close Firefox and then start Firefox again (don't use restart).
* Install Tab mix again.

**Comment by poire-z** [comment]
Thanks !

This single step was enough to solve the window title issue (and probably the other Ctrl-Tab issue too, time will tell):

> Open about:support and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup.

I had read about it when starting using firefox-scripts, but I never had the need to use it, so I forgot about it :/
May be this will also solve all the minor annoyances I've been having :)

(I'll keep your other steps in mind next time I have issues. I still have `extensions.experiments.enabled = false`, I have never read about it.)

Thank you again.

**Comment by VLM-TechEd** [comment]
Onemen, 

 

I am having many problems, too. But I am using pre.17. Where is pre-18?

 

Thank you.

**Comment by pyrates999** [comment]
Use this build for firefox 121 and later: https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.18.20231207.1.xpi

It is the last build uploaded before a new pre-release.

**Comment by VLM-TechEd** [comment]
Works so far, with one small exception: Tabs don’t display multiple spaces (a recurring problem). Otherwise, looks good so far! Thank you.

**Comment by pyrates999** [comment]
Please create a new issue then regarding that.

**Comment by VLM-TechEd** [comment]
It’s actually a recurrent issue, returning.

I will do so. 😊

**Comment by onemen** [comment]
I am planing to publish version 1.0.0-pre.18 later this month.

its still need more work.

**Comment by pyrates999** [comment]
ok, thank you :)

**Comment by Zipfer** [comment]
If you get a white tab header when switching to multiple tab rows. Change theme to Dark instead of Auto system theme. I thought it was some JS issues but everything turned out to be much simpler.

**Comment by L0garithmic** [comment]
Thank you for this! Worked again!

**Comment by XeonG** [comment]
I am using https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.18.20240120.1.xpi on 124.0a1 (2024-01-24) (64-bit)  and opening a new tab.. is not opening directly to the right of the current open tab... its going right to the end of the tab bar.. is this broken..  why are mozilal have to be retards.. like stuff like this is built into vivaldi now.. its a shame gotta go through all this trouble just to get semi functional firefox browser.

**Comment by onemen** [comment]
@XeonG , 
please post a file with your Tab Mix Plus preferences

**Comment by XeonG** [comment]
yeah it was the setting 'Open other abs next to current one... that was previously turned on, but it seems in newer one it needs to be off so all new tabs open next to the current open one.. strange but its working with that off now.

![firefox_SDHTRFElge](https://github.com/onemen/TabMixPlus/assets/1556183/a6ffccde-9006-4b60-8611-56caa8d8455f)

other thing is that it seems my theme styles have changed a bit.. old version tab colors looked less washed out.. in the new one the same firefox theme/style tab colors.. and its more white washed in the lower the opacity.. 
![firefox_awvJtHqUno](https://github.com/onemen/TabMixPlus/assets/1556183/7e2744aa-859a-4432-8a8a-30635ee48606)
![firefox_IQqjnn182v](https://github.com/onemen/TabMixPlus/assets/1556183/eaa39464-1439-49d1-a531-e3929f2b0f77)
![firefox_yXkHEijdzv](https://github.com/onemen/TabMixPlus/assets/1556183/7927e193-76f0-439b-a04d-219ae4ca81f3)

**Comment by onemen** [comment]
I can confirm that `Open New Tab next to current one` does not work, i will look into it...

**Comment by onemen** [comment]
@XeonG,

Download and install this new [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.18.20240127.1.xpi)

**Comment by XeonG** [comment]
what changed in that?

**Comment by onemen** [comment]
> what changed in that?

 Open New Tab next to curren

**Comment by XeonG** [comment]
yeah for some reason firefox didn't work after restart with that addon, reverted back to the previous version and it worked again

**Comment by onemen** [comment]
version [1.0.0-pre.18](https://github.com/onemen/TabMixPlus/releases/tag/v1.0.0-pre.18) is out

**Comment by malone19** [comment]
Hi Guys, TPM did just auto update to 1.0.0-pre.18. After this I updated FF from 114.00 zu current version 122.0. After restart TMP is disabled. Any ideas?

**Comment by pyrates999** [comment]
You'll need to setup firefox again to allow this type of extension: https://github.com/onemen/TabMixPlus/discussions/237

**Comment by malone19** [comment]
Works now, thanks.

**Comment by pyrates999** [comment]
welcome

**Comment by Kalinette** [comment]
Hello.

Unable to install TabMixPlus under freshly installed Firefox 122 or 117 (test). I follow the procedures to the letter but I always get the answer:
This add-on could not be installed because it appears to be corrupt.

I've been on the problem for two days with no solutions.

**Comment by onemen** [comment]
@Kalinette,
Follow the instructions from here: [installation](https://github.com/onemen/TabMixPlus?tab=readme-ov-file#installation), [troubleshooting](https://github.com/onemen/TabMixPlus?tab=readme-ov-file#troubleshooting)

**Comment by L0garithmic** [comment]
> Hello.
> 
> Unable to install TabMixPlus under freshly installed Firefox 122 or 117 (test). I follow the procedures to the letter but I always get the answer: This add-on could not be installed because it appears to be corrupt.
> 
> I've been on the problem for two days with no solutions.

Probably forgot to create the "chrome" folder, which is what I did. Instructions could be a little clearer regarding that.

**Comment by onemen** [comment]
>1.3. Create chrome folder in your Profile Folder (if one does not exist) and extract [utils](https://github.com/onemen/TabMixPlus/files/14075742/utils_extensions_and_scripts.zip) folder in it.

How to make this any clearer?

**Comment by Kalinette** [comment]
I uninstalled Firefox and deleted all files related to it. After reinstallation, Tabmixplus is installed without any problem by following the same procedure. I had already installed it on another PC.
So I will never know what happened.
Thanks for the answers and thank you onemen for your excellent work.
Gold medal for this extension that I have known since its beginnings.

**Comment by VLM-TechEd** [comment]
FWIW, I did the same when Fx 117 came out (I think it was 117). After that, I’ve had no problems with TMP. So I guess that sometimes, the app stores so much garbage that the only way to get things done is to start over.

**Comment by XeonG** [comment]
> > 1.3. Create chrome folder in your Profile Folder (if one does not exist) and extract [utils](https://github.com/onemen/TabMixPlus/files/14075742/utils_extensions_and_scripts.zip) folder in it.
> 
> How to make this any clearer?

By showing what the folder structure is meant to look like when working, instead of leaving it to intepration of what extracting utils for in it means exactly... ie a screenshot does wonders to make it obvious
![explorer_0WlQYJnNVq](https://github.com/onemen/TabMixPlus/assets/1556183/5148efad-ce0c-40a5-87e7-463048594586)

**Comment by pyrates999** [comment]
I would change it to this:

1.3a. Create chrome folder in your Profile Folder (if one does not exist) and go into it
1.3b. In the chrome folder, extract [utils](https://github.com/onemen/TabMixPlus/files/14075742/utils_extensions_and_scripts.zip) folder in it.

**Comment by L0garithmic** [comment]
> > 1.3. Create chrome folder in your Profile Folder (if one does not exist) and extract [utils](https://github.com/onemen/TabMixPlus/files/14075742/utils_extensions_and_scripts.zip) folder in it.
> 
> How to make this any clearer?

Yeah, like [pyrates999](https://github.com/pyrates999) said, I was bad and skimmed through the settings twice as I have done this multiple times, new system install and missed the chrome part twice. I would say split it into 2 parts.

1.3a. Create chrome folder in your Profile Folder (if one does not exist)
1.3b. Eextract [utils](https://github.com/onemen/TabMixPlus/files/14075742/utils_extensions_and_scripts.zip) folder in it.

Just visually enough to realize, it is a step and to not blow by

**Comment by onemen** [comment]
I have just updated the [README](https://github.com/onemen/TabMixPlus?tab=readme-ov-file#installation)

let me know if you have any suggestion for improve it

**Comment by pyrates999** [comment]
That looks great :)

**Comment by Kalinette** [comment]
Good job, thank you.

**Comment by VLM-TechEd** [comment]
I second that sentiment!

**Comment by Kalinette** [comment]
Hi onemen.

Maybe add in the installation procedure:

Check that:  “extensions.experiments.enabled”  is enabled in about:config.

THANKS !

**Comment by 117649** [comment]
> Hi onemen.
> 
> Maybe add in the installation procedure:
> 
> Check that: “extensions.experiments.enabled” is enabled in about:config.
> 
> THANKS !

That only needed for dev ed/nightly with bootloader.xpi

**Comment by Kalinette** [comment]
Well sorry onemen.
It's been 2 days since a friend tried to install Tmp without result.
He contacted me and I told him to check "extensions.experiments.enabled" under Firefox 122.01 and this setting was False as for me. Tmp therefore refuses to install with message: Archive corrupted.

**Comment by onemen** [comment]
I just tested it again on my Windows 11 and i can install firefox-scripts and Tab Mix Plus on new profile without setting `extensions.experiments.enabled` to true.

If any of you see this message: 
![appears_corrupt](https://github.com/onemen/TabMixPlus/assets/3650909/307bea8a-6c4c-455a-83f6-0587fcacaf91)

### Reinstall scripts
You need to reinstall firefox-scripts again. this message only appeared if the script did not copied to the right place.
 Follow the [instructions](https://github.com/onemen/TabMixPlus#installation) step-by-step

**Comment by Kalinette** [comment]
In any case here in France, if we do not switch "extensions.experiments.enabled" to True, Tmp is not installed.
Scipts files are placed correctly in the right places, 100% guaranteed. Several people have noticed the same thing.

Excerpt from forum discussion:

Nocturne25

Posted on 02/18/2024 at 10:46:32 profilanswer
 

Oh that’s curious. I did the procedure again this morning to be sure and it worked fine.
 
Have you checked that: “extensions.experiments.enabled” is “True” in about:config?


steph_d

Posted on 02/18/2024 at 11:32:35 profilanswer
 

Hello.
That was it, it works now under win10 :)
THANKS


Nothing serious, I'm just reporting the observation.

**Comment by onemen** [comment]
i have added it to the [troubleshooting](https://github.com/onemen/TabMixPlus#troubleshooting) section

**Comment by tomchiverton** [comment]
This setting was toggled back to the (non working, default) setting in the last few days, most probally by the install of FireFox 123.0.1 (Ubuntu, via https://packages.mozilla.org/apt
The auto install of latest TMP 1.19.1 had no effect.
As soon as I used about:config to toggle this setting, then the multi row tabs I'm used to came back.

**Comment by onemen** [comment]
I am not changing `extensions.experiments.enabled` in Tab Mix Plus or in the installation scripts
if the preference was reset by Ubuntu or Firefox you will have to set it again
