### ISSUE TITLE
as of Firefox v120+ , the TMP is not changing/updating the Window Title Bar

### ISSUE THREAD

**Issue by dv8472** [onemen/TabMixPlus#254]
Hello,
OS: Arch Linux (up-to-date)
Window manager: OpenBox
Firefox (FF): v121
TMP: v1.0.0-pre.17

Ever since FF v120+ I've been observing following behaviour:
1. after browser start/restart, usually the last opened tab is opened and the page's title is shown in the Window Title Bar
![image](https://github.com/onemen/TabMixPlus/assets/22549066/a0719682-1e9e-46a0-b6a1-4a1094ab3710)
2. however, when I switch between the tabs, the Window Title Bar's content doesn't change/update anymore, it's always showing the content from the tab opened at start/restart
![image](https://github.com/onemen/TabMixPlus/assets/22549066/b2dccfa8-731b-4606-b70c-8b31340dee68)
and another example:
![image](https://github.com/onemen/TabMixPlus/assets/22549066/106c7d43-abef-4536-815e-f84457d350a7)

Have also disabled all another add-ons, until I've isolated it.
After disabling the TMP in the FF, it works as expected, Window Title Bar is updated with current content at every tab.
My TMP config:
attachment: [20240113-1651-FF-TMPpref.txt](https://github.com/onemen/TabMixPlus/files/13928803/20240113-1651-FF-TMPpref.txt)
pastebin: https://pastebin.com/FThUJh6k

**Comment by onemen** [comment]
Download and install this NEW [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.18.20231207.1.xpi)

**Comment by dv8472** [comment]
That was fast.
Thank you very much, it works!
