### ISSUE TITLE
Closing a tab does not focus on last selected tab

### ISSUE THREAD

**Issue by mekd66** [onemen/TabMixPlus#255]
I have chosen the option that after closing current tab, FF should go and focus on the last selected tab.
This is useful when you open a link in a new tab and then you close the new tab and want to go back to the page/tab from which you opened the link.
Since FF version 121 (I have 121.0.1) this is not working and when closing a tab FF goes to the last tab.

**Comment by onemen** [comment]
Download and install this NEW [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.18.20231207.1.xpi)

**Comment by mekd66** [comment]
Works like a charm!
Thank you.
