### ISSUE TITLE
TMP icons not displayed anywhere

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#256]
HI again! I have TMP working perfectly in Fx 121.x, with one exception: I cannot find the icons (closed window list, etc.). Where are they these days?

**Comment by onemen** [comment]
![image](https://github.com/onemen/TabMixPlus/assets/3650909/52fd6cea-960e-4151-8d56-12d6e06af4d0)

**Comment by VLM-TechEd** [comment]
(Sheepishly) Thank you. For some reason, my eyes just didn’t see them.
