### ISSUE TITLE
Input focus changes from search bar to location bar 1 second after browser launch

### ISSUE THREAD

**Issue by DmitriyMur** [onemen/TabMixPlus#257]
I have separate search bar enabled in Firefox settings. After I launch Firefox, usually I click on search bar and begin typing some search request into it immediately after browser window appears. If Tab Mix Plus extension is enabled, it changes keyboard input focus 1-2 seconds after browser launch back to location bar (which was in focus by default), in the middle of me typing search request, so the result always is: first half of my request is in search bar, second half in location bar, I hit enter and nothing useful comes out of this.

I have tab close buttons disabled and a changed setting of tab width in Tab Mix Plus settings, so I visually observe that input focus changes the moment that tab close button disappears and tab width increases, so this undesirable behavior happens at the very moment Tab Mix Plus applies its changes to browser interface.

This problem does not appear if Tab Mix Plus is disabled, focus stays on search bar in that case.

**Comment by pyrates999** [comment]
try installing this: https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.18.20231207.1.xpi

**Comment by DmitriyMur** [comment]
Installed, unfortunately the bug persists.

**Comment by onemen** [comment]
can you post a file with your Tab Mix preferences ?

**Comment by Ramel** [comment]
Same in Firefox 121.0.1 (64 bits)

**Comment by onemen** [comment]
Download and install this [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.18.20240120.1.xpi)

**Comment by DmitriyMur** [comment]
Test build fixed it, thank you!
Indispensable extension, it is the only reason I'm still on Firefox.

**Comment by srjjgm** [comment]
> Test build fixed it, thank you! Indispensable extension, it is the only reason I'm still on Firefox.

I still use Firefox because of Tab Mix Plus and StyloaiX, wich is a fork of the old Stylish and allows me to modify the Firefox interface.
