### ISSUE TITLE
With "fission.webContentIsolationStrategy" set to 2 auto reload will make the tab of localhost blank when trriggered 

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#258]
@onemen The url of the tab is something like ```192.168.10.1:9990```
This is quite wired.
Happened to me on 123.0b2 and 122.0
All it takes is set "fission.webContentIsolationStrategy" to 2 then restart with cache cleared.
TMP prefs does not seems to have a part in this.

**Comment by onemen** [comment]
Is it working for you when you use `Browser Reload Skip Cache` - with `Ctrl+Shift+R` ?

**Comment by 117649** [comment]
> Is it working for you when you use `Browser Reload Skip Cache` - with `Ctrl+Shift+R` ?

Doing so result in a proper reload of the tab just like any other methods to reload a tab.
But when auto load is fired the tab turn into blank(html is empty) immediately and no more actions.

**Comment by onemen** [comment]
Download and install this new [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.18.20240127.1.xpi)

**Comment by 117649** [comment]
> Download and install this new [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.18.20240127.1.xpi)

So far so good.
Good for push to the repo I think?
