### ISSUE TITLE
Mouse clicking not working.

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#26]
Error log for `Close Tab` and `Open anew tab` not seeing any others so far.
```
TypeError: can't access property "audioMuted", browser is undefined
TabState.jsm:108:9
    _collectBaseTabData resource:///modules/sessionstore/TabState.jsm:108
    collect resource:///modules/sessionstore/TabState.jsm:67
    collect resource:///modules/sessionstore/TabState.jsm:34
    ssi_onTabClose resource:///modules/sessionstore/SessionStore.jsm:2667
    ssi_handleEvent resource:///modules/sessionstore/SessionStore.jsm:1616
    _beginRemoveTab chrome://tabmixplus/content/changecode.js line 218 > eval:155
    removeTab chrome://browser/content/tabbrowser.js:3386
    removeTab chrome://tabmixplus/content/minit/tablib.js:255
    TMP_doCommand chrome://tabmixplus/content/click/click.js:156
    TMP_clickAction chrome://tabmixplus/content/click/click.js:137
    TMP_onTabBarDblClick chrome://tabmixplus/content/click/click.js:129
    handleEvent chrome://tabmixplus/content/tab/tab.js:748
TypeError: can't access property "isRemoteBrowser", e.target.linkedBrowser is undefined
Browsers.jsm:170:8
    handleEvent chrome://tabgroups-resource/content/modules/utils/Browsers.jsm:170
    _beginRemoveTab chrome://tabmixplus/content/changecode.js line 218 > eval:155
    removeTab chrome://browser/content/tabbrowser.js:3386
    removeTab chrome://tabmixplus/content/minit/tablib.js:255
    TMP_doCommand chrome://tabmixplus/content/click/click.js:156
    TMP_clickAction chrome://tabmixplus/content/click/click.js:137
    TMP_onTabBarDblClick chrome://tabmixplus/content/click/click.js:129
    handleEvent chrome://tabmixplus/content/tab/tab.js:748
TypeError: can't access property "ownerGlobal", aBrowser is undefined
PrivateBrowsingUtils.jsm:40:21
    isBrowserPrivate resource://gre/modules/PrivateBrowsingUtils.jsm:40
    isPrivateTab chrome://browser/content/parent/ext-browser.js:44
    emitRemoved chrome://browser/content/parent/ext-browser.js:746
    handleEvent chrome://browser/content/parent/ext-browser.js:578
    _beginRemoveTab chrome://tabmixplus/content/changecode.js line 218 > eval:155
    removeTab chrome://browser/content/tabbrowser.js:3386
    removeTab chrome://tabmixplus/content/minit/tablib.js:255
    TMP_doCommand chrome://tabmixplus/content/click/click.js:156
    TMP_clickAction chrome://tabmixplus/content/click/click.js:137
    TMP_onTabBarDblClick chrome://tabmixplus/content/click/click.js:129
    handleEvent chrome://tabmixplus/content/tab/tab.js:748
Uncaught TypeError: can't access property "registeredOpenURI", browser is undefined
    _beginRemoveTab chrome://tabmixplus/content/changecode.js line 218 > eval:188
    removeTab chrome://browser/content/tabbrowser.js:3386
    removeTab chrome://tabmixplus/content/minit/tablib.js:255
    TMP_doCommand chrome://tabmixplus/content/click/click.js:156
    TMP_clickAction chrome://tabmixplus/content/click/click.js:137
    TMP_onTabBarDblClick chrome://tabmixplus/content/click/click.js:129
    handleEvent chrome://tabmixplus/content/tab/tab.js:748
```

**Comment by onemen** [comment]
Can you post you Tab mix preference ?

**Comment by 117649** [comment]
![image](https://user-images.githubusercontent.com/8281345/106243063-a249ab80-6243-11eb-93aa-30580e353a3b.png)

**Comment by onemen** [comment]
there is an issue with ```aEvent.target.localName``` it is not 'tabs'

try to change  these line in onTabClick and onTabBarDblClick
```diff
-    var clickOutTabs = aEvent.target.localName == "tabs";
+    const clickOutTabs = aEvent.target.localName == "arrowscrollbox";
```

**Comment by onemen** [comment]
Let me know if there are more issues after #28 fixed

**Comment by 117649** [comment]
https://github.com/onemen/TabMixPlus/issues/28#issuecomment-770219021
This seems working for me.
 
I think we missing support for Multi-select tabs, now TMP seems blocking this feature.

**Comment by onemen** [comment]
if Multi-select tabs is only work with Ctrl-click (windows) we can add it as one of the options, so user can use shift-click instead
then when user click action in Multi-select tabs we just let Firefox control the action

**Comment by 117649** [comment]
`browser.tabs.closeTabByDblclick` is also a factor need to be considered.

**Comment by 117649** [comment]
> if Multi-select tabs is only work with Ctrl-click (windows) we can add it as one of the options, so user can use shift-click instead
> then when user click action in Multi-select tabs we just let Firefox control the action

Looks like this is doable. 
https://github.com/mozilla/gecko-dev/blob/0db73daa4b03ce7513a7dd5f31109143dc3b149e/browser/base/content/tabbrowser-tab.js#L342-L358

**Comment by onemen** [comment]
I'm not sure we can modify on_mousedown with eval since it call super at the end, if that is the case we just need to remove ctrl/cmd from tab options

**Comment by 117649** [comment]
> I'm not sure we can modify on_mousedown with eval since it call super at the end, if that is the case we just need to remove ctrl/cmd from tab options

As for now except current selected tab 'ctrl + click' won't call 'on_mousedown'. TMP's event listener get the event every time effectively replaced 'on_mousedown'.

For `super.on_mousedown()`  we can use `this.__proto__.__proto__.on_mousedown()` to reach same thing.
What `super.on_mousedown()`  [doing](https://github.com/mozilla/gecko-dev/blob/450a2f0808e3c46237faee7a5ad7bc93e09144db/toolkit/content/widgets/tabbox.js#L308-L348) is pretty much just select the tab it won't get called if the tab is already current selection.
And we may not want that since it select another tab regardless. We may want to wait for sure it not a double click thus we can manipulate other tabs without change tab selection. I'm not sure if the older firefox really works in this way may be just because  mine running slow with 290+ tabs.

**Comment by onemen** [comment]
![image](https://user-images.githubusercontent.com/3650909/106626247-2bcce680-6580-11eb-92d1-909531e1d0bd.png)

At the moment user can enable multi-selection by disabling our options for Ctrl on tab and Shift on tab (Ctrl for selecting/unselecting single tab, shift for selecting range).

I think the best solution is to add new check box for multi-selection (need to find better label, maybe in Firefox help about it),
when this feature is enable it should automatically disable the options for Ctrl and Shift as described above, when it disabled it turn the other back. 

In order to enable Firefox multi-selection handler (mousedown) to work, we need to modify our ```tabBindings.js - onMouseCommand```

Our code stop the event when ```mousedown``` event is fired on a tab with modifiers
```
      // don't allow mouse click/down with modifiers to select tab
      if (aEvent.shiftKey || aEvent.ctrlKey || aEvent.altKey || aEvent.metaKey)
        aEvent.stopPropagation();
      else if (aSelectNewTab) {....
```

we need to change this and stop only modifies that we use in our click option above, so when when multi-selection is on we should allow shift/ctrl/meta to go throw

let me know what you think

**Comment by 117649** [comment]
> ![image](https://user-images.githubusercontent.com/3650909/106626247-2bcce680-6580-11eb-92d1-909531e1d0bd.png)
> 
> At the moment user can enable multi-selection by disabling our options for Ctrl on tab and Shift on tab (Ctrl for selecting/unselecting single tab, shift for selecting range).
> 
> I think the best solution is to add new check box for multi-selection (need to find better label, maybe in Firefox help about it),
> when this feature is enable it should automatically disable the options for Ctrl and Shift as described above, when it disabled it turn the other back.
> 
> In order to enable Firefox multi-selection handler (mousedown) to work, we need to modify our `tabBindings.js - onMouseCommand`
> 
> Our code stop the event when `mousedown` event is fired on a tab with modifiers
> 
> ```
>       // don't allow mouse click/down with modifiers to select tab
>       if (aEvent.shiftKey || aEvent.ctrlKey || aEvent.altKey || aEvent.metaKey)
>         aEvent.stopPropagation();
>       else if (aSelectNewTab) {....
> ```
> 
> we need to change this and stop only modifies that we use in our click option above, so when when multi-selection is on we should allow shift/ctrl/meta to go throw
> 
> let me know what you think

If we can ensure multi-selection is enable while 'ctrl on tab' and 'shift on tab' is disabled, A proper text description may be just enough.

In future I think complete took over the 'multi-select' control and force user to allocate them two kinds of events(range selecting may could be optional) would be preferred.

**Comment by 117649** [comment]
Lets see we actually have 3 kinds behaviors here:

1. Multi-select: holding 'ctrl' select to add to selections, select again to remove from selections.
2. Range-select: holding 'shift' select a start then select an end to add all on the path to selections, select a shorter path to remove those outside new path from selections
3. Greedy Range-select: holding 'ctrl' & 'shift' select a start then select an end  to add all on the path to selections, select a new end to add more on path to selection(no removal at all).

If we want to took these command into our options we may need to follow Mozilla and add option for second holding key.
Or we may have some default second key protocol for 'Range-select' while assigned it to different controls for switching to greedy select.

**Comment by 117649** [comment]
Was think about an ideal to handle the ranged multi-select:
We could add a drop list for user to choose a second key for holding for switch to greedy ranged select.
A new preference item is required for this.
Then in `click.js` we can use this Pref to decided if we need to check for a '2 keys holding and click' event.
If so we pass down this event as an event of the another key and use the Pref of that key for click action.
This is the way that require minimal change on current codes I can think of for making range-select a option of our click options system.

I'll see if I can put up together some code for test later when I got time.

**Comment by 117649** [comment]
Tried integrate multi-select with our click options: https://github.com/117649/TabMixPlus/commit/36791cc76f4ce483d2adc2a737499bb12733abeb
Looks like working from my simple tests. Since there is not yet UI elements for this you have to apply settings from `about:config`
1 new preference named `extensions.tabmix.anotherKey` need to be created for code to run.
It should receive number type, meanings of each digit as follow. 0: disabled, 1: ctrl key, 2:shift key, 3: alt key.   
To use multi-select set `extensions.tabmix.{key}ClickTab` to 33.
To use ranged-select set `extensions.tabmix.{key}ClickTab` to 34.
To use greedy ranged-select set `extensions.tabmix.anotherKey` to one of ctrl, shift, alt which is not set to 34 then hold both key and click.

I hope you can try this out and if you find it is convenient we can carry on to create UI elements.

**Comment by 117649** [comment]
I just went on and made some UI elements for it:https://github.com/117649/TabMixPlus/commit/f764e9ec04aa7c6069c5c1156cb19a284dc5b9e4

Still have to create preference manually.

**Comment by onemen** [comment]
Since this is the only feature that require 2 separate preference  together it will be easier if we show these preference again separately. 

I don't think we need an extra preference extensions.tabmix.anotherKey, use the preference for 33 as the 2nd key.

we have to make sure that user set both preference

**Comment by 117649** [comment]
> Since this is the only feature that require 2 separate preference together it will be easier if we show these preference again separately.
> 
> I don't think we need an extra preference extensions.tabmix.anotherKey, use the preference for 33 as the 2nd key.
> 
> we have to make sure that user set both preference

No, you can have user set only one of two.

**Comment by 117649** [comment]
Try this:https://github.com/117649/TabMixPlus/commit/e8b23987ac6020a0abbbefceb473740092e00f8c

**Comment by 117649** [comment]
https://github.com/117649/TabMixPlus/commit/071558ce81b0686e0c1449367b6046b887a0a382

**Comment by 117649** [comment]
https://github.com/117649/TabMixPlus/commit/ddbea2163947fcb9b6287f9ed8c97b1d48a6725d

**Comment by onemen** [comment]
Thank you for your work @117649

just pushed https://github.com/onemen/TabMixPlus/commit/11c112279de573015e31273127a08cca7a4caa8f
