### ISSUE TITLE
New Tab (After This Tab) does not seem to work

### ISSUE THREAD

**Issue by pyrates999** [onemen/TabMixPlus#262]
When you right click on a tab and select **New Tab (After This Tab)**, nothing happens.  I can only add a new tab by clicking on the **Open a new tab (Ctrl + T)** Plus button on the right side.

Using Firefox 122.0.1 64-bit on windows 10 19045.3930.
Using tab mix plus extension version 1.0.0-pre.18 updated on January 30/2024.

I've tried going to **about:support** and clicking on **Clear startup cache...** button, but did not fix it.

Here is my preferences file:

[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/14207707/TMPpref.txt)

**Comment by 117649** [comment]
> When you right click on a tab and select **New Tab (After This Tab)**, nothing happens. I can only add a new tab by clicking on the **Open a new tab (Ctrl + T)** Plus button on the right side.
> 
> Using Firefox 122.0.1 64-bit on windows 10 19045.3930. Using tab mix plus extension version 1.0.0-pre.18 updated on January 30/2024.
> 
> I've tried going to **about:support** and clicking on **Clear startup cache...** button, but did not fix it.
> 
> Here is my preferences file:
> 
> [TMPpref.txt](https://github.com/onemen/TabMixPlus/files/14207707/TMPpref.txt)

@onemen same here.

**Comment by onemen** [comment]
typo

```diff
--- a/addon/chrome/content/click/click.js
+++ b/addon/chrome/content/click/click.js
@@ -525,7 +525,7 @@ var TabmixContext = {
       Tabmix.setItem(newTab, "oncommand", "TMP_BrowserOpenTab();");
     } else {
       Tabmix.setItem(newTab, "label", newTab.getAttribute("_newtab") + "  " + newTab.getAttribute("_afterthis"));
-      Tabmix.setItem(newTab, "oncommand", `TMP_BrowserOpenTab(${Tabmix.isVersion(1150) ? {} : null}, TabContextMenu.contextTab);`);
+      Tabmix.setItem(newTab, "oncommand", `TMP_BrowserOpenTab(${Tabmix.isVersion(1150) ? `{}` : `null`}, TabContextMenu.contextTab);`);
     }
```

I will upload new version this weekend

**Comment by onemen** [comment]
@117649 

can you test it and verify that it solve this issue ?

**Comment by 117649** [comment]
> @117649
> 
> can you test it and verify that it solve this issue ?

I can only guess what you want me to do here.

![image](https://github.com/onemen/TabMixPlus/assets/8281345/6e5258ef-3be6-4953-a294-a15797e6a4b2)

I put this change in and tested on 123 dev ed as I don't want to restart 122 release and  reload hundreds of tabs.
 After installation **New Tab (After This Tab)** open the new tab as it should be and at where it should be.

**Comment by onemen** [comment]
@pyrates999 

Download and test this new [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.19.20240211.1.xpi)

**Comment by pyrates999** [comment]
@onemen

That fixed it.  But I found a new bug.  Opening new tabs uses the setting for **Homepage and new windows** instead of **New Tabs**:

![image](https://github.com/onemen/TabMixPlus/assets/106135298/37828143-0b22-4313-98c0-fd22ab812cf6)

So when I right click on a tab and select **New Tab (After This Tab)**, and when I click on the Plus button for **Open a new tab (Ctrl + T)**, it will show me the page for **Firefox Home (Default)** instead of **Blank Page**.

When I change **Homepage and new windows** to be **Blank Page**, then new tabs will be a blank page.

**Comment by onemen** [comment]
@pyrates999 

Update the preference in Tab Mix to load `Blank Tab` on new tabs
![image](https://github.com/onemen/TabMixPlus/assets/3650909/432368b9-8872-4f9c-97f0-1b58b9e79d79)

**Comment by pyrates999** [comment]
That fixed it, thanks!
