### ISSUE TITLE
Smooth scrolling tab bar does not work properly

### ISSUE THREAD

**Issue by Gordon-Dry** [onemen/TabMixPlus#263]
It's just a huge jump.

Partially fixed, see https://github.com/onemen/TabMixPlus/issues/263#issuecomment-1946009306

**Comment by onemen** [comment]
please upload a file with your Tab Mix preferences

**Comment by Gordon-Dry** [comment]
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/14226273/TMPpref.txt)

**Comment by onemen** [comment]
I don't see any problem with smooth scrolling.

try to follow our [troubleshooting](https://onemen.github.io/tabmixplus-docs/troubleshooting/)

**Comment by Gordon-Dry** [comment]
```
  "addons": [
    {
      "name": "'Improve YouTube!' 🎧 (for YouTube & Videos)",
      "type": "extension",
      "version": "4.615",
      "isActive": true,
      "id": "{3c6bf0cc-3ae2-42fb-9993-0d33104fdcaf}"
    },
    {
      "name": "AdBlocker for YouTube™",
      "type": "extension",
      "version": "0.4.5",
      "isActive": true,
      "id": "jid1-q4sG8pYhq8KGHs@jetpack"
    },
    {
      "name": "Add-ons Search Detection",
      "type": "extension",
      "version": "2.0.0",
      "isActive": true,
      "id": "addons-search-detection@mozilla.com"
    },
    {
      "name": "Amazon.de",
      "type": "extension",
      "version": "1.13",
      "isActive": true,
      "id": "amazon@search.mozilla.org"
    },
    {
      "name": "Bing",
      "type": "extension",
      "version": "1.6",
      "isActive": true,
      "id": "bing@search.mozilla.org"
    },
    {
      "name": "Brave search",
      "type": "extension",
      "version": "1.0.1",
      "isActive": true,
      "id": "BraveSearchExtension@io.Uvera"
    },
    {
      "name": "Cookie Quick Manager",
      "type": "extension",
      "version": "0.5rc2",
      "isActive": true,
      "id": "{60f82f00-9ad5-4de5-b31c-b16a47c51558}"
    },
    {
      "name": "Copy PlainText",
      "type": "extension",
      "version": "1.15",
      "isActive": true,
      "id": "copyplaintext@eros.man"
    },
    {
      "name": "DeepL Übersetzer: Lesen und Schreiben in Fremdsprachen",
      "type": "extension",
      "version": "1.12.3",
      "isActive": true,
      "id": "firefox-extension@deepl.com"
    },
    {
      "name": "DownThemAll!",
      "type": "extension",
      "version": "4.12.1",
      "isActive": true,
      "id": "{DDC359D1-844A-42a7-9AA1-88A850A938A8}"
    },
    {
      "name": "DuckDuckGo",
      "type": "extension",
      "version": "1.4",
      "isActive": true,
      "id": "ddg@search.mozilla.org"
    },
    {
      "name": "eBay",
      "type": "extension",
      "version": "1.4",
      "isActive": true,
      "id": "ebay@search.mozilla.org"
    },
    {
      "name": "Ecosia",
      "type": "extension",
      "version": "1.2",
      "isActive": true,
      "id": "ecosia@search.mozilla.org"
    },
    {
      "name": "Form History Control (II)",
      "type": "extension",
      "version": "2.5.8.0",
      "isActive": true,
      "id": "formhistory@yahoo.com"
    },
    {
      "name": "FoxyProxy",
      "type": "extension",
      "version": "8.9",
      "isActive": true,
      "id": "foxyproxy@eric.h.jung"
    },
    {
      "name": "Google",
      "type": "extension",
      "version": "1.4",
      "isActive": true,
      "id": "google@search.mozilla.org"
    },
    {
      "name": "I still don't care about cookies",
      "type": "extension",
      "version": "1.1.4",
      "isActive": true,
      "id": "idcac-pub@guus.ninja"
    },
    {
      "name": "LEO Eng-Deu",
      "type": "extension",
      "version": "1.1",
      "isActive": true,
      "id": "leo_ende_de@search.mozilla.org"
    },
    {
      "name": "Return YouTube Dislike",
      "type": "extension",
      "version": "3.0.0.14",
      "isActive": true,
      "id": "{762f9885-5a13-4abd-9c77-433dcd38b8fd}"
    },
    {
      "name": "Sicherer Passwort Generator",
      "type": "extension",
      "version": "1.0.9",
      "isActive": true,
      "id": "password.generator@kolya.ca"
    },
    {
      "name": "Speichere mein Kennwort",
      "type": "extension",
      "version": "2.9",
      "isActive": true,
      "id": "admin@fastaddons.com_SaveMyPassword"
    },
    {
      "name": "SponsorBlock für YouTube – Überspringe gesponserte Videosegmente",
      "type": "extension",
      "version": "5.5.4",
      "isActive": true,
      "id": "sponsorBlocker@ajay.app"
    },
    {
      "name": "Tab Mix Plus",
      "type": "extension",
      "version": "1.0.0-pre.18",
      "isActive": true,
      "id": "{dc572301-7619-498c-a57d-39143191b318}"
    },
    {
      "name": "Text Link",
      "type": "extension",
      "version": "6.1.9",
      "isActive": true,
      "id": "{54BB9F3F-07E5-486c-9B39-C7398B99391C}"
    },
    {
      "name": "uBlock Origin",
      "type": "extension",
      "version": "1.55.0",
      "isActive": true,
      "id": "uBlock0@raymondhill.net"
    },
    {
      "name": "Wikipedia (de)",
      "type": "extension",
      "version": "1.3",
      "isActive": true,
      "id": "wikipedia@search.mozilla.org"
    },
    {
      "name": "Yet Another Smooth Scrolling WE",
      "type": "extension",
      "version": "2.0.11",
      "isActive": true,
      "id": "yetanothersmoothscrollingwe@kataho"
    },
    {
      "name": "Youtube-shorts block",
      "type": "extension",
      "version": "1.4.1",
      "isActive": true,
      "id": "{34daeb50-c2d2-4f14-886a-7160b24d66a4}"
    },
    {
      "name": "Zoom Page WE",
      "type": "extension",
      "version": "19.13",
      "isActive": true,
      "id": "zoompage-we@DW-dev"
    },
    {
      "name": "Dunkel",
      "type": "theme",
      "version": "1.2",
      "isActive": true,
      "id": "firefox-compact-dark@mozilla.org"
    },
    {
      "name": "FoxyTab",
      "type": "extension",
      "version": "2.31",
      "isActive": false,
      "id": "foxytab@eros.man"
    },
    {
      "name": "Tab Session Manager",
      "type": "extension",
      "version": "6.12.2",
      "isActive": false,
      "id": "Tab-Session-Manager@sienori"
    },
    {
      "name": "Firefox Alpenglow",
      "type": "theme",
      "version": "1.4",
      "isActive": false,
      "id": "firefox-alpenglow@mozilla.org"
    },
    {
      "name": "Hell",
      "type": "theme",
      "version": "1.2",
      "isActive": false,
      "id": "firefox-compact-light@mozilla.org"
    },
    {
      "name": "System-Theme – automatisch",
      "type": "theme",
      "version": "1.3",
      "isActive": false,
      "id": "default-theme@mozilla.org"
    }

```

**Comment by onemen** [comment]
Thank you for your info, however currently I don't have any knowledge about conflicting extensions

In order to find out the cause of your issue you will have to disable other extensions manually
try do disable `Yet Another Smooth Scrolling WE`

If you have `userChrome.css` in your profile, make sure to test if disabling any css rules helps

**Comment by Gordon-Dry** [comment]
Neither helps.

**Comment by onemen** [comment]
try these steps:

- create new profile
- follow the [installation steps](https://github.com/onemen/TabMixPlus?tab=readme-ov-file#installation) for Firefox scripts
- install Tab Mix Plus
- import you preferences
- test that Smooth scrolling work as it should
- start adding you other extensions, close and start Firefox and test if Smooth scrolling work after each extension you installed

**Comment by Gordon-Dry** [comment]
As the profile was already brand new (less than 3 days old) and disabling all other addons did not help I only can assume that was it.
I need to adapt to the new era of "nothing works anymore".

**Comment by 117649** [comment]
> As the profile was already brand new (less than 3 days old) and disabling all other addons did not help I only can assume that was it. I need to adapt to the new era of "nothing works anymore".

Check if these helps:https://github.com/yokoffing/Betterfox/blob/main/Smoothfox.js

**Comment by Gordon-Dry** [comment]
No, unfortunately.

**Comment by onemen** [comment]
@Gordon-Dry,

just to be sure, create new test profile, install [firefox-scripts](https://github.com/onemen/TabMixPlus/?tab=readme-ov-file#installation) and Tab Mix Plus. test if it Smooth scrolling works...

**Comment by Gordon-Dry** [comment]
I finally got it.
It's so dumb ... Mozilla indeed did a bad job by starting to lean towards (aka. licking feet of) Chromium.

I had to re-enable the native Windows feature "Animate Controls and Elements Inside Windows" (my Windows is german-localized and the feature is called "Steuerelemente und Elemente innerhalb von Fenstern animieren".

It's dumb that the browser UI's features depend on native OS features. Just like that.

I did not have those kind of issues with Pale Moon (but others).
W3C standards are the standards, not Google and/or Microsoft standards.

**Comment by pyrates999** [comment]
I disagree.  That is a common option used in any application to allow for smooth scrolling inside the applications window.

May I ask why you disabled it?

**Comment by Gordon-Dry** [comment]
I disabled it years ago because I was sick of native Windows desktop or UI animation behaviour.

Imho the user should have the possibility to enable or disable behaviours of different software's UI without being forced to be dependent of the OS default settings.

btw I found a way to alter the amount of tabbar to be scrolled when moving the mousewheel for one notch:
mousewheel.default.delta_multiplier_y
This could be in the mod's settings as well.

**Comment by onemen** [comment]
> But, I still have the issue that the scroll of the tabbar moves too far.
> 
> I had this before (without smooth scrolling, just jumping there) and I have it now.
> 
> How do I decrease the amount of tabbar to be scrolled over?

Probably in your mouse settings

**Comment by Gordon-Dry** [comment]
As I already said, it was okay with Pale Moon.

And I edited something into the last post, I repeat:
```
btw I found a way to alter the amount of tabbar to be scrolled when moving the mousewheel for one notch:
mousewheel.default.delta_multiplier_y
This could be in the mod's settings as well.
```

**Comment by onemen** [comment]
Ok.

So this is not an issue of Tab mix plus

**Comment by Gordon-Dry** [comment]
Yes and no.
Compared to the behaviour of TMP on Pale Moon, it is.

Era of pseudo standarding.

Perhaps Homer Simpson will be right with his statement about the future of the internet some day.

**Comment by pyrates999** [comment]
No, this is not an issue with tab mix plus.

I don't think Palemoon used hardware acceleration for its smooth scrolling.  That's why it was able to do smooth scrolling with that option turned off.  It was doing smooth scrolling in software, very inefficient.
