### ISSUE TITLE
Closing tab behavior issue

### ISSUE THREAD

**Issue by nanisise** [onemen/TabMixPlus#264]
test environment:
Windows 10
Firefox 115 ESR
Tab Mix Plus v1.0.0-pre.18

Tab Mix Plus setting:
![未命名](https://github.com/onemen/TabMixPlus/assets/31593913/d6a4da7a-de37-4a14-8ac9-de7af73b576c)

only set this option，other options are default

When scrolling the page toolbar to the last tab and double-click to close any of the tabs in page toolbar,
then the remaining tabs on the left will fill the space left by the closed tab, as shown in the following video

https://github.com/onemen/TabMixPlus/assets/31593913/c58f0f89-19d2-4fa3-9d9c-b615b93d5e46

But if using the close button on each tab, the remaining tabs on the right will fill the space left by the closed tab, 
as shown in the following video

https://github.com/onemen/TabMixPlus/assets/31593913/1fbfff20-78e7-42f8-84fc-dc4b90b8559e

Firefox by default,  the remaining tabs on the right to fill the space left by the closed tab, so  the behavior of double-clicking with the mouse to close the tab can be fixed?

This problem only occurs when scrolling the page toolbar to the last tab. If the page toolbar is not scrolled to the last tab, the behavior of  double-clicking with the mouse or the close button on each page will be the same.

**Comment by 117649** [comment]
What if you close the tab with right-click context menu?

**Comment by nanisise** [comment]
> What if you close the tab with right-click context menu?

the remaining tabs on the left will fill the space left by the closed tab,  just like double-clicking

**Comment by onemen** [comment]
When you click on tab close button the tabs don't scroll until the mouse leaves the tab, so the mouse on the right of the one you closed move to the position of the tab you remove.

I will have to check in the Firefox and Tab Mix code how to replicate this behavior to our function that close tab on dbl-click

**Comment by onemen** [comment]
Download and test this new [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.19.20240211.2.xpi)

**Comment by nanisise** [comment]
> Download and test this new [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.19.20240211.2.xpi)

i've tested the new test build, it seems work, thanks
