### ISSUE TITLE
TMP disables AltGr+Return on certain FF browsers

### ISSUE THREAD

**Issue by JustGibberish** [onemen/TabMixPlus#265]
With TMP enabled, Alt+Return in the url bar no longer opens the target in a new tab on
- Floorp 11.9.0 and
- LibreWolf 122.0-2.

Didn't test with vanilla FF yet as I currently don't use it anywhere.

With TMP turned off in about:addons, it works again. Is there any place I could look to find a difference in settings between the two states other than about:config (it's probably not that simple, right)?

**Comment by onemen** [comment]
Alt+Return work for me on Firefox.

maybe there are some differences between Firefox and Floorp.
 
try to use Ctrl+Return for now

**Comment by JustGibberish** [comment]
Oh, just forgot to mention. I tried that as suggested in the old forum. It doesn't work either.

**Comment by onemen** [comment]
![opentabsfrom](https://github.com/onemen/TabMixPlus/assets/3650909/cfb98738-fce9-4b68-a17b-c5ac1b1e1ccd)

`Alt+Return` reverse these preferences. When the preference to open new tab from `Address bar` is on, `Return` will open the 
address in new tab while `Alt+Return` will open the address in current tab. When the preference is off, the command is reversed and `Alt+Return` will open the address in new tab.

let me know if this is how it work for you

**Comment by JustGibberish** [comment]
> `Alt+Return` reverse these preferences. When the preference to open new tab from `Address bar` is on, `Return` will open the address in new tab while `Alt+Return` will open the address in current tab. When the preference is off, the command is reversed and `Alt+Return` will open the address in new tab.
> 
> let me know if this is how it work for you

No, that was not the issue.

However, I am an idiot: The Alt key I actually use to open url bar inputs in a new tab is actually [AltGr](https://en.wikipedia.org/wiki/AltGr_key), which is the right Alt key on some layouts with three or more symbols on some of the keys. Wiki says AltGr is not usually present on US keyboards. You can emulate AltGr via Crtl+Alt, so they're likely the same thing from the OS' perspective - could that be an issue for TMP?

On plain firefox, the functionality is the same with both plain Alt and AltGr, meaning it'll open the url bar input in a new tab no matter which one you use. TMP does not disable Alt+Return, but it does disable AltGr+Return. It does that on vanilla firefox as well (I checked today). I know it didn't do that "in the old days", but I can't tell with which version that change appeared as I only have really old versions of TMP and the latest one, nothing in between.

**Comment by onemen** [comment]
post your Tab Mix Plus preference as a file

**Comment by onemen** [comment]
Your input about `AltGr key` helped me identify the issue.

I have found this comment in Firefox bug report from Jul 31, 2019
> Before this change, AltGr+Enter wouldn't open url in new tab on non-English layouts on Windows. This happened because non-> English layouts generated AltGr event on pressing right Alt key. Checking for this event in _whereToOpen function fixes the issue.

let me know what is your operating system, and language (keyboard layouts)

**Comment by onemen** [comment]
Download and install this NEW [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.19.20240215.1.xpi)

Test all the places that you are using AltGr

**Comment by JustGibberish** [comment]
> operating system, and language (keyboard layouts)
I tried it on 2 different machines, one with Windows 10 pro 22H2, the other with Windows 11 pro 23H2. Both with German OS and keyboard layout.

> Download and install this NEW [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.19.20240215.1.xpi)
> 
> Test all the places that you are using AltGr
I'm on it.

**Comment by JustGibberish** [comment]
First glance, it seems to work fine now. I will get back if if I find anything strange.

HUUUGE thank you!
