### ISSUE TITLE
Cannot avoid blank tabs being opened for magnet: links

### ISSUE THREAD

**Issue by Gordon-Dry** [onemen/TabMixPlus#267]
I can choose file types or try regular expressions, but a simple
`magnet:*`
does not work.

**Comment by onemen** [comment]
I am using this
`/^magnet:/`

**Note**
when you need to use regular expression for link it is best to enclose it with forward slash
this regular expression will match any link that starts with magnet:

**Comment by Gordon-Dry** [comment]
Thank you.
