### ISSUE TITLE
Open links to other sites in new tab does not work all the time

### ISSUE THREAD

**Issue by Gordon-Dry** [onemen/TabMixPlus#269]
FF 123.0
TMP 1.0.0-pre.18

On a DuckDuckGo search result; clicking on a link opens in a new tab with a ca. 60% chance, clicking the same link again can result in being opened in the same tab.
In other cases the first click opens in the same tab, the next click opens in a new tab.
It's unpredictable.

**Comment by onemen** [comment]
Post you Tab mix preference in a file.

it will help if you provide specific examples.

**Comment by Gordon-Dry** [comment]
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/14365245/TMPpref.txt)

**Comment by onemen** [comment]
In my testing it only open links to `https://duckduckgo.com/` in the same tab.

try to change `duckduckgo` settings

![duckduck-settings](https://github.com/onemen/TabMixPlus/assets/3650909/c848cb53-dd6a-4c2e-bbf3-41cdaecba45d)

![image](https://github.com/onemen/TabMixPlus/assets/3650909/d4a4e45c-d2e5-4d25-92dd-df6ea4755850)

**Comment by Gordon-Dry** [comment]
Thank you.

Of course I could have considered that, especially as this is a search engine...
