### ISSUE TITLE
Tab relation detection not working 

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#27]
Due to the change of the Firefox we now no longer have a `referrerURI` in `params`.  
`referrerInfo` seems replaced it.
https://github.com/onemen/TabMixPlus/blob/06b5130a94be1e2d8a06cd4df94ab8e35062c753/addon/chrome/content/minit/tablib.js#L136-L170

https://github.com/mozilla/gecko-dev/blob/0db73daa4b03ce7513a7dd5f31109143dc3b149e/browser/base/content/tabbrowser.js#L1616-L1641

**Comment by onemen** [comment]
Fixed by https://github.com/onemen/TabMixPlus/commit/22910bcc69a22ad888889b04cf0e4b1c3776f130
