### ISSUE TITLE
Internal links to "Help" or "Homepage" are going 404

### ISSUE THREAD

**Issue by Gordon-Dry** [onemen/TabMixPlus#270]
![Screen-2024-02-21_15-43-40](https://github.com/onemen/TabMixPlus/assets/29145213/882ceea4-9b0e-4936-86a6-2af08430ece5)
https://onemen.github.io/tabmixplus-docs/help/links = 404

![Screen-2024-02-21_15-44-57](https://github.com/onemen/TabMixPlus/assets/29145213/6e9a2e22-b3ec-4fcb-b834-04851379cb1e)
https://onemen.github.io/tabmixplus-docs = 404

**Comment by onemen** [comment]
Sorry about that it was out while I was testing new version

it is up again
