### ISSUE TITLE
Feature Request: TabMixPlus New Tab Button and Tabs below Bookmarks Toolbar.

### ISSUE THREAD

**Issue by StavrosTsik** [onemen/TabMixPlus#272]
1. In TabMixPlus options under `Display -> Tab Bar`, I have enabled the **Multi-row** setting.

![Screenshot 2024-02-25 221904](https://github.com/onemen/TabMixPlus/assets/96174036/9a93a6da-6833-4d70-b92f-3c10477fdf81)

As the rows are increasing, the "New Tab" button isn't centered dynamically.  It always stays on top.

![Screenshot 2024-02-25 043534](https://github.com/onemen/TabMixPlus/assets/96174036/60a58240-83d0-45a3-b2c4-206ca3fd5da5)

That is by default or is something that can be **"fixed"** ?

2. The **Position** setting for the Tab Bar in the same page, has two options"

![Untitled11](https://github.com/onemen/TabMixPlus/assets/96174036/a4645f47-5833-439d-8753-ead04efcf2b5)

Can it be a third option of placing the Tabs below Bookmarks toolbar like it was e.g In Firefox 3.x or in Firefox 4.x (with the option **"Tabs not on Top"**) ? 

![Untitled](https://github.com/onemen/TabMixPlus/assets/96174036/36df2bb4-9221-4a2e-986a-275e4230398e)

![Untitled1](https://github.com/onemen/TabMixPlus/assets/96174036/b4177709-c15e-42fe-88a7-690654aa6d41)

I mean, if TabMixPlus can do **`"Bottom (below content)"`**, how hard is **"Below Bookmarks Toolbar"** ?

**Comment by pyrates999** [comment]
Do you mean a new tab button would be to the right of the very last tab?

**Comment by StavrosTsik** [comment]
> Do you mean a new tab button would be to the right of the very last tab?

No. I mean something like this. Right in the center.. (And as the Tab Rows increasing, the new tab button is always centered)

![307622813-60a58240-83d0-45a3-b2c4-206ca3fd5da5](https://github.com/onemen/TabMixPlus/assets/96174036/773acf24-62b2-4a79-a90b-e3d68bf0c4ba)

**Comment by onemen** [comment]
@StavrosTsik 

#### **"New Tab" button** position:
- Add this css rule to your `userChrome.css` file in your profile `chrome` folder

```css
#new-tab-button {
  align-self: center;
}
```
- check in `about:config` and make sure `toolkit.legacyUserProfileCustomizations.stylesheets` it **true**

#### Tab bar position: Below Bookmarks Toolbar
> I mean, if TabMixPlus can do "Bottom (below content)", how hard is "Below Bookmarks Toolbar" ?

I will welcome any **Pull request** to add this feature

**Comment by StavrosTsik** [comment]
> * Add this css rule to your `userChrome.css` file in your profile `chrome` folder

Ok. I will try it. But can’t this be implemented in a future version of TabMixPlus so there’s no need of any CSS customization?

**Comment by onemen** [comment]
We have endless ways to position elements  in the window. I am not planing to add all those as options to Tab Mix Plus

**Comment by StavrosTsik** [comment]
Understood. I was only referring to this specific feature and not as an option but as an automatic formatting.

**Comment by onemen** [comment]
there are not preference I want to have as default in Tab Mix Plus

**Comment by StavrosTsik** [comment]
> try to run this command in the `Browser Console`
> 
> ```js
> (tabs=document.getElementById("TabsToolbar"),tabs.parentNode.insertBefore(document.getElementById("PersonalToolbar"), tabs))
> ```


I run this command but what it really does, is to move Bookmarks toolbar **"On Top of Tab Bar"** and below File Menu.

![New Bitmap image](https://github.com/onemen/TabMixPlus/assets/96174036/782aec45-693e-430c-9118-6f8ec2c12ee5)

Half of the requested feature (File Menu -> Nav/Address Bar -> Bookmarks toolbar -> Tab Bar)

![Untitled](https://github.com/onemen/TabMixPlus/assets/96174036/2db30389-731e-4339-97e0-4c1618ebc8b0)

**Comment by onemen** [comment]
try to run this command in the `Browser Console`
```js
(bm=document.getElementById("PersonalToolbar"),bm.parentNode.insertBefore(document.getElementById("TabsToolbar"), bm.nextSibling))
```

**Comment by StavrosTsik** [comment]
> try to run this command in the `Browser Console`
> 
> ```js
> (bm=document.getElementById("PersonalToolbar"),bm.parentNode.insertBefore(document.getElementById("TabsToolbar"), bm.nextSibling))
> ```

Bullseye. That's it. 

![New Bitmap image](https://github.com/onemen/TabMixPlus/assets/96174036/d57e996f-3949-4423-940f-7745507299c2)

How do I make this command permanent in **`Browser Console`** ? Because when Firefox restarts, I have to run the command again and again.

**Comment by onemen** [comment]
[tabs_below_bookmarks.uc.zip](https://github.com/onemen/TabMixPlus/files/14547599/tabs_below_bookmarks.uc.zip)

this zip file contains one script, tabs_below_bookmarks.uc.js

- Place this script in your profile/chrome folder.
- You should have user script `userChrome.jsm` installed in your profile/chrome/utils. Read [here](https://onemen.github.io/tabmixplus-docs/other/installation/#install-utils) how to install utils.

**Comment by StavrosTsik** [comment]
@onemen

Ιs there also a css rule for **"Close tab button"** and **"All tabs button"** (beyond "New Tab" button you provided me above) to add to **`userChrome.css`**, to be automatically centered when the "**Multi-row**" option is selected ?

![Screenshot 2024-03-17 215316](https://github.com/onemen/TabMixPlus/assets/96174036/76d69e0b-61c1-4cdc-85b9-93095b85c134)
![Screenshot 2024-03-17 224550](https://github.com/onemen/TabMixPlus/assets/96174036/006a44e6-41ba-4a5e-b686-1192e2fddf6d)

**Comment by StavrosTsik** [comment]
Works like a charm!! :satisfied::satisfied:
