### ISSUE TITLE
"Open all in tabs" no longer working in latest Waterfox

### ISSUE THREAD

**Issue by N1mu3h** [onemen/TabMixPlus#275]
Since the last Waterfox update 2 weeks the option to "Open all in tabs" from a folder of bookmarks no longer works. Someone in the Waterfox subreddit says using the middle mouse button doesn't work for it any more either.

If we disable TMP then "Open all in tabs" works again. For now I'm just dragging the folder to the tab bar, but it would be great if this could get fixed. Not sure who broke it though, TMP or Waterfox.

**Comment by N1mu3h** [comment]
Unfortunately that didn't help, Open All in Tabs still doesn't work. Thanks for trying though ☺️

**Comment by onemen** [comment]
report if you get any messages in the `Browser Console`

**Comment by N1mu3h** [comment]
Does this help? Or do I need to do anything else?
Hmm, it won't let me add the screenshot so I uploaded it [here](https://i.imgur.com/rVaRv5H.jpg).

**Comment by onemen** [comment]
```shell
19:33:20.938 Uncaught ReferenceError: originalOpenTabset is not defined
    <anonymous> chrome://tabmix-resource/content/Places.jsm line 90 > eval:3
    openMultipleLinksInTabs resource:///modules/PlacesUIUtils.sys.mjs:1057
    oncommand chrome://browser/content/browser.xhtml:1
[Places.jsm line 90 > eval:3:7](chrome://tabmix-resource/content/Places.jsm%20line%2090%20%3E%20eval)
19:33:26.085 This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[browser.xhtml](view-source:chrome://browser/content/browser.xhtml)
19:33:26.357 TypeError: window.PrivateBrowsingUtils is undefined
[WaterfoxGlue.sys.mjs:234:15](resource:///modules/WaterfoxGlue.sys.mjs)
```

I will work on this tomorrow

**Comment by N1mu3h** [comment]
I have NO idea what all that code means, but thank you SO MUCH for looking into this 💙

**Comment by onemen** [comment]
Waterfox made changed to the code 2 weeks ago
```js
  overridePlacesUIUtils() {
    // Save a reference to the original function
    const originalOpenTabset = PlacesUIUtils.openTabset;

    // Redefine the function
    PlacesUIUtils.openTabset = function(aEvent, aWindow, aTabs, loadInBackground) {
      // Call the original function with the modified arguments
      return originalOpenTabset.call(this, aEvent, aWindow, aTabs, loadInBackground, aEvent.userContextId || 0);
    };
```

When Tab Mix Plus try to update `PlacesUIUtils.openTabset` the function can not find the reference to originalOpenTabset

**Comment by N1mu3h** [comment]
Yea I knew they changed something, but I have no idea what. As long as it's fixable I'm sure you'll find a solution ☺️

**Comment by onemen** [comment]
Download and install this NEW [test build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/test-build-1.0.0-pre.19.20240309.1.xpi)

**Comment by N1mu3h** [comment]
Yesssss, you did it - Open All in Tabs is working again!

Thank you soooo much for the quick fix! 😍
