### ISSUE TITLE
event.target.localName not match tab or tabs

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#28]
event.target.localName gBrowser.tabContainer no longer match tab or tabs

we need to scan the code and replace ```event.target.localName``` with the proper value
some of the issues related to #21 and #26 caused by this issue

**Comment by 117649** [comment]
For me, I may just straight use `gBrowser.tabContainer.contains(event.target)`.
`aEvent.currentTarget` may also be choice I suppose?

**Comment by onemen** [comment]
aEvent.currentTarget can be null

i will use aEvent.target.localName === "arrowscrollbox" for instead of "tabs"
and use aEvent.target.closest("tab.tabbrowser-tab") to get the tab for events on tabs

**Comment by onemen** [comment]
fixed by https://github.com/onemen/TabMixPlus/commit/beeeec35cc704d7b6d6f3b1a2bfacb7d1cc7e16a
