### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by halt76** [onemen/TabMixPlus#282]
I installed 1.19.1-20240311.0855.
After update it will be 1.19.1.
Which is newer?

**Comment by onemen** [comment]
1.19.1-20240311.0855 it the latest [dev-build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build)

**Comment by onemen** [comment]
Thank you for the report

new [dev-build](https://api.bitbucket.org/2.0/repositories/onemen/tabmixplus-for-firefox/downloads/tab_mix_plus-dev-build.xpi) is now `1.19.2-20240313.1135`
