### ISSUE TITLE
Tab size behavior in multi-row

### ISSUE THREAD

**Issue by IsletsOfLangerhans** [onemen/TabMixPlus#286]
I've just started using TMP with Firefox 124, and have noticed a change in behavior with multi-row versus my previous experience in Waterfox Classic.  Previously, the tabs would get smaller and smaller until they reached minimum size, and then create a new row.  But any new tabs created at that point would be that minimum size, even if they are in the new row.

In Firefox 124, any tabs created in the new row are full sized (until they also start running out of room and get smaller).  Is there any way to change this, so that it acts like it used to?

**Comment by onemen** [comment]
Read #285

**Comment by IsletsOfLangerhans** [comment]
Sorry, I had missed that one.
