### ISSUE TITLE
126beta The right-click part is not displayed

### ISSUE THREAD

**Issue by dsyo2008** [onemen/TabMixPlus#288]
It needs to be right-clicked multiple times, and then the display is normal. It needs to be right-clicked multiple times each time it is started. Please understand that I don’t speak English. Please use Google Translate and you should understand it.
![图片](https://github.com/onemen/TabMixPlus/assets/3739056/492e395d-11f2-4491-848f-c87872850e2d)
![图片](https://github.com/onemen/TabMixPlus/assets/3739056/47386433-7eb1-446f-bf3f-4a2081586483)

**Comment by onemen** [comment]
There are multiple changes in Firefox 126.

I will try to work on it next weekend

**Comment by onemen** [comment]
Download and install [Latest Developer Build](https://api.bitbucket.org/2.0/repositories/onemen/tabmixplus-for-firefox/downloads/tab_mix_plus-dev-build.xpi)
