### ISSUE TITLE
ErrMSg on 126b1

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#290]
![image](https://github.com/onemen/TabMixPlus/assets/8281345/50387c8c-219e-4210-b698-6fcc49c09100)
![image](https://github.com/onemen/TabMixPlus/assets/8281345/1677c65e-bc03-46cb-a3b8-28d9be4542a7)

**Comment by onemen** [comment]
There are multiple changes in Firefox 126.

I will try to work on it next weekend

**Comment by onemen** [comment]
Download and install [Latest Developer Build](https://api.bitbucket.org/2.0/repositories/onemen/tabmixplus-for-firefox/downloads/tab_mix_plus-dev-build.xpi)

**Comment by 117649** [comment]
Looks like they are gone.
