### ISSUE TITLE
Open newtab from urlbar issue

### ISSUE THREAD

**Issue by nanisise** [onemen/TabMixPlus#291]
test environment:
Windows 10
Firefox 115 ESR
Tab Mix Plus v1.19.1

When setting "open new tab from urlbar" option checked  in Tab Mix Plus, 
and  typing any terms in urlbar, if the result is from bookmark, Tab Mix Plus will open in the new tab
But if the result is from history, Tab Mix Plus will open in the current tab.

This behavior can't be changed even setting "open new tab from history" option checked.

**Comment by onemen** [comment]
please attach a file with all your Tab Mix Plus preferences

**Comment by nanisise** [comment]
Hi, this is my Tab Mix Plus preferences
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/15050262/TMPpref.txt)

**Comment by onemen** [comment]
I can not reproduce this issue.

do you see any messages in the Browser Console after the address loads in the current tab?

can you post step to reproduce with examples urls ?

**Comment by nanisise** [comment]
This is the setting:
![未命名](https://github.com/onemen/TabMixPlus/assets/31593913/bc9b6ee6-7328-4f07-8a10-a46efdf8482c)

And this is issue video:

https://github.com/onemen/TabMixPlus/assets/31593913/a2023905-facc-47ee-9a5d-7529a4ed930f


I also captured the console log during oprating, no error log...
![未命名2](https://github.com/onemen/TabMixPlus/assets/31593913/6a097872-9525-43a8-b4bd-7329571bfaa8)

**Comment by onemen** [comment]
Thank you,

I see the issue now, I hope to fix it soon

**Comment by onemen** [comment]
Download this [test build](https://github.com/onemen/TabMixPlus/files/15051261/test-build-1.20.0-20240421.1204.zip) zip file

Change its extension from `.zip` to `.xpi` and install it.

Report back

**Comment by nanisise** [comment]
Hi, after tested, it works.
Thanks for your hard work.
