### ISSUE TITLE
127 whereToOpenLink -> BrowserUtils.whereToOpenLink

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#296]
![image](https://github.com/onemen/TabMixPlus/assets/8281345/891a58e4-4e6f-48ab-bc1d-01e9d51654e9)
whereToOpenLink -> BrowserUtils.whereToOpenLink

**Comment by onemen** [comment]
Use Tab Mix latest [development build](https://api.bitbucket.org/2.0/repositories/onemen/tabmixplus-for-firefox/downloads/tab_mix_plus-dev-build.xpi)

**Comment by 117649** [comment]
> Use Tab Mix latest [development build](https://api.bitbucket.org/2.0/repositories/onemen/tabmixplus-for-firefox/downloads/tab_mix_plus-dev-build.xpi)

No change. The error still there.

**Comment by onemen** [comment]
It look like i have a typo in my last commit
I will fix it later today

**Comment by onemen** [comment]
Download the development build again 
https://github.com/onemen/TabMixPlus/releases/tag/dev-build
