### ISSUE TITLE
Bookmarks not working on single click with 127.b01

### ISSUE THREAD

**Issue by BobHD** [onemen/TabMixPlus#297]
Hi,

With Firefox Dev Edition 127.01, clicking on a bookmark, either on the sidebar or on the toolbar, does nothing.
You have to right click on it and choose an option on the menu to make them work.

I'm using the TMP version provided here:

https://github.com/onemen/TabMixPlus/discussions/292

**Comment by onemen** [comment]
try to use Tab Mix latest [development build](https://api.bitbucket.org/2.0/repositories/onemen/tabmixplus-for-firefox/downloads/tab_mix_plus-dev-build.xpi)

**Comment by BobHD** [comment]
This signed version is useful, no more warning that it's not verified, and I can still install the add-ons that were reported in the #292 thread.
But unfortunately, it does not solve the bookmark problem.

**Comment by onemen** [comment]
- Attach file with your Tab Mix Plus preferences.
- provide steps to reproduce this issue.
- post screenshot from the Browser console after you try to open a bookmark with single click.

**Comment by BobHD** [comment]
Here. 
The video shows what happens when I left click on several bookmarks, and what happens when I right click.

![console](https://github.com/onemen/TabMixPlus/assets/15735678/f4d7828e-2e8b-4878-84ac-8900ff13cdbe)

[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/15318313/TMPpref.txt)

https://github.com/onemen/TabMixPlus/assets/15735678/98766b83-92ed-43c5-bb69-4c106cb6a2d4

**Comment by onemen** [comment]
make sure you are using the latest development build from today version: 1.19.2-20240515.0729 or newer
https://github.com/onemen/TabMixPlus/releases/download/dev-build/tab_mix_plus-dev-build.xpi

**Comment by BobHD** [comment]
That worked, thanks.
