### ISSUE TITLE
Firefox 126 & TMP: "Open New Tab next to current one" not working anymore

### ISSUE THREAD

**Issue by dv8472** [onemen/TabMixPlus#298]
After upgrading to FF v126, the option "Open New Tab next to current one" doesn't seem to work anymore.
![image](https://github.com/onemen/TabMixPlus/assets/22549066/82d10aa2-5277-4fc8-a098-da3ea612ce4d)

New tabs are being opened automatically at the end.

**Comment by onemen** [comment]
use the latest development build from today version: 1.19.2-20240515.0729 or newer
https://github.com/onemen/TabMixPlus/releases/download/dev-build/tab_mix_plus-dev-build.xpi

also verify that all your firefox-scripts are up-to-date 
https://github.com/onemen/TabMixPlus/files/14075743/fx-folder.zip
https://github.com/onemen/TabMixPlus/files/14075742/utils_extensions_and_scripts.zip

**Comment by dv8472** [comment]
That was it, newer version of TMP 1.19.2-20240515.0729 fixes this.
Thanks!
