### ISSUE TITLE
Firefox 126 & TMP: "Reload Tab Every" not remembered on Tabs after browser restart

### ISSUE THREAD

**Issue by dv8472** [onemen/TabMixPlus#299]
I had some Tabs being reloaded every X sec/min/hour:
![image](https://github.com/onemen/TabMixPlus/assets/22549066/af74e9fd-2a6b-48d1-abae-7aacce478024)
using this feature:
![image](https://github.com/onemen/TabMixPlus/assets/22549066/f86fbb3a-4f1c-4b08-a308-4b6610ed8048)

Previously, after I restarted the browser, the feature was kept active on the Tab, and automatically started reloading site content again.

After upgrading to FF v126, the "clock" icon disappears from the Tab, and it's not being reloaded anymore automatically.

**Comment by onemen** [comment]
use the latest development build from today version: 1.19.2-20240515.0729 or newer
https://github.com/onemen/TabMixPlus/releases/download/dev-build/tab_mix_plus-dev-build.xpi

also verify that all your firefox-scripts are up-to-date 
https://github.com/onemen/TabMixPlus/files/14075743/fx-folder.zip
https://github.com/onemen/TabMixPlus/files/14075742/utils_extensions_and_scripts.zip

**Comment by dv8472** [comment]
That was it, newer version of TMP 1.19.2-20240515.0729 fixes this.
Thanks!
