### ISSUE TITLE
Append button not create good widgets 

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#30]
I just got Fx86.0b4 dropped.
Then:
`ReferenceError: Windows is not defined Overlays.jsm:755:5`
Shows up and it look like everything else is not load correctly due to it.

**Comment by 117649** [comment]
I've filled in `Windows` with raw definition then more complains shows up.  
```
setAttribute is not defined Overlays.jsm:861
Node.insertBefore: Argument 1 is not an object. Overlays.jsm:874
can't access property "removeChild", node.tempAppend.container.parentNode is null Overlays.jsm:879
tempAppend already exists! Overlays.jsm:851
Node.insertBefore: Argument 1 is not an object. Overlays.jsm:874
can't access property "removeChild", node.tempAppend.container.parentNode is null Overlays.jsm:879
tempAppend already exists! Overlays.jsm:851
Node.insertBefore: Argument 1 is not an object. Overlays.jsm:874
can't access property "removeChild", node.tempAppend.container.parentNode is null Overlays.jsm:879
```

**Comment by onemen** [comment]
I have this error is the past but not anymore, and i'm using Firefox Nightly 87.0a1

what type of bootstrap helper are you using, i'm using the script version

**Comment by 117649** [comment]
> I have this error is the past but not anymore, and i'm using Firefox Nightly 87.0a1
> 
> what type of bootstrap helper are you using, i'm using the script version

I'm using the extension type. 
So there is no problem with script type?

**Comment by onemen** [comment]
It works for me, I'm on windows 10
check on the bootstrap helper repository maybe there is an issue about this bug

**Comment by 117649** [comment]
> It works for me, I'm on windows 10
> check on the bootstrap helper repository maybe there is an issue about this bug

The problem persists for me after switch to script.
have you tested Firefox developer edition 86.0b4 on you environment?

**Comment by 117649** [comment]
https://github.com/117649/TabMixPlus/commit/1bea7c21dd9557baeb77e58651367756484b5676
Changes I have to made for it to load properly.

**Comment by onemen** [comment]
I'v just have the same error with undefined ```Windows```, after dragging Tab mix toolbar buttons to the main toolbar and restart firefox.

Resetting ```browser.uiCustomization.state``` in ```about:config``` disabling  Tab mix and enabling it again after restart seems to fix the issue

**Comment by 117649** [comment]
> I'v just have the same error with undefined `Windows`, after dragging Tab mix toolbar buttons to the main toolbar and restart firefox.
> 
> Resetting `browser.uiCustomization.state` in `about:config` disabling Tab mix and enabling it again after restart seems to fix the issue

The widgets system of Firefox have changed dramatically. Codes took from Tab-Group is not enough to handle the `<toolbarbutton>` unless it type is set to "custom" and I've clearly missed some parts of code that is fundamental for it that to work.

I'll see if I can come up with something for `Overlay.jsm`.

**Comment by onemen** [comment]
UNLOADED and listenOnce are not defined

why not to use TabmixSvc.forEachBrowserWindow

**Comment by 117649** [comment]
> UNLOADED and listenOnce are not defined
> 
> why not to use TabmixSvc.forEachBrowserWindow

We don't need UNLOADED since we don't have a unload procedure. I can fill in listenOnce.

The definition of TabmixSvc.forEachBrowserWindow is further down the line its not right to assume we would have it here unless  it been forward to Overlay.jsm or bootstrap.js .

**Comment by 117649** [comment]
https://github.com/117649/TabMixPlus/commit/f84bd4ee39f8948fa9cc48056aa98360aca6b717
My trying on fix this.

TMP buttons are from overlay nodes now and start issuing errors.

**Comment by 117649** [comment]
Note: "menu-button" is no more we now have 'button-and-view' which in comparison is a item of a button and a drop down panel warped together instead of a button bound together with a drop down menu.

Better choice for future may be just instance widgets in bootstrap.js with JavaScript.

**Comment by 117649** [comment]
With #32 no error on start for me at least for now.
