### ISSUE TITLE
del

### ISSUE THREAD

**Issue by ghost** [onemen/TabMixPlus#301]

**Comment by Apocalypse612** [comment]
It appears as though this issue only triggers when interacting with the last tab. It even auto scrolls the tabbar when reopening a closed tab for some unknown reason.

**Comment by onemen** [comment]
Try new version

Tab mix Plus [version 1.20.0](https://github.com/onemen/TabMixPlus/releases/download/v1.20.0/tab_mix_plus-1.20.0.xpi) is out.

Verify that all your firefox-scripts are up-to-date 
https://github.com/onemen/TabMixPlus/files/14075743/fx-folder.zip
https://github.com/onemen/TabMixPlus/files/14075742/utils_extensions_and_scripts.zip

**Comment by Apocalypse612** [comment]
I am using that, and just installed this version today.

Further,

**Comment by onemen** [comment]
When you close tab in multi-row, the tab bar scrolls to show the new selected tab

**Comment by janciorules** [comment]
Hello,

Unfortunately, I have the same problem as author.
Today I've installed ver. 1.21.1 with current utils/scripts on Firefox 128.0.3 (official Mozilla linux binaries) on Debian 12.
After enabling multi row tab bar (my preferred) I'm unable to make it focus on/scroll to just opened/newest tab (blank or link from other tab). My tabs are opening at the end of the list (properly) but the tabs on bar are scrolled randomly. When I show the tab list, the newly opened tab is highlighted as bold (active), but the tab bar is not scrolled to this opened tab properly. The workaround with mouse gesture didn't help unfortunately. 
I have about 2000 tabs in my window so it is very painful to scroll the tab list to the last tab. Unfortunately clicking and selecting the tab on the list doesn't scroll to the tab properly either on the bar . I had to turn off the multi row view for now.

I'll be glad for any suggestions. Thanks!
![Tab Mix Plus Options_002](https://github.com/user-attachments/assets/e238497b-7073-49c9-a03c-cbc7034537a4)
![Tab Mix Plus Options_001](https://github.com/user-attachments/assets/73a51f9c-9ea0-48e3-9035-8d1ae7c610b3)

**Comment by onemen** [comment]
@janciorules,

can you attach a file with your complete Tab Mix Plus preferences?

**Comment by janciorules** [comment]
I did export the configuration from the extension menu. Is it enough?

[TMPpref.gz](https://github.com/user-attachments/files/16438580/TMPpref.gz)

**Comment by onemen** [comment]
@janciorules,

Read here how to export your preferences (https://onemen.github.io/tabmixplus-docs/help/preferences-button/)

In order to help me solve this issue, please provide the steps needed to reproduce it

**Comment by janciorules** [comment]
> @janciorules,
> 
> Read here how to export your preferences (https://onemen.github.io/tabmixplus-docs/help/preferences-button/)
> In order to help me solve this issue, please provide the steps needed to reproduce it

yes, this is exactly what I did in the previous post, Can you see the attached file?. I exported preferences to the text file called "TMPpref" and then gzipped it. You can decompress it using 7-zip (Windows) or gzip (Linux/Unix). And then open it in any text editor.

**Comment by onemen** [comment]
I open the file you attached. I was not sure it was the right file, since multirow was off.

In order to help me solve this issue, please provide the steps needed to reproduce it

**Comment by janciorules** [comment]
> I open the file you attached. I was not sure it was the right file, since multirow was off.

Sorry, my fault, I exported after disabling Multi Row. Here's the proper file. With this configuration, when I
- open [+] new/blank tab
- open a link from other tab/website
- choose highlighted (bold) tab from the tab list

tab bar doesn't scroll to the chosen/new tab as expected

[TMPpref.txt.gz](https://github.com/user-attachments/files/16450892/TMPpref.txt.gz)

**Comment by onemen** [comment]
@janciorules,

I was not able to reproduce this issue on windows 11 and windows 10, i will try to test it on Linux next week

**Comment by janciorules** [comment]
Today I tested several scenarios:
- windows 10 + Firefox 128 (fresh profile, 1 windows,  112 tabs) = **Multi Row worked properly**
- the same Linux + Firefox 128 original profile as earlier, opened another browser window  (with 146 tabs) = **Multi Row worked properly**
- at the same time Linux/Firefox Window (with 2255 tabs)  = **Multi Row didn't work properly (autoscroll)**
- windows 10 + Firefox 128 (imported whole profile from Linux, all windows, tabs 2255 tabs)  = **Multi Row didn't work properly (autoscroll)**

so for now it seems that there's a problem with scrolling **so many tabs** in multi row configuration.

**Comment by pyrates999** [comment]
which Linux distro did you test with if I may ask?

**Comment by pyrates999** [comment]
Ok, thanks.  I figure it be useful in trying to verify the bug.

**Comment by onemen** [comment]
Do you see any message in your browser console when scroll failed?
