### ISSUE TITLE
Please return single tab scrolling as an option

### ISSUE THREAD

**Issue by Squall-Leonhart** [onemen/TabMixPlus#303]
You removed this like 15 years ago and it annoyed me then so i'd modify the extension to revert it, and i've just reverted it again with 1.2.0 by outright replacing the scrolling block in tabmix.js,  i'd rather just have an option to set this behavior instead of having to modifying the extension every update.

Single tab scrolling allows for far more precise wheel mouse scrolling on high end mice that have a free-wheel mode, the multiple-tab scroll always overshoots and leaves me having to look back amongst my tabs.

**Comment by onemen** [comment]
Add PR with the chahe you proposing

**Comment by onemen** [comment]
@Squall-Leonhart

Can you post the code you are using, or open a PR?

**Comment by Squall-Leonhart** [comment]
all i do is revert to an older version of the TMP code which still read out as 

```
      if (TabmixSvc.isPaleMoon && Tabmix.isVersion(0, 280) && !TabmixTabbar.isMultiRow) {
        return;
      }
      // this code is based on scrollbox.xml wheel/DOMMouseScroll event handler
      let scrollByDelta = function(delta) {
        let scrollByPixels = true;
        let instant;
        let scrollAmount = 0;
        if (Tabmix.isVersion(530) && TabmixTabbar.isMultiRow) {
          delta = delta > 0 ? 1 : -1;
          scrollAmount = delta * tabStrip.lineScrollAmount;
        } else if (Tabmix.isVersion(480) &&
            aEvent.deltaMode == aEvent.DOM_DELTA_PIXEL) {
          scrollAmount = delta;
          instant = true;
        } else if (Tabmix.isVersion(490) &&
            aEvent.deltaMode == aEvent.DOM_DELTA_PAGE) {
          scrollAmount = delta * tabStrip.scrollClientSize;
        } else {
          // scroll the tabbar by one tab
          if (orient == "horizontal" || TabmixTabbar.isMultiRow) {
            delta = delta > 0 ? 1 : -1;
          }
          scrollByPixels = false;
          tabStrip.scrollByIndex(delta);
        }

        if (scrollByPixels) {
          let useSmoothScroll = Tabmix.isVersion(530) && !Tabmix.isVersion(570) &&
            aEvent.deltaMode != aEvent.DOM_DELTA_PIXEL && tabStrip.smoothScroll;
          if (useSmoothScroll) {
            tabStrip._smoothScrollByPixels(scrollAmount);
          } else if (Tabmix.isVersion(570)) {
            tabStrip.scrollByPixels(scrollAmount, instant);
          } else {
            tabStrip.scrollByPixels(scrollAmount);
          }
        }
```

**Comment by Squall-Leonhart** [comment]
which removed

```
        } else if (Tabmix.isVersion(530)) {
          scrollAmount = delta * tabStrip.lineScrollAmount;
```

from old versions of the extension

**Comment by onemen** [comment]
Where do you insert this code in Tab Mix version 1.2, please attach the modified file

**Comment by Squall-Leonhart** [comment]
the letscrollbydelta block in https://github.com/onemen/TabMixPlus/blob/57caa6e171da688b6cd911509f3436191e64f05d/addon/chrome/content/tabmix.js#L1006

**Comment by onemen** [comment]
why can't you post the code that you are using + you Tab Mix Plus preferences

**Comment by onemen** [comment]
Download this [test build](https://github.com/user-attachments/files/16066498/test-build-1.22.0-20240702.1311.zip), rename it to .xpi and install it.

![image](https://github.com/onemen/TabMixPlus/assets/3650909/bef6099f-6feb-42b1-a169-9b453eabbb74)

- Enable `Scroll by Tabs`.
- Select the amount of tabs you want to scroll by.

Report if it solved this issue
