### ISSUE TITLE
[Bug]When Tab mix plus is installed, clicking anything in the Menu bar's history menu of one window will replace an actively selected about: pages in another window

### ISSUE THREAD

**Issue by Squall-Leonhart** [onemen/TabMixPlus#304]
Starting up a new Waterfox G6 profile and adding TMP to it, one can immediately reproduce this issue

First off, Turn on the Menu bar (The top strip)

1. Open a tab and load about:memory, about:performance, etc. Leave it selected
2. Open a new Window.
3. Try to open any history in the new window you just opened from the History menu at the top of the window.

The browser will replace the about: page in window one, rather than the current selected tab in the window you selected the history from.

The menu bar's history menu behaves correctly without TMP installed.

The Library history view, and hamburger menu history do not display this issue.

**Comment by onemen** [comment]
Thank you for the report.

I can reproduce this issue.

please attach a file with your Tab Mix Plus preferences.

**Comment by Squall-Leonhart** [comment]
I can do that, but it  begins from default TMP settings
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/15485161/TMPpref.txt)

**Comment by onemen** [comment]
Download this [test build](https://github.com/onemen/TabMixPlus/files/15485781/test-build-1.21.0-20240529.1719.zip), extract the xpi file and install it.

Report if it solved this issue

**Comment by Squall-Leonhart** [comment]
That does indeed seem to resolve it.
