### ISSUE TITLE
All tabs button keeps disappearing

### ISSUE THREAD

**Issue by PrinceOC912** [onemen/TabMixPlus#305]
Every time I set the all tabs button to show up on the tab bar it disappears after restarting firefox. I am using version 1.20.1-20240606.1715 and firefox nightly.

**Comment by onemen** [comment]
Attach a file with your Tab Mix Plus preference.

What is your Firefox version?

**Comment by PrinceOC912** [comment]
Never mind. Apparently I had browser.tabs.tabmanager.enabled set to false in my user.js file. I will close this issue now.
