### ISSUE TITLE
Left clicking link on Locked tab results in 2 new tabs and stealing focus (FF 127 Final)

### ISSUE THREAD

**Issue by Insearchof18** [onemen/TabMixPlus#306]
First time posting on github (just created my account lol), so apologies if I make any mistakes in reporting this issue! :)

After updating to Firefox 127, I started experiencing the above issue (tested on a system with 126.0.1 with latest TMP and everything's working perfectly). What was happening before the update with Locked tabs was that a single new tab would open with the resulting page and would not steal focus (middle-clicking a link still results in this correct behaviour).

To test, I installed a fresh copy of FF 127 (new profile) on a different machine that didn't have it (no other extensions installed), followed the instructions (https://onemen.github.io/tabmixplus-docs/other/installation/) from scratch to install TMP (tested with both the latest and the dev releases), and using the default TMP settings (without making any changes), I was able to replicate the issue. All tests done on Windows 10 x64 (22H2) systems.

Please let me know if any further info is needed for troubleshooting!

**Comment by onemen** [comment]
thry the latest [dev-build](https://github.com/onemen/TabMixPlus/releases/download/dev-build/tab_mix_plus-dev-build.xpi)

- Any message in the Browser console?
- attach a file with you Tab Mix Plus preferences

**Comment by onemen** [comment]
![tab_opening](https://github.com/onemen/TabMixPlus/assets/3650909/0b597449-70de-41b6-8a64-30335c1769e3)


The issue is with the 'Link' preference above, when you enable it, the issue is gone.
I will investigate more tomorrow.

**Comment by dxzy** [comment]
Same problem,
not open Link Focus/ Lock this tabs→left click link→two tab & steal focus,
middle click→one tab,
if open Link Foucus setup →one tab.

**Comment by onemen** [comment]
This was a regression from commit ba7df31

 Download and install the latest [dev-build](https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/tab_mix_plus-dev-build.xpi) from today
