### ISSUE TITLE
Shotcut key of "Reopens last closed tab"

### ISSUE THREAD

**Issue by MememeOyaji** [onemen/TabMixPlus#309]
The default setting is "Ctrl+Shift+T", it still works Ver.1.21.1.
But I have set "Ctrl+F12", that worked until Ver.1.20.0, it does not work.
I have tried making several shortcuts, some works some does not work.
Regards.

**Comment by onemen** [comment]
- What is your Firefox version?
- What is your operating system?
- attach a file with your Tab Mix Plus preferences.
- Any messages in the Browser console when you try to apply `Ctrl-F12`?

**Comment by MememeOyaji** [comment]
Firefox Version : Firefox 115.12.0 ESR & WaterfoxG 6.0.16
OS : Windows10Pro 22H2
[TMPpref.txt](https://github.com/user-attachments/files/16118646/TMPpref.txt)

No messages appeared when I changed to Ctrl+F12 nor to Ctrl+Shift+T.
I have used TMP for more than 10 years before web extension version, I set "reopens last closed tab" Ctrl+F12 from the beginning (or it was the default setting at that time?).
I noticed the issue yesterday, and tried to change the key to Ctrl+Shift+T then I could reopen the last tab, I changed again to Ctrl+F12 then I could not reopen the closed tab.
Next I installed TMP1.20.0 I found that both shortcut keys.

**Comment by onemen** [comment]
can you check if `Ctrl+F12` work after you restart the window?

**Comment by MememeOyaji** [comment]
Hello,
Now I checked it by Waterfox with new profile installing only TMP1.21.1. (No other addons !)
I only changed the shortcut from Ctrl+Shift+T to Ctrl+F12, I did not change other entries.
The result was same, after restart Waterfox.
After I changed back to Ctrl+Shift+T, I can reopen the closed tab without restart.     2024年7月7日日曜日 20:27:00 JST、onemen ***@***.***>が書いたメール:  
 
 


can you check if Ctrl+F12 work after you restart the window?

**Comment by onemen** [comment]
@ MememeOyaji 

Download this [test build](https://github.com/user-attachments/files/16119338/test-build-1.22.0-20240707.1531.zip), rename it to .xpi and install it.

Report if it solved this issue.

**Comment by MememeOyaji** [comment]
Good !
I made a new profile on Waterfox again, installed the test-build, the shortcut key "Ctrl+F12" works normally.
Thank you !
