### ISSUE TITLE
After browser update TabMixPlus options to change tabbar position (above or below content) are locked.

### ISSUE THREAD

**Issue by Shahius** [onemen/TabMixPlus#310]
Firefox Nightly updated to version 130.0a1 (2024-07-10) (64-bit). 
After that my tab bar moved to top (above content) and the option to switch it back down is locked. 
It reads that this preference is controlled by other extension that apply vertical tabs. But I don't have any tab extension, don't have vertical tabs installed. I temporary disabled all my extensions leaving enabled only TabMixPlus. The problem still exists. 
I suspect they changed something in browser with the 130.0 release. 

![Screenshot_1](https://github.com/onemen/TabMixPlus/assets/107578713/38346716-0fad-4606-b298-03b0694093c6)
![Screenshot_2](https://github.com/onemen/TabMixPlus/assets/107578713/896da8fe-2eb6-4de1-a002-bd7e33d0f3f0)

**Comment by onemen** [comment]
I am currently working on updating Tab Mix Plus to work with the new feature of `vertical tabs` that will be in Firefox.

I hope to load fixed `Development Build` later today

![verticalTbs](https://github.com/onemen/TabMixPlus/assets/3650909/14f210e9-872d-4c6c-b682-449520a832f0)

**Comment by Shahius** [comment]
Oh. Thank you for the update!

**Comment by onemen** [comment]
@Shahius 

New [Development build](https://api.bitbucket.org/2.0/repositories/onemen/tabmixplus-for-firefox/downloads/tab_mix_plus-dev-build.xpi) is out.

Read about the new `Vertical Tabs` in Firefox [here](https://github.com/onemen/TabMixPlus/discussions/311)

**Comment by Shahius** [comment]
So far so good with the development build!
