### ISSUE TITLE
Bug:   Volatile search bar arrow button

### ISSUE THREAD

**Issue by Kalinette** [onemen/TabMixPlus#312]
Hello,

Since Firefox 127.0, the volatile search bar arrow button no longer works.

Everything works fine by disabling TabMixPlus.

THANKS.

![Capture d’écran 2024-07-26 090751](https://github.com/user-attachments/assets/91da9cfd-8c8a-40d4-b3df-e005adf5f297)

**Comment by onemen** [comment]
@Kalinette,

Thank you for reporting about this issue.

Do you see any related message in the browser console after clicking the button?
Please attach a file with your Tab Mix Plus preferences.

**Comment by onemen** [comment]
It was just small typo that apply some changes form Firefox version 129 instead of version 127

Download this [test build](https://github.com/user-attachments/files/16405116/test-build-1.22.0-20240728.2311.zip)
Rename the file extension to `.xpi` and install it
