### ISSUE TITLE
Freeze Tab, Protect Tab and Lock Tab functions are doing nothing and have broken enabling

### ISSUE THREAD

**Issue by Aleksandra0056** [onemen/TabMixPlus#313]
When according to the information I found, the Freeze Tab, Protect Tab and Lock Tab functions did this:

1. Freeze Tab: This function prevents the tab from being refreshed or reloaded.
2. Protect Tab: Protecting a tab with this function prevents it from being closed accidentally.
3. Lock Tab: The lock tab function helps to prevent a tab from being moved.

----------

However, I tried to use these 3 features, but none of them worked. Also, when I enable the Freeze Tab, then the Protect Tab and Lock Tab automatically enable together with the Freeze Tab.

**Comment by onemen** [comment]
Read Tab Mix Plus [documentation](https://onemen.github.io/tabmixplus-docs/help/frozen_tabs/)

**Comment by Aleksandra0056** [comment]
> Read Tab Mix Plus [documentation](https://onemen.github.io/tabmixplus-docs/help/frozen_tabs/)

Ah, I see. But these functions are still doing nothing when clicking at them from Tab context menu.

**Comment by Aleksandra0056** [comment]
Moment, I tried it now and it worked, weird. Maybe I misunderstood the purpose of these functions.
