### ISSUE TITLE
Blinking separator between "Select All" and "Save Page As..." right-click context menu items

### ISSUE THREAD

**Issue by Aleksandra0056** [onemen/TabMixPlus#314]
I noticed this 2 years ago, so I will finally report it here.

I guess, that it has something to do with legacy context menu separators code since TabMixPlus maybe loads this archaic separator (which was lastly in v88.0.0 until Select All was removed as a separator-divided group) but it fails every time due to the absence of the old code which further loads this archaic separator.

Take a look at a video depicting the issue:

https://github.com/user-attachments/assets/f7b7d5f4-c1b5-477a-b22a-1986af75919b

**Comment by onemen** [comment]
Can you attach a file with your Tab mix plus preferences

**Comment by Aleksandra0056** [comment]
Yes.

Here it is:
[TMPpref.txt](https://github.com/user-attachments/files/16522257/TMPpref.txt)

**Comment by onemen** [comment]
I don't see it.

specify your:
- Firefox version
- Tab Mix Plus version
- operating system

**Comment by Aleksandra0056** [comment]
- Firefox v129.0.0
- Tab Mix Plus v1.22.0
- Windows 10 22H2

It isn't appearing only in the new tab, but also in context menus from other pages. The separator appears but instantly disappears. Maybe you have better computer, so you don't see it.

**Comment by onemen** [comment]
Download this [test build](https://github.com/user-attachments/files/16523433/test-build-1.22.1-20240807.1526.zip)

Rename it to `.xpi` and install it.

Report back

**Comment by Aleksandra0056** [comment]
> Download this [test build](https://github.com/user-attachments/files/16523433/test-build-1.22.1-20240807.1526.zip)
> 
> Rename it to `.xpi` and install it.
> 
> Report back

Okay, now the blinking separator completely disappeared after installing the test build.

**Comment by onemen** [comment]
That's how it is work in Firefox. You can see the same without Tab mix plus

**Comment by Aleksandra0056** [comment]
Yes, I know how Firefox and its extensions work. I'm closing this as complete since it's solved.
