### ISSUE TITLE
Bug: "Open Link in New Private Window" no longer works. 

### ISSUE THREAD

**Issue by combat-entropy** [onemen/TabMixPlus#318]
Right clicking on a link and selecting "Open Link in New Private Window" no longer works. 

Running Firefox129 and TabMixPlus 1.22.0 (was previously running 128 without experiencing this issue).

I get the following error in the browser console:
```
Uncaught ReferenceError: win is not defined
    openLinkInPrivateWindow chrome://tabmixplus/content/changecode.js line 222 > eval:2
    <anonymous> chrome://browser/content/browser-context.js:50`
```

I have attached my preferences
[TMPpref.txt](https://github.com/user-attachments/files/16568437/TMPpref.txt)
 if they are needed.
Cheers.

**Comment by onemen** [comment]
Read this
https://github.com/onemen/TabMixPlus/discussions/316

**Comment by combat-entropy** [comment]
My apologies I did not see that, I only searched the issue tracker. Removing,Restarting,Installing,Restarting did not fix my issue. However clicking "clear startup cache" in about:support did.  Marking this as closed.
