### ISSUE TITLE
[Waterfox]Context menu's broken by restoring a session or opening a closed window that was closed on an about: page

### ISSUE THREAD

**Issue by Squall-Leonhart** [onemen/TabMixPlus#319]
When you close the browser or a window on one of these pages (about:memory, about:profiles) on the next opening of the window the context menu is not populated correctly, with TMP text missing, and TMP expandable menu's not expanding.

**Comment by onemen** [comment]
Any messages in the Browser Console?
Attach a file with your Tab mix Preferences
What is you Waterfox version?
Do you see the same issue on clean profile?

**Comment by Squall-Leonhart** [comment]
in the process of trying to narrow down reproduction, i can't get it to show the context menu items properly at all now

1.22

G6-18

1.22


Tabmix ERROR at get hasContentOpener:
TMP_eventListener.onWindowOpen failed
this.browsingContext is null
Stack Trace:
  File "chrome://global/content/elements/browser-custom-element.js", line 687, col 15, in get hasContentOpener
  File "resource:///modules/BrowserUIUtils.jsm", line 39, col 9, in checkEmptyPageOrigin
  File "chrome://browser/content/tabbrowser-tab.js", line 227, col 27, in get isEmpty
  File "chrome://tabmixplus/content/links/userInterface.js", line 396, col 40, in Tabmix.setTabStyle
  File "chrome://tabmixplus/content/tab/tab.js", line 2192, col 16, in updateTabsStyle
  File "chrome://tabmixplus/content/tabmix.js", line 548, col 24, in TMP_EL_onWindowOpen
  File "chrome://tabmixplus/content/tabmix.js", line 547, col 12, in TMP_EL_onWindowOpen
  File "chrome://tabmixplus/content/tabmix.js", line 1189, col 29, in tabmix_initialization_run
  File "chrome://tabmixplus/content/tabmix.js", line 242, col 29, in TMP_EL_init
tabmix.js:1194:18
Uncaught (in promise) TypeError: this.browsingContext is null
    get hasContentOpener chrome://global/content/elements/browser-custom-element.js:687
    checkEmptyPageOrigin resource:///modules/BrowserUIUtils.jsm:39
    get isEmpty chrome://browser/content/tabbrowser-tab.js:227
    setTabStyle chrome://tabmixplus/content/links/userInterface.js:396
    TMP_restoreTabState chrome://tabmixplus/content/links/userInterface.js:357
    onSSWindowRestored chrome://tabmixplus/content/tabmix.js:625
    onSSWindowRestored chrome://tabmixplus/content/tabmix.js:620
browser-custom-element.js:687:15
Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
ReferenceError: getComputedStyle is not defined
    set resource:///modules/StatusBar.sys.mjs line 198 > eval:28
    update chrome://browser/content/tabbrowser.js:7381
    onStatusChange chrome://browser/content/browser.js:5520
    callListeners chrome://browser/content/tabbrowser.js:972
    _callProgressListeners chrome://browser/content/tabbrowser.js:986
    _callProgressListeners chrome://browser/content/tabbrowser.js:6570
    onStatusChange chrome://browser/content/tabbrowser.js:7092
tabbrowser.js:977:23
TypeError: browser.frameLoader is null AsyncTabSwitcher.jsm:274:25
ReferenceError: getComputedStyle is not defined
    set resource:///modules/StatusBar.sys.mjs line 198 > eval:28
    update chrome://browser/content/tabbrowser.js:7381
    _hide chrome://browser/content/browser.js:5722
    update chrome://browser/content/browser.js:5682
    setOverLink chrome://browser/content/browser.js:5085
    onLocationChange chrome://browser/content/browser.js:5279
    callListeners chrome://browser/content/tabbrowser.js:972
    _callProgressListeners chrome://browser/content/tabbrowser.js:986
    _callProgressListeners chrome://browser/content/tabbrowser.js:6570
    onLocationChange chrome://browser/content/tabbrowser.js:7063
tabbrowser.js:977:23
Uncaught ReferenceError: getComputedStyle is not defined
    set resource:///modules/StatusBar.sys.mjs line 198 > eval:28
    update chrome://browser/content/tabbrowser.js:7381
    _timer chrome://browser/content/browser.js:5711
StatusBar.sys.mjs line 198 > eval:28:9
    set resource:///modules/StatusBar.sys.mjs line 198 > eval:28
    update chrome://browser/content/tabbrowser.js:7381
    _timer chrome://browser/content/browser.js:5711
this.window.gBrowserInit is undefined ext-browser.js:1129

>  Do you see the same issue on clean profile?

Sporadically.

[TMPpref.txt](https://github.com/user-attachments/files/16570889/TMPpref.txt)

**Comment by onemen** [comment]
Download this [test build](https://github.com/user-attachments/files/16571665/test-build-1.22.1-20240811.0828.zip)

Rename it to `.xpi` and install it.

Report back

**Comment by Squall-Leonhart** [comment]
That looks to have worked!, great job
