### ISSUE TITLE
right clicking on tab and selecting new tab opens up 2 tabs

### ISSUE THREAD

**Issue by pyrates999** [onemen/TabMixPlus#321]
I am running Firefox 129.0 on x86-64 with TabMixPlus addon version 1.22.0.

When I right click on the currently active tab and click on **New Tab (After This Tab)**, it will then open up 2 new tabs instead of 1 as expected.

Here is my preferences file:

[TMPpref.txt](https://github.com/user-attachments/files/16581750/TMPpref.txt)

And here is the output from browser console:

`TypeError: URL constructor: http://about:newtab is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
URL constructor: http://about:newtab is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
TypeError: URL constructor: http://about:blank is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
URL constructor: http://about:blank is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
TypeError: URL constructor: http://about:blank is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
URL constructor: http://about:blank is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
TypeError: URL constructor: http://about:newtab is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
URL constructor: http://about:newtab is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
TypeError: URL constructor: http://about:newtab is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
URL constructor: http://about:newtab is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
`

But if I go to the File menu and click on New Tab, it only opens one tab as expected.

Here is the output from Browser Console:

`TypeError: URL constructor: http://about:newtab is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
URL constructor: http://about:newtab is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)`

It also seems to be putting **http://** behind the internal url **about:newtab**.

**Comment by onemen** [comment]
Thank you for the report.

I can reproduce the issue, i will work on it tomorrow.

**Comment by pyrates999** [comment]
Ok, that didn't work at first.  So I went to [about:support](about:support) and clicked on **Clear Startup Cache...**.  Then it worked.

Here is the output from Browser Console:

`TypeError: URL constructor: http://about:newtab is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)
URL constructor: http://about:newtab is not a valid URL. [background.js:439:18](moz-extension://6656771d-6779-46b9-982f-f062d768dd02/background.js)`

**Comment by pyrates999** [comment]
This could be another bug to fix where it tries to go to http://about:newtab instead of about:newtab

**Comment by pyrates999** [comment]
Thanks for the fix!

**Comment by onemen** [comment]
I don't see in my console any messages regarding `about:newtab` maybe it is related to another extension your are using
check in your profile for extension with id `6656771d-6779-46b9-982f-f062d768dd02`

**Comment by pyrates999** [comment]
You're right.  This was caused by another add-on I had installed.  Thanks.  Now closing this.
