### ISSUE TITLE
New tab button Location

### ISSUE THREAD

**Issue by banta84** [onemen/TabMixPlus#325]
Hi! After Firefox updating to 130.0 _New tab button_ in multirow mode can be only left or right corner. I try latest development build too, but with same result - now need constantly move cursor from center to far right/left corner. I found this issue https://github.com/onemen/TabMixPlus/issues/322 , so this works as intended?

**Comment by onemen** [comment]
This should fix it.

Download this [test build](https://github.com/user-attachments/files/16922595/test-build-1.22.1-20240908.1736.zip)

Rename it to `.xpi` and install it.

Report back

**Comment by banta84** [comment]
Now works fine! Like old good days =) Thank you!
