### ISSUE TITLE
BUG : multi row doesn't work with last Firefox Developer Portable Edition 131.0b4 and tab mix plus 1.22.0

### ISSUE THREAD

**Issue by fraynaud33** [onemen/TabMixPlus#326]
Hello, 
Thank you for your work, the multi row tab is essential.
I can't succes to have multi row on Firefox Developer Portable 131.0b4 (maybe on 131.0b1 too).
I try with Firefox Portable 129 and I have multi row.
I make a clean and fresh installation of Firefox Developer Portable 131.0b4 (64-bit)  without any extension and the problem is always here.
[TMPpref.txt](https://github.com/user-attachments/files/16934647/TMPpref.txt)
[about-support.txt](https://github.com/user-attachments/files/16934651/about-support.txt)
![image](https://github.com/user-attachments/assets/c21d7f82-6f3d-472b-8cc3-5414bc45a6ba)
![image](https://github.com/user-attachments/assets/e82837d4-c0ad-4aef-b3db-9091be413231)

Edit : I install an "old" Firefox Developer Portable 130.0b1 version and it works, i have multi row.

Any idea what could happen ?
Thank you.

**Comment by onemen** [comment]
Install the latest [development build](https://github.com/onemen/TabMixPlus/releases/download/dev-build/tab_mix_plus-dev-build.xpi)

**Comment by onemen** [comment]
Version [123](https://github.com/onemen/TabMixPlus/releases/tag/v1.23.0) is out

**Comment by fraynaud33** [comment]
It works !
Thank you for the quick fix.
![image](https://github.com/user-attachments/assets/8a9973a3-42f3-4c32-b908-8df000e3d8b5)
