### ISSUE TITLE
Can't close current tab by clicking on close tab button or middle clicking after update from 115.15.0 esr to 128.3.0 esr

### ISSUE THREAD

**Issue by YogSottot** [onemen/TabMixPlus#330]
Firefox 128.3.0 esr (linux 64-bit) 
TMP 1.23.0

I can't close the current tab by clicking on the middle mouse button or control+w
I can middle click to close fine on OTHER tabs just not the current one.

When I disable the TMP, this functionality works.

Attached is my config:
[TMPpref.txt](https://github.com/user-attachments/files/17226864/TMPpref.txt)

**Comment by onemen** [comment]
I can not reproduce it on Windows 11.

do you see any messages in the Browser console?

check if you have the same issue with the latest [dev-build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build)

**Comment by YogSottot** [comment]
The console is empty.
Same problem with dev-build.

**Comment by YogSottot** [comment]
Created a clean profile, installed the extension. The problem did not occur.
Copied all userjs / usercss, problem did not reproduce.
Copied and installed all extensions, problem did not reproduce.

It's puzzling. Don't know what else the problem could be. 
But the problem is obviously local only to me. Closing the issue.

**Comment by onemen** [comment]
Try to clear cache
Open about:support page and click "Clear startup cache…" to force Firefox to load the installed the extension properly

**Comment by YogSottot** [comment]
> Сlearing the cache did not help either.

**Comment by YogSottot** [comment]
Problem was in `user_pref("extensions.tabmix.focusTab", 6);`
I reset it to the default 2 and the problem disappeared.
I can't figure out where exactly this option is configured in the gui.
