### ISSUE TITLE
Pinned tabs are not displayed when multirow tabs and allow pinned tabs to scroll are enabled

### ISSUE THREAD

**Issue by YogSottot** [onemen/TabMixPlus#331]
After update from 115.15.0 esr to 128.3.0 esr
Firefox 128.3.0 esr (linux 64-bit)
TMP 1.23.0

Pinned tabs are not displayed when multirow tabs and allow pinned tabs to scroll are enabled.

![image](https://github.com/user-attachments/assets/eaf36d92-ae35-491d-91d9-67e685f01aa7)

If i disable allow pinned tabs to scroll, the pinned tabs will appear

![image](https://github.com/user-attachments/assets/f5c68bc2-f2b0-44d9-8a84-5380ac3ad763)

If you switch off multirow tabs, the pinned tabs displayed too.

Attached is my config:
[TMPpref.txt](https://github.com/user-attachments/files/17227080/TMPpref.txt)

**Comment by onemen** [comment]
Thank you for the report.

I can reproduce this issue.
I will look into it

**Comment by onemen** [comment]
This should fix it.

Download this [test build](https://github.com/user-attachments/files/17239292/test-build-1.23.1-20241003.0745.zip)

Rename it to `.xpi` and install it.

Report back

**Comment by YogSottot** [comment]
Thank you. This problem has been fixed.
