### ISSUE TITLE
space showing between tabs on 1.24.0 of addon

### ISSUE THREAD

**Issue by pyrates999** [onemen/TabMixPlus#334]
I'm on Firefox 131.0.2.

There is now a space being shown between each tab on it's left and right side:

![image](https://github.com/user-attachments/assets/184f746e-5c46-46c0-b0cf-0d26833d544a)

But not on the top and bottom.

Here is my preferences:

[TMPpref.txt](https://github.com/user-attachments/files/17308196/TMPpref.txt)

This was not happening in 1.23.0.

**Comment by onemen** [comment]
What is you platform?
Are you using special theme or styles?

**Comment by pyrates999** [comment]
My OS is windows 10.  Here is my chrome directory:

[chrome.zip](https://github.com/user-attachments/files/17328269/chrome.zip)

I've configured it so that it looks like it did back in firefox 56, before firefox did any spacing between each tab.

**Comment by onemen** [comment]
I have tested your settings + chrome files on new profile
I did not see any issue

- Download and install latest [Development build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build) 
- Download and install latest [Firefox scripts](https://github.com/xiaoxiaoflood/firefox-scripts)
- Open about:support page and click "Clear startup cache…" to force Firefox to load the installed scripts on the next startup.
- Open the browser console; look for error in your scripts, you may need to update some of your scripts

**Comment by pyrates999** [comment]
Ok, did that from the instructions here: https://github.com/xiaoxiaoflood/firefox-scripts?tab=readme-ov-file

It still looks the same with the space between each tab on the left and right side.

I also found out I enabled this in about:config, **browser.compactmode.show** preference set to **true**.

I did it so that I could enable the firefox 56 theme.

**Comment by onemen** [comment]
test how it look on new profile

**Comment by pyrates999** [comment]
After creating a new profile, and applying the files in chrome to it, it is the same result:

![image](https://github.com/user-attachments/assets/6e197927-59a8-44ed-98bb-9d221f6e5ad0)

Here is the export of tab mix plus preferences along with my chrome directory zipped up:

[chrome.zip](https://github.com/user-attachments/files/17342075/chrome.zip)
[TMPpref.txt](https://github.com/user-attachments/files/17342076/TMPpref.txt)

**Comment by pyrates999** [comment]
I suspect it has to do with the auto fit feature where you automatically resize each tab to fit on its row so there is no empty spaces.  If you could tell me how to disable that, I can verify that is causing it or not.

**Comment by onemen** [comment]
set `new tab button` to be on the right side instead of after tabs

**Comment by pyrates999** [comment]
That didn't work either.

So I disabled the new tab button from not being shown at all.  Then went to **about:support** and clicked on **Clear Startup Cache...**, and that worked:

![image](https://github.com/user-attachments/assets/844732db-ed52-4644-a810-22be11dc86e2)

**Comment by pyrates999** [comment]
This was not needed for version 1.23.0 though.

**Comment by pyrates999** [comment]
I think the new tab button is taking up more space that is needed.

**Comment by pyrates999** [comment]
Ok, If I set tab width minimum and maximum to 110 instead of 120 pixels, then it works.  But I still prefer 120.

**Comment by pyrates999** [comment]
I set the new tab button on the left side and it looks to be quite wide:

![image](https://github.com/user-attachments/assets/0f6fa80f-97a2-4920-8d41-8629163a919c)

**Comment by pyrates999** [comment]
Downgrading back to 1.23.0 fixes it.

**Comment by pyrates999** [comment]
I think I found where it's different.  In 1.23.0, this is the right side of the tab bar:

![image](https://github.com/user-attachments/assets/abc2cc62-8532-4816-b68d-7a1ecf894eff)

In 1.24.0, it is thinner on the right side of the tab bar:

![image](https://github.com/user-attachments/assets/19447739-e727-44fd-8043-828ceed487b7)

**Comment by onemen** [comment]
I will try to look into it during the weekend...

**Comment by onemen** [comment]
OK,
the issue was incompatibility between you custom userChrome.css 

Add this rue after the rule for `.tabbrowser-tab .tab-background {`
```css
#tabbrowser-tabs[orient="horizontal"][multibar]:not([widthFitTitle]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[fadein]:not([pinned]) .tab-background {
  max-width: var(--tabmix-overflow-max-width, var(--tab-min-width)) !important;
}
```

**Comment by pyrates999** [comment]
Thank you very much!  That fixes it :)

**Comment by pyrates999** [comment]
I added this to my chrome\userChrome.css

`#tabbrowser-tabs[orient="horizontal"][multibar]:not([widthFitTitle]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[fadein]:not([pinned]) .tab-background {
  max-width: var(--tabmix-overflow-max-width, var(--tab-min-width)) !important;
}`

**Comment by onemen** [comment]
@pyrates999 

I am planing to add option to turn this feature off, and also for users that set the same min and max width, i will adjust both min-width and max-width to a value the fit window width also fro the first row, to prevent the change in tab width when tabs moves to 2nd row.
I will let you know if you need to update your `userChrome.css`, when this change lands in the development build

**Comment by pyrates999** [comment]
Thank you very much!

**Comment by onemen** [comment]
Download and install [Development Build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build)

![image](https://github.com/user-attachments/assets/40cbe731-8343-4070-a48c-22903a550e4e)

update your `userChrome.css`
```css
#tabbrowser-tabs[orient="horizontal"][multibar]:not([widthFitTitle]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[fadein]:not([pinned]) .tab-background {
  max-width: var(--tabmix-tab-overflow-width, var(--tab-min-width)) !important;
}
```

I didn't change the width for when there is only one row since everything move anyhow when the new tab and new tab button jump to the 2nd line

**Comment by pyrates999** [comment]
That works.  How do I adjust the number of pixels wide that the new tab button is though?

**Comment by pyrates999** [comment]
Oh another thing I noticed is that there is a List All Tabs button in the tab bar that Tab Mix Plus seems to add.  And if I right click on the area and select customize toolbar..., there is also a List All Tabs button that I could move to the tab bar.

This is the one that tab mix plus seems to include that I then can't remove:

![image](https://github.com/user-attachments/assets/9e7e3a52-6e5e-43af-9bc4-a10b80be7653)

And here is the List All Tabs button in the customize toolbar:

![image](https://github.com/user-attachments/assets/51a10243-3f5e-4f6a-a665-1cb7bd2afc15)

Both do the same thing.

**Comment by pyrates999** [comment]
Oh I can hide it if I set this in about:config to false:

**browser.tabs.tabmanager.enabled**

**Comment by pyrates999** [comment]
And something that has been annoying me.  If I open up tab mix plus options, and I am already in Display with Tab Bar selected.  I have to click on Tab twice before it will be selected.

**Comment by pyrates999** [comment]
So now that is done.  If I have 3 buttons in the tab bar on the right side, the tabs width will be wider.  If I only have 2 buttons in the tab bar on the right side, the tabs width will be set to what I have them in userChrome.css and in tab mix plus options.

Examples:

1. arrows, new tab button -> tabs width will be set to what I have them in userChrome.css and in tab mix plus options.
2. arrows, new tab button, list all tabs button -> tabs width will be increased from 120 pixels to 128 pixels.

So since I can't remove the arrows, I include the new tab button, but not the list all tabs button on the right side for now.

**Comment by onemen** [comment]
1. when you turn off  `Tab width fills rows on overflow` `--tabmix-tab-overflow-width` is undefined so ` max-width: var(--tabmix-tab-overflow-width, var(--tab-min-width)` will set max-width to be the same as min-width

2.  List All Tabs button (red button in the image above), is build in from Firefox, you can not remove it, so we have an option to hide it in Display > Tab bar. Setting `browser.tabs.tabmanager.enabled` to `false` do the same

3. this is a bug that i need to fix
> And something that has been annoying me. If I open up tab mix plus options, and I am already in Display with Tab Bar selected. I have to click on Tab twice before it will be selected.

**Comment by pyrates999** [comment]
1. I have my max-width value set to 120, same as my min-width value.  So it increasing it to 128 should be a bug.

![image](https://github.com/user-attachments/assets/91693db4-5aed-4ed0-af30-5261b0b9e9e2)

2. Ah thank you.  I didn't know where that was set.
3. Ok, thank you.

**Comment by onemen** [comment]
when you enable `Tab width fills rows on overflow` Tab mix will increase tab min-width to fill the row.

**Comment by pyrates999** [comment]
I've disabled that.  Now each tab stays at 120 pixels wide.

This is what it looks like when I only have 2 items on the left side:

![image](https://github.com/user-attachments/assets/e3fe9418-e420-4252-81e5-57cd35c91daf)

But when I have 3 items on the left side, this is what it looks like:

![image](https://github.com/user-attachments/assets/fa0583ca-a5fe-4484-8a0a-199bc3011fc7)

That is a lot of extra space.  And I haven't added any blank spaces.

How do I remove this part of it?

![image](https://github.com/user-attachments/assets/3e4ee96c-0a9b-48b5-8c6a-cc845a9cf9d8)

**Comment by onemen** [comment]
![image](https://github.com/user-attachments/assets/2607c884-308f-4edc-b2c5-d36d11e11594)
This is how ti look for me when i enable `Tab width fills rows on overflow`

**Comment by pyrates999** [comment]
That image has 4 items on the side instead of 3.

Are your tabs 120 pixels wide?

If I add this to my userChrome.css as you said to:

```
#tabbrowser-tabs[orient="horizontal"][multibar]:not([widthFitTitle]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[fadein]:not([pinned]) .tab-background {
  max-width: var(--tabmix-tab-overflow-width, var(--tab-min-width)) !important;
}
```

It increases each tab to 128 pixels.  I just want to remove the extra space that is added when 3 items are on the right side.

**Comment by pyrates999** [comment]
This is with `Tab width fills rows on overflow` disabled.  And I did not add this to `userChrome.css`:

`#tabbrowser-tabs[orient="horizontal"][multibar]:not([widthFitTitle]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[fadein]:not([pinned]) .tab-background {
  max-width: var(--tabmix-tab-overflow-width, var(--tab-min-width)) !important;
  //max-width: 128px !important;
}`

I think the extra space is added automatically when there are 3 or more items on the right side.  You add room for 3 more.  Which is for these options:
* new tab button
* close tab button
* all tabs button

And when all are ticked, there is room for one more on the right side:

![image](https://github.com/user-attachments/assets/59bb0cfa-da13-4e28-aa0b-e16fef4554a7)

If none are ticked, and I tick **Extra spaces on both side**, then it adds 4 extra spaces.

![image](https://github.com/user-attachments/assets/31282ed0-628d-49e8-8c6a-a47dc7be6e94)

If I tick only one of these options with the list all tabs button from customize toolbar...:
* new tab button
* close tab button
* all tabs button

There are room for 3 additional items:

![image](https://github.com/user-attachments/assets/3e3ae1a6-d765-4de6-8961-fefe73bffa79)

But then if I tick **Extra spaces on both side**, the room for 3 additional items changes to a slightly smaller value:

![image](https://github.com/user-attachments/assets/3599085c-ed3b-44b3-808f-f946d5ff3489)

**Comment by pyrates999** [comment]
So to fix this, when there are 3 items, allocate 3 spaces.  When there are 4 items, allocate 4 spaces, etc.

I see for when there are 1 or 2, the total space allocated is for 2 items.  Hence why 2 items doesn't have any extra space added to it.

You can see it has allocated space for 2 items here when there is 1 or 2 items:

![image](https://github.com/user-attachments/assets/be4394e1-aa4e-4854-8eda-a1f2e3212b5b)
![image](https://github.com/user-attachments/assets/a9b97e47-ccbd-4ff7-b951-2cfea6887d08)

**Comment by pyrates999** [comment]
I'm not sure what the option **Extra spaces on both sides** is supposed to do here exactly.

**Comment by pyrates999** [comment]
If I disable tab mix plus, the sidebar now fits 3 items without adding extra spaces to it:

![image](https://github.com/user-attachments/assets/2de9bf6a-c85a-44f4-aa2e-a8a0c817f0f7)

**Comment by pyrates999** [comment]
Alright, I found out it was because the tab would not fit.  So here's the changes I made to userChrome.css:

`.tabbrowser-tab .tab-background {
  box-shadow: 0 0 0px 1px color-mix(in srgb, currentColor 40%, transparent), 0 10px 10px rgba(255,255,255,0.2) inset !important;
  background-image: var(--toolbar-non-lwt-bgimage) !important;
  border-radius: 3px 3px 0 0 !important;
  margin-bottom: 0px !important;
  max-height: 28px !important;
  max-width: 117px !important;
}

:root {
  --tab-min-height: 28px !important;
  --tab-max-height: 28px !important;
  --tab-min-width: 117px !important;
  --tab-max-width: 117px !important;
  --arrowpanel-menuitem-padding: 4px 8px !important;
}`

And here are the settings in tab mix plus:

![image](https://github.com/user-attachments/assets/22084aee-0998-4ebb-9653-2b4d869ef591)
![image](https://github.com/user-attachments/assets/e55d2210-ffa7-49d9-9028-f4e21978b79a)

**Comment by onemen** [comment]
did you try to remove all width related rules from your `userChrome.css`
Tab mix update the value for width according to your preferences

```diff
.tabbrowser-tab .tab-background {
  box-shadow: 0 0 0px 1px color-mix(in srgb, currentColor 40%, transparent), 0 10px 10px rgba(255,255,255,0.2) inset !important;
  background-image: var(--toolbar-non-lwt-bgimage) !important;
  border-radius: 3px 3px 0 0 !important;
  margin-bottom: 0px !important;
  max-height: 28px !important;
-  max-width: 117px !important;
}

:root {
  --tab-min-height: 28px !important;
  --tab-max-height: 28px !important;
-  --tab-min-width: 117px !important;
-  --tab-max-width: 117px !important;
  --arrowpanel-menuitem-padding: 4px 8px !important;
}
```

**Comment by pyrates999** [comment]
Oh, I will try that then!

**Comment by pyrates999** [comment]
Oh and I also realized that each item on the right side of the tab bar is 30 pixels wide.  So that's how I was also able to calculate this.

**Comment by pyrates999** [comment]
Ok, now it is even better.  I added this back into userChrome.css:

```
#tabbrowser-tabs[orient="horizontal"][multibar]:not([widthFitTitle]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[fadein]:not([pinned]) .tab-background {
  max-width: var(--tabmix-tab-overflow-width, var(--tab-min-width)) !important;
}
```

And enabled `Tab width fills rows on overflow` enabled.  Now there is no more empty space on the right side, and the tab order and location of each tab is relatively the same.
