### ISSUE TITLE
FF 131 scrolling tab bar impossible

### ISSUE THREAD

**Issue by Gordon-Dry** [onemen/TabMixPlus#335]
FF 131.0 broke a lot of stuff.

**Comment by pyrates999** [comment]
Is it firefox 131.0.2?  Because that was just released.

And what do you mean by scrolling tab bar impossible?

**Comment by onemen** [comment]
Try the latest [Development Build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build)

Download and install it

Report back

**Comment by srjjgm** [comment]
There is a bug that I think is from Firefox 131.
If I enable "flexible tabs" and the tab bar is "scrollable with left and right buttons", the tab scroll buttons only appear after many tabs are open, and not immediately when the window size is exceeded.
This happens with Firefox 131.0.2 and Tab Mix 1.23 or 1.24.

**Comment by onemen** [comment]
post a file with you Tab Mix preferences

**Comment by srjjgm** [comment]
[TMPpref.txt](https://github.com/user-attachments/files/17347826/TMPpref.txt)

**Comment by Gordon-Dry** [comment]
> Is it firefox 131.0.2? Because that was just released.
> 
> And what do you mean by scrolling tab bar impossible?

Hovering the cursor over the tab bar and using the mouse wherel to scroll horizontally through them, smoothly (not tab-wise).
This stopped working with FF 131.x

**Comment by onemen** [comment]
@Gordon-Dry 
Can you post your Tab mix preferences?

**Comment by JustGibberish** [comment]
Same here, so just adding another data point. With tmp (last release version + the 2 dev builds linked above) on vanilla ff 131, scrolling the tab bar ceased to work entirely: Mouse wheel doesn't work and the scroll buttons are gone. Look and behaviour in that regard are the same no matter whether tmp is set to

- (only) wheel scroll or
- (also) show scroll buttons on the right side or
- on either side.

With this, it can also happen that the active tab is out of view, which feels super weird :D

Only multi-row tab bar still seems to works.

**Comment by onemen** [comment]
Thank your for the report

I can reproduce this issue.

I look like that it only happens when using single row of tabs and 'Tab width fits tab title' is off.

Can any of you verify this?

**Comment by Gordon-Dry** [comment]
I got these settings:
[TMPpref.txt](https://github.com/user-attachments/files/17350059/TMPpref.txt)

**Comment by srjjgm** [comment]
> I look like that it only happens when using single row of tabs and 'Tab width fits tab title' is off.
> 
> Can any of you verify this?

You can test it. Disable TMP or just the "flexible tabs" option and apply the following CSS:

#tabbrowser-tabs[orient="horizontal"] .tabbrowser-tab:not([pinned]) {
flex: 0 0 auto !important;
}

The tab scroll buttons will not appear.
This only happens, of course, with a single row of tabs.

**Comment by onemen** [comment]
I will have to find different way to implement `Tab width fits tab title`

@117649, do you have time to look into this issue. for some reason setting `flex: 0 0 auto !important;` on tab interfere with the parent container width calculation

**Comment by onemen** [comment]
This test build should fix this issue

Download this [test-build](https://github.com/user-attachments/files/17354729/test-build-1.24.1-20241013.0957.zip)

Rename it to `.xpi`and install it.

Report back

**Comment by onemen** [comment]
@srjjgm 

can you test it with `width: max-content`
```css
#tabbrowser-tabs[orient="horizontal"] .tabbrowser-tab:not([pinned]) {
  flex: 0 0 auto !important;
  width: max-content;
}
```

**Comment by srjjgm** [comment]
This test build fixed the issue. I think you fixed a bug in Firefox 131, because if I disable TMP and use only CSS (this code you suggested is an example), it doesn't work well.
I tried everything with CSS and nothing worked.

I used this code to make the tabs have variable width according to the title, setting the minimum and maximum width:

.tabbrowser-tab:not([pinned]) {flex: none !important;}

But this code didn't work in version 131, because the tab scroll buttons didn't appear.
Thanks!

**Comment by onemen** [comment]
@srjjgm 

did you test this without Tab mix
```css
#tabbrowser-tabs[orient="horizontal"] .tabbrowser-tab:not([pinned]) {
  flex: 0 0 auto !important;
  width: max-content;
}
```

**Comment by srjjgm** [comment]
You're right, it works without Tab Mix.
But what worked best here was enabling the "flexible tabs" option in Tab Mix, with the new test build.

**Comment by onemen** [comment]
@srjjgm 

Test this [test-build](https://github.com/user-attachments/files/17356693/test-build-1.24.1-20241013.2126.zip)

Rename it to `.xpi` and install it.

```diff
#tabbrowser-tabs[orient="horizontal"][widthFitTitle] > #tabbrowser-arrowscrollbox > .tabbrowser-tab:not([pinned]) {
   flex: 0 0 auto !important;
-  width: auto !important;
+  width: max-content !important;
}
```

In this test build I only changed one line

Report back

**Comment by srjjgm** [comment]
In my tests, the previous test build worked better.
In the latter, when resizing the window, scrolling the tab bar does not show all the tabs; you have to click the scroll buttons.

**Comment by pyrates999** [comment]
does the tabs width change size when this happens?

**Comment by onemen** [comment]
> In my tests, the previous test build worked better. In the latter, when resizing the window, scrolling the tab bar does not show all the tabs; you have to click the scroll buttons.

OK.

I think I will use the first [test build](https://github.com/user-attachments/files/17354729/test-build-1.24.1-20241013.0957.zip) 

I would like to here reports from other testers before i push it to the repository.

**Comment by Gordon-Dry** [comment]
> I think I will use the first [test build](https://github.com/user-attachments/files/17354729/test-build-1.24.1-20241013.0957.zip)

I only tested this one - without any CSS fiddling - and it solved my issue.

**Comment by srjjgm** [comment]
> I would like to here reports from other testers before i push it to the repository.

Unfortunately, few people do this.
I would like to thank you for your dedication to Tab Mix Plus over the years.
I can't imagine Firefox without TMP.

**Comment by srjjgm** [comment]
> does the tabs width change size when this happens?

No, it doesn't change, but Firefox apparently has more difficulty calculating how much space all the open tabs are taking up in the tab bar.

**Comment by JustGibberish** [comment]
> I think I will use the first [test build](https://github.com/user-attachments/files/17354729/test-build-1.24.1-20241013.0957.zip)
> 
> I would like to here reports from other testers before i push it to the repository.

Installed this today and everything seems to work as it should. Scroll buttons are back, too. No issue with tab sizing either (both fixed and variable width work).
