### ISSUE TITLE
Some Item text Missing in Right-cick Menu on Page issue

### ISSUE THREAD

**Issue by nanisise** [onemen/TabMixPlus#339]
test environment:
Windows 10
Firefox 128 ESR Language: zh-TW
Tab Mix Plus v1.24.0

After updating Tab Mix Plus from 1.23 to 1.24 with Firefox 128 ESR, Some Item text Missing in Right-cick Menu on Page, as following picture:
![未命名](https://github.com/user-attachments/assets/28a63617-b51e-4f4c-96ef-680e3eeeae38)

My Firefox Language is **zh-TW**, so I think the missing Item Text is "**Recover closed Page**", and maybe it is only happened in  Language zh-TW.

**Comment by onemen** [comment]
I have just installed Firefox ESR 128 [Chinese (Traditional) - 正體中文 (繁體)](https://www.mozilla.org/en-US/firefox/all/desktop-esr/win64/zh-TW/).

I don't see any issue, when using my Tab mix preferences on Windows 11

- Attach a file with your Tab Mix preferences.
- Do you see any messages in the Browser console when you start Firefox

**Comment by nanisise** [comment]
Hi, after I Clear startup cache, it works...well, that's wierd. Thanks.
