### ISSUE TITLE
TMP emptied 'Close Multiple Tabs' sub menu 

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#34]
Before:
![image](https://user-images.githubusercontent.com/8281345/106854896-0f9f8580-66f7-11eb-91ab-19e4fae4813e.png)
After:
![image](https://user-images.githubusercontent.com/8281345/106854916-1928ed80-66f7-11eb-867b-96c4ae15fb4a.png)

I don't recall seeing this in earlier commits. Gonna check recent commits to see If anything related can be find.

**Comment by onemen** [comment]
Yes ```TabmixContext.buildTabContextMenu``` need update
- add preference to all new menu items that was added to Firefox since version 56 (55 ?).
- update reordering in ```buildTabContextMenu```.
- add preferences to group related menu items in sub-menu, Firefox already have one for close, we can add sub menu for reload.
- more ...

its in my todo list

**Comment by onemen** [comment]
one more issue regarding tab context menu, many labels are missing when tab context menu are triggeres for the first time from allTabs panle

![image](https://user-images.githubusercontent.com/3650909/106925759-10e1aa00-6719-11eb-8f17-0ea968025812.png)

**Comment by 117649** [comment]
> one more issue regarding tab context menu, many labels are missing when tab context menu are triggeres for the first time from allTabs panle
> 
> ![image](https://user-images.githubusercontent.com/3650909/106925759-10e1aa00-6719-11eb-8f17-0ea968025812.png)

I only ever see this while enabling TMP and keep a context menu opened earlier.

**Comment by 117649** [comment]
![image](https://user-images.githubusercontent.com/8281345/107234920-20d1f480-6a5f-11eb-89c6-dc095cb5c81b.png)
Its looks like there is some kind of lazy load mechanic for the l10n items that delay the loading of the text until the cursor first entering tab container area and Mozilla just forget that all tabs button is just outside tab container.
![image](https://user-images.githubusercontent.com/8281345/107234931-23cce500-6a5f-11eb-9456-36731a29ddfc.png)

**Comment by onemen** [comment]
Maybe it related to [Bug 1691553](https://bugzilla.mozilla.org/show_bug.cgi?id=1691553)

**Comment by onemen** [comment]
Fixed by 10847c11bdff674925d93592080c5187a298cdfd
