### ISSUE TITLE
Auto Refresh Tab is not work at Firefox 128.3.0 ESR issue

### ISSUE THREAD

**Issue by nanisise** [onemen/TabMixPlus#340]
test environment:
Windows 10
Firefox 128.3.0 ESR
Tab Mix Plus v1.24.0

Hi, After tested,  Auto Refresh Tab is not work  at Firefox 128.3.0 ESR、128.3.1 ESR.
But at Firefox 128.2.0 ESR, It works normally.

I don't see any error messages in the Browser console.

By the way, I also tested Tab Mix Plus v1.23.0, it has the same issue.

**Comment by pyrates999** [comment]
what if you disable tab mix plus?  does auto refresh then work?

**Comment by onemen** [comment]
Do you mean to `Reload Tab Every...`?

Attach a file with your Tab Mix preferences

**Comment by nanisise** [comment]
Yes, I Mean to `Reload Tab Every...`, it not work at Firefox 128.3.0 ESR

This is my preferences:
[TMPpref.txt](https://github.com/user-attachments/files/17339406/TMPpref.txt)

**Comment by onemen** [comment]
Download and install [Development Build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build)

Report back.

**Comment by nanisise** [comment]
After tested Development Build at 128.3.0 ESR, It works normally, thanks.
