### ISSUE TITLE
Floorp v11.19.1 - Auto tab reload

### ISSUE THREAD

**Issue by theLittlePrinceAD** [onemen/TabMixPlus#342]
I hope I am wrong, but at my side having latest FF and Floorp, as well as latest TMP - since the last 1-2 updates of TMP the function "Tab reloading" does not work anymore.

**Comment by pyrates999** [comment]
try the dev build here: https://github.com/onemen/TabMixPlus/releases

if that doesn't work, try the build here: https://github.com/onemen/TabMixPlus/issues/340

I'm not sure which one is newer.

**Comment by theLittlePrinceAD** [comment]
> try the dev build here: https://github.com/onemen/TabMixPlus/releases
> 
> if that doesn't work, try the build here: #340
> 
> I'm not sure which one is newer.

Thank you for the answer and advice.
Actually both stated by you versions are one and the same.
In Firefox 128.3.1 ESR - TMP IS working!
In Floorp-win64.installer v11.19.1 - TMP is NOT working!

**Comment by onemen** [comment]
@theLittlePrinceAD

Thank you for reporting about this issue.

Attach a file with you Tab mix preferences

Do you see any messages in the Browser console when you start `Floorp`

**Comment by theLittlePrinceAD** [comment]
> @theLittlePrinceAD
> 
> Thank you for reporting about this issue.
> 
> Attach a file with you Tab mix preferences
> 
[TMPpref.txt](https://github.com/user-attachments/files/17366201/TMPpref.txt)

> Do you see any messages in the Browser console when you start `Floorp`
No - there is now message in Browser console when starting Floorp.

**Comment by onemen** [comment]
What is you Floorp version?

**Comment by theLittlePrinceAD** [comment]
> What is you Floorp version?

floorp-win64.installer.exe -  v11.19.1.

**Comment by onemen** [comment]
> > What is you Floorp version?
> 
> floorp-win64.installer.exe - v11.19.1.

Since Floorp v11.19.1 is a modified version of Firefox 128, Tab mix does not work properly on this version.

**Comment by theLittlePrinceAD** [comment]
Its a pity, bu we understand.
Thank you!

**Comment by theLittlePrinceAD** [comment]
Thank you for your passion in your work!
- installed from file- restarted- 2 times switched off and on auto reload tab (1 min)

Unfortunately it does not auto-reload @Floorp.


    On Monday, October 21, 2024 at 02:14:54 PM GMT+3, onemen ***@***.***> wrote:  
 
 


This test build should fix compatibility issues between Tab Mix and Floorp

Download this test-build

Rename it to .xpiand install it.

Report back

**Comment by onemen** [comment]
This one should work

Download this [test-build](https://github.com/user-attachments/files/17461727/test-build-1.24.1-20241021.1637.zip)

Rename it to `.xpi` and install it.

Open about:support page and click "Clear startup cache…" to force Firefox to load the installed version.

Report back

**Comment by theLittlePrinceAD** [comment]
You are GREAT!Perfectly working!
Also - if I set to autoreload, close Floor and start it again - the autoreload works again without having to set it again.
This version is working in FF also.

Thank you! Thank you! Thank you! Thank you! Thank you! Thank you!


    On Monday, October 21, 2024 at 04:41:16 PM GMT+3, onemen ***@***.***> wrote:  
 
 


This one should work

Download this test-build

Rename it to .xpi and install it.

Open about:support page and click "Clear startup cache…" to force Firefox to load the installed version.

Report back
