### ISSUE TITLE
Missing texts

### ISSUE THREAD

**Issue by dwd1** [onemen/TabMixPlus#343]
Hi, after the latest update (1.24.0) I have missing text fields if I right click on a tab. Latest dev build does this too.
![image](https://github.com/user-attachments/assets/818dff7c-b68c-44a3-b859-31a109a57a3f)

**Comment by onemen** [comment]
Open about:support page and click "Clear startup cache…" to force Firefox to load the new version

**Comment by dwd1** [comment]
This solved the problem. Thank you very much for your quick reply and many years of work!
