### ISSUE TITLE
tab width is completely broken

### ISSUE THREAD

**Issue by purple512** [onemen/TabMixPlus#349]
so I can't use 1.24.0 because the tab widths with multi-row function is completely broken.

I was using 1.23.0, but then I upgraded to Fx 132 and now dragging tabs is completely broken.

So I'm screwed, I just can't use Tab Mix Plus now. What am I supposed to do? I need fixed width tabs to work. that is, I set min width = max width and that means all tabs should be the same size, no variation, no nonsense about filling out empty rows or whatever. Just fixed width. why's is it so hard?

**Comment by pyrates999** [comment]
install the dev build: https://github.com/onemen/TabMixPlus/releases/tag/dev-build

**Comment by onemen** [comment]
You can use Tab mix  [dev-build](https://github.com/onemen/TabMixPlus/releases/download/dev-build/tab_mix_plus-dev-build.xpi) with any version form 115 ESR to the latest Nightly

**Comment by pyrates999** [comment]
A dev build doesn't mean it's only for the dev version of firefox.
