### ISSUE TITLE
My Firefox Developer Edition 87.0b5 is not loading bootstrap addons right

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#35]
I'm trying use multiple bootstrap addons and found that browser startup have a big chance been interrupt and hangs especially when having more than one addons enabled and restore a session. (most of the UI are loaded but not the tabs of restored session, tool bar button's menu, booksmark bar items)
I'm using script loader for addons.
And Tab Groups just not been loaded while browser start.
Are you seeing any of this?

Addons:
[roomybookmarksredux](https://github.com/p1usminus/roomybookmarksredux/commit/70bd876dd2065d529e669b9a71da3e87f91e3205)
[TMP](https://github.com/onemen/TabMixPlus/tree/rewrite/main)
[Tab-Groups](https://github.com/117649/Tab-Groups)

**Comment by 117649** [comment]
Roomy + TMP seems to be the reason.

**Comment by 117649** [comment]
My suspicion is something may be just loading sequence triggers something in TMP that in turn lock up session restore and in turn blocking further startup of the browser.

**Comment by onemen** [comment]
There is uncaught error in gBrowserInit._delayedStartup that prevent the function to notify "browser-delayed-startup-finished"

SessionStore have observer that wait to be notified about "browser-delayed-startup-finished" before it restore last session.

I need to investigate more to find what causing this error

**Comment by 117649** [comment]
Thanks for investigate this.

**Comment by onemen** [comment]
Fixed by https://github.com/onemen/TabMixPlus/commit/19bdd1b55b41ab935165cd7c3fc98e19147d0f55

When more extensions are installed our startup code may run later.
In this case ```Tabmix.beforeBrowserInitOnLoad``` run after ```MozAfterPaint``` was fired but before ```gBrowserInit._delayedStartup``` finished.
Since we check only for ```gBrowserInit.delayedStartupFinished``` our old code generated numerous calls to ```gBrowserInit._delayedStartup```
