### ISSUE TITLE
Can't download 

### ISSUE THREAD

**Issue by Jayinem** [onemen/TabMixPlus#350]
Followed all of the steps in the link here but then couldn't download it, can't download it on github either. Just does nothing when I click on it. 

https://onemen.github.io/tabmixplus-docs/other/installation/

**Comment by Jayinem** [comment]
Nevermind I just realized I have to save the .xpi to my computer.

**Comment by pyrates999** [comment]
This should have been in discussions I think as it's not a bug in the xpi itself.
