### ISSUE TITLE
Cannot Drag Tab for Relocation

### ISSUE THREAD

**Issue by Furionsama** [onemen/TabMixPlus#352]
As title said, I would like to report the bug that happened with me.
I just realized that I cannot drag the tab to change the sequence, and I have no idea since when.

Tested for both development build and stable build, the result is the same.
If i disable or uninstall Tab Mix Plus, the tab can be dragged (normal).

Currently I am using LibreWolf 132.0-1 with Tab Mix Plus development build (1.24.1-20241102.0714).

Please help.

Thank you.

**Comment by pyrates999** [comment]
can you export your tab mix plus preferences and upload it here?

**Comment by onemen** [comment]
I don't see any issue when testing the development build on Firefox 132.0.2

Open `about:support` page and click "Clear startup cache…" to force Firefox to load the development build the next startup.

if the problem persist:
 - attach a file with your Tab Mix Plus preferences.
 - report about any message you see in the browser console when you drag tabs around.

**Comment by 117649** [comment]
Exactly the thing happens on ff 133b https://bugzilla.mozilla.org/show_bug.cgi?id=1925312
You sure the version you're on?

**Comment by onemen** [comment]
@117649 

maybe the issue related to tab group

**Comment by Furionsama** [comment]
> I don't see any issue when testing the development build on Firefox 132.0.2
> 
> Open `about:support` page and click "Clear startup cache…" to force Firefox to load the development build the next startup.
> 
> if the problem persist:
> 
>     * attach a file with your Tab Mix Plus preferences.
> 
>     * report about any message you see in the browser console when you drag tabs around.

Thank you @onemen ..
After I clear the startup cache, the tab can be dragged.

But now comes new issue, that whenever I type new address or some text in address bar, it supposed to open in new tab, but it opened in the current tab instead.
I have tried to import my previous preference file, but still the same.

Please help.

[TMPpref.txt](https://github.com/user-attachments/files/17625457/TMPpref.txt)
![241105 08_01_14 - Tab Mix Plus Options](https://github.com/user-attachments/assets/abf1554c-4143-4944-9bad-69f815913e50)

**Comment by Furionsama** [comment]
Thank you all for your help and support..
Since there is a new issue, I would like to close this ticket, and open new ticket instead..

New ticket can be found on #354
