### ISSUE TITLE
New Link Cannot Open in New Tab

### ISSUE THREAD

**Issue by Furionsama** [onemen/TabMixPlus#354]
Thank you @onemen for the suggestion in ticket [#352](https://github.com/onemen/TabMixPlus/issues/352)
After I cleared the startup cache, the tab can be dragged.

But now comes new issue, that whenever I type new address or some text in address bar, it supposed to open in new tab, but it opened in the current tab instead.
I have tried to import my previous preference file, but still the same.

Please help.
[TMPpref.txt](https://github.com/user-attachments/files/17626732/TMPpref.txt)
![241105 08_01_14 - Tab Mix Plus Options](https://github.com/user-attachments/assets/5fdd44af-d88a-4ff1-8540-8377a16650d0)
![241105 11_28_22 - Tab Mix Plus Options](https://github.com/user-attachments/assets/130f7879-c7c5-4b94-85c5-7c3ff8b75e9e)

**Comment by onemen** [comment]
Download this [test build](https://github.com/user-attachments/files/17631012/test-build-1.24.1-20241105.1236.zip)

Rename it to `.xpi` and install it.

Report back

**Comment by Furionsama** [comment]
> Download this [test build](https://github.com/user-attachments/files/17631012/test-build-1.24.1-20241105.1236.zip)
> 
> Rename it to `.xpi` and install it.
> 
> Report back

Sir @onemen, it works!
Thank you very much.

Shall I close this ticket?
