### ISSUE TITLE
Pinned Tabs Width now same as Normal Tabs

### ISSUE THREAD

**Issue by noto10** [onemen/TabMixPlus#355]
After updating Firefox Dev Build to 133, Pinned Tabs now appear to be the same width as normal tabs using latest TabMixPlus dev build 1.24.1-20241105.1330.

**Comment by onemen** [comment]
![image](https://github.com/user-attachments/assets/e8779ad3-9d9e-429f-a647-a2c7a3fbc7c9)

I don't see this issue on my Windows 11 with Firefox 133

do you have any costumes styles?

 Open `about:support` page and click "Clear startup cache…" to force Firefox to load the latest installed `Tab Mix Plus` on the next startup
