### ISSUE TITLE
BUG: TabMixPlus v1.25 [nov. 9th] Breaks Multi-row support

### ISSUE THREAD

**Issue by Wontell** [onemen/TabMixPlus#357]
TabMixPlus v1.25 [nov. 9th] Breaks Multi-Row support
Rolling back to previous version fixed the issue

Solutions that I tried: Updating fx-folder and utils to latest version, didnt helped.

FireFox 132.0.1 64bit
Simple Tab Groups Plugin

**Comment by pyrates999** [comment]
go to: about:support

click on `Clear startup cache...` button.

**Comment by pyrates999** [comment]
I just had to do this and it fixed it.

**Comment by Wontell** [comment]
> about:support
> 
> click on `Clear startup cache...`

I can confirm that this worked

**Comment by Wontell** [comment]
Solution:

1] about:support
2] Clear startup cache...
