### ISSUE TITLE
Rows stopped working after upgrading

### ISSUE THREAD

**Issue by carmenshu78** [onemen/TabMixPlus#359]
### Discussed in https://github.com/onemen/TabMixPlus/discussions/358

<div type='discussions-op-text'>

<sup>Originally posted by **carmenshu78** November  9, 2024</sup>
Hi Everyone! After upgrading to 1.25 version, I can't see my tabs in rows like before. Is anyone experiencing the same?</div>

**Comment by rbullrich** [comment]
Hi there! Same issue here.And I use the feature a lot!. 

I´m attaching Firefox troubleshooting and TBM Preferences.. 
[Firefox Troubleshooting Info.txt](https://github.com/user-attachments/files/17689047/Firefox.Troubleshooting.Info.txt)
[TMPpref.txt](https://github.com/user-attachments/files/17689048/TMPpref.txt)

**Comment by carmenshu78** [comment]
Thanks! I downgraded to the 1.24 version and the rows came back too

**Comment by pyrates999** [comment]
go to: about:support

click on Clear startup cache... button.

**Comment by 117649** [comment]
> @117649
> 
> Lately I see this type of issue after each update.
> 
> Do you think that Firefox changed how it installs update in a way that messed up updating legacy extension that using your scripts?
> 
> maybe @xiaoxiaoflood can help
> 
> We already call `showRestartNotification("upgraded", window);` when `ADDON_UPGRADE`.
> 
> How about we add `Services.appinfo.invalidateCachesOnRestart()`, and if user click `Not Now` maybe we can add flag to call `Services.appinfo.invalidateCachesOnRestart()` in `shutdown` function.
> 
> Can you test if?

em. I have to admit I don't fully understand what your point is here.
Is this all about cache clear? 
Only thing I can recall is FF do like to cache chrome pages at some time. Is it more like to do that now then before? I really don't know.

And I did a quick search in @xiaoxiaoflood's script there is only 1 hit of `Services.appinfo.invalidateCachesOnRestart()` which is in 'userChromeJS Manager' which not have a thing to do legacy addons thus add it to `shutdown` should have effect.

**Comment by 117649** [comment]
Oh, is this some how may relate to `gBrowser.moveTabTo(<tab>, <index>)`?
One thing I just know is if you use a index beyond `gBrowser.tabs`'s length you'll break the tab bar. At least in 133b now.

**Comment by carmenshu78** [comment]
> go to: about:support
> 
> click on Clear startup cache... button.

it worked! thanks

**Comment by onemen** [comment]
@117649

I just thinking about running `Services.appinfo.invalidateCachesOnRestart()` automatically after update to prevent cache issue with new version.

@carmenshu78,

did you install version 1.25 from a download you did manually or was it an `automatic updates`

**Comment by polk900** [comment]
> go to: about:support
> click on Clear startup cache... button.
It worked. Thanks!

**Comment by carmenshu78** [comment]
> @117649
> 
> I just thinking about running `Services.appinfo.invalidateCachesOnRestart()` automatically after update to prevent cache issue with new version.
> 
> @carmenshu78,
> 
> did you install version 1.25 from a download you did manually or was it an `automatic updates`

It was an automatic update

**Comment by 117649** [comment]
> @117649
> 
> I just thinking about running `Services.appinfo.invalidateCachesOnRestart()` automatically after update to prevent cache issue with new version.
> 
> @carmenshu78,
> 
> did you install version 1.25 from a download you did manually or was it an `automatic updates`
> 

In a place like `install()` yes.

I'm feeling deja Vu here. Have we talked about this or something very close some time ago and I was on the side suggest it to be added?

**Comment by pyrates999** [comment]
For me it was an automatic update, and I had to do what I suggested to get multiple rows back.

**Comment by pyrates999** [comment]
what I wanna know is, what caused that when the extension was updated?  What would change in the code to cause firefox to ignore the part of the code that enables multiple rows?

**Comment by onemen** [comment]
Can you all provide information about your operating system and Firefox version.

I can not reproduce this issue on my `Windows 11`.

> @pyrates999
> what I wanna know is, what caused that when the extension was updated?

I don't know, but since clearing the cache solve the issue, i guess that when we update legacy extension Firefox doesn't automatically clear cache. So it is possible that it mix Tab mix code from multiple versions.

We where always advise you to `Clear startup cache…` when updating `Firefox scripts`

I am going to automatically `Clear startup cache…` when ever Tab mix versions change

**Comment by pyrates999** [comment]
I'm on windows 10 19045.5011.  My Firefox version is 132.0.1.

Here is my preferences file: 
[TMPpref.txt](https://github.com/user-attachments/files/17701262/TMPpref.txt)

and here is my chrome directory from my firefox profile directory:
[chrome.zip](https://github.com/user-attachments/files/17701277/chrome.zip)

**Comment by onemen** [comment]
@pyrates999 

Your `chrome/utils` folder contains some obsolete files.
Remove old files and make sure to only install latest version from [firefox-scripts](https://github.com/xiaoxiaoflood/firefox-scripts/)
Also make sure the `config.js` file is up-to-date.

You can use `Restart Firefox` button to clear cache

![restart_button](https://github.com/user-attachments/assets/15ebefa7-3991-4f0b-874c-0b2dd1626477)

**Comment by pyrates999** [comment]
If you mean utils-old, I've now removed it.

**Comment by 117649** [comment]
> For me it was an automatic update, and I had to do what I suggested to get multiple rows back.

In short, you browser would like to cache web pages when it likes.
And the browser's UI is a web page itself`chrome://browser/content/browser.xhtml` so it get cached. 

You know what TMP does is modify browser's UI, right?

**Comment by onemen** [comment]
> If you mean utils-old, I've now removed it.

no, in `utils` folder itself you have some old files

**Comment by pyrates999** [comment]
Hi @onemen,

So I went to https://github.com/xiaoxiaoflood/firefox-scripts/?tab=readme-ov-file

And clicked the link to download utils.zip: [utils → I'm interested in both scripts and extensions](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/utils.zip)

I then compared the files from the extracted utils.zip and in my chrome/utils, and they matched:

![image](https://github.com/user-attachments/assets/5188e2e7-ae47-49ec-b153-50f703eff855)

And I do see the dates for them as being in the range of 2019-2022.

So on the same page, I then downloaded utils.zip from here:

![image](https://github.com/user-attachments/assets/a6eda650-f1ad-4f1b-bd77-dc19dd3c73f2)

And it too matched what I had previously downloaded.

Can you point me to a different link for utils.zip that has newer dates or versions of files?

**Comment by onemen** [comment]
@pyrates999, you have the latest

**Comment by pyrates999** [comment]
ok, thanks :)
