### ISSUE TITLE
new tab button on tabs bar not displayed right while option set to "After last tab"

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#36]
If the tabs is overflowing the new tab button will not show.
At this moment disable and re-enable the option would cause new tab button show on right of the tab bar and it will stay on there even if tabs stop overflow.
Stop overflowing disable and re-enable the option can make new tab button show after last tab.
Found out that when disable then re-enable the option the attribute would be set to "right-side" regardless what the menu selection is while tab bar is overflowing.
![image](https://user-images.githubusercontent.com/8281345/110315240-f4040380-8043-11eb-8b24-aa3cc49af24a.png)

**Comment by 117649** [comment]
Adding this here seems fixed it.
```diff
 #TabsToolbar[tabmix-show-newtabbutton*="side"] #tabbrowser-tabs[hasadjacentnewtabbutton]:not([overflow="true"]) ~ #new-tab-button,
+#TabsToolbar[tabmix-show-newtabbutton*="aftertabs"] #tabbrowser-tabs[overflow="true"] ~ #new-tab-button,
 #TabsToolbar[tabmix-show-newtabbutton*="side"] #new-tab-button {
   visibility: visible;
 }
```
https://github.com/onemen/TabMixPlus/blob/19bdd1b55b41ab935165cd7c3fc98e19147d0f55/addon/chrome/content/overlay/browser.css#L159-L162

**Comment by 117649** [comment]
Looks like this cause the second problem and nothing calls it while tab bar goes in and out overflow caused first.
Wonder with added css are we still need this?
https://github.com/onemen/TabMixPlus/blob/19bdd1b55b41ab935165cd7c3fc98e19147d0f55/addon/chrome/content/tab/tab.js#L2036-L2041

**Comment by onemen** [comment]
maybe it related to mutli-row.

i will look into it

**Comment by 117649** [comment]
> maybe it related to mutli-row.
> 
> i will look into it

How is it going?

You know, if you can make some intermediate commit on that part I can see what I can help.

**Comment by onemen** [comment]
I'm considering to always show the new tab button on the right when there are more then one row, and also to show the scroll button 
this will simplify multi-row code and prevent flickering when the button move from after last tab to the side and when the button disappear and reappear

**Comment by 117649** [comment]
> 
> 
> I'm considering to always show the new tab button on the right when there are more then one row, and also to show the scroll button
> this will simplify multi-row code and prevent flickering when the button move from after last tab to the side and when the button disappear and reappear

@onemen This seems sure to cause some waste of space. I think I've got old code working to a degree it may just require a little fix. And about scroll button I think is better to just replace those with a tiny scroll bar that just fit in between tab bar and new tab button. And just hide it when multi bar is not overflowing.

**Comment by onemen** [comment]
Do you still have this issue with the latest #41 update?

**Comment by 117649** [comment]
> 
> 
> Do you still have this issue with the latest #41 update?

Not yet.

**Comment by onemen** [comment]
I still see this issue on multi-row mode.
It look like that the code that check if the button can be after the last tab without overflowing is broken

**Comment by 117649** [comment]
> 
> 
> I still see this issue on multi-row mode.
> It look like that the code that check if the button can be after the last tab without overflowing is broken

It looks like going to be a fight with corner cases.
Here are what I've found: 
On multi-row mod if new tab button after last tab are shown enter customize mode cause it to disappear. Resize window can make new tab button at right show. 

When not overflowing if space at the end of the last row can't fit both last tab and new tab button but can fit last tab alone, the last tab show at a new row(not cause overflowing), new tab button show at right. If the space can't fit last tab also both will show at the new row. It should be either both at end or both at new row.

However I didn't found any thing too problematic when overflowing.

**Comment by 117649** [comment]
@onemen Now new tab button are not displayed in customize mode.
And it is seems because of this rule.
https://github.com/onemen/TabMixPlus/blob/19bdd1b55b41ab935165cd7c3fc98e19147d0f55/addon/chrome/content/overlay/browser.css#L164-L167

An easy fix.
```diff
- #TabsToolbar[tabmix-show-newtabbutton*="aftertabs"]  #new-tab-button,
+ :root:not([customizing]) #TabsToolbar[tabmix-show-newtabbutton*="aftertabs"]  #new-tab-button,
  #TabsToolbar:not([tabmix-show-newtabbutton])  #new-tab-button {
    visibility: collapse;
  }
```

**Comment by onemen** [comment]
This issue is fixed, for any regression of it open new issue
