### ISSUE TITLE
How do you exclude a site from opening in new tabs?

### ISSUE THREAD

**Issue by Jayinem** [onemen/TabMixPlus#362]
This particular site does not work with tab mix plus it only creates blank pages. I literally had to disable tab mix plus to even use the site. But I looked through the documentation and couldn't find out how to exclude a site, also looked through settings. Maybe it was obvious and I missed it.

**Comment by pyrates999** [comment]
do you mean all your tabs are blank?  If so, you're running an older version of tab mix plus.  That was fixed in a newer release of tab mix plus.

**Comment by onemen** [comment]
@Jayinem, 

Export your Tab Mix preference to a file, ([read how](https://onemen.github.io/tabmixplus-docs/help/preferences-button/) to do it), and attach it here.

I will check it to review you preferences

**Comment by Jayinem** [comment]
It's alright that site works now. Not sure how it even got fixed but I had restarted firefox and it still did it.
