### ISSUE TITLE
"Reload Tab Every..." Not Reloading

### ISSUE THREAD

**Issue by Sqrlly** [onemen/TabMixPlus#363]
Enabling a tab to reload every x minutes is not actually reloading now.

I've used this feature for ages and very handy.  I just recently updated my Waterfox to 6.5.1 and TMP to 1.25.0.  Did the clear startup cache and restarted too.  Everything else looks to be working smoothly so far.  I can set a tab to reload and it will put the clock icon on the tab, but the tab doesn't actually do the reload.  And this includes me doing a manual reload of the page after setting the auto reload time, as in the past it sometimes needed that.

I've also tested this on a page I made that just displays the current time.

**Comment by onemen** [comment]
This test build should fix this issue

Download this [test-build](https://github.com/user-attachments/files/17814842/test-build-1.25.1-20241119.1401.zip)

Rename it to `.xpi`and install it.
Open `about:support` page and click "Clear startup cache…" to force Firefox to load the installed version.

Report back

**Comment by Sqrlly** [comment]
Reporting back!  Looking good!  Installed the test build and it is now reloading pages.  Waited several minutes and got several reloads.  And the tabs are automatically refreshing themselves upon Waterfox start up, like it used to too.

Thanks!
