### ISSUE TITLE
Tab Mix Plus stops working after a short time

### ISSUE THREAD

**Issue by Jayinem** [onemen/TabMixPlus#365]
It'll work right then it just stops working where it doesn't load pages in new tabs without me messing with it, and I have to reinstall the .xpi. This happens about once per day lately. I followed the instructions to add the files to both firefox directories.

**Comment by onemen** [comment]
What version of Firefox you are using and what is your operating system?

Do you see sny messages in the brwoser console?

Attach a file with your Tab Mix preferdnces.

**Comment by Jayinem** [comment]
I'm not very technically, I don't know how to check if any messages in browser console, and how do I attach preferences?

**Comment by Jayinem** [comment]
It's not working on IGN.com for some reason, but neither is Tabloc. The site was working the other day. Maybe IGN changed something?

**Comment by zhuxh2001** [comment]
我遇到同样的问题，已经困扰了近一个月了，从Firefox 132.0至133.3都重现了这个问题，重新安装一次 .xpi（包括近期更新的版本）可以暂时摆脱这个问题

**Comment by onemen** [comment]
Make sure you are using latest Tab Mix vesion 1.26.0

Read the docs
https://onemen.github.io/tabmixplus-docs/other/installation/#troubleshooting

**Comment by 117649** [comment]
@onemen Is the load in new tab at least part of it actually setting FF preference? 
I do notice my preference been changed for one time after upgrade to 133.

**Comment by zhuxh2001** [comment]
> Make sure you are using latest Tab Mix vesion 1.26.0
> 
> Read the docs https://onemen.github.io/tabmixplus-docs/other/installation/#troubleshooting

感谢，按照链接的方法，逐一操作之后，测试了两天，再没有发生了！

Tab Mix Plus stops working

If Tab Mix Plus stops working after Firefox update was installed or after you installed update of Firefox Scripts , follow these instructions

    Uninstall Tab Mix Plus.
    Reinstall the latest versions of Firefox Scripts (see [instructions](https://onemen.github.io/tabmixplus-docs/other/installation/#install-firefox-scripts) above)
    Open about:support page and click Clear startup cache… to force Firefox to load the installed scripts on the next startup.
    Close Firefox again, wait 10 second, to make sure Firefox finished to clear the cache.
    Open Firefox and [reinstall](https://onemen.github.io/tabmixplus-docs/other/installation/#install-tab-mix-plus) latest Tab Mix Plus again.

**Comment by onemen** [comment]
@117649 

> @onemen Is the load in new tab at least part of it actually setting FF preference? I do notice my preference been changed for one time after upgrade to 133.

Can you specify which preference changed?

**Comment by 117649** [comment]
> @117649
> 
> > @onemen Is the load in new tab at least part of it actually setting FF preference? I do notice my preference been changed for one time after upgrade to 133.
> 
> Can you specify which preference changed?

Open the link in new tab. I unset then set it again in TMP option then it no longer occur.

**Comment by onemen** [comment]
@zhuxh2001 

attache your Tab Mix preferences as a file
also specify the preference from about:config for:
 - sidebar.revamp
 - sidebar.verticalTabs
any other preference that related to using the sidebar

can you provide a screenshot that show what exactly you drag and where you drop it
post any messages you see in the browser console after Tab Mix stop working

**Comment by zhuxh2001** [comment]
> @zhuxh2001
> 
> attache your Tab Mix preferences as a file also specify the preference from about:config for:
> 
>     * sidebar.revamp
> 
>     * sidebar.verticalTabs
>       any other preference that related to using the sidebar
> 
> 
> can you provide a screenshot that show what exactly you drag and where you drop it post any messages you see in the browser console after Tab Mix stop working

<img width="1134" alt="sidebar" src="https://github.com/user-attachments/assets/e438ea41-0805-433d-ab39-32bc1df349aa" />
[TMPpref20241218.txt](https://github.com/user-attachments/files/18177518/TMPpref20241218.txt)

**Comment by zhuxh2001** [comment]
> @zhuxh2001
> 
> attache your Tab Mix preferences as a file also specify the preference from about:config for:
> 
>     * sidebar.revamp
> 
>     * sidebar.verticalTabs
>       any other preference that related to using the sidebar
> 
> 
> can you provide a screenshot that show what exactly you drag and where you drop it post any messages you see in the browser console after Tab Mix stop working

1、attache your Tab Mix preferences as a file：
[TMPpref20241218.txt](https://github.com/user-attachments/files/18177637/TMPpref20241218.txt)

2、about:config for sidebar
<img width="1134" alt="sidebar" src="https://github.com/user-attachments/assets/55ab0b85-6c9e-4061-b0bf-37ea867644fd" />

3、drag and drop it
<img width="915" alt="拖放" src="https://github.com/user-attachments/assets/be3c7c63-a17f-4ecc-8bfd-9355249d00a1" />

4、故障图片
<img width="833" alt="故障" src="https://github.com/user-attachments/assets/54ac064d-b833-421b-bce4-a7332840656e" />
<img width="611" alt="故障右键菜单" src="https://github.com/user-attachments/assets/9a2cec20-281d-4de4-ae26-9feb854afbbb" />

**Comment by onemen** [comment]
@zhuxh2001 

Download this [test-build](https://github.com/user-attachments/files/18181378/test-build-1.26.1-20241218.1440.zip)

Rename it to `.xpi`and install it.

Report back

**Comment by zhuxh2001** [comment]
> @zhuxh2001
> 
> Download this [test-build](https://github.com/user-attachments/files/18181378/test-build-1.26.1-20241218.1440.zip)
> 
> Rename it to `.xpi`and install it.
> 
> Report back

使用这个test-build正常了，拖放标签栏之后，故障不再出现，非常感谢！
<img width="643" alt="微信图片_20241219111311" src="https://github.com/user-attachments/assets/1c8032bb-e568-4883-85cd-0b19c84b1357" />

**Comment by onemen** [comment]
Thank you for the report
