### ISSUE TITLE
135.0a1 (2024-11-28) (64-bit) Nightly search and address bar not working

### ISSUE THREAD

**Issue by Shahius** [onemen/TabMixPlus#366]
After update 135.0a1 (2024-11-28) (64-bit) Nightly search and address bar stopped working. I type in address or search, press Enter and nothing happens.

![image](https://github.com/user-attachments/assets/14cae9ff-dca8-4783-9d13-2f8e11dd430f)

**Comment by onemen** [comment]
Download and install latest [development build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build)

**Comment by Shahius** [comment]
> Download and install latest [development build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build)

Dev. build works! Thank you!
