### ISSUE TITLE
134.0b2 Can't reorder tabs anymore

### ISSUE THREAD

**Issue by zakius** [onemen/TabMixPlus#367]
Once I drag it and release my mouse button the tab snaps back to the initial place

**Comment by onemen** [comment]
Download and install latest [development build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build)

**Comment by 117649** [comment]
@onemen  Eh. After install latest dev-build on 133 can't drop dragged tab at cursor's place the tab would be place at a position a way left to its start position.
It is ok on 134.
So I guess it some how relate to this?
The version I rewind back to on 133 for it to work is 1.25.1-20241122.1625

**Comment by zakius** [comment]
I confirm it working on 134

**Comment by onemen** [comment]
@117649 

Download and install latest [development build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build)
I've just uploaded version 1.25.1-20241202.0840 with the fix.

**Comment by 117649** [comment]
> @117649
> 
> Download and install latest [development build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build) I've just uploaded version 1.25.1-20241202.0848 with the fix for Firefox 133.

I confirm its OK on 133
