### ISSUE TITLE
Problem installing TabMixPlus - Fixed

### ISSUE THREAD

**Issue by foxsilverfox** [onemen/TabMixPlus#368]
Firefox 133
Windows 11
I was getting "Add-on appears corrupt" after following all the instructions. Then I notice file autoconfig.js in the folder with config-prefs.js. After renaming autoconfig.js to zautoconfig.js and clearing startup cache TabMixPlus instalation went through

**Comment by foxsilverfox** [comment]
JIC, autoconfig.js content
pref("general.config.filename", "mozilla.cfg");
pref("general.config.obscure_value", 0);

**Comment by foxsilverfox** [comment]
autoconfig.js content
pref("general.config.filename", "mozilla.cfg");
pref("general.config.obscure_value", 0);

**Comment by pyrates999** [comment]
you probably need to update the pre-requisite files that need to be installed here: https://github.com/onemen/TabMixPlus?tab=readme-ov-file#installation

**Comment by foxsilverfox** [comment]
> you probably need to update the pre-requisite files that need to be installed here: https://github.com/onemen/TabMixPlus?tab=readme-ov-file#installation

As I said "After renaming autoconfig.js to zautoconfig.js and clearing startup cache TabMixPlus instalation went through"
