### ISSUE TITLE
Prevents "Open All Bookmarks" to work with librewolf-133.0-3

### ISSUE THREAD

**Issue by BobHD** [onemen/TabMixPlus#369]
Hi,

After upgrading LibreWolf from 132.0.2-1  to 133.0-3, right clicking on a folder showed in the Bookmarks sidebar performs no actions.

Disabling TMP makes it work. Re-enabling it makes it stop working again.

That does not happen with Firefox 133.0.

I use this:

https://gitlab.com/api/v4/projects/44042130/packages/generic/librewolf/133.0-3/librewolf-133.0-3-windows-x86_64-setup.exe

on Windows10.

Thanks.

**Comment by onemen** [comment]
This test build should fix this issue

Download this [test-build](https://github.com/user-attachments/files/18062926/test-build-1.26.1-20241209-1633.zip)

Rename it to `.xpi`and install it.

Report back

**Comment by BobHD** [comment]
That works, thanks!
