### ISSUE TITLE
Can we make gBrowser.tabContainer._lockTabSizing optional?

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#37]
![image](https://user-images.githubusercontent.com/8281345/110465818-de5c1000-810f-11eb-8cb5-54a236473eed.png)
After first tab is closed.
![image](https://user-images.githubusercontent.com/8281345/110465886-f6339400-810f-11eb-9d66-6f6fa9d3cee6.png)

**Comment by 117649** [comment]
Have found this is caused by this:
https://github.com/onemen/TabMixPlus/blob/19bdd1b55b41ab935165cd7c3fc98e19147d0f55/addon/chrome/content/minit/tablib.js#L475-L484
Seems to be explicitly did. I'm just wonder why.

**Comment by onemen** [comment]
This is what gBrowser.tabContainer._lockTabSizing, when user close tab with close tab button, next tab width is set so the mouse is over the close button of the next tab.
Firefox added this feature many years ago.

**Comment by 117649** [comment]
May make a preference and a switch to it?

We now have a bunch of things that can achieve same result(close a stream of tabs fast) like close everything to the right and multi selection. Nowadays users may get confused by this behaviors especially when they set the close button on tab to hide.
