### ISSUE TITLE
Merge Windows in tab context menu not working

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#38]
Error:
```
Uncaught TypeError: Services.wm.getZOrderDOMWindowEnumerator is not a function
    getWindowsList chrome://tabmix-resource/content/MergeWindows.jsm:266
    _mergeWindows chrome://tabmix-resource/content/MergeWindows.jsm:44
    oncommand chrome://browser/content/browser.xhtml:1
```
'Services.wm.getZOrderDOMWindowEnumerator' is no more but there is a 'Services.wm.getZOrderAppWindowEnumerator'.
I'll bet they just change the name.

**Comment by onemen** [comment]
I'm not sure, 
we need to get ChromeWindow Enumerator

**Comment by onemen** [comment]
I think we can use Services.wm.getEnumerator("navigator:browser") for all OS
