### ISSUE TITLE
Cannot open any entries from the Library window

### ISSUE THREAD

**Issue by soknife** [onemen/TabMixPlus#42]
Getting the following error when trying to open any bookmark/history entry from the Library window (Ctrl + Shift + H)
Opening from the bookmarks toolbar, or library pop-up pane works (although history doesn't remember the container but I don't know if that's related to TMP)

```
Uncaught ReferenceError: BrowserWindowTracker is not defined
    getBrowserWindow chrome://tabmix-resource/content/Places.jsm:39
    PUIU_openNodeWithEvent chrome://tabmix-resource/content/Places.jsm line 71 > eval:4
    CT_openSelectedNode chrome://browser/content/places/places.js:1451
    CT_onClick chrome://browser/content/places/places.js:1461
    onclick chrome://browser/content/places/places.xhtml:1
Places.jsm:39:1
```

Firefox Developer Edition 87.0b9
Clean profile no other add-ons
Config only modified to allow for unsigned add-ons
Default TMP preferences

**Comment by 117649** [comment]
Add `XPCOMUtils.defineLazyModuleGetter(this,"BrowserWindowTracker",
  "resource:///modules/BrowserWindowTracker.jsm");` here fixed problem for me.
https://github.com/onemen/TabMixPlus/blob/19bdd1b55b41ab935165cd7c3fc98e19147d0f55/addon/modules/Places.jsm#L9-L29

**Comment by onemen** [comment]
👍
