### ISSUE TITLE
Can we remove progress meter on tabs?

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#44]
I think that progress meter on tabs is obsolete.
with the new design of burst animation it have no real value to the user.

according to my testing, for most of the tab the progress value get at most 2 hits, the value change from 0 to 50% to 80% and 100%. it also happens to fast to be visible.

Maybe we can improve the code to get move visible update, but it stile think that we don't really need it.

**Comment by 117649** [comment]
I'm pretty like that. But I do have to admit Firefox or any browser just eager to get ride of them.
The burst animation on most situations for me just too dark to be seen.
May I suggest that we leave it as it is for now? Later we may let it act like a alternate style of the burst animation and have burst animation use the color setting of it.

**Comment by onemen** [comment]
Do you actually see the progress bar moving, for the most tab i don't see it at all.
I'm using windows, maybe it is different for other platform?

**Comment by 117649** [comment]
> 
> 
> Do you actually see the progress bar moving, for the most tab i don't see it at all.
> I'm using windows, maybe it is different for other platform?

I'm using windows too. It indeed very rare to see cause the progress value given out by Firefox just jump from 0% to 100% for most of the time.

**Comment by onemen** [comment]
@117649 

do you see any tab progress with latest Firefox ?

**Comment by 117649** [comment]
> @117649
> 
> do you see any tab progress with latest Firefox ?

I have to say I love this feature.








Sigh. 
But to be honest, I don't think I see it for several versions.

**Comment by onemen** [comment]
try this change and let me know if it work for you

addon\chrome\content\overlay\browser.css
```diff
  .tab-progress {
    margin: 0;
    min-width: 0;
-  width: 0;
  }
```

**Comment by onemen** [comment]
It look like Firefox does not call our `onProgressChange` function (in tab.js)

it work in Firefox 102, and not working since Firefox 104

I will try to find what changed in Firefox ....

**Comment by 117649** [comment]
> try this change and let me know if it work for you
> 
> addon\chrome\content\overlay\browser.css
> 
> ```diff
>   .tab-progress {
>     margin: 0;
>     min-width: 0;
> -  width: 0;
>   }
> ```

Have you tried this you-self? will it work?

**Comment by onemen** [comment]
> Have you tried this you-self? will it work?

It only work if you set the tab-progress manually, I still need to find out why `onProgressChange` is not triggered

**Comment by onemen** [comment]
most of the time `onProgressChange` only triggered one time with progress = 100%, so the progress bar does not show
