### ISSUE TITLE
How to use helper loader

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#5]
@117649, you post this on #3
> For the Firefox versions compatibility it is a little bizarre situation here:
> 
>     1. For the latest Waterfox G3 which is based on Firefox 78ESR the compatibility should just be straightforward.
> 
>     2. You need a [helper](https://github.com/117649/firefox-scripts) to load the bootstrap legacy add-on, Waterfox already came with one.
> 
>     3. The helper came in two types [extension](https://github.com/117649/firefox-scripts/tree/master/extensions/bootstrapLoader) and [script](https://github.com/117649/firefox-scripts/tree/master/chrome/utils). I would consider the one waterfox provided is script type.
> 
>     4. The two types of the helper CAN co-exist BUT SHOULD NOT since this will cause two helper in the browser and load every bootstrap legacy add-on twice. Which will cause problem.

If i understand it correctly, the user of Tab Mix Plus will have to install the helper loader (script or extension), we are not going to wrap the loader with Tab Mix xpi file

**Comment by 117649** [comment]
Yes you are right.
