### ISSUE TITLE
Changing permission submenu (from tab context menu) throw an error

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#51]
```
 NS_ERROR_FILE_NOT_FOUND: content.js:74
      receiveMessage chrome://tabmixplus/content/scripts/content.js:74
      (Async: MessageListener.receiveMessage)
      init chrome://tabmixplus/content/scripts/content.js:58
      forEach self-hosted:205
      init chrome://tabmixplus/content/scripts/content.js:58
      <anonymous> chrome://tabmixplus/content/scripts/content.js:519
```

**Comment by 117649** [comment]
[Bug 1497144 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1497144)

**Comment by 117649** [comment]
@onemen 
What this function supposes to do?
I can fix the error but it seems has no effect on page loading.

**Comment by onemen** [comment]
> [Bug 1497144 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1497144)
> 
> In `content/scripts/content.js` change `DocShellCapabilities.restore` to `SessionStoreUtils.restoreDocShellCapabilities` and `DocShellCapabilities.collect` to `SessionStoreUtils.collectDocShellCapabilities` will remove the error but I'm not sure the thing is functioning as intend.

> @onemen
> What this function supposes to do?
> I can fix the error but it seems has no effect on page loading.

I'v already fix it, thank you for your help
