### ISSUE TITLE
New Tab options are broken

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#52]
Two are broken options are broken

1. setting/resetting custom **New Tab Page** (```browser.newtab.url```) not working.
     This function throw an error on both option. Tabmix not working at all when Firefox start with browser.newtab.url not as "about:newtab"
```
  modules/NewTabURL.jsm
  updateNewTabURL() {
    let value = Services.prefs.getStringPref(FIREFOX_PREF);
    if (value == ABOUT_NEW_TAB) {
      aboutNewTabService.resetNewTabURL();
    } else {
      aboutNewTabService.newTabURL = value;
    }
  }
```

2. setting this option to **Home page** prevents any new tab command (clicking on new tab button, using shortcut)
  ```
    userInterface.js:48:7
    Uncaught ReferenceError: gHomeButton is not defined
    TMP_BrowserOpenTab chrome://tabmixplus/content/links/userInterface.js:48
    oncommand chrome://browser/content/browser.xhtml:1
  ```

  

![new_tab](https://user-images.githubusercontent.com/3650909/124795387-a8f9ee80-df58-11eb-9cd5-aeec076de2e4.png)

**Comment by 117649** [comment]
Seems that `browser.newtab.url` is no longer in function but [this](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/newtab-aboutconfig.uc.js) should bring it back.

**Comment by 117649** [comment]
>     1. setting/resetting custom **New Tab Page** (`browser.newtab.url`) not working.
>        This function throw an error on both option. Tabmix not working at all when Firefox start with browser.newtab.url not as "about:newtab"

All in all following changes are enough for me to solve the error and regain function.

In `chrome://tabmix-resource/content/NewTabURL.jsm`:
```diff
-XPCOMUtils.defineLazyServiceGetter(this, "aboutNewTabService",
-  "@mozilla.org/browser/aboutnewtab-service;1",
-  "nsIAboutNewTabService");
+XPCOMUtils.defineLazyModuleGetter(this, "AboutNewTab",
+  "resource:///modules/AboutNewTab.jsm");
```

```diff
   updateNewTabURL() {
    let value = Services.prefs.getStringPref(FIREFOX_PREF);
    if (value == ABOUT_NEW_TAB) {
-      aboutNewTabService.resetNewTabURL();
+      AboutNewTab.resetNewTabURL();
    } else {
-      aboutNewTabService.newTabURL = value;
+      AboutNewTab.newTabURL = value;
    }
  }
```

**Comment by 117649** [comment]
>     2. setting this option to **Home page** prevents any new tab command (clicking on new tab button, using shortcut)

In `chrome\content\links\userInterface.js`:
```diff
-      url = gHomeButton.getHomePage().split("|")[0];
+      url = HomePage.get().split("|")[0];
```

I'm not making a new branch and PR for these changes as they are just too tiny for the time required.
But do tell me you need one.

**Comment by onemen** [comment]
Thank you @117649 👍
