### ISSUE TITLE
Tabmix Options window spinners (html:input type="number") should have a min value

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#53]
Some spinner are missing min value.

For  Tab Width (```id="minWidth" id="maxWidth"```) the min value should be the size of pinned tab

Changing the value for ```Dispkay > Tab Bar > Scroll Delay id="scrollDelay"``` throw an error ```TypeError: setting getter-only property "_scrollDelay"```, I will address this issue but the pref need a min

there are others without a min.

@117649 can you take this one ?

**Comment by 117649** [comment]
Yes I can. I suppose this is because the file been changed from .xul to .xhtml and attributes for input element are not identical. So, can I assume they still have the attribute that contain the value of min?

Otherwise we have to find out the number and that will take time.

**Comment by onemen** [comment]
You can set all spinner that don't have min to min="0" except for ```id="minWidth" id="maxWidth"``` that should be min="40"

**Comment by 117649** [comment]
https://github.com/onemen/TabMixPlus/pull/54
