### ISSUE TITLE
Removed: Reload skip cache – for bookmarks open in tabs

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#55]
I have just removed this feature (commit a0c1fca3a65b48e640e5b1b1e9c4385e57fd4126)

Reason for removing it:
- it does not work!!, and throw an error:

```
    [Exception... "Component returned failure code: 0x80004001
    (NS_ERROR_NOT_IMPLEMENTED) [nsIRequest.loadFlags]"  nsresult:
    "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame ::
    chrome://tabmixplus/content/tab/tab.js :: TMP_onStateChange ::
    line 2660"  data: no]
```

- it was only used by:
  -  our session manager that now doesn't work.
  -  when user open group of bookmarks while the feature Load tabs progressively was on.

@117649, i don't find important but if you know about a simple fix let me know.

**Comment by 117649** [comment]
@onemen I have no ideal what this is.

**Comment by onemen** [comment]
OK,
nothing to worry about
