### ISSUE TITLE
Options window have some style issues

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#58]
With or without Proton there are some style issues in our options window.

here some examples:
![options-style-issues](https://user-images.githubusercontent.com/3650909/126610373-4d6ac910-8d67-4655-8d99-6a54d1f988ff.png)

**Comment by 117649** [comment]
Currently most source I can find suggests that just set fixed 'width' style for html input.

**Comment by onemen** [comment]
@117649 
We have 4 ```preferences.css``` files with many duplicates rules: 
- skin/preferences.css 
- skin/preferences/preferences.css
- skin/app_version/78/preferences.css (almost a copy of the one above ?)
- content/preferences/preferences.css

**Comment by 117649** [comment]
> 
> 
> @117649
> We have 4 `preferences.css` files with many duplicates rules:
> 
>     * skin/preferences.css
> 
>     * skin/preferences/preferences.css
> 
>     * skin/app_version/78/preferences.css (almost a copy of the one above ?)
> 
>     * content/preferences/preferences.css

I think one of them may be a copy of default css for prefwindow from old firefox.

**Comment by onemen** [comment]
> 
> 
> Currently most source I can find suggests that just set fixed 'width' style for html input.

@117649, 
check this patch, it simply generate ```width: calc(4ch + 21px);```
the unit ch is the width of the digit 0 (zero) in the current font& size

let me know how it work for you

```diff
diff --git a/addon/chrome/content/preferences/prefs-ce.js b/addon/chrome/content/preferences/prefs-ce.js
index 47deed26..584d2112 100644
--- a/addon/chrome/content/preferences/prefs-ce.js
+++ b/addon/chrome/content/preferences/prefs-ce.js
@@ -621,6 +621,10 @@ class PrefPane extends MozXULElement {
     contentBox.append(...childNodes);
     this.initializeAttributeInheritance();
 
+    this.querySelectorAll('input[type="number"]').forEach(input => {
+      input.setAttribute("style", `width: calc(${Number(input.size)}ch + 21px);`);
+    });
+
     this._loaded = false;
     this._deferredValueUpdateElements = new Set();
     this._content = this.getElementsByClassName('content-box')[0];
```

**Comment by 117649** [comment]
@onemen 
I've tried size value of 2,3,4 and 5. I'm feel 21px a little wide, 20px is just right.
And I also recommend use "paneload" event provided by 'pref-ce.js':
```js
this.document.documentElement.addEventListener("paneload",
    e=>e.target.querySelectorAll('input[type="number"]').forEach(input => {
    input.setAttribute("style", `width: calc(${Number(input.size)}ch + 21px);`);
}))
```

**Comment by onemen** [comment]
> And I also recommend use "paneload" event provided by 'pref-ce.js'. I've done my try with this way:

"paneload" is just a synthetic event that we fires just few lines after connectedCallback.
we don't need any delay to enter style attribute into DOM elements.
we can actually do it on ```childNodes``` before ```contentBox.append(...childNodes);```

**Comment by 117649** [comment]
> 
> 
> > And I also recommend use "paneload" event provided by 'pref-ce.js'. I've done my try with this way:
> 
> "paneload" is just a synthetic event that we fires just few lines after connectedCallback.
> we don't need any delay to enter style attribute into DOM elements.
> we can actually do it on `childNodes` before `contentBox.append(...childNodes);`

I'd like to keep 'PrefPane' general.

May be you could override 'fragment' getter for this one in 'preference.js'? I've done such thing with 'instantApply'.

**Comment by onemen** [comment]
How about just use **gPrefWindow.initPane** instead

**Comment by 117649** [comment]
> 
> 
> How about just use **gPrefWindow.initPane** instead

Isn't this one same with "paneload"?

**Comment by onemen** [comment]
@117649 
> ```js
> this.document.documentElement.addEventListener("paneload",
>     e=>e.target.querySelectorAll('input[type="number"]').forEach(input => {
>     input.setAttribute("style", `width: calc(${Number(input.size)}ch + 21px);`);
> }))
> ```

where exactly did you add this?
we need to add the same code also to pref-appearance-ce.js or pref-appearance.js

**Comment by 117649** [comment]
@onemen 

> where exactly did you add this?
> we need to add the same code also to pref-appearance-ce.js or pref-appearance.js

window element.

**Comment by onemen** [comment]
Ok,
I'v add it at the top of preferences.js

Regarding  pref-appearance, I can add to pref-appearance.js > init function, or since MozColorbox is our custome element i can add it to MozColorbox > connectedCallback

**Comment by 117649** [comment]
> Regarding pref-appearance, I can add to pref-appearance.js > init function, or since MozColorbox is our custome element i can add it to MozColorbox > connectedCallback

I'd prefer **pref-appearance.js**.

**Comment by onemen** [comment]
@117649 

Can you test if this css fix this issue without any JavaScript ?

Add this to ```numberinput.css```
```css
input[type="number"] {
  padding-inline-start: 4px;
  text-align: start;
}
```

**Comment by onemen** [comment]
even better
```css
input[type=number][size="2"]{ width: calc(2ch + 20px);}
input[type=number][size="3"]{ width: calc(3ch + 20px);}
input[type=number][size="4"]{ width: calc(4ch + 20px);}
input[type=number][size="5"]{ width: calc(5ch + 20px);}
input[type=number][size="6"]{ width: calc(6ch + 20px);}
```

**Comment by 117649** [comment]
> 
> 
> even better
> 
> ```css
> input[type=number][size="2"]{ width: calc(2ch + 20px);}
> input[type=number][size="3"]{ width: calc(3ch + 20px);}
> input[type=number][size="4"]{ width: calc(4ch + 20px);}
> input[type=number][size="5"]{ width: calc(5ch + 20px);}
> input[type=number][size="6"]{ width: calc(6ch + 20px);}
> ```

Working fine.

**Comment by onemen** [comment]
Done by #59
