### ISSUE TITLE
How to use extension from folder on development

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#6]
In the good old days before Webextensions I could place a file in profile/extensions folder with a link to my working directory.
that configuration eliminate the need to create XPI file and install it after each change

for extension with id EXT_NAME@AAA.com the file name was the same as the id (EXT_NAME@AAA.com)
and its content was 
```
path\to\working\direcory
```

Is it possible to do the same with Firefox nightly when using helper loader ?

**Comment by 117649** [comment]
@xiaoxiaoflood
 May require a modified loader.

**Comment by onemen** [comment]
look like it and install the extension, however it always use the cached data even after restart.
I will try look how Firefox remove the cached extension data after updated

**Comment by 117649** [comment]
Are you 

> look like it and install the extension, however it always use the cached data even after restart.
> I will try look how Firefox remove the cached extension data after updated

Are you using the folder or XPI?

**Comment by 117649** [comment]
Are you 

> look like it and install the extension, however it always use the cached data even after restart.
> I will try look how Firefox remove the cached extension data after updated

Are you using the folder or XPI?

For clearing cache this [instruction](https://github.com/xiaoxiaoflood/firefox-scripts#instructions) for custom script may be useful.

**Comment by onemen** [comment]
Look like there is Firefox preference for this
```extensions.%ID%.getAddons.cache.enabled```

just replace %ID% with addon Id, and set it to false in about:config
Tab Mix ID is: {dc572301-7619-498c-a57d-39143191b318}
```extensions.{dc572301-7619-498c-a57d-39143191b318}.getAddons.cache.enabled ---> false```
