### ISSUE TITLE
its time for new readme

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#65]

**Comment by 117649** [comment]
[An example that may be helpful](https://github.com/p1usminus/roomybookmarksredux)
But anyway most important part should be get user understand how to install bootstrap loader.

**Comment by onemen** [comment]
Are there any special instruction on how to create xpi file from the source ?

**Comment by 117649** [comment]
> 
> 
> Are there any special instruction on how to create xpi file from the source ?

No.

**Comment by 117649** [comment]
> 
> 
> Are there any special instruction on how to create xpi file from the source ?

@onemen One thing is you should use robust and well tested tool to compress the **.zip** that can be properly decompressed by different tools and on different OS.

One bad example is the zip compress module of the default powsershell version of win 10.
The zip file it generated can only be decompress by and on Windows with compress manager tool. Don't use it.

You've been quiet for a while hope you're all well.

**Comment by 117649** [comment]
> 
> 
> I'v just published the first development build. https://github.com/onemen/TabMixPlus/releases
> can you test how it work



> 
> 
> also check the new RADME

Of course.

**Comment by 117649** [comment]
@onemen The content of this page are vital to the installation and hard to find.
https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/extensions/bootstrapLoader/README.md
Better just include it in TMP's README.

**Comment by onemen** [comment]
I already have this link
https://github.com/onemen/TabMixPlus/blame/main/README.md#L28-L29

**Comment by 117649** [comment]
> 
> 
> I already have this link
> https://github.com/onemen/TabMixPlus/blame/main/README.md#L28-L29

Well those two prefs are still needed if using chrome script as far as I know.
Without the them Firefox won't allow install legacy **.xpi** at all.

**Comment by 117649** [comment]
And some small UI problem(The help button):
![图片](https://user-images.githubusercontent.com/8281345/132944669-67c37efa-870f-4e41-ade5-388507ba5cbc.png)

**Comment by onemen** [comment]
> Well those two prefs are still needed if using chrome script as far as I know.
> Without the them Firefox won't allow install legacy **.xpi** at all.

config.js lock xpinstall.signatures.required 
you don't need this pref for chrome script extensions.experiments.enabled

**Comment by 117649** [comment]
> 
> 
> > Well those two prefs are still needed if using chrome script as far as I know.
> > Without the them Firefox won't allow install legacy **.xpi** at all.
> 
> config.js lock xpinstall.signatures.required
> you don't need this pref for chrome script extensions.experiments.enabled

Ok, just tried it you are right.

**Comment by 117649** [comment]
I have this one record confirms that set **xpinstall.whitelist.required=false** helps 'file corrupt' error.
https://dm.reddit.com/r/FirefoxAddons/comments/pm53qx/github_onementabmixplus_at_v100pre1/hcjn36a/

**Comment by onemen** [comment]
> I have this one record confirms that set **xpinstall.whitelist.required=false** helps 'file corrupt' error.
> https://dm.reddit.com/r/FirefoxAddons/comments/pm53qx/github_onementabmixplus_at_v100pre1/hcjn36a/

Can ask @xiaoxiaoflood if it xpinstall.whitelist.required=false setting can be part of bootstrapLoader and firefox-scripts?
If not i can add it to our README.md

**Comment by 117649** [comment]
> Can ask @xiaoxiaoflood if it xpinstall.whitelist.required=false setting can be part of bootstrapLoader and firefox-scripts?
> If not i can add it to our README.md

I think you can open issue on https://github.com/xiaoxiaoflood/firefox-scripts/issues .
In my opinion it not seems very realistic. **bootstrapLoader** need setting prefs itself **firefox-scripts** actually use config.js which is user editable, and Waterfox haven't update loader for quite a while.

Add a troubleshoot section to README.md is faster and easier.

**Comment by yakoder** [comment]
Suggestion: making it more clear as to _which_ version of userChromeJS is needed. Assumed "extension-only" and TMP didn't show up in the Addons list (and, although moot point & unsure what did it, with ESR 78 _nothing_ was showing up in that list, but got ESR 91.1 today & had to redo everything).  If only "utils → I'm only interested in extensions" version of userChromeJS is installed, TMP seems to function, but no options. I tried the "utils → I'm interested in both scripts and extensions" version, and TMP seems happy happy.

I would've just cleaned that up a bit & did a PR, but it is sounding like a few others are already working on the README.

**Comment by 117649** [comment]
> 
> 
> Suggestion: making it more clear as to _which_ version of userChromeJS is needed. Assumed "extension-only" and TMP didn't show up in the Addons list (and, although moot point & unsure what did it, with ESR 78 _nothing_ was showing up in that list, but got ESR 91.1 today & had to redo everything). If only "utils → I'm only interested in extensions" version of userChromeJS is installed, TMP seems to function, but no options. I tried the "utils → I'm interested in both scripts and extensions" version, and TMP seems happy happy.
> 
> I would've just cleaned that up a bit & did a PR, but it is sounding like a few others are already working on the README.

Well, In fact it not like that. The different between that two is only a module to load userCustomJS file.
It more likely because your update wiped all cache.
