### ISSUE TITLE
Auto reload broken

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#67]
No error emitting the thing just not in function.

**Comment by 117649** [comment]
It seems need to be a **linkedBrowser** with **remote** attribute is true.

**Comment by onemen** [comment]
I see this error from Firefox 91+, it work on Firefox 90.
I will check Firefox code for changes
```
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIWebPageDescriptor.currentDescriptor] content.js:121
    receiveMessage chrome://tabmixplus/content/scripts/content.js:121
    (Async: MessageListener.receiveMessage)
    init chrome://tabmixplus/content/scripts/content.js:57
    forEach self-hosted:205
    init chrome://tabmixplus/content/scripts/content.js:57
    <anonymous> chrome://tabmixplus/content/scripts/content.js:574
```

**Comment by 117649** [comment]
I'm on:
![image](https://user-images.githubusercontent.com/8281345/130566181-ce74cae7-6098-4296-8c62-f8b2cb49884c.png)

The **content.js** seems not be loaded at all.

**Comment by onemen** [comment]
I need to test a web page with postData, do you have any idea how to test reloading a page with postData ?

**Comment by 117649** [comment]
> 
> 
> I need to test a web page with postData, do you have any idea how to test reloading a page with postData ?

No

**Comment by 117649** [comment]
May be try the tab restored by session restore?

**Comment by onemen** [comment]
Tabmix have this warning, when user try to Auto-reload page with postData, many years, (i don't remember when i was last testing it)

```
confirm_autoreloadPostData_title=Warning!
confirm_autoreloadPostData=The page on which you tried to enable Auto Reload contains POSTDATA.\nIf you enable Auto Reload, any action the form carries out (such as an online purchase) will be repeated.\n\nAre you sure that you want to enable Auto Reload?
confirm_autoreloadPostData_remote=The page on which you tried to enable Auto Reload contains POSTDATA.\nIf you enable Auto Reload, any action the form carries out (such as an online purchase) will be lost.\n\nAre you sure that you want to enable Auto Reload?
```

maybe we don't need it at all with modern browsers?
when i manually reload page with form it reload with all the form data

**Comment by 117649** [comment]
I'm not sure.
No body deploy such stupid page code online doesn't mean it technically impossible.

**Comment by onemen** [comment]
Actually we set Auto-reload to always bypass cache, history or proxy and with that all form data is indeed lost
that's why i'v added the check for is postdata exist on the page to only show the warning when postdata exist

```
  var loadFlags = Ci.nsIWebNavigation.LOAD_FLAGS_BYPASS_HISTORY |
                  Ci.nsIWebNavigation.LOAD_FLAGS_BYPASS_PROXY |
                  Ci.nsIWebNavigation.LOAD_FLAGS_BYPASS_CACHE;
```
https://github.com/onemen/TabMixPlus/blob/4b36ebcc1d5227c490d20658f2b890002e223c6e/addon/modules/AutoReload.jsm#L323:L325

**Comment by onemen** [comment]
How about we use SessionStore.getTabState(tab) and show the warning if the state contained formdata ?

**Comment by 117649** [comment]
I really don't know much on this but seem reasonable enough.

**Comment by 117649** [comment]
Sometimes when you have form data in the page and you refresh the page the browser would complain.
How about just follow that?

**Comment by onemen** [comment]
> 
> Sometimes when you have form data in the page and you refresh the page the browser would complain.
> How about just follow that?

Can you provide an example to such a page?

**Comment by onemen** [comment]
Found one... https://regex101.com/

![unload](https://user-images.githubusercontent.com/3650909/130730943-8ac5632a-2115-4cda-a1c5-dc927a46f541.png)

This is notification is specific to the page, it has nothing to do with our current code that check for post data
we can check if a page have such prompt by calling ```tab.linkedBrowser.permitUnload()``` before we try to reload it

**Comment by 117649** [comment]
> This notification is specific to the page, it has nothing to do with our current code that check for post data
> we can check if a page have such prompt by calling `tab.linkedBrowser.permitUnload()` before we try to reload it

This is one of the kind but I do know there is other type that says it would send data again usually on a login page.
