### ISSUE TITLE
Enable auto update

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#69]
@117649 , i'v noticed that you don't have updates.json in your repositories [Tab-Groups](https://github.com/117649/Tab-Groups/tree/Tab-Groups-2.1.4b1_r1.3) and [Saved Password Editor Redux](https://github.com/117649/SavedPasswordEditorRedux/tree/v2.11.4) is there any other why to enable auto update for bootstrap extensions? 

We need to update the link in install.rdf and the content of updates.json to Github urls

**Comment by 117649** [comment]
Not I know anything about...

I just don't have it setup for my repos...

**Comment by Frikun** [comment]
WOW! I see "One Tab" as my #1 appreciated add-on ever. But I'm a retired Ex-HP Rep & know my limitations. I have no clue what you are talking about when I have ??? root folders in 8 machines & 25+ TB'S in these ancient collection's. Whew! LOL 😕

**Comment by onemen** [comment]
@Frikun,

Your comment is not related to this issue, I don't know what do you mean
