### ISSUE TITLE
I cannot install xpi for legacy TMP support

### ISSUE THREAD

**Issue by Bearmancer** [onemen/TabMixPlus#76]
I set the value of xpinstall.whitelist.required to false but I still cannot install the xpi file required to enable the extension for latest Firefox.

**Comment by onemen** [comment]
I have a discussion about this issue with the developer of userChromeJS.
post your read and post more details [here](https://github.com/xiaoxiaoflood/firefox-scripts/issues/92).

**Comment by 117649** [comment]
Have you install bootstrap loader properly?
have you cleared you startup cache?

**Comment by Bearmancer** [comment]
I use Firefox beta not Nightly so I installed chromejs. I cleared my startup cache too.

________________________________

**Comment by Bearmancer** [comment]
Here all the images of what I did: https://imgur.com/a/sM4zQ0z

I reinstalled the extension too. No difference.

**Comment by Bearmancer** [comment]
I tried installing bootstraploader but that didn't work either. Got the same xpi issue as with the other xpi file.

**Comment by 117649** [comment]
> 
> 
> I tried installing bootstraploader but that didn't work either. Got the same xpi issue as with the other xpi file.

Don't use both together.

Can you open browser toolbox and capture the error thrown when you install **.xpi** ?

**Comment by onemen** [comment]
download the xpi and save it locally, then try to install it

**Comment by Bearmancer** [comment]
It is locally installed. How else will I install it to Firefox?

**Comment by onemen** [comment]
Did you do step 1 from [here](https://github.com/xiaoxiaoflood/firefox-scripts#instructions)?

**Comment by etjim** [comment]
When you do step 3 "Download one of the files below and extract its content in chrome folder." of userChromeJS Instructions , you need to choise "utils → I'm only interested in extensions" or "utils → I'm interested in both scripts and extensions".

After finish all Step you can install TMP，Unnecessary install bootstraploader.xip

**Comment by Bearmancer** [comment]
I already downloaded the extension chromejs. I did the additional step only for safety.

I can't install the tmp xpi
________________________________

**Comment by Bearmancer** [comment]
> 
> 
> > I tried installing bootstraploader but that didn't work either. Got the same xpi issue as with the other xpi file.
> 
> Don't use both together.
> 
> Can you open browser toolbox and capture the error thrown when you install **.xpi** ?

1631885368893	addons.xpi	WARN	Invalid XPI: Error: File C:\Users\Lance\Desktop\tab_mix_plus-0.5.8.1.xpi does not contain a valid manifest(resource://gre/modules/addons/XPIInstall.jsm:669:11) JS Stack trace: loadManifest@XPIInstall.jsm:669:11
async*loadManifest@XPIInstall.jsm:1542:28
init@XPIInstall.jsm:2048:18
getInstallForURL@XPIInstall.jsm:4321:21
XPIProvider[meth]@XPIProvider.jsm:3246:28
promiseCallProvider@AddonManager.jsm:245:31
getInstallForURL@AddonManager.jsm:1772:27
getInstallForURL@AddonManager.jsm:3993:33
onDrop@drag-drop-addon-installer.js:66:40
handleEvent@drag-drop-addon-installer.js:33:12
EventListener.handleEvent*connectedCallback@drag-drop-addon-installer.js:10:12
@drag-drop-addon-installer.js:81:16

**Comment by etjim** [comment]
> 
> I already downloaded the extension chromejs. I did the additional step only for safety. I can't install the tmp xpi
> […](#)
> ________________________________ From: etjim Sent: Fri Sep 17 18:37:01 GMT+05:30 2021 To: onemen/TabMixPlus Cc: Bearmancer , Author Subject: Re: [onemen/TabMixPlus] I cannot install xpi for legacy TMP support (#76) When you do step 3 "Download one of the files below and extract its content in chrome folder." of userChromeJS Instructions , you need to choise "utils → I'm only interested in extensions" or "utils → I'm interested in both scripts and extensions". After finish all Step you can install TMP，Unnecessary install bootstraploader.xip — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fonemen%2FTabMixPlus%2Fissues%2F76%23issuecomment-921781993&data=04%7C01%7C%7C8ebfd9c266f649c075d908d979dc0890%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637674808214921024%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Thq3jSQJ9QhgRShmLUu6ns4gNwU3MbnHb8MAjfqIKVA%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQWHKKR7H7AX2HDGAGK4JRLUCM4PFANCNFSM5EGS5LGA&data=04%7C01%7C%7C8ebfd9c266f649c075d908d979dc0890%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637674808214931019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=o2EvNk0v6zQQ4Ome5Pe3o8J1eG9uEfZP9Z816a2FcQo%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8ebfd9c266f649c075d908d979dc0890%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637674808214931019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=waqVEg0fQHYRm3tXYqFeSJJVwYjUaLM%2FTok0S3xOUwA%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8ebfd9c266f649c075d908d979dc0890%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637674808214941012%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GhzDhxb%2BEb5vFrCyqu25zBLqlY8eIp8Q1QCAknZi5lc%3D&reserved=0>.

close firefox.
Open the profiles and delete the "startupCache" floder,andthen install TMP again.
Reiterated, unnecessary install bootstraploader.xpi. The “utils” already have BootstrapLoader.jsm.
I use this method successfully installed TMP on Firefox Dev 93.

**Comment by Bearmancer** [comment]
OK nevermind. I got it working. I downloaded the wrong xpi file.

**Comment by onemen** [comment]
>
> OK nevermind. I got it working. I downloaded the wrong xpi file.

Can you tell what did you download instead, maybe other do the same ?

**Comment by 117649** [comment]
> 
> 
> > OK nevermind. I got it working. I downloaded the wrong xpi file.
> 
> Can you tell what did you download instead, maybe other do the same ?

I have glimpse it is 5.0.8.1 ....

**Comment by Bearmancer** [comment]
I downloaded it from here: https://github.com/onemen/TabMixPlus/releases

Instead of what I used to do that was download xpi and dump it: https://bitbucket.org/onemen/tabmixplus/downloads/

**Comment by Bearmancer** [comment]
I can’t install extensions suddenly. Simple Tab Group also stopped working. What could be the reason?

**Comment by Bearmancer** [comment]
Turns out the extension is causing the issue. Disabling it allows Simple Tab Group to work and I can also download other extensions. Is this a known bug?

**Comment by 117649** [comment]
Do you have bootstraploader.xpi installed?

**Comment by Bearmancer** [comment]
I couldn’t install the xpi because firefox wouldn’t allow it.

Is there a way to bypass it?

**Comment by Bearmancer** [comment]
I tried installing the extension on a new laptop and followed all the same steps but I still get the corrupted add on error. I used xpis from both github and bitbucket.

**Comment by onemen** [comment]
Your probably missed a step.

- Follow ALL the instruction form [Read Me](https://github.com/onemen/TabMixPlus/#readme)
- Use only xpi from GitHub
- Save the xpi to your laptop

**Comment by Bearmancer** [comment]
> 
i assume that i dont have to do step 4 and 5 from: https://github.com/xiaoxiaoflood/firefox-scripts#instructions

they arent applicable for me correct?

aisde from that every time i try to install the xpi it says the add on is corrupted. ive followed all the steps. 

you can see what ive done here: https://imgur.com/a/SecZDhh

**Comment by onemen** [comment]
1. Most likely that the error is In the your profile chrome folder.
 create `utils` folder inside your chrome folder and move all the file to it.
If you check the file you have downloaded all its content are in utils folder.
[utils → I'm only interested in extensions](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/utils_extensions_only.zip)

2. I see that you have config.js in you `Firefox Mozilla` folder, make sure that the file `config-prefs.js` is in `Firefox Mozilla defaults\pref`

3. make sure that the content of `config-prefs.js` is
```js
pref("general.config.obscure_value", 0);
pref("general.config.filename", "config.js");
pref("general.config.sandbox_enabled", false);
```

**Comment by Bearmancer** [comment]
Wow everything except utils subfolder was the same.It worked. Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
