### ISSUE TITLE
Tab style option for Background Color was working. then feiled with checkbox became greyed out

### ISSUE THREAD

**Issue by NotesTracker** [onemen/TabMixPlus#78]
Many, many thanks for this WE extension. I recently moved from Waterfox Classic to Waterfox G3 and the expension is a life saver! I got everything working to my satisfaction, with the Current Tab having a distinctive background color and it was working well,

Then I tried to put rounded top corners on the tabs, and while doing this (or for other unknown coincidental reason) the colored background of the Current Tab stopped working, **The checkbox for Background Color is now greyed out** and I haven't been able   to get it working again.

Is there anything I can tweak to fix this?

![TabMixPlus-WE-greyed-out-background-color-checkbox](https://user-images.githubusercontent.com/16795905/134013958-5685752f-713e-40f2-9d0c-9853becf5508.jpg)

**Comment by 117649** [comment]
Uncheck **Disable custom background colors**

**Comment by NotesTracker** [comment]
That was it, many thanks @117849.

Forgive an old bloke, Don't know why I overlooked the Disable custom background colors option.
