### ISSUE TITLE
Shortcut fails for Reopen last closed tab

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#79]
I just learned about and installed the new TMP for Fx yesterday, and I am SO happy!!! Thank you!!!

I can reopen the last closed tab using the context menus (both tab and main). I can use the shortcut I provided (ctrl-alt-Z) to reopen all closed tabs. Other shortcuts I created seem to work (though I've not tested everyone yet.) But I cannot seem to get any shortcut to reopen the last closed tab. I have tried alt-Z (which I use in Pale Moon and would like to use here for consistency), ctrl-shift-Z, and alt-U. TMP reports that ctrl-shift-Z is already used, so that failure is understandable (without something like keyconfig). But should not alt-Z or alt-U work?

**Comment by onemen** [comment]
Maybe Firefox block changes to some build-in shortcuts
I need to investigate this more.

**Comment by VLM-TechEd** [comment]
Thank you for responding, I deeply appreciate that. Fx did block (or attempt to block) ctrl-shift-Z; the message appears in the options dialog on a yellow field beneath the heading “Edit keyboard shortcuts” with the text “Some of your shortcuts are in use by other commands.” This message appeared when I attempted to enter ctrl-shift-Z and disappeared the moment I removed that shortcut. I saw no feedback in response to alt-Z or alt-U. If I can provide additional details or help by testing or in some other way, please ask. 😊 

 

Best regards,

**Comment by onemen** [comment]
The same issue apply to all build-in shortcuts that appears in our list in Options > Menu > Shortcuts,
our code manage to change the modifiers but not the key

need to investigate more...

**Comment by onemen** [comment]
got it

when user change shortcut we re-insert the "mainKeyset" to the DOM, this triggers async fluent translation for keys with data-l10n-id attribute, once the translation finished it reset the key attribute to its default value.

to fix this issue i will just remove data-l10n-id from keys

**Comment by VLM-TechEd** [comment]
You are SO very good! Will there be an updated release in the coming days?

 

Thank you!

**Comment by onemen** [comment]
Test this http://tabmixplus.org/dev-builds/test%20builds/tab_mix_plus-1.0.0-pre.2.20210925.1.xpi

**Comment by VLM-TechEd** [comment]
Happy to. But now you’re going to witness a bit of my ignorance. When I click or copy/paste the .xpi link, I’m not sure what happens. Firefox is set to always ask where to put downloads, but that doesn’t happen. Nothing appears in the Downloads folder. I don’t see how to save the link, then install it. (I am also using Pale Moon, and right now PM is set as the default program to open .xpi files.) Finally, when I just click on the link and let it run, TMP doesn’t appear to be updated. You haven’t yet put this version up on either the change log or releases pages (for obvious reasons 😊). 

 

If you would be kind enough to tell me how to use the link, I’ll test right away.

 

Sorry to be so ignorant in this regard.

 

Elchanan

**Comment by VLM-TechEd** [comment]
Hi again,

 

I got hold of a second computer on which PM is not installed and Fx is the default browser and opener of .xpi files. The link still didn’t install in Fx. I want to help, but I’m not sure what to do. If you could guide me, I will gladly follow your lead.

 

Best,

Elchanan

**Comment by VLM-TechEd** [comment]
It appears that Firefox tried to install this version but failed. I had to reinstall the version released yesterday. Just FYI.

 

Elchanan

**Comment by onemen** [comment]
Download this file, (right click on the link and select **Save Link as...** from the menu)
[tab_mix_plus-1.0.0-pre.2.20210925.1.zip](https://github.com/onemen/TabMixPlus/files/7230745/tab_mix_plus-1.0.0-pre.2.20210925.1.zip)

**Comment by VLM-TechEd** [comment]
Okay, I have it. I put the chrome contents in the %appdata%\…\chrome folder and the default contents in the Program Files\…\<profile>.release\default folder. Where does the remainder go? Also, is there supposed to be a new .xpi file?

 

Thanks!

Elchanan

**Comment by onemen** [comment]
You don't need to unzip the file, just drag it as-is
And if you want **xpi** just change the extension of the file you downloaded from zip to xpi

> note: when you reply from Gmail or other mail client remove all the content after your reply (... from the previous mail)

**Comment by VLM-TechEd** [comment]
Ah yes, I remember reading about changing .zip to .xpi. The new version works perfectly on my system. However, it installs (based on the response of Firefox) but does not appear to fix the problem on our second system. I think all the prerequisites are properly in place. However, That machine is in use right now, so I’ll check it later and report back. My guess is that the extension is fine and that I’ve misinstalled something related to userChromJS on the second system. (However, several scripts to appear to be working, so I’m not sure.)

 

Will report back later today (Pacific time zone).

**Comment by VLM-TechEd** [comment]
The new TMP now works perfectly on both of our systems. For some reason, it did not install correctly when I dragged the .xpi file onto a Fx window. When I could get back on the computer, I tried installing by double-clicking the .xpi file, and the extension installed correctly. So all is well here.

 

Thank you!!!!!
