### ISSUE TITLE
Open ALL links in new tab is not working

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#80]
[makondo @ Tabmix](http://tabmixplus.org/forum/viewtopic.php?f=1&t=20051&p=73819#p73819) Forum, report about this issue:
>Open ALL links in new tab is not working? It doesn't for me.
>imported settings from the old Fx where it used to work fine - all links in new tabs at the end. Is this option suppose to work?

This is a bug !
I'm already working on it.

**Comment by Mrsash2020** [comment]
Hi
I was going to report the same. I am using another addon for this currently until you resolve it. Here is a link to that addon 
https://github.com/averissimo/open-links-in-tabs

**Comment by onemen** [comment]
Did you install latest Tab Mix Plus version?
https://github.com/onemen/TabMixPlus/releases

**Comment by onemen** [comment]
- what is your operating system?
 - post your Tab Mix Plus preferences and as a file.
 - check if you can reproduce this issue on new profile
 - do you see any message in the browser console after tab context menu was visible?
 - post an example for a page to reproduce this issue

**Comment by onemen** [comment]
- selected more than one link on a page
- then right click on the selected links to bring the context menu
- report if you see any messages in the browser console

**Comment by Mrsash2020** [comment]
I opened the browser console Ctl+Shift+ J
Opened a webpage with multiple links
highlighted multiple links and right clicked as I did before.


Cant see anything. What should I be looking for. Sorry novice here so you have to point me to what I should be looking for, seems quite a few windows in the browser console.

thanks

**Comment by onemen** [comment]
I have no idea why you don't see **Open Links in New Tabs**
![open_links](https://user-images.githubusercontent.com/3650909/137581805-0b838bf5-3906-4df2-892d-a38c291a97c5.png)

Make sure to download and install the latest version - [v1.0.0-pre.3](https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.3/tab_mix_plus-dev-build.xpi)

To test if there is relevant messages in the browser console:
- open the browser console Ctl+Shift+ J
- clear all existing messages
- got back to Firefox browser page
- select more then one link
- right click while the mouse is **over one of the selected links**
- report if you see **Open Links in New Tabs** and if you see any new message in the browser console

**Comment by onemen** [comment]
I don't know, maybe it was some cache issue.
next time you can verify that version was installed by looking at the extension page in about:addons

![version](https://user-images.githubusercontent.com/3650909/137592668-4b108c06-601c-43c9-bfd5-3d5abaaf8cdf.png)

**Comment by Mrsash2020** [comment]
Maybe Cache issue indeed. When I installed Pre 2 and then updated to Pre 3, I did check it there and it did show the versions but wasn't working. Think we can say thats weird. 

Also noticed your session manager is working for me somehow, not the firefox one. I think its carried over with the update I did from Firefox version 56 to the latest. I tested restoring while my TMP has 'Use Firefox's built in session manager' unticked and it worked.
Then I ticked 'Use Firefox's built in session manager'(would not let me untick after that) and used firefox's session manager I think.
didnt like it so imported the settings for TMP again and got yours working again. 

Sorry probably should start another thread but any plans on allow for level of compacting menus/bookmark/right click to fit more ? I would appreciate any step by step instructions if not. I tried to follow some other guide which assumed I know how to CSS but failed horribly.

thanks again

**Comment by onemen** [comment]
> level of compacting menus/bookmark/right click to fit more ?
I have no idea what you mean by compacting menus.

**Comment by onemen** [comment]
You can add:
```css
menupopup > menuitem, menupopup > menu {
  padding-block: 2px !important;
}
```

in userChrome.css file
if the file does not exist, create one inside chrome folder in your profile
also set **toolkit.legacyUserProfileCustomizations.stylesheets** to true in about:config

change the value 2px to fit your needs

**Comment by onemen** [comment]
> 
> Tried it but did not work. Closed and opened FF and still the same. Anything else I should try?

It should work, It worked for me.
make sure the file is in your profile under chrome folder

**Comment by Mrsash2020** [comment]
Ok wouldn't work for me. 
Moved profile/chrome contents out except userChrome.css, this meant other stuff did not work. But for testing it was ok. Viola! Restarted FF and compact menus working. Moved stuff back into profile/chrome then restarted FF again. Still works. Phew. Will check if everything else is still functioning.
