### ISSUE TITLE
"Paste and Go" is broken

### ISSUE THREAD

**Issue by JustOff** [onemen/TabMixPlus#81]
"Paste and Go" feature doesn't work and breaks the address bar after the first call.

```console
TypeError: result is null
    handleCommand chrome://tabmixplus/content/minit/minit.js:929
    handleCommand self-hosted:1175
    _initPasteAndGo resource:///modules/UrlbarInput.jsm:2543
```

FF 92.0.1
TMP 1.0.0-pre.2

**Comment by onemen** [comment]
Are you using an extension for "Paste and Go" ?
How do you enable it?

**Comment by JustOff** [comment]
I'm talking about the native Firefox address bar's context menu feature:

![2021-09-29_23-28-12](https://user-images.githubusercontent.com/340855/135343667-234172b4-bb76-4ab3-910f-bc795f5320c9.png)

**Comment by onemen** [comment]
So far I can't reproduce it on clean profile

Export your Tab mix preferences to a file and attache it here

read [this](http://tabmixplus.org/support/viewpage.php?t=2&p=tabmix-does-not-work)

**Comment by JustOff** [comment]
It's very strange. I always have this error in a clean FF profile with default TMP settings and no other extensions installed.

[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/7255144/TMPpref.txt)

**Comment by onemen** [comment]
How do you copy and what is the content you try to paste into the urlbar?

**Comment by JustOff** [comment]
Any link and even simple text (which usually opens in a default search engine) leads to an error, even if I copy it from Windows Notepad.

firefox-scripts is installed using "[I'm interested in both scripts and extensions](https://github.com/xiaoxiaoflood/firefox-scripts#tested-on-firefox-developer-edition-930b6-windows-10)" option.

I would be happy to provide any additional details, but I can not invent what else to add.

**Comment by onemen** [comment]
> That's one small step for onemen, one giant leap for mankind

```diff
      let isMouseEvent = event instanceof MouseEvent;
      let altEnter = !isMouseEvent && event &&
          event.altKey && !gBrowser.selectedTab.isEmpty;
      let where = "current";
-     let url = result.payload?.url ?? this.value;
+     let url = result?.payload?.url ?? this.value;
      let loadNewTab = Tabmix.whereToOpen("extensions.tabmix.opentabfor.urlbar",
        altEnter).inNew && !(/^ *javascript:/.test(url));
      if (isMouseEvent || altEnter || loadNewTab) {
```

**Comment by JustOff** [comment]
Well, it helped!

**Comment by onemen** [comment]
Yes thank you,
with your preference and comments I was able to reproduce it, and verify the the fix solved the issue. (`result?` just check that result is not null)
