### ISSUE TITLE
Tabs below URL bar

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#84]
I see the options to put tabs at the top or bottom of the entire window, but is there a way to put the tabs up top but below the URL bar? Can this option be added, if available?

Thank you.

**Comment by onemen** [comment]
try this
https://support.mozilla.org/bm/questions/1245826

**Comment by VLM-TechEd** [comment]
Thank you. This code is a helpful beginning. It makes some nice cosmetic changes to my Firefox installation. For example, it enables me to color the tab and nav bars as I please, which I have done. It draws the individual tabs nicely as “squares” (really oblongs, but very nice), and it enables the tabs to display across the entire width of the screen. Apparently, it does the latter by displaying the title bar, light gray, and placing the min/max/close buttons in it, resulting in lost vertical space. And it does not move the URL bar above the tab bar. It also causes display of an additional empty light gray bar below the URL bar. 

 

I wish I understood how to work with css code, as I’d attempt to fix it. I tried to excerpt only the color-changing code (first :root section), but I must require some additional code to finish up. 

 

Thanks!

VLMin
