### ISSUE TITLE
dev build 1.0.0 pre.2/ pre.1 don't install in FF 93.0 -> "..appears to be corrupt"

### ISSUE THREAD

**Issue by LeeBinder** [onemen/TabMixPlus#86]
"The add-on downloaded from this site could not be installed because it appears to be corrupt"

FF 93.0 Mac Intel + a new empty virgin profile.

When I try to install via `about:debugging#/runtime/this-firefox` -> Load Temporary Add-on:

> no manifest.json is found

[EDIT] figured it out as per https://github.com/xiaoxiaoflood/firefox-scripts#instructions

Is there a lasting solution? Because with this approach, TMP would eventually get disabled again after a major update which overwrites the Firefox.app

**Comment by pepek1122583** [comment]
Looks like working only on Waterfox G3
Tried with FF 93 -> Manifest problem
FF beta 94.0b3 -> Manifest problem

Tried unpack webextension to root folder but missing ID
I added missing Id and trying install with xpinstall.signatures.required to false, without success :/

**Comment by onemen** [comment]
I will try to install Mac on my `Oracle VM VirtualBox` and check what is the proper way to install Tab Mix Plus on Mac

**Comment by LeeBinder** [comment]
Oh .. :( after FF restart, Tab Mix Plus has been deactivated and can't be re-activated, not even after remove, quit FF, start again, try to re-install - no matter if here from the webpage nor manually from the downloaded .xpi.

I checked - the files inside the Firefox.app folder are still present.

I overwrote them again, quit FF, re-launched: still no chance.

Tried again in a new virgin profile: same thing, won't work.

Odd..

**Comment by onemen** [comment]
I've just installed Mac on a VirtualBox and Tab mix works without a problem.

try these steps:
- remove Tab mix from the profile that it does not work in and restart Firefox.
- set in about config xpinstall.whitelist.required to false (we have some reports that it can help)
- follow steps 2, 3 and 6 from [here](https://github.com/xiaoxiaoflood/firefox-scripts#instructions), make sure to install the [utils folder](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/utils_extensions_only.zip) you downloaded inside **chrome** folder in your profile folder.

After you complete step 6 and restarts Firefox install Tab mix again from the xpi file you have downloaded from this site

**Comment by 117649** [comment]
> Thank you for reviving your legacy plugin and porting it into a web-extension - priceless, invaluable 🥇

NO ITS NOT A web-extension!!!

IT STILL A LEGACY EXTENSION!

THAT WHY IT NEED USE CustomJS FOR RESTORED LEGACY BOOTSTRAP LOADER THAT MOZILLA HAVE REMOVED!
 
If people could just understand this that would just make their life much easier on install TMP.

**Comment by LeeBinder** [comment]
uh-oh, sorry for not having read properly, @117649 , and thanks for pointing that out - I redacted my comment above.

What remains unaltered is that TMP stays priceless and invaluable 👍

**Comment by DARKFiB3R** [comment]
> I've just installed Mac on a VirtualBox and Tab mix works without a problem.
> 
> try these steps:
> 
>     * remove Tab mix from the profile that it does not work in and restart Firefox.
> 
>     * set in about config xpinstall.whitelist.required to false (we have some reports that it can help)
> 
>     * follow steps 2, 3 and 6 from [here](https://github.com/xiaoxiaoflood/firefox-scripts#instructions), make sure to install the [utils folder](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/utils_extensions_only.zip) you downloaded inside **chrome** folder in your profile folder.
> 
> 
> After you complete step 6 and restarts Firefox install Tab mix again from the xpi file you have downloaded from this site

Is this still required in Sept 2022? 

Really looking forward to having TMP back in my life :D

Thanks.

**Comment by onemen** [comment]
> Is this still required in Sept 2022?

Yes
