### ISSUE TITLE
Bookmark name not = customized tab name

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#87]
When I open a tab from a bookmark, the tab name follows the bookmark name. But when I change tab name and then bookmark that tab, the bookmark name does not follow the tab name. In the XUL version, it does, so I'm guessing that this is unintentional behavior by TMP.

**Comment by onemen** [comment]
what is your operating system and Firefox version?

**Comment by VLM-TechEd** [comment]
Windows 10 Home, Firefox 93.0. (I believe that’s the current version of Firefox ???)
