### ISSUE TITLE
New bookmarks do not default to renamed tab titles

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#88]
Greetings!

When we create a bookmark using a custom Bookmark Name, then open that bookmark, the tab title = the bookmark title. Perfect.

But when we rename a tab and then bookmark it, the original tab title, not the renamed title, appears in the Bookmark Name field. I believe this works — meaning that the Bookmark Name = the retitled tab name — in the XUL version (e.g., Pale Moon). 

Thank you.

**Comment by onemen** [comment]
You already reported about this issue 3 days ago #87

I hope to upload new version by the end of this week

**Comment by onemen** [comment]
> but it seems there is a special problem with reopening the last closed tab; all the other shortcuts I have tested seem to work. I was attempting to provide additional information

did you refer to #79 ? 
it was fixed and you reported that it works for you
