### ISSUE TITLE
Merge moves selected tabs to wrong window

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#92]
In the XUL version of TMP, if I select one or more tabs (but not all tabs) in window A for merging, then focus on window B, then again on window A, then make the merge, the selected tabs in window A are moved to window B. That is, they are moved to the most recently focused window other than A. But in the new Fx version of TMP, the selected tabs are consistently moved to the "wrong" window.

**Comment by VLM-TechEd** [comment]
Well this is weird. It happened so fast that I copied and manually pasted in the link in a new tab. When I hit “Enter”, Firefox’s “Add extension” blipped up for a second or so, with “Cancel” highlighted and “Add” grayed out. Then it disappeared. I’ve never seen that before.

**Comment by onemen** [comment]
Right click on the link and click Save Link As..

**Comment by VLM-TechEd** [comment]
I know. But in Outlook, I only get the options Select / Open / Copy Link; there is no Save As or similar. I don’t recall how I got past this last time. Perhaps you provided a link ending explicitly in .xpi. I don’t remember.

**Comment by onemen** [comment]
Maybe you can use Firefox to download the file , i heard it is a good browser :wink:

**Comment by VLM-TechEd** [comment]
Yes, that’s what I tried and wrote to you about in my first email on this:

 

Well this is weird. It happened so fast that I copied and manually pasted in the link in a new tab. 
When I hit “Enter”, Firefox’s “Add extension” blipped up for a second or so, with “Cancel” highlighted 
and “Add” grayed out. Then it disappeared. I’ve never seen that before. 

 

In other words, Firefox tried to install it, not download it, or it downloads it and can’t install it. I’ve not seen the disappearing “Add extension” before.

**Comment by onemen** [comment]
You can download a link by right click on the link and select **Save Link As...** !!!
Not by clicking on it from outlook or by paste it to a now tab

**Comment by VLM-TechEd** [comment]
Yes, I know. But in Outlook, that option is available only for attachments, not for inline links, and I don’t know enough to circumvent the limitation. Inline links have only 3 options: Select / Open / Copy Link.

 

Would you be willing to send as an attachment? I’m really sorry, I just don’t have the knowledge/skills using Outlook to do any better.

**Comment by onemen** [comment]
Why you are using Outlook to download ?
Use Firefox or other browsers

**Comment by VLM-TechEd** [comment]
I am using Outlook because we are communicating via email. Please just attach the file to an email. Outlook only knows how to follow inline links; there is no Save As except for attachments. And as I told you, Firefox (and also Pale Moon) tries to install the file, not download it. If there is a setting that can change this behavior, I am unaware of it.

**Comment by onemen** [comment]
I'm not communicate via email, you are
Just use the browser, navigate to https://github.com/onemen/TabMixPlus/issues/92 and download the link

you can also navigate to http://tabmixplus.org/dev-builds/test%20builds/
and download the file 1.0.0-pre.3.20211016.1.xpi

**Comment by VLM-TechEd** [comment]
Ohhhhhhhhh. I’ve got it. Now, Firefox says “This add-on could not be installed because it appears to be corrupt.”

**Comment by onemen** [comment]
Are you sure you download the file and tried to installed it on profile that you use for Tab mix before?
I install the same file without any problem

**Comment by onemen** [comment]
You have to download the file and actually save it to your file system.
do not try to install it by dragging the link or clicking the link
after you downloaded the file, install it from you file system

**Comment by onemen** [comment]
fixed by 78e5695b2cc62406e80dabe791ace8f640eae70a
