### ISSUE TITLE
TMP hides status bar & stops loading new tabs

### ISSUE THREAD

**Issue by mimteatr** [onemen/TabMixPlus#94]
Hello,

I'm using `toolbars_below_content.css` by **MrOtherGuy**. and `status-bar.uc.js` by **xiaoxiaoflood**.

When NOT using TMP, tabs load normally and status bar is visible:
<img width="950" alt="firefox_etoR6TWYLx" src="https://user-images.githubusercontent.com/36078037/140653252-49aac4e7-3874-47ea-90b7-b60e42bb99aa.png">

If enabling also "tabs below content" in TPM options, it hides left side of status bar and cannot load loadi new tabs:
<img width="946" alt="OO2oqlb4Ps" src="https://user-images.githubusercontent.com/36078037/140653261-e6056b92-b39a-4191-a074-51a1541a437c.png">

If it's disabled, then tabs keep loading normally but are hidden behind status bar and you can barely see their top.
<img width="955" alt="Screenshot 2021-11-07 184823" src="https://user-images.githubusercontent.com/36078037/140654065-2b692e06-2f7c-493d-b58d-69df18c0b5aa.png">

Please help, thanks!

**Comment by onemen** [comment]
Report about this issue to `toolbars_below_content.css` and `status-bar.uc.js` developers

did you customized any of the above files?

**Comment by mimteatr** [comment]
Why should I report to them if I wrote you above that everything works fine without using TMP??

The problem is while using TPM! 

I thought that explaining it thoroughly while attaching the specific images would expose to you the problem clearly enough. 

Isn't that the purpose here?

**Comment by onemen** [comment]
> Why should I report to them if I wrote you above that everything works fine without using TMP

**Tab Mix Plus** works fine without using `toolbars_below_content.css` and `status-bar.uc.js`
There are some incompatibility between `toolbars_below_content.css`, `status-bar.uc.js` and **Tab Mix Plus**

Maybe one of the other developers can help to solve the issue

did you customized any of the above files?

**Comment by mimteatr** [comment]
I understand. 

I didn't customize them, using them as is. 

I'll try contacting the css developers. 

Thank you

**Comment by onemen** [comment]
Closing out old issues that have long grown stale.
Feel free to ping me if this is still an issue and I can reopen.
