### ISSUE TITLE
Dopdown for position tabs at Top and Bottom has become broken

### ISSUE THREAD

**Issue by NotesTracker** [onemen/TabMixPlus#95]
![TabMixPlus_ 1 0 0-pre 3 (2021-10-14)_TOP_and_BOTTOM_dropdown_broken](https://user-images.githubusercontent.com/16795905/140694600-08c86ecc-de19-4df6-aa59-11f9aeee958a.jpg)

This problem occurred out of the blue a few days ago on my Windows 10 system. I haven't a clue what caused it, and reinstalling -- by removing the add-on and then running the TabMixPlus-1.0.0-pre.3_(2021-10-14).xpi -- did not fix the problem, the drop-down remains empty (no TOP or BOTTOM options appear).

I had four Waterfox windows open at the time, and in three of them the tabs appeared at the top, and where I expected at the bottom for the fourth window. For the first three windows, I selected all tabs and dragged them to a new window, where lucky for me they then appeared at the bottom.

Very peculiar! How can the Top/Bottom drop down be made to work properly again? What could have caused this problem? I didn't do anything deliberate to make it happen, it just happened unexpectedly. 

To grasp at straws, one possible cause MIGHT be that Waterfox auto-updated from G3 to G4 during the same day or two, which I didn't notice happening.

**Comment by onemen** [comment]
What Waterfox version you are using?

Report if you have any messages in the Browser Console
