### ISSUE TITLE
Minor annoyance:  TMP removes extra spaces in tab titles

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#97]
When I enter a custom tab title that contains consecutive spaces, TMP appears to retain the information — the multiple spaces are there when I reopen the tab title — but TMP only displays a single space character in the tab itself. Being visually limited, I use extra spaces to make certain information easier for me to see/read. I realize that this would be considered only a minor annoyance, but perhaps it is also quick easy to fix. ?? Thank you.

**Comment by VLM-TechEd** [comment]
PS: In the XUL version of TMP (Pale Moon), the extra spaces have always appeared in the tab title.

**Comment by onemen** [comment]
can you provide screenshot example of a tab in Pale Moon and Firefox with the same title 

Attache a file with your Tab mix preferences

**Comment by onemen** [comment]
Firefox add `white-space: nowrap;` to tab label

try to add this to your userChrome.css file:
```css
.tabbrowser-tab .tab-label {
  white-space: break-spaces;
}
```

**Comment by VLM-TechEd** [comment]
Works, thank you!

 

.tabbrowser-tab .tab-label {
  white-space: break-spaces;
}
