### ISSUE TITLE
Request: Possible to force unloaded state?

### ISSUE THREAD

**Issue by Chwoka** [onemen/TabMixPlus#98]
When the browser first opens, all tabs are unloaded. I believe that's called lazy loading, and it's good for memory. I'd like to be able to manually force tabs into this unloaded dormant state, if that's possible? Maybe even open background tabs that way?

**Comment by onemen** [comment]
we have options to open unloaded tabs when loading group of bookmarks
See in this [help page](http://tabmixplus.org/support/viewtopic.php?t=3)  Don't load tabs until selected - all background tabs remain unloaded until selected.

I'm not planing to add `manually force tabs into this unloaded`

**Comment by onemen** [comment]
Closing out old issues that have long grown stale.
Feel free to ping me if this is still an issue and I can reopen.
